### ISSUE TITLE
waterway schema feedback

### ISSUE THREAD

**Issue by pnorman** [openmaptiles/openmaptiles#100]
- Some rendering engines will need a waterway and waterway_name layer for the same as transport.

- The first paragraph states

  > Rivers based of OpenStreetMap waterways for z9 to z14 and Natural Earth rivers and lake centerlines from z3 to z8. Linestrings without a name or which are too short are filtered out at low zoom levels.

  These are purely implementation details - what zooms are used for what datasource and the filtering done can change.

- [x] Intermittent is an important property, as is tunnel

- [x] What classes exist on what zooms isn't documented. For reference, this is when osm-carto starts rendering the classes: river: z8, canal: z12, wadi: z13, stream: z13, ditch: z13, drain: z13, derelict_canal: z12

**Comment by daliborjanak** [comment]
Tunnels are implemented in #326. @eva-j please update the docs

**Comment by eva-j** [comment]
Intermittent waters implemented in https://github.com/openmaptiles/openmaptiles/pull/585
Documentation updated in https://github.com/openmaptiles/openmaptiles/pull/702
