### ISSUE TITLE
PBF generated from postserve has glitches, but mbtile pbfs work fine

### ISSUE THREAD

**Issue by caleb87** [openmaptiles/openmaptiles#1004]
**What object is missing/extra/wrong? What did you expect to be in the map instead?**
Postserve pbf tiles render with glitches, but when generating mbtiles, the tiles render fine.

I tried on bright.json and blue one and both rendered the same. 

The image without red boxes is rendered with tiles.mbtiles. The other 3 have bugs when using the same mapbox gl js style, but with postserve as a source. 

![postserve3](https://user-images.githubusercontent.com/6970514/94377986-8047ed00-00da-11eb-88b1-ae9ff121968c.jpg)

- URL / link to the specific location in a live map demo where the bug is visible
----http://3.85.116.149/index.html
- Zoom level(s) at which the bug appears
----shows at all zoom levels
- Screenshot of the problem is very beneficial! It's permanent and browser-independent. Drag&drop an image to the report.
----screenshot above
- Check our GL styles (https://openmaptiles.org/styles/) and list the affected one (OSM Bright, Basic, Terrain, Positron, etc).
----affects bright/blue, see screenshot

`{"tilejson": "2.2.0", "name": "OpenMapTiles", "description": "A tileset showcasing all layers in OpenMapTiles. https://openmaptiles.org", "version": "3.11.0", "attribution": "<a href=\"https://www.openmaptiles.org/\" target=\"_blank\">&copy; OpenMapTiles<\/a> <a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\">&copy; OpenStreetMap contributors<\/a>", "tiles": ["http://localhost:8090/tiles/{z}/{x}/{y}.pbf"], "minzoom": 0, "maxzoom": 14, "bounds": [-180.0, -85.0511, 180.0, 85.0511], "center": [-12.2168, 28.6135, 4], "vector_layers": [{"id": "water", "description": "Water polygons representing oceans and lakes. Covered watered areas are excluded (`covered=yes`).\nOn low zoom levels all water originates from Natural Earth. To get a more correct display of the south pole you should also\nstyle the covering ice shelves over the water.\nOn higher zoom levels water polygons from [OpenStreetMapData](http://osmdata.openstreetmap.de/) are used.\nThe polygons are split into many smaller polygons to improve rendering performance.\nThis however can lead to less rendering options in clients since these boundaries show up. So you might not be\nable to use border styling for ocean water features.", "minzoom": 0, "maxzoom": 14, "fields": {"class": "String", "intermittent": "Number", "brunnel": "String"}}, {"id": "waterway", "description": "OpenStreetMap [waterways](https://wiki.openstreetmap.org/wiki/Waterways) for higher zoom levels (z9 and more)\nand Natural Earth rivers and lake centerlines for low zoom levels (z3 - z8).\nLinestrings without a name or which are too short are filtered\nout at low zoom levels.\nTill z11 there is `river` class only, in z12 there is also `canal` generated,\nstarting z13 there is no generalization according to `class` field applied.\nWaterways do not have a `subclass` field.", "minzoom": 0, "maxzoom": 14, "fields": {"name": "String", "name_en": "String", "name_de": "String", "name:am": "String", "name:ar": "String", "name:az": "String", "name:be": "String", "name:bg": "String", "name:br": "String", "name:bs": "String", "name:ca": "String", "name:co": "String", "name:cs": "String", "name:cy": "String", "name:da": "String", "name:de": "String", "name:el": "String", "name:en": "String", "name:eo": "String", "name:es": "String", "name:et": "String", "name:eu": "String", "name:fi": "String", "name:fr": "String", "name:fy": "String", "name:ga": "String", "name:gd": "String", "name:he": "String", "name:hi": "String", "name:hr": "String", "name:hu": "String", "name:hy": "String", "name:id": "String", "name:is": "String", "name:it": "String", "name:ja": "String", "name:ja_kana": "String", "name:ja_rm": "String", "name:ka": "String", "name:kk": "String", "name:kn": "String", "name:ko": "String", "name:ko_rm": "String", "name:ku": "String", "name:la": "String", "name:lb": "String", "name:lt": "String", "name:lv": "String", "name:mk": "String", "name:mt": "String", "name:ml": "String", "name:nl": "String", "name:no": "String", "name:oc": "String", "name:pl": "String", "name:pt": "String", "name:rm": "String", "name:ro": "String", "name:ru": "String", "name:sk": "String", "name:sl": "String", "name:sq": "String", "name:sr": "String", "name:sr-Latn": "String", "name:sv": "String", "name:ta": "String", "name:te": "String", "name:th": "String", "name:tr": "String", "name:uk": "String", "name:zh": "String", "name_int": "String", "name:latin": "String", "name:nonlatin": "String", "class": "String", "brunnel": "String", "intermittent": "Number"}}, {"id": "landcover", "description": "Landcover is used to describe the physical material at the surface of the earth. At lower zoom levels this is\nfrom Natural Earth data for glaciers and ice shelves and at higher zoom levels the landcover is [implied by OSM tags](http://wiki.openstreetmap.org/wiki/Landcover). The most common use case for this layer\n  is to style wood (`class=wood`) and grass (`class=grass`) areas.", "minzoom": 0, "maxzoom": 14, "fields": {"class": "String", "subclass": "String"}}, {"id": "landuse", "description": "Landuse is used to describe use of land by humans. At lower zoom levels this is\nfrom Natural Earth data for residential (urban) areas and at higher zoom levels mostly OSM `landuse` tags.", "minzoom": 0, "maxzoom": 14, "fields": {"class": "String"}}, {"id": "mountain_peak", "description": "[Natural peaks](http://wiki.openstreetmap.org/wiki/Tag:natural%3Dpeak)", "minzoom": 0, "maxzoom": 14, "fields": {"osm_id": "Number", "name": "String", "name_en": "String", "name_de": "String", "name:am": "String", "name:ar": "String", "name:az": "String", "name:be": "String", "name:bg": "String", "name:br": "String", "name:bs": "String", "name:ca": "String", "name:co": "String", "name:cs": "String", "name:cy": "String", "name:da": "String", "name:de": "String", "name:el": "String", "name:en": "String", "name:eo": "String", "name:es": "String", "name:et": "String", "name:eu": "String", "name:fi": "String", "name:fr": "String", "name:fy": "String", "name:ga": "String", "name:gd": "String", "name:he": "String", "name:hi": "String", "name:hr": "String", "name:hu": "String", "name:hy": "String", "name:id": "String", "name:is": "String", "name:it": "String", "name:ja": "String", "name:ja_kana": "String", "name:ja_rm": "String", "name:ka": "String", "name:kk": "String", "name:kn": "String", "name:ko": "String", "name:ko_rm": "String", "name:ku": "String", "name:la": "String", "name:lb": "String", "name:lt": "String", "name:lv": "String", "name:mk": "String", "name:mt": "String", "name:ml": "String", "name:nl": "String", "name:no": "String", "name:oc": "String", "name:pl": "String", "name:pt": "String", "name:rm": "String", "name:ro": "String", "name:ru": "String", "name:sk": "String", "name:sl": "String", "name:sq": "String", "name:sr": "String", "name:sr-Latn": "String", "name:sv": "String", "name:ta": "String", "name:te": "String", "name:th": "String", "name:tr": "String", "name:uk": "String", "name:zh": "String", "name_int": "String", "name:latin": "String", "name:nonlatin": "String", "class": "String", "ele": "Number", "ele_ft": "Number", "rank": "Number"}}, {"id": "park", "description": "The park layer contains parks from OpenStreetMap tagged with\n[`boundary=national_park`](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dnational_park),\n[`boundary=protected_area`](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dprotected_area),\nor [`leisure=nature_reserve`](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dnature_reserve).", "minzoom": 0, "maxzoom": 14, "fields": {"class": "String", "name": "String", "name_en": "String", "name_de": "String", "name:am": "String", "name:ar": "String", "name:az": "String", "name:be": "String", "name:bg": "String", "name:br": "String", "name:bs": "String", "name:ca": "String", "name:co": "String", "name:cs": "String", "name:cy": "String", "name:da": "String", "name:de": "String", "name:el": "String", "name:en": "String", "name:eo": "String", "name:es": "String", "name:et": "String", "name:eu": "String", "name:fi": "String", "name:fr": "String", "name:fy": "String", "name:ga": "String", "name:gd": "String", "name:he": "String", "name:hi": "String", "name:hr": "String", "name:hu": "String", "name:hy": "String", "name:id": "String", "name:is": "String", "name:it": "String", "name:ja": "String", "name:ja_kana": "String", "name:ja_rm": "String", "name:ka": "String", "name:kk": "String", "name:kn": "String", "name:ko": "String", "name:ko_rm": "String", "name:ku": "String", "name:la": "String", "name:lb": "String", "name:lt": "String", "name:lv": "String", "name:mk": "String", "name:mt": "String", "name:ml": "String", "name:nl": "String", "name:no": "String", "name:oc": "String", "name:pl": "String", "name:pt": "String", "name:rm": "String", "name:ro": "String", "name:ru": "String", "name:sk": "String", "name:sl": "String", "name:sq": "String", "name:sr": "String", "name:sr-Latn": "String", "name:sv": "String", "name:ta": "String", "name:te": "String", "name:th": "String", "name:tr": "String", "name:uk": "String", "name:zh": "String", "name_int": "String", "name:latin": "String", "name:nonlatin": "String", "rank": "Number"}}, {"id": "boundary", "description": "Contains administrative boundaries as linestrings.\nUntil z4 [Natural Earth data](http://www.naturalearthdata.com/downloads/) is used after which\nOSM boundaries ([`boundary=administrative`](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative))\nare present from z5 to z14 (also for maritime boundaries with `admin_level <= 2` at z4).\nOSM data contains several [`admin_level`](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#admin_level)\nbut for most styles it makes sense to just style `admin_level=2` and `admin_level=4`.", "minzoom": 0, "maxzoom": 14, "fields": {"admin_level": "Number", "disputed": "Number", "disputed_name": "String", "claimed_by": "String", "maritime": "Number"}}, {"id": "aeroway", "description": "Aeroway polygons based of OpenStreetMap [aeroways](http://wiki.openstreetmap.org/wiki/Aeroways).\nAirport buildings are contained in the **building** layer but all\nother airport related polygons can be found in the **aeroway** layer.", "minzoom": 0, "maxzoom": 14, "fields": {"ref": "String", "class": "String"}}, {"id": "transportation", "description": "**transportation** contains roads, railways, aerial ways, and shipping\n lines.\nThis layer is directly derived from the OSM road hierarchy.\nAt lower zoom levels major highways from Natural Earth are used.\nIt contains all roads from motorways to primary, secondary and\ntertiary roads to residential roads and\nfoot paths. Styling the roads is the most essential part of the map.\nThe `transportation` layer also contains polygons for features like plazas.", "minzoom": 0, "maxzoom": 14, "fields": {"class": "String", "subclass": "String", "oneway": "Number", "ramp": "Number", "brunnel": "String", "service": "String", "layer": "Number", "level": "Number", "indoor": "Number", "bicycle": "String", "foot": "String", "horse": "String", "mtb_scale": "String", "surface": "String"}}, {"id": "building", "description": "All [OSM Buildings](http://wiki.openstreetmap.org/wiki/Buildings). All building tags are imported ([`building=*`](http://wiki.openstreetmap.org/wiki/Key:building)). The buildings are not yet ready for 3D rendering support and any help to improve\nthis is welcomed.", "minzoom": 0, "maxzoom": 14, "fields": {"osm_id": "Number", "render_height": "Number", "render_min_height": "Number", "colour": "String", "hide_3d": "Boolean"}}, {"id": "water_name", "description": "Lake center lines for labelling lake bodies.\nThis is based of the [osm-lakelines](https://github.com/lukasmartinelli/osm-lakelines) project\nwhich derives nice centerlines from OSM water bodies. Only the most important lakes contain labels.", "minzoom": 0, "maxzoom": 14, "fields": {"osm_id": "Number", "name": "String", "name_en": "String", "name_de": "String", "name:am": "String", "name:ar": "String", "name:az": "String", "name:be": "String", "name:bg": "String", "name:br": "String", "name:bs": "String", "name:ca": "String", "name:co": "String", "name:cs": "String", "name:cy": "String", "name:da": "String", "name:de": "String", "name:el": "String", "name:en": "String", "name:eo": "String", "name:es": "String", "name:et": "String", "name:eu": "String", "name:fi": "String", "name:fr": "String", "name:fy": "String", "name:ga": "String", "name:gd": "String", "name:he": "String", "name:hi": "String", "name:hr": "String", "name:hu": "String", "name:hy": "String", "name:id": "String", "name:is": "String", "name:it": "String", "name:ja": "String", "name:ja_kana": "String", "name:ja_rm": "String", "name:ka": "String", "name:kk": "String", "name:kn": "String", "name:ko": "String", "name:ko_rm": "String", "name:ku": "String", "name:la": "String", "name:lb": "String", "name:lt": "String", "name:lv": "String", "name:mk": "String", "name:mt": "String", "name:ml": "String", "name:nl": "String", "name:no": "String", "name:oc": "String", "name:pl": "String", "name:pt": "String", "name:rm": "String", "name:ro": "String", "name:ru": "String", "name:sk": "String", "name:sl": "String", "name:sq": "String", "name:sr": "String", "name:sr-Latn": "String", "name:sv": "String", "name:ta": "String", "name:te": "String", "name:th": "String", "name:tr": "String", "name:uk": "String", "name:zh": "String", "name_int": "String", "name:latin": "String", "name:nonlatin": "String", "class": "String", "intermittent": "Number"}}, {"id": "transportation_name", "description": "This is the layer for labelling the highways. Only highways that are named `name=*` and are long enough\nto place text upon appear. The OSM roads are stitched together if they contain the same name\nto have better label placement than having many small linestrings.\nFor motorways you should use the `ref` field to label them while for other roads you should use `name`.", "minzoom": 0, "maxzoom": 14, "fields": {"name": "String", "name_en": "String", "name_de": "String", "name:am": "String", "name:ar": "String", "name:az": "String", "name:be": "String", "name:bg": "String", "name:br": "String", "name:bs": "String", "name:ca": "String", "name:co": "String", "name:cs": "String", "name:cy": "String", "name:da": "String", "name:de": "String", "name:el": "String", "name:en": "String", "name:eo": "String", "name:es": "String", "name:et": "String", "name:eu": "String", "name:fi": "String", "name:fr": "String", "name:fy": "String", "name:ga": "String", "name:gd": "String", "name:he": "String", "name:hi": "String", "name:hr": "String", "name:hu": "String", "name:hy": "String", "name:id": "String", "name:is": "String", "name:it": "String", "name:ja": "String", "name:ja_kana": "String", "name:ja_rm": "String", "name:ka": "String", "name:kk": "String", "name:kn": "String", "name:ko": "String", "name:ko_rm": "String", "name:ku": "String", "name:la": "String", "name:lb": "String", "name:lt": "String", "name:lv": "String", "name:mk": "String", "name:mt": "String", "name:ml": "String", "name:nl": "String", "name:no": "String", "name:oc": "String", "name:pl": "String", "name:pt": "String", "name:rm": "String", "name:ro": "String", "name:ru": "String", "name:sk": "String", "name:sl": "String", "name:sq": "String", "name:sr": "String", "name:sr-Latn": "String", "name:sv": "String", "name:ta": "String", "name:te": "String", "name:th": "String", "name:tr": "String", "name:uk": "String", "name:zh": "String", "name_int": "String", "name:latin": "String", "name:nonlatin": "String", "ref": "String", "ref_length": "Number", "network": "String", "class": "String", "subclass": "String", "layer": "Number", "level": "Number", "indoor": "Number"}}, {"id": "place", "description": "The place layer consists out of [countries](http://wiki.openstreetmap.org/wiki/Tag:place%3Dcountry),\n[states](http://wiki.openstreetmap.org/wiki/Tag:place%3Dstate) and [cities](http://wiki.openstreetmap.org/wiki/Key:place).\nApart from the roads this is also one of the more important layers to create a beautiful map.\nWe suggest you use different font styles and sizes to create a text hierarchy.", "minzoom": 0, "maxzoom": 14, "fields": {"osm_id": "Number", "name": "String", "name_en": "String", "name_de": "String", "name:am": "String", "name:ar": "String", "name:az": "String", "name:be": "String", "name:bg": "String", "name:br": "String", "name:bs": "String", "name:ca": "String", "name:co": "String", "name:cs": "String", "name:cy": "String", "name:da": "String", "name:de": "String", "name:el": "String", "name:en": "String", "name:eo": "String", "name:es": "String", "name:et": "String", "name:eu": "String", "name:fi": "String", "name:fr": "String", "name:fy": "String", "name:ga": "String", "name:gd": "String", "name:he": "String", "name:hi": "String", "name:hr": "String", "name:hu": "String", "name:hy": "String", "name:id": "String", "name:is": "String", "name:it": "String", "name:ja": "String", "name:ja_kana": "String", "name:ja_rm": "String", "name:ka": "String", "name:kk": "String", "name:kn": "String", "name:ko": "String", "name:ko_rm": "String", "name:ku": "String", "name:la": "String", "name:lb": "String", "name:lt": "String", "name:lv": "String", "name:mk": "String", "name:mt": "String", "name:ml": "String", "name:nl": "String", "name:no": "String", "name:oc": "String", "name:pl": "String", "name:pt": "String", "name:rm": "String", "name:ro": "String", "name:ru": "String", "name:sk": "String", "name:sl": "String", "name:sq": "String", "name:sr": "String", "name:sr-Latn": "String", "name:sv": "String", "name:ta": "String", "name:te": "String", "name:th": "String", "name:tr": "String", "name:uk": "String", "name:zh": "String", "name_int": "String", "name:latin": "String", "name:nonlatin": "String", "class": "String", "rank": "Number", "capital": "Number", "iso_a2": "String"}}, {"id": "housenumber", "description": "Everything in OpenStreetMap which contains a `addr:housenumber` tag useful for labelling housenumbers on a map.\nThis adds significant size to *z14*. For buildings the centroid of the building is used as housenumber.", "minzoom": 0, "maxzoom": 14, "fields": {"housenumber": "String"}}, {"id": "poi", "description": "[Points of interests](http://wiki.openstreetmap.org/wiki/Points_of_interest) containing\na of a variety of OpenStreetMap tags. Mostly contains amenities, sport, shop and tourist POIs.", "minzoom": 0, "maxzoom": 14, "fields": {"osm_id": "Number", "name": "String", "name_en": "String", "name_de": "String", "name:am": "String", "name:ar": "String", "name:az": "String", "name:be": "String", "name:bg": "String", "name:br": "String", "name:bs": "String", "name:ca": "String", "name:co": "String", "name:cs": "String", "name:cy": "String", "name:da": "String", "name:de": "String", "name:el": "String", "name:en": "String", "name:eo": "String", "name:es": "String", "name:et": "String", "name:eu": "String", "name:fi": "String", "name:fr": "String", "name:fy": "String", "name:ga": "String", "name:gd": "String", "name:he": "String", "name:hi": "String", "name:hr": "String", "name:hu": "String", "name:hy": "String", "name:id": "String", "name:is": "String", "name:it": "String", "name:ja": "String", "name:ja_kana": "String", "name:ja_rm": "String", "name:ka": "String", "name:kk": "String", "name:kn": "String", "name:ko": "String", "name:ko_rm": "String", "name:ku": "String", "name:la": "String", "name:lb": "String", "name:lt": "String", "name:lv": "String", "name:mk": "String", "name:mt": "String", "name:ml": "String", "name:nl": "String", "name:no": "String", "name:oc": "String", "name:pl": "String", "name:pt": "String", "name:rm": "String", "name:ro": "String", "name:ru": "String", "name:sk": "String", "name:sl": "String", "name:sq": "String", "name:sr": "String", "name:sr-Latn": "String", "name:sv": "String", "name:ta": "String", "name:te": "String", "name:th": "String", "name:tr": "String", "name:uk": "String", "name:zh": "String", "name_int": "String", "name:latin": "String", "name:nonlatin": "String", "class": "String", "subclass": "String", "agg_stop": "Number", "layer": "Number", "level": "Number", "indoor": "Number", "rank": "Number"}}, {"id": "aerodrome_label", "description": "[Aerodrome labels](http://wiki.openstreetmap.org/wiki/Tag:aeroway%3Daerodrome)", "minzoom": 0, "maxzoom": 14, "fields": {"osm_id": "Number", "name": "String", "name_en": "String", "name_de": "String", "name:am": "String", "name:ar": "String", "name:az": "String", "name:be": "String", "name:bg": "String", "name:br": "String", "name:bs": "String", "name:ca": "String", "name:co": "String", "name:cs": "String", "name:cy": "String", "name:da": "String", "name:de": "String", "name:el": "String", "name:en": "String", "name:eo": "String", "name:es": "String", "name:et": "String", "name:eu": "String", "name:fi": "String", "name:fr": "String", "name:fy": "String", "name:ga": "String", "name:gd": "String", "name:he": "String", "name:hi": "String", "name:hr": "String", "name:hu": "String", "name:hy": "String", "name:id": "String", "name:is": "String", "name:it": "String", "name:ja": "String", "name:ja_kana": "String", "name:ja_rm": "String", "name:ka": "String", "name:kk": "String", "name:kn": "String", "name:ko": "String", "name:ko_rm": "String", "name:ku": "String", "name:la": "String", "name:lb": "String", "name:lt": "String", "name:lv": "String", "name:mk": "String", "name:mt": "String", "name:ml": "String", "name:nl": "String", "name:no": "String", "name:oc": "String", "name:pl": "String", "name:pt": "String", "name:rm": "String", "name:ro": "String", "name:ru": "String", "name:sk": "String", "name:sl": "String", "name:sq": "String", "name:sr": "String", "name:sr-Latn": "String", "name:sv": "String", "name:ta": "String", "name:te": "String", "name:th": "String", "name:tr": "String", "name:uk": "String", "name:zh": "String", "name_int": "String", "name:latin": "String", "name:nonlatin": "String", "class": "String", "iata": "String", "icao": "String", "ele": "Number", "ele_ft": "Number"}}]}`

**Comment by frodrigo** [comment]
Not, sure but the buffer of the tile should be larger, it is 4 (unit ?)
https://github.com/openmaptiles/openmaptiles/blob/master/layers/transportation/transportation.yaml#L12

**Comment by caleb87** [comment]
Thanks for the suggestion. I checked and it is set to 4.

I also got a demo working: http://3.85.116.149/index.html
The demo is set to this random spot:
![glitch](https://user-images.githubusercontent.com/6970514/94451123-e37d6200-0162-11eb-8e19-7db786af12cb.jpg)


There are glitches like that all over the map. Some are worse than others.

**Comment by TomPohys** [comment]
Hi @caleb87, did you solved the glitches? Where was the problem? Thanks

**Comment by caleb87** [comment]
I solved it by just using pre-generated tiles.mbtiles instead of postserve. Postserve is also really slow as well in large cities. Great for a quick test though.

**Comment by TomPohys** [comment]
Thanks for your comment.
