### ISSUE TITLE
quickstart fails with error 123

### ISSUE THREAD

**Issue by caleb87** [openmaptiles/openmaptiles#1016]
quickstart failed here with little information as to why. I thought it may have run out of memory, but I upped it to 144gb aws server and it failed again. I was importing North America. 

 Any idea how to determine what the issue was?

```
CREATE FUNCTION
Time: 4.110 ms
psql:/sql/parallel/building.sql:254: NOTICE:  Finished layer building
DO
Time: 0.118 ms
make: *** [import-sql] Error 123

```

**Comment by smellman** [comment]
Can you show `docker-compose logs` output?
I failed with same message with planet importing but I forgot to run this command so I retried import planet.

**Comment by caleb87** [comment]
I'm not real familiar with docker. I know I need to learn it. If i run that command it just outputs:

```
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

I started docker with "sudo service docker start".  


On a side note, I just did a 100mb extract and it finished in like 10 minutes. So the issue is with the size of the import.

**Comment by smellman** [comment]
> So the issue is with the size of the import.
We need to research it is issue with the size or not.
`docker-compose logs` may show postgresql error.

Now I retried importing, maybe I will check it after 3 days. (my machine needs 80 hours to raise this issue)

**Comment by caleb87** [comment]
Yeah I tried docker-compose logs but i only got the  error "couldn't connect". That's when I tried the small import.

I'm trying the North America import again. It takes about 3 hours to happen. If I figure out how to get docker logs i'll post them.

**Comment by TomPohys** [comment]
If you are using Openmaptiles-tools 5.3, there is a `stop` in parallel processing when an error is rose (it will stop processing much early then before). Before 5.3, there can be an error in the middle of the process, but it will continue the `make import-sql` until the end and then shows an error.

So please, try to search for `ERROR:` in a log.

**Comment by caleb87** [comment]
According to the log, the docker images are v5.2. I could try to upgrade and re-run.

Here's my log from the import. The only error I saw was "psql:/sql/parallel/transportation__transportation_name.sql:152: ERROR:  array size exceeds the maximum allowed (1,073,741,823)"

[omt.log](https://github.com/openmaptiles/openmaptiles/files/5328122/omt.log)


It dies while running make **import-sql**.  I can re-run make import-sql and it always dies here:
```
psql:/sql/parallel/building.sql:254: NOTICE:  Finished layer building
DO
Time: 0.118 ms
make: *** [import-sql] Error 123
```

**Comment by caleb87** [comment]
I looked at a healthy log from a North American import I did before, and this is what the output should be.

**CREATE FUNCTION
Time: 2.313 ms
psql:/sql/parallel/building.sql:254: NOTICE:  Finished layer building
DO
Time: 0.119 ms
**Finished importing sql files matching '/sql/parallel/*.sql'
Importing /sql/run_last.sql (md5 4994dd5171b6d68068cb10973b27bc2b  -  39 lines) into Postgres...**
Timing is on.
psql:/sql/run_last.sql:2: NOTICE:  function getmvt(pg_catalog.int4,pg_catalog.int4,pg_catalog.int4) does not exist, skipping
DROP FUNCTION
Time: 0.506 ms
CREATE FUNCTION
Time: 9.688 ms

-------------------------------------------------------------------------------------
====> : Analyze PostgreSQL tables
Start - postgresql: ANALYZE VERBOSE;**

**Comment by caleb87** [comment]
> > So the issue is with the size of the import.
> 
> We need to research it is issue with the size or not.
> `docker-compose logs` may show postgresql error.
> 
> Now I retried importing, maybe I will check it after 3 days. (my machine needs 80 hours to raise this issue)

So I deleted all my OMT files and docker images, started fresh, and it worked. I don't know how I was able to jack it up. Let me know if you get yours to work and I'll close this issue.

**Comment by smellman** [comment]
I get the errors with planet when `CREATE MATERIALIZED VIEW osm_transportation_merge_linestring`.
It seems [shared memory issue](https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device).
```
postgres_1                      | 2020-10-05T09:56:35.679281206Z 2020-10-05 09:56:35.679 GMT [1681] ERROR:  canceling autovacuum task
postgres_1                      | 2020-10-05T09:56:35.679377305Z 2020-10-05 09:56:35.679 GMT [1681] CONTEXT:  while scanning block 425112 of relation "import.osm_poi_polygon"
postgres_1                      | 2020-10-05T09:56:35.679483184Z        automatic vacuum of table "openmaptiles.import.osm_poi_polygon"
postgres_1                      | 2020-10-05T09:56:36.109275376Z 2020-10-05 09:56:36.109 GMT [1684] ERROR:  canceling autovacuum task
postgres_1                      | 2020-10-05T09:56:36.109358306Z 2020-10-05 09:56:36.109 GMT [1684] CONTEXT:  while scanning block 4222863 of relation "import.osm_highway_linestring"
postgres_1                      | 2020-10-05T09:56:36.109459794Z        automatic vacuum of table "openmaptiles.import.osm_highway_linestring"
postgres_1                      | 2020-10-05T10:01:39.248890145Z 2020-10-05 10:01:39.246 GMT [1687] ERROR:  canceling autovacuum task
postgres_1                      | 2020-10-05T10:01:39.248954825Z 2020-10-05 10:01:39.246 GMT [1687] CONTEXT:  while scanning block 6648095 of relation "import.osm_building_polygon"
postgres_1                      | 2020-10-05T10:01:39.248975174Z        automatic vacuum of table "openmaptiles.import.osm_building_polygon"
postgres_1                      | 2020-10-05T10:14:22.675457487Z 2020-10-05 10:14:22.675 GMT [1844] ERROR:  canceling autovacuum task
postgres_1                      | 2020-10-05T10:14:22.675539767Z 2020-10-05 10:14:22.675 GMT [1844] CONTEXT:  while scanning block 131754 of relation "import.osm_landuse_polygon_gen1"
postgres_1                      | 2020-10-05T10:14:22.675633087Z        automatic vacuum of table "openmaptiles.import.osm_landuse_polygon_gen1"
postgres_1                      | 2020-10-05T13:15:59.186207507Z 2020-10-05 13:15:59.186 GMT [2256] ERROR:  invalid memory alloc request size 3318371140
postgres_1                      | 2020-10-05T13:15:59.187327925Z 2020-10-05 13:15:59.186 GMT [2256] CONTEXT:  PL/pgSQL function osm_building_block_gen1() line 6 at FOR over SELECT rows
postgres_1                      | 2020-10-05T13:15:59.187350485Z 2020-10-05 13:15:59.186 GMT [2256] STATEMENT:  CREATE MATERIALIZED VIEW osm_building_block_gen1 AS
postgres_1                      | 2020-10-05T13:15:59.187355555Z        SELECT *
postgres_1                      | 2020-10-05T13:15:59.205154907Z        FROM osm_building_block_gen1();
postgres_1                      | 2020-10-05T13:20:27.579531739Z 2020-10-05 13:20:27.579 GMT [2248] ERROR:  could not resize shared memory segment "/PostgreSQL.1085808662" to 50438144 bytes: No space left on device
postgres_1                      | 2020-10-05T13:20:27.579596089Z 2020-10-05 13:20:27.579 GMT [2248] STATEMENT:  CREATE MATERIALIZED VIEW osm_transportation_merge_linestring AS
postgres_1                      | 2020-10-05T13:20:27.579606789Z        (
postgres_1                      | 2020-10-05T13:20:27.579616089Z        SELECT (ST_Dump(geometry)).geom AS geometry,
postgres_1                      | 2020-10-05T13:20:27.579623669Z               NULL::bigint AS osm_id,
postgres_1                      | 2020-10-05T13:20:27.579630809Z               highway,
postgres_1                      | 2020-10-05T13:20:27.579639039Z               construction,
postgres_1                      | 2020-10-05T13:20:27.579645129Z               z_order
postgres_1                      | 2020-10-05T13:20:27.579651529Z        FROM (
postgres_1                      | 2020-10-05T13:20:27.579657759Z                 SELECT ST_LineMerge(ST_Collect(geometry)) AS geometry,
postgres_1                      | 2020-10-05T13:20:27.579663439Z                        highway,
postgres_1                      | 2020-10-05T13:20:27.579669899Z                        construction,
postgres_1                      | 2020-10-05T13:20:27.579675879Z                        min(z_order) AS z_order
postgres_1                      | 2020-10-05T13:20:27.579682059Z                 FROM osm_highway_linestring
postgres_1                      | 2020-10-05T13:20:27.579688389Z                 WHERE (highway IN ('motorway', 'trunk', 'primary') OR
postgres_1                      | 2020-10-05T13:20:27.579724069Z                        highway = 'construction' AND construction IN ('motorway', 'trunk', 'primary'))
postgres_1                      | 2020-10-05T13:20:27.579741929Z                   AND ST_IsValid(geometry)
postgres_1                      | 2020-10-05T13:20:27.579752589Z                 GROUP BY highway, construction
postgres_1                      | 2020-10-05T13:20:27.579760299Z             ) AS highway_union
postgres_1                      | 2020-10-05T13:20:27.579766669Z            ) /* DELAY_MATERIALIZED_VIEW_CREATION */;
postgres_1                      | 2020-10-05T13:20:27.579777969Z 2020-10-05 13:20:27.579 GMT [2398] FATAL:  terminating connection due to administrator command
postgres_1                      | 2020-10-05T13:20:27.579784509Z 2020-10-05 13:20:27.579 GMT [2398] STATEMENT:  CREATE MATERIALIZED VIEW osm_transportation_merge_linestring AS
postgres_1                      | 2020-10-05T13:20:27.579790649Z        (
postgres_1                      | 2020-10-05T13:20:27.579796619Z        SELECT (ST_Dump(geometry)).geom AS geometry,
postgres_1                      | 2020-10-05T13:20:27.579802219Z               NULL::bigint AS osm_id,
postgres_1                      | 2020-10-05T13:20:27.579808819Z               highway,
postgres_1                      | 2020-10-05T13:20:27.579814159Z               construction,
postgres_1                      | 2020-10-05T13:20:27.579819779Z               z_order
postgres_1                      | 2020-10-05T13:20:27.579825909Z        FROM (
postgres_1                      | 2020-10-05T13:20:27.579831719Z                 SELECT ST_LineMerge(ST_Collect(geometry)) AS geometry,
postgres_1                      | 2020-10-05T13:20:27.579836949Z                        highway,
postgres_1                      | 2020-10-05T13:20:27.579842159Z                        construction,
postgres_1                      | 2020-10-05T13:20:27.579847429Z                        min(z_order) AS z_order
postgres_1                      | 2020-10-05T13:20:27.579865319Z                 FROM osm_highway_linestring
postgres_1                      | 2020-10-05T13:20:27.579872119Z                 WHERE (highway IN ('motorway', 'trunk', 'primary') OR
postgres_1                      | 2020-10-05T13:20:27.579889399Z                        highway = 'construction' AND construction IN ('motorway', 'trunk', 'primary'))
postgres_1                      | 2020-10-05T13:20:27.579897859Z                   AND ST_IsValid(geometry)
postgres_1                      | 2020-10-05T13:20:27.579903559Z                 GROUP BY highway, construction
postgres_1                      | 2020-10-05T13:20:27.579909429Z             ) AS highway_union
postgres_1                      | 2020-10-05T13:20:27.579914409Z            ) /* DELAY_MATERIALIZED_VIEW_CREATION */;
...
postgres_1                      | 2020-10-05T13:20:27.582967340Z 2020-10-05 13:20:27.582 GMT [1] LOG:  background worker "parallel worker" (PID 2395) exited with exit code 1
postgres_1                      | 2020-10-05T13:20:27.583003620Z 2020-10-05 13:20:27.582 GMT [1] LOG:  background worker "parallel worker" (PID 2396) exited with exit code 1
postgres_1                      | 2020-10-05T13:20:27.583010290Z 2020-10-05 13:20:27.582 GMT [1] LOG:  background worker "parallel worker" (PID 2397) exited with exit code 1
postgres_1                      | 2020-10-05T13:20:27.583015380Z 2020-10-05 13:20:27.582 GMT [1] LOG:  background worker "parallel worker" (PID 2398) exited with exit code 1
postgres_1                      | 2020-10-05T14:33:00.282484447Z 2020-10-05 14:33:00.282 GMT [2605] ERROR:  canceling autovacuum task
postgres_1                      | 2020-10-05T14:33:00.282518487Z 2020-10-05 14:33:00.282 GMT [2605] CONTEXT:  while scanning block 141708 of relation "public.osm_waterway_linestring"
postgres_1                      | 2020-10-05T14:33:00.282524917Z        automatic vacuum of table "openmaptiles.public.osm_waterway_linestring"
postgres_1                      | 2020-10-05T15:29:47.896159420Z 2020-10-05 15:29:47.895 GMT [2666] ERROR:  canceling autovacuum task
postgres_1                      | 2020-10-05T15:29:47.896210811Z 2020-10-05 15:29:47.895 GMT [2666] CONTEXT:  while scanning block 10695 of relation "public.osm_poi_point"
postgres_1                      | 2020-10-05T15:29:47.896221571Z        automatic vacuum of table "openmaptiles.public.osm_poi_point"
```

**Comment by caleb87** [comment]
> bytes: No space left on device

Says right here what your error is: bytes: **No space left on device**

**Comment by smellman** [comment]
@caleb87 `No space left on device` is not only hard drive issue..., disk full, inode, or memory issue.

**Comment by darkm20** [comment]
Hello! Similar error on my side as well: Error 124 while generating europe at the stage of "import-sql".
quickstart for small countries (Albania, Italy, ...) works properly.
For Europe I run it manually. Make import-osm is OK.
The VM is quite powerful with 8 CPUs and 16GB. I get the error after approx 2 days of processing.

Docker version:
Docker version 19.03.13, build 4484c46d9d
Docker-compose:
docker-compose version 1.27.4, build 40524192

I attach the docker-compose logs.
[docker-compose.log](https://github.com/openmaptiles/openmaptiles/files/5607165/docker-compose.log)
<img width="784" alt="screeb" src="https://user-images.githubusercontent.com/19962515/100436568-d1a33700-309f-11eb-83ad-1a48bc1075ed.PNG">

Thank you!

**Comment by TomPohys** [comment]
Hi @darkm20, what version of OMT do you used (are you using #1044 fix?). There are parallel processing of import-sql, so in log have to be some error during processing. Could you please look at it? 

Thanks

**Comment by darkm20** [comment]
> Hi @darkm20, what version of OMT do you used (are you using #1044 fix?). There are parallel processing of import-sql, so in log have to be some error during processing. Could you please look at it?
> 
> Thanks

Hello @TomPohys ! Thanks for the quick response!
I just updated my local repo with the latest changes (the one which I've run was about 2 weeks old).
It's strange because I limited the zoom levels 0-10.
Anyway pulled now the latest changes and re-run the quickstart europe. Let's see if I have an improvement.
This time I will let the quickstart do the entire process autonomously. I will be back here with the logs as soon as it will be completed.

Thanks again!

**Comment by TomPohys** [comment]
OK, let's wait.

The zoom limitation is for `generate-tiles`. The `import-osm` and `import-sql` includes all tables, mat.view and views which are defined in `openmaptiles.yaml`. So if there is any change in any `layer` folder (sqls or yamls), please do not forget to run `make clean` (remove `build` folder).

**Comment by caleb87** [comment]
> OK, let's wait.
> 
> The zoom limitation is for `generate-tiles`. The `import-osm` and `import-sql` includes all tables, mat.view and views which are defined in `openmaptiles.yaml`. So if there is any change in any `layer` folder (sqls or yamls), please do not forget to run `make clean` (remove `build` folder).

Pretty sure this was my issue, which is why it worked when I just started from scratch.

I prefer serving tiles with postserve though. Much easier in my opinion. I use cloudfront to cache it for a few days. As far as i understand, the import-diff/generate-changed-vectortiles only does zoom 14, so you have to manually figure out which tiles to regenerate for z0-13.

**Comment by darkm20** [comment]
> OK, let's wait.
> 
> The zoom limitation is for `generate-tiles`. The `import-osm` and `import-sql` includes all tables, mat.view and views which are defined in `openmaptiles.yaml`. So if there is any change in any `layer` folder (sqls or yamls), please do not forget to run `make clean` (remove `build` folder).

Hello @TomPohys , just for your update the process runs flawlessly now, thanks to your quick indications!
I was able to generate europe with about 1.5 days with my current config.
As well I was able to generate sub tiles by limiting the bounding box.

Thank you again! I really appreciate.

**Comment by TomPohys** [comment]
Thank you all for the discussion.
