### ISSUE TITLE
major roads with no name on map

### ISSUE THREAD

**Issue by caleb87** [openmaptiles/openmaptiles#1017]
The maps linked below show two major roads that display no road name at any zoom level. OSM itself has no name, but it has a road number and a relation with a road name. 

The road number for the one is: RM 3260
The relation is Ranch to Market Road 3260

https://www.maptiler.com/maps/#bright//vector/14.7/-100.36436/36.20038
https://www.openstreetmap.org/edit#map=19/36.20177/-100.36639

How would we get the road number or relation name to show instead?

**Comment by TomPohys** [comment]
Hi @caleb87, the change has to be done in style for layer `transportation_name`, where instead of `name` you want to tho show `ref`.

**Comment by caleb87** [comment]
You are right. Thanks for the explanation.
