### ISSUE TITLE
Differences between downloaded and self-generated map tiles

### ISSUE THREAD

**Issue by Cacaonut** [openmaptiles/openmaptiles#1019]
Hello there!

I've been using OpenMapTiles downloaded for free from the website in my applications for a while now. But as the latest version available there is from 2017 I tried generating them myself. Viewing the results for a map of the Alps in QGIS I noticed the following difference:
In the downloaded maps there is data available outside the Alps for higher zoom levels as well, while in the self-generated maps there is only data on zoom level 0 and on zoom level 1 and greater just the tiles containing the Alps have any data, as you can see in the images below.

![image](https://user-images.githubusercontent.com/26356901/95449707-696c8a80-0965-11eb-9601-ff63313ae8ac.png)
Downloaded tiles at **zoom level 0**

![image](https://user-images.githubusercontent.com/26356901/95449848-a20c6400-0965-11eb-8899-0d570f106e4b.png)
Self-generated tiles at **zoom level 0**: Notice, that the points, which contain state names, are not here.

![image](https://user-images.githubusercontent.com/26356901/95450043-f4e61b80-0965-11eb-9256-d172bf2bbfa0.png)
Downloaded tiles at **zoom level 1**

![image](https://user-images.githubusercontent.com/26356901/95450093-0b8c7280-0966-11eb-807e-1798d4046256.png)
Self-generated tiles at **zoom level 1**: Only the upper right tile is displayed, as it contains the Alps.

The tiles were manually generated using those commands and editing the .env file to set MAX_ZOOM to 14:
```
make
make start-db
make import-data
make download area=alps
make import-osm
make import-borders
make import-wikidata
make import-sql
make generate-dc-config
make generate-tiles
```
Using quickstart.sh gave the same result.

Was the downloadable map generated differently or have there been any changes that cause this behaviour since 2017?

**Comment by TomPohys** [comment]
Hi @Cacaonut, the free downloadable vector tiles from [2017](https://openmaptiles.com/downloads/dataset/osm/europe/alps/#5.25/46.983/11.131) were created by [OpenMapTiles v 3.6.1](https://github.com/openmaptiles/openmaptiles/releases/tag/v3.6.1). If you create your own vector tiles by using the OpenMapTiles project the last stable version is [3.11](https://github.com/openmaptiles/openmaptiles/releases/tag/v3.11) and the release of version [3.12](https://github.com/openmaptiles/openmaptiles/issues?q=is%3Aopen+is%3Aissue+milestone%3Av3.12) is very close.

From version OpenMapTiles version 3.6 were done a lot of enhancement in data and style for vector tiles. If you would like to have the same data in manually generated tiles, please download the release [OpenMapTiles v 3.6.1](https://github.com/openmaptiles/openmaptiles/releases/tag/v3.6.1) and generate tiles again by using [REAMDE](https://github.com/openmaptiles/openmaptiles/tree/3.6.1) from this release.

I hope that it helps.

**Comment by Cacaonut** [comment]
Ok, thanks for the clarification. I'm just going to generate vector tiles of the entire world on lower zoom levels and only the Alps on higher zoom levels and merge those two files afterwards. That should give me nearly the same data as the downloadable tiles but with the most recent version.
