### ISSUE TITLE
cannot drop table backup.osm_landuse_polygon

### ISSUE THREAD

**Issue by kender1314** [openmaptiles/openmaptiles#1020]
I follow the tutorial, this error occurs when I execute the "make import-osm" command

SQL Error: pq: cannot drop table backup.osm_landuse_polygon because other objects depend on it in query SELECT DropGeometryTable('backup', 'osm_landuse_polygon');

data: central-america-latest.osm.pbf

**Comment by kender1314** [comment]
I follow the tutorial, this error occurs when I execute the "make import-osm" command

SQL Error: pq: cannot drop table backup.osm_landuse_polygon because other objects depend on it in query SELECT DropGeometryTable('backup', 'osm_landuse_polygon');

data: central-america-latest.osm.pbf

**Comment by kender1314** [comment]
How to solve this problem, thank you

**Comment by TomPohys** [comment]
Hi @kender1314, does the quickstart work?

**Comment by kender1314** [comment]
> Hi @kender1314, does the quickstart work?

Can be used normally

**Comment by TomPohys** [comment]
Did you run `make import-osm` into a clear (after import-data and import-borders) PostgreSQL or there was some data? 

Does `./quickstart.sh central-america` meet your requirements?

**Comment by kender1314** [comment]
Thank you very much, it should be that the data has not been cleaned up.

**Comment by kender1314** [comment]
Thank you very much, it should be that the data has not been cleaned up @TomPohys
