### ISSUE TITLE
requests.exceptions.ProxyError: HTTPSConnectionPool(host='query.wikidata.org', port=443): Max retries exceeded with url: /bigdata/namespace/wdq/sparql (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

### ISSUE THREAD

**Issue by kender1314** [openmaptiles/openmaptiles#1023]
I followed the tutorial and when I ran the ./quickstart.sh albania command, this error occurred

---------------------------------------------------------------------------------------------------------------------
====> : Start importing Wikidata: Wikidata Query Service -> PostgreSQL
      : The Wikidata license: CC0 - https://www.wikidata.org/wiki/Wikidata:Main_Page 
      : Thank you Wikidata Contributors ! 
docker-compose  run --rm --user=0:0 openmaptiles-tools import-wikidata --cache /cache/wikidata-cache.json openmaptiles.yaml
Found 13 tables with the 'tags' hstore fields
  * osm_aerodrome_label_point
  * osm_city_point
  * osm_continent_point
  * osm_country_point
  * osm_island_point
  * osm_island_polygon
  * osm_marine_point
  * osm_peak_point
  * osm_poi_point
  * osm_poi_polygon
  * osm_state_point
  * osm_water_polygon
  * osm_waterway_linestring
Cache file /cache/wikidata-cache.json does not exist, will create
Searching for Wikidata IDs in 13 tables...
Found 553 Wikidata IDs to load.
Dropping and Re-creating wd_names table...
  NOTICE: table "wd_names" does not exist, skipping @ None
Query Wikidata Query Service for 553 IDs...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 930, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 361, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query.wikidata.org', port=443): Max retries exceeded with url: /bigdata/namespace/wdq/sparql (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/import-wikidata", line 286, in <module>
    asyncio.run(main(docopt(__doc__, version=openmaptiles.__version__)))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/src/app/import-wikidata", line 130, in main
    dups = await create_ids_from_wdqs(conn, new_ids, cache, storage_table, verbose)
  File "/usr/src/app/import-wikidata", line 171, in create_ids_from_wdqs
    for row in wd_query(query):
  File "/usr/src/app/import-wikidata", line 267, in wd_query
    r = requests.post(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='query.wikidata.org', port=443): Max retries exceeded with url: /bigdata/namespace/wdq/sparql (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

------------------------------------------------------------------------------------------------------------------------

Because of the wall, I set up a proxy for  openmaptiles-tools in docker-compose.yaml

----------------------------------------------------------------------------------------------------------------------

 openmaptiles-tools:
    image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}"
    env_file: .env
    environment:
      # Must match the version of this file (first line)
      # download-osm will use it when generating a composer file
      MAKE_DC_VERSION: "2.3"
      # Allow DIFF_MODE, MIN_ZOOM, and MAX_ZOOM to be overwritten from shell
      DIFF_MODE: ${DIFF_MODE}
      MIN_ZOOM: ${MIN_ZOOM}
      MAX_ZOOM: ${MAX_ZOOM}
      # Imposm configuration file describes how to load updates when enabled
      IMPOSM_CONFIG_FILE: ${IMPOSM_CONFIG_FILE}
      # Which files to use during import-borders processing
      BORDERS_CLEANUP_FILE: ${BORDERS_CLEANUP_FILE}
      BORDERS_PBF_FILE: ${BORDERS_PBF_FILE}
      BORDERS_CSV_FILE: ${BORDERS_CSV_FILE}
      # Control import-sql processes
      MAX_PARALLEL_PSQL: ${MAX_PARALLEL_PSQL}
      http_proxy: http://192.168.59.100:8118
      https_proxy: https://192.168.59.100:8118
      HTTP_PROXY: http://192.168.59.100:8118
      HTTPS_PROXY: https://192.168.59.100:8118
    networks:
      - postgres_conn
    volumes:
      - .:/tileset
      - ./data:/import
      - ./build/sql:/sql
      - ./build:/mapping
      - ./cache:/cache

---------------------------------------------------------------------------------------------------------------------
I have tested it myself, and I created a new container with docker-compose, using this proxy can be normal.
How to solve this problem, thank you very much

**Comment by TomPohys** [comment]
Hi @kender1314, something similar was mention in https://github.com/openmaptiles/openmaptiles/issues/784 or https://github.com/openmaptiles/openmaptiles/issues/801. Please try to modify docker setup to be able to pass through the proxy. 

Thanks

**Comment by kender1314** [comment]
Execute the following command to solve this problem
`pip install cryptography
pip install pyOpenSSL
pip install certifi`

**Comment by TomPohys** [comment]
Thanks @kender1314 for the comment!

**Comment by KingKOl** [comment]
```bash
line 575：replace with this
import-wikidata: init-dirs
	$(DOCKER_COMPOSE) $(DC_CONFIG_CACHE) run $(DC_OPTS_CACHE) openmaptiles-tools bash -c \
	'pip install cryptography pyOpenSSL certifi && \
	import-wikidata --cache /cache/wikidata-cache.json $(TILESET_FILE)'
```

**Comment by KingKOl** [comment]
@TomPohys @TomPohys @kender1314 

in makefile line 575：replace with this to solve this problem
```
import-wikidata: init-dirs
	$(DOCKER_COMPOSE) $(DC_CONFIG_CACHE) run $(DC_OPTS_CACHE) openmaptiles-tools bash -c \
	'pip install cryptography pyOpenSSL certifi && \
	import-wikidata --cache /cache/wikidata-cache.json $(TILESET_FILE)'
```
