### ISSUE TITLE
 convert_housenumber_point takes forever (any hints?)

### ISSUE THREAD

**Issue by stryba** [openmaptiles/openmaptiles#1024]
I am trying to create mbtiles for europe using openmaptiles quickstart.sh (docker).
Machine is:
6 Epyc Cores
24GB RAM
600 GB SSDs

Just finished poi layer sql and sits on housenumber sql (convert_housenumber_point(true)) for 6 days already, using 1 core and 4 GB of RAM only. Is this normal?

**Comment by quentar** [comment]
From my personal experience as just user:
 it takes a while, europe is most dense and biggest region there is (in terms of data), you might want to mount additional swap as in peaks it can take up to 64GB so you risk running out of memory. 
Rendering zoom14 for whole europe on 1 machine might take a month really.
I had some luck tweaking postgresql to use more memory for speeds up (ie
`command: postgres -c work_mem=1GB -c maintenance_work_mem=1GB -c shared_buffers=2GB -c temp_buffers=256MB`
into docker_compose.yml `services: postgres:` section, but then it eats more memory so you need more swap.

If you use last release 3.11 it might get through initial import faster.

**Comment by stryba** [comment]
Thanks for the input. I don't believe it is rendering yet, I think it is still importing though. The select query for housnumbers in `convert_housenumber_point` takes forever. Not sure memory will help me here as it only uses 4 GB right now. Never the less I have enough swap set though.

**Comment by eva-j** [comment]
Duplicate to https://github.com/openmaptiles/openmaptiles/issues/1005
