### ISSUE TITLE
generated disputed boundaries data into PostgreSQL and missing in .mbtiles file

### ISSUE THREAD

**Issue by chidwilash** [openmaptiles/openmaptiles#1041]
1. Downloaded disputed boundaries data folder(we can see below reference for disputed boundaries data folder)
(https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-breakaway-disputed-areas/)
2. Converted this folder(ne_10m_admin_0_boundary_lines_disputed_areas) into .osm.pbf file
3. And I included this folder name(ne_10m_admin_0_boundary_lines_disputed_areas) into sql query in opemaptiles-tools/docker/import-data/clean-natural-earth.sh(you can see below image line.no 4 for better understanding)
![Screenshot from 2020-11-17 13-05-22](https://user-images.githubusercontent.com/54620832/99359907-c731b200-28d5-11eb-8290-2ce288721e57.png)

4. Build a new docker image with these disputed boundaries changes
5. And then generate the .mbtiles

**Comment by TomPohys** [comment]
Hi @chidwilash, what boundary features will be in mbtiles file depends on the schema of the `boundary` layer. Please, modify the [function layer_boundary](https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.sql) in `bountary.sql`.

**Comment by chidwilash** [comment]
Thanks

>

**Comment by chidwilash** [comment]
Hi Thomas,

How to add new disputed layers data sql query in below file
https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.sql
