### ISSUE TITLE
Water type=lagoon missing

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#1046]
It seems like the water type `lagoon` is missing in the OpenMapTiles vector tiles.

Example area is Indian River Bay on east coast US:

![Screenshot 2020-11-25 at 1 33 02 PM](https://user-images.githubusercontent.com/59284/100229381-726ce780-2f24-11eb-85b5-a1f1d110a246.png)
https://www.maptiler.com/maps/#streets//vector/11.81/-75.13255/38.65809

![Screenshot 2020-11-25 at 1 33 19 PM](https://user-images.githubusercontent.com/59284/100229414-7c8ee600-2f24-11eb-8e52-c5620daab434.png)
https://www.openstreetmap.org/#map=13/38.6437/-75.1527

**Comment by lazaa32** [comment]
Related to https://github.com/openmaptiles/openmaptiles/pull/605 ?

**Comment by eva-j** [comment]
After really short look - as `natural=water` it should be included in OMT already.
For now there is no `natural=bay` in tags (see also "note" https://www.openstreetmap.org/relation/6366094) so it should not be related to #605.

**Comment by klokan** [comment]
Another missing `natural=water`:
https://www.maptiler.com/maps/#streets//vector/12/-76.32795/38.93226
![Screenshot 2020-11-26 at 16 04 54](https://user-images.githubusercontent.com/59284/100366603-4d01db80-3001-11eb-8665-fd1698c090a2.png)
https://www.openstreetmap.org/#map=13/38.9342/-76.3084

**Comment by TomPohys** [comment]
These water polygons were many times re-tagged in history, but are now correctly tagged as `natural:water` in OSM, so in release 3.12 they will be correctly displayed.

**Comment by TomPohys** [comment]
Tested with v3.12 and lagoons are there.
