### ISSUE TITLE
Cemetery tagged as amenity=grave_yard are missing

### ISSUE THREAD

**Issue by pyrog** [openmaptiles/openmaptiles#1057]
`amenity=grave_yard` are missing in tiles, only the POI is present.

Example : [way 31855109](https://www.openstreetmap.org/way/31855109)
See in [Maputnik](https://maputnik.github.io/editor/#17/47.72471/-3.33599)

**Comment by TomPohys** [comment]
Hi @pyrog, thank you for your notice. Graveyard should be included in OpenMapTiles (bigger landuse=cemetery are included). Are you able to create PR? Thanks a lot.
