### ISSUE TITLE
Add city subdivision place=quarter

### ISSUE THREAD

**Issue by jdhoek** [openmaptiles/openmaptiles#1064]
The OSM-based website [knooppuntnet.nl](https://knooppuntnet.nl/en/map/hiking) uses OSM Liberty through OpenMapTiles. The rendered tiles currently lack `place=quarter` tags, even though the larger `place=suburb` and smaller `place=neighbourhood` are included. I would like to see `place=quarter` rendered as well (https://github.com/vmarc/knooppuntnet/issues/136).

Because `place=quarter` sits between `place=suburb` and `place=neighbourhood` in the OSM tagging hierarchy of city subdivisions, adding it to OpenMapTiles looks straightforward. I have done so here: https://github.com/jdhoek/openmaptiles/commit/bc8b21c883e34ef58289861bc0aaa7a54e2245c9

Is this sufficient to be able to use it in a style such as OSM Liberty and submit a patch there?

**Comment by TomPohys** [comment]
Hi @jdhoek, thank you for your notice. It looks useful to have a `quarter` in OpenMapTiles. Do you have time to create a PR?

**Comment by jdhoek** [comment]
I had the commit ready, but this project's guidelines forbade offering a PR without an issue and the `help wanted` tag edit by one of the maintainers.

**Comment by jdhoek** [comment]
#1065 has that commit.
