### ISSUE TITLE
class=island missing

### ISSUE THREAD

**Issue by webmap2015** [openmaptiles/openmaptiles#1067]
Hi, some island is missing in the OpenMapTiles vector tiles.

Example area is Sea of Marmara on Turkey.

![image](https://user-images.githubusercontent.com/10267317/105098252-da6e2300-5aba-11eb-938a-f9f215281492.png)

https://www.maptiler.com/maps/#streets//vector/8.76/28.4769/40.6919

![image](https://user-images.githubusercontent.com/10267317/105097867-57e56380-5aba-11eb-8af6-6783a716eaf3.png)

https://www.openstreetmap.org/#map=10/40.6650/28.3365

Thanks.

**Comment by TomPohys** [comment]
Hi @webmap2015, thank you. It looks like there is some problem with relations (tags) in OSM https://www.openstreetmap.org/relation/5511568.

**Comment by webmap2015** [comment]
Hi,
Between zoom level  5 and 5.99, the island appears.

![image](https://user-images.githubusercontent.com/10267317/106365220-191a9d80-6345-11eb-8c66-10ae6c11853e.png)

https://www.maptiler.com/maps/#streets//vector/5/30.63/39.73
https://www.maptiler.com/maps/#streets//vector/5.99/30.63/39.73

**Comment by webmap2015** [comment]
Thanks.
