### ISSUE TITLE
setup: make command exits with code 1

### ISSUE THREAD

**Issue by NicholasKonrad** [openmaptiles/openmaptiles#1075]
I cloned this repo onto my machine that is running the following:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041

To be able to execute the makefile I installed MinGW via Chocolately. With Docker being installed for Windows and the Linux subsystem I am running Docker 20.10, docker-compose 1.27, GNU bash 5.0.17, git 2.28. I  executed the "make" command with the current path being just inside the folder where the makefile is stored.
It returns the following message: 

`$ mingw32-make`
```
'pwd' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
The system cannot find the path specified.
'tr' is not recognized as an internal or external command,
operable program or batch file.
'id' is not recognized as an internal or external command,
operable program or batch file.
'id' is not recognized as an internal or external command,
operable program or batch file.
The syntax of the command is incorrect.
Makefile:235: recipe for target 'init-dirs' failed
mingw32-make: *** [init-dirs] Error 1
```

I am unfamiliar with both Docker and Unix systems so I do not how to handle those errors. How I get this repo running on a Windows PC?

**Comment by TomPohys** [comment]
Hi @NicholasKonrad, the most straightforward way is to use WSL (Windows Subsystem for Linux). I wrote some step by step manual for this in https://github.com/openmaptiles/openmaptiles/issues/1095#issuecomment-817099375.

**Comment by TomPohys** [comment]
Hi @NicholasKonrad, is this still a problem?

**Comment by TomPohys** [comment]
Thanks, was the manual useful?

**Comment by NicholasKonrad** [comment]
Hi @TomPohys, we ended up using a different framework so using WSL was not required. Thank you for still showing interest in this issue.
