### ISSUE TITLE
Error during 'make import-sql'

### ISSUE THREAD

**Issue by agoddard** [openmaptiles/openmaptiles#1076]
Howdy 👋 I'm playing with a planet import at the moment, and the `make import-sql`  task failed with the following output:

```
CREATE FUNCTION
Time: 10.083 ms
psql:/sql/parallel/poi.sql:450: NOTICE:  Finished layer poi
DO
Time: 0.575 ms
make: *** [Makefile:397: import-sql] Error 124
```

The only things that look out of place in the Postgres logs are lines such as:
```
postgres_1                      | CONTEXT:  PL/pgSQL function populate_geometry_columns(oid,boolean) line 64 at RAISE
postgres_1                      | WARNING:  Could not convert 'geometry' in 'import.osm_park_polygon_gen_z6' to use typmod with srid 3857, type Polygon: Geometry type (MultiPolygon) does not match colum
n type (Polygon)
postgres_1                      | CONTEXT:  PL/pgSQL function populate_geometry_columns(oid,boolean) line 64 at RAISE
```

though it is unclear whether this is related.

I'm wondering how best to troubleshoot the issue? A subsequent `make update-osm` fails with `[Feb  4 19:39:55] [diff] unable to read last.state.txtstat /import/last.state.txt: no such file or directory` so it seems as though the error with import-sql stopped the complete import.

**Comment by reissig** [comment]
same issue

Release 3.12.1
./quickstart north-america

make: *** [Makefile:397: import-sql] Fehler 124

395 .PHONY: import-sql
396 import-sql: all start-db-nowait
397         $(DOCKER_COMPOSE) run $(DC_OPTS) openmaptiles-tools sh -c 'pgwait && import-sql' | \
398           awk -v s=": WARNING:" '1{print; fflush()} $$0~s{print "\n*** WARNING detected, aborting"; exit(1)}'

**Comment by TomPohys** [comment]
Hi @agoddard, the error `type Polygon: Geometry type (MultiPolygon) does not match column` could be caused by some changes in OSM, which now caused creating `multipolygon` during import. Could you please look into the database into table `osm_park_polygon_gen_z6` or `osm_park_polygon_gen_z7` and try to find if there is `multipolygon` instead of `polygon`? Or do you have some older PBF which you can try to import?

But during `import-sql` on `parks` there is only `FUNCTION update_osm_park_polygon_row()`. And create centroid over `multipolygon` is possible.

**Comment by agoddard** [comment]
@TomPohys ah, that might be the hint there.. this PBF is 4 months old, but I need to import it to generate updated tiles from tiles that were generated back then. Both of those tables have both Types:

```
select distinct ST_GeometryType(geometry) from osm_park_polygon_gen_z7;
 st_geometrytype
-----------------
 ST_MultiPolygon
 ST_Polygon
```

I could perhaps revert to the openmaptiles release from when this PBF was generated, but then would I need to update to the latest release before running `update-osm`, and if so would the tables migrate during that process? Or I could dump the multipolygons and re-import them as polygons 🤔

**Comment by agoddard** [comment]
@reissig I can run the Quickstart on the current version for north america fine in version 3.12.1, your issue might be different - you can run `docker-compose logs` to see the postgresql output, which might provide a hint about a similar issue with one of the db queries.

**Comment by agoddard** [comment]
@TomPohys I tried this on `master` with the latest planet pbf.. I downloaded the latest planet, then ran `update-osm` to get it up to date and then `make import-sql` and got the same error as the old PBF. There are both geometry types present there too:

```
Time: 1012.774 ms (00:01.013)
CREATE TRIGGER
Time: 3.756 ms
CREATE FUNCTION
Time: 10.077 ms
psql:/sql/parallel/poi.sql:450: NOTICE:  Finished layer poi
DO
Time: 0.669 ms
make: *** [Makefile:397: import-sql] Error 124

openmaptiles=# select distinct ST_GeometryType(geometry) from osm_park_polygon_gen_z7;
 st_geometrytype
-----------------
 ST_MultiPolygon
 ST_Polygon
```

(I ran it on master and not 3.12)

**Comment by frodrigo** [comment]
Duplicate of #1018

**Comment by agoddard** [comment]
Thanks @frodrigo! I hadn't noticed that there, will close this and track in #1018.
