### ISSUE TITLE
connect between buildings and realtion associatedStreet

### ISSUE THREAD

**Issue by giskate** [openmaptiles/openmaptiles#1077]
I loaded buildings using .yaml. I would like to realise geocoding using OSM-data, but I can't find attribute that 
connects buildings with associatedStreet from relations. 
Finally I would like to have one table 'buildings' with attribute streetname.

**Comment by TomPohys** [comment]
Hi @giskate, there are several threads that are dealing with buildings. The last one explained, why are buildings with associatedstreet removed : https://github.com/openmaptiles/openmaptiles/pull/841 (as a follower of https://github.com/openmaptiles/openmaptiles/pull/754) and how was previously implemented (https://github.com/openmaptiles/openmaptiles/pull/284). 

I hope it will help.

**Comment by giskate** [comment]
thank you, I applied that approach. Finally I would like to have one table 'buildings' with attribute streetname.

**Comment by TomPohys** [comment]
Hi @giskate, did you make some progress on this? I would like to help you more. Thanks

**Comment by giskate** [comment]
> Hi @giskate, did you make some progress on this? I would like to help you more. Thanks

Hello, @TomPohys , we decided don't use this approach, thank you
