### ISSUE TITLE
error during "make generate-tiles"

### ISSUE THREAD

**Issue by mos168** [openmaptiles/openmaptiles#1078]
I face this error when running quickstart.sh for albania. Ubuntu version 18.04.3 fresh install. The log is attached(includes PC details).
CPU i9-7900X
RAM: 32 GB
Free space 3.4-3.6 TB
Docker version 20.10.3, build 48d30b5
docker-compose version 1.28.2, build 67630359

`[K[1m 46.539s]  21.3459%   4.4k/ 20.6k @   42/s | ✓ 4.4k □ 1.7k | 6m 31s leftutils.sh: line 30:    18 Segmentation fault      (core dumped) "$@" 3>&2- 2>&1- 1>&3-
20 Done                    | ( sed -u "/is deprecated/d" )
1
Makefile:402: recipe for target 'generate-tiles' failed
make: *** [generate-tiles] Error 1`

[quickstart.log](https://github.com/openmaptiles/openmaptiles/files/5959123/quickstart.log)

**Comment by TomPohys** [comment]
Hi @mos168, I have just went `quickstart.sh` for Albania. I tested also the number of threads (10 and 20) and built the tiles up to zoom 14 with no `Segmentation fault`. Did you make some other changes than zoom and number of threads?

**Comment by mos168** [comment]
Hi @TomPohys, the Min zoom was 0 and Max zoom was 14. I tried doing this with different number of threads, 10 and 20. I also changed MAX_PARALLEL_PSQL to 10 and 20 respectively. I made no other changes. I tried it with v3.12 and v3.12.1.

**Comment by mos168** [comment]
Seemed to be some odd hardware issue, even after multiple ubuntu refreshes did not work. Everything seems to work fine on any other machine.
