### ISSUE TITLE
Change aerodrome_label min zoom level to 7

### ISSUE THREAD

**Issue by jehie** [openmaptiles/openmaptiles#1082]
Hello!

Would it be possible to change the min zoom level limit on the [aerodrome_label](https://github.com/openmaptiles/openmaptiles/blob/master/layers/aerodrome_label/aerodrome_label.sql#L40) for example to 7?

Currently, it is not possible to create a map where we could show the locations of the major airports on for example US State level.

I can make the changes and PR, if we can move forward with this.

**Comment by frodrigo** [comment]
Doable. But maybe only for the bigger with at lest `iata` or `icao` code.

**Comment by ZeLonewolf** [comment]
The schema currently has the following `class` values for an aerodrome_label:
* international
* public
* regional
* military
* private
* other

I haven't looked at the question of what zoom might make sense to start showing these, but if we're going to differentiate them it might make sense to have `class=international` show up at a lower zoom than the other values.

**Comment by TomPohys** [comment]
Good idea @ZeLonewolf, `international` with full info `iata` or `icao` (probably most important airports) could be moved to e.g. zoom 8. Zoom 7 should still give a general overview. Aerodrome should also not collide with city names.
