### ISSUE TITLE
embassy and project report on taginfo

### ISSUE THREAD

**Issue by Marc-marc-marc** [openmaptiles/openmaptiles#1084]
in 2018, the community approved  the depreciation of the amenity=embassy tag and approved office=diplomatic diplomatic=embassy
osm2VectorsTiles is listed as using the old tag and I don't find OpenMapTiles [in the project using the new tag](https://taginfo.openstreetmap.org/tags/office=diplomatic#projects)
is OpenMapTiles using the tag but does not report it to taginfo? or is it still the old tag that is used and if so, could you take the new one into account?

**Comment by TomPohys** [comment]
Hi @Marc-marc-marc, you are right, the OMT is using the old `amenity=embassy`. It should be updated to `office=diplomatic`.

**Comment by frodrigo** [comment]
`office=diplomatic` should replace `amenity=embassy`? or as an addition?
From a quick survey, only the Bright style use `embassy`.

**Comment by Marc-marc-marc** [comment]
office=diplomatic replace amenity=embassy.
there are still ~2000 objects having only the old tag (mostly errors as the correct objects have been massively converted) , a manual review and mass editing procedure is underway
