### ISSUE TITLE
planet bbox error

### ISSUE THREAD

**Issue by fabiuk** [openmaptiles/openmaptiles#1086]
Hello,

is someone else also facing an issue at generating planet tiles? I'm using the actual master of openmaptiles and openmaptiles-tools with default configuration of tile generation.

Quickstart call:

`bash quickstart.sh --empty planet`

After the successful download I get this:

```
Traceback (most recent call last):
  File "/usr/src/app/download-osm", line 763, in <module>
    main()
  File "/usr/src/app/download-osm", line 759, in main
    exit(asyncio.run(main_async(docopt(__doc__, version=openmaptiles.__version__))))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/src/app/download-osm", line 691, in main_async
    if bbox:
UnboundLocalError: local variable 'bbox' referenced before assignment
make: *** [Makefile:315: download] Error 1
```

A solution for me was removing `--bbox "$(AREA_BBOX_FILE)"` at the _download-osm_ in the makefile at `.PHONY: $(ALL_DOWNLOADS)`

Am I missing something in the config or in the quickstart execution?

best regards
FPI

**Comment by claustres** [comment]
I don't use the quickstart script but I am running into the same issue with `make download area=planet`. Maybe it's related to the fact that I removed the BBOX var from my `.env` file in order to control it manually when generating tiles.

**Comment by etresoft** [comment]
> A solution for me was removing `--bbox "$(AREA_BBOX_FILE)"` at the _download-osm_ in the makefile at `.PHONY: $(ALL_DOWNLOADS)`

Can you clarify something? When you say this was a solution, did you delete your planet file and start again from scratch? Or did you just try the quickstart again?

I'm seeing the same problem. But when I run the quickstart again, I've already downloaded the planet file, so I avoid the bug. But the only way to test a fix is to download a new planet file, or try to hack things up to avoid that.

I'm guessing the solution would be to change line 688 from:

if exit_code == 0 and args['--bbox']:

to:

if exit_code == 0 and !args.planet and args['--bbox']:

If I am interpreting the .env file correctly, the bbox file is only ever used to override the hard-coded value in .env. If correct, then the above code should work and the correct action would be to just skip this section.

**Comment by fabiuk** [comment]
> Can you clarify something? When you say this was a solution, did you delete your planet file and start again from scratch? Or did you just try the quickstart again?

I'm starting the quickstart in a gitlab ci-pipeline, after a fail there is a cleanup. By doing it manual it works at the second run as the file is already there and it skips that part.

**Comment by etresoft** [comment]
I guess my Python is wrong. Not is not always !. Sometimes it is just not.

**Comment by TomPohys** [comment]
Hi, thanks a lot for point this out. Could you please create a PR into OpenMapTiles Tools? Thanks

**Comment by TomPohys** [comment]
Thanks, OMT-T are updated!
