### ISSUE TITLE
Is there a clean uninstall guideline?

### ISSUE THREAD

**Issue by zcemycl** [openmaptiles/openmaptiles#1087]
Is there a clean uninstall guideline? I manage to clean up the docker images, using docker rm and docker rmi. But many files are still not cleaned up, and occupy my local.

**Comment by frodrigo** [comment]
Clear the data directory.

**Comment by zcemycl** [comment]
@frodrigo The data folder created in this repo? Or somewhere else?

**Comment by frodrigo** [comment]
Yes in the repo.

To you also remove the docker volumes ?

Best way to clean from the project is `docker-compose down -v`

**Comment by zcemycl** [comment]
@frodrigo okay thank you. The storage is back.
