### ISSUE TITLE
How to use osm-bright-gl-style in the map?

### ISSUE THREAD

**Issue by zcemycl** [openmaptiles/openmaptiles#1100]
I follow the steps to run tileserver, 
```
./quickstart.sh
make start-tileserver
```
It shows the styles (only basic preview) and data, and I can view it without problems. But I wonder how I can add osm bright to my styles. Is Mapbox Studio the only way to achieve that? Or I can change settings in `.env` or `openmaptiles.yaml` or `Makefile`?

Thanks

**Comment by rikardomarenzzi** [comment]
Hello @zcemycl i run into the same problem....
So far I found out that you have to create a config.json file in the /data folder. Additionally there have to be styling files in the same folder. 

How to build a config file is described on the website https://tileserver.readthedocs.io/en/latest/config.html explained. 
However, the explanation is far from sufficient. About other forum contributions I have found out that we have to make additional adjustments in the style files. Especially in the style.json file of the associated style.

The next problem is that there is no example of how these style files should be structured. 
Here on Github there are release files for the individual styles for download.

Unfortunately, I have not yet found an exact example. I hope someone can show us an exact example of a real config file with the corresponding style files.

**Comment by amorfinv** [comment]
Hello. I kind if answered this [here](https://github.com/maptiler/tileserver-gl/issues/530#issuecomment-821288022).

It is probably the wrong way to do it. But I guess you don't really need to worry about your config.json.

**Comment by zcemycl** [comment]
@amorfinv Hey, thank you! That helps. But I get confused about the step to restart the container. What I did is, 
1. Let the container running with `make start-tileserver`. Maybe in tmux running as background.
2. Restart it via `docker restart container_id`. 

I will close this issue. Please refer to your [link](https://github.com/maptiler/tileserver-gl/issues/530#issuecomment-821288022).

**Comment by amorfinv** [comment]
Hello @zcemycl,

Glad to hear it worked out for you. I have docker desktop so there is just a button to restart haha. The `docker restart container_id` should do the same thing. I don't use tmux so I am not sure if things would be different.

When you run `make start-tileserver` it will start a server and show the log of your activity. I don't think you will be able to restart with a command in the same terminal session that executed `make start-tileserver`.

You would need to open a new terminal session and then run `docker restart container_id`. However, this closes the log from your `make start-tileserver` terminal session. But your container should still be running. If you run `docker logs -f container_id` after the restart you should see the log again and track the activity of the server.

Docker desktop just makes it a bit easier to track and restart the containers. Unsure if that cleared things up.
