### ISSUE TITLE
Clearify own OSM data instructions

### ISSUE THREAD

**Issue by jvolker** [openmaptiles/openmaptiles#1102]
I've tried using OpenMapTiles with a custom extract from bbbikes.org.  I've followed the instructions in https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md#using-your-own-osm-data but ran into a few issues. I've suggested some changes here: https://github.com/openmaptiles/openmaptiles/pull/1101

Furthermore, I had trouble understanding the following from those instructions:

> Inside of folder have to be docker-compose-config.yml file too, otherwize whole folder data/ will be deleted and download-osm will try to download osm.pbf file from geofabric, osmfr or bbbike.

What folder requires a `docker-compose-config.yml` file? 
It would be great if this paragraph would go a bit further into detail.

Thanks.

**Comment by TomPohys** [comment]
Thanks for PR. You are right, the `docker-compose-congif.yml` is obsolete and it is not used anymore. It was replaced by `area.bbox` file, which contains only bbox value.
