### ISSUE TITLE
Error when running make import-sql

### ISSUE THREAD

**Issue by bricechart** [openmaptiles/openmaptiles#1106]
I'm getting the following error when running _make import-sql_ Any ideas?

`psql:/sql/parallel/building.sql:100: ERROR:  GEOSUnaryUnion: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -8539739.7009410355 4727139.8920735931 at -8539739.7009410355 4727139.8920735931
CONTEXT:  PL/pgSQL function osm_building_block_gen1() line 14 at FOR over SELECT rows
Time: 71378856.199 ms (19:49:38.856)
xargs: sh: exited with status 255; aborting
ERROR: 124
`

**Comment by TomPohys** [comment]
Hi @bricechart, this is duplication for https://github.com/openmaptiles/openmaptiles/issues/1058. Please, update your PostGIS image with `latest` tools ([comment](https://github.com/openmaptiles/openmaptiles/issues/1058#issuecomment-825475217)), where is update GEOS to 3.9.1., which solve this error.
