### ISSUE TITLE
Appearance of disconnected road segments

### ISSUE THREAD

**Issue by caleb87** [openmaptiles/openmaptiles#1107]
**Issue**: All map styles have an appearance of "disconnected" road segments, even though the road is not disconnected.
**Expected**: Road segments should display continuously as the road does in OSM 
**URL**: https://www.maptiler.com/maps/#bright//vector/10.54/-111.7859/33.3631
**Zoom**: 8-10 are the worst, but appears at most zooms
**Screenshot**:  
![omtexample](https://user-images.githubusercontent.com/6970514/115757509-4e86c400-a353-11eb-9e01-887de6640311.jpg)
Styles Affected: All

**Comment by TomPohys** [comment]
Hi @caleb87, thanks a lot for this issue. It looks like there is a too hard filter for the length of a line segment in [transportation.sql](https://github.com/openmaptiles/openmaptiles/blob/76d5d753d8fae35e4d316f5532461835a3acf36b/layers/transportation/transportation.sql#L269)
The zoom 10 really not looks good. The ZRes(11) is c. 76m and in US there is a lot of small segments (changes in tags such as a number of lines, surface,...) (e.g. https://www.openstreetmap.org/edit?way=436932493#map=17/33.33544/-111.84165).

**Comment by caleb87** [comment]
Thanks for the explanation. I wonder what it would take to create a seamless line. Probably would have to pre-compute the OSM data, and merge all ways with end-to-end connections of the same class/attributes? Ugh
