### ISSUE TITLE
[Question] Is it possible to add custom data to tiles? If so, how to do this?

### ISSUE THREAD

**Issue by proprogrammer2015** [openmaptiles/openmaptiles#1112]
Hi guys, 

I really appreciate the work you do on openmaptiles! 

Regarding to that, is it a simple way to add custom data to i.e. boundary feature layer? If so, which tool do I have to modify? Is it possible via yaml layer config?

Thanks in advance ;)

**Comment by frodrigo** [comment]
Not sure what you want to achieve. Maybe look at this

https://github.com/makina-maps/openmaptiles-layer-boundary_polygon
https://github.com/makina-maps/osm-adminstrative-area-gl-style

**Comment by proprogrammer2015** [comment]
Hey @frodrigo ,
Thanks for insights!

I tried your examples and it's almost what I'm looking for, but the relation_ids does not match to me.

Essentially I want to include in boudary layer the osm id of entire ploygon for i.e city/county/district. As for now, when I click the boundary line feature it shows particular line osm_id, but I want entire ploygon osm_id.

I'm not sure how to do this.
Is there any docs regarding composing mapping.yaml and sql files?

**Comment by frodrigo** [comment]
> I tried your examples and it's almost what I'm looking for, but the relation_ids does not match to me.
> 
> Essentially I want to include in boudary layer the osm id of entire ploygon for i.e city/county/district. As for now, when I click the boundary line feature it shows particular line osm_id, but I want entire ploygon osm_id.

The relation id is here https://github.com/makina-maps/openmaptiles-layer-boundary_polygon/blob/master/boundary_polygon/mapping.yaml#L90


> Is there any docs regarding composing mapping.yaml and sql files?

It is an open issue #970

**Comment by proprogrammer2015** [comment]
Yup, you're right @frodrigo. It works very well. Thank you so much!

Nonetheless, I still have to learn more how to compose layer queries, is there any detialed docs about it?
