### ISSUE TITLE
detail information about roads and point of interest are not available in the generated *.mbtiles file

### ISSUE THREAD

**Issue by dinesh3367** [openmaptiles/openmaptiles#1113]
I did generate *.mbtiles extract for the illinois area from openmaptiles quickstart.sh script.
Between commented the make import-wikidata step
The mbtiles generation is completed for illinois area, but while viewing the maps i am not able to see information about roads and point of interest in the choosen area {illinois}

![tileserver](https://user-images.githubusercontent.com/31798603/118803403-efb85a00-b8c0-11eb-8271-b2695b3e667b.png)
![map](https://user-images.githubusercontent.com/31798603/118803274-ca2b5080-b8c0-11eb-8392-922995f5ebea.png)

is there anything i am missing during generation process or the styles team ??

**Comment by TomPohys** [comment]
Hi @dinesh3367, some information and features are available from lower zoom levels. For example POI are available from zoom 12 (public transport stations) and all other POI from zoom 14. This is set up for poi in https://github.com/openmaptiles/openmaptiles/blob/master/layers/poi/poi.sql and graphical version in diagrams which are available for every layer (https://github.com/openmaptiles/openmaptiles/tree/master/layers/poi). This is also available in https://openmaptiles.org/schema/ (Show Diagrams)

**Comment by dinesh3367** [comment]
Thank you for the information. I am able to view the roads and poi in OSM Bright Style. Furthermore i did change the zoom levels and noticed the information presented in the maps.
