### ISSUE TITLE
Add support for highway=motorway_junction

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1114]
Highway exits are an important feature of street centric maps.  Adding `highway=motorway_junction` and `ref` would allow rendering of highway exits as icons and/or labels.

**Comment by klokan** [comment]
Sounds good. Your afford on the American style is great! Would be happy to review any related Pull Requests to OpenMapTiles.

**Comment by ZeLonewolf** [comment]
Here is an example of how highway exits might render in an American-style map:
![image](https://user-images.githubusercontent.com/3254090/120231649-d055f100-c21f-11eb-87bd-e8e1788ab4ae.png)
