### ISSUE TITLE
Failed to import sql data of Europe region

### ISSUE THREAD

**Issue by SitkaCharley** [openmaptiles/openmaptiles#1115]
I followed the instructions on how to prepare, download and import sql data into postgres database, but the proceedure failed at step 'make import-sql' with the following error: 

> psql:/sql/parallel/landcover.sql:30: ERROR:  relation "osm_landcover_polygon" does not exist
LINE 8:     FROM osm_landcover_polygon
                 ^
Time: 1.994 ms
xargs: sh: exited with status 255; aborting
Makefile:391: recipe for target 'import-sql' failed
make: *** [import-sql] Error 124

Previously, I did run the following steps as described in repository's README file:

> make
make start-db
make import-data
make download area=europe
make import-osm
make import-borders

and then

> make import-sql

always fails. Am I doing something wrong or is it a bug? 
I changed `.env` configuration because I've had troubles to execute successfully the prevoius steps. The params I changed are the following:

> BORDERS_CLEANUP=true
MAX_PARALLEL_PSQL=1
COPY_CONCURRENCY=6

================================================================

My machine configuration:

_Software:_
> # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    **Ubuntu 18.04.5 LTS**

Release:        18.04
Codename:       bionic
> # uname -r
**4.15.0**-142-generic
> # docker-compose -v
docker-compose version **1.17.1**, build unknown
> # docker --version
Docker version **20.10.6**, build 370c289

_Hardware:_
6 cores CPU
320 GB Solid drive
16 GB RAM

I attach the whole log for 'make import-sql' step. 

[import-sql.log](https://github.com/openmaptiles/openmaptiles/files/6548228/import-sql.log)
[config-env.txt](https://github.com/openmaptiles/openmaptiles/files/6548237/config-env.txt)

**Comment by SitkaCharley** [comment]
I also successfully has built the tiles for a smaller country - Andorra, applying these same steps.

**Comment by TomPohys** [comment]
`osm_landcover_polygon` table is created during `import-osm` [in mapping.yaml](https://github.com/openmaptiles/openmaptiles/blob/master/layers/landcover/mapping.yaml#L3), so if this table is missing, something must happened during `import-osm` step. Could you please try `make psql-list-tables` or directly `make psql` and try to investigate, what happened with `osm_landcover_polygon` table after `import-osm` step?

Thanks

**Comment by SitkaCharley** [comment]
`osm_landcover_polygon` seem to be missing:

> openmaptiles=# select * from osm_landcover_polygon;
ERROR:  relation "osm_landcover_polygon" does not exist
LINE 1: select * from osm_landcover_polygon;
                      ^

It is not listed in `make psql-list-tables`, as seen in the [result](https://github.com/openmaptiles/openmaptiles/files/6551926/psql-list-tables.log) that command returns

=============================
commit ae9498547d89f7a3aeb74c28be24842781b1970c

**Comment by TomPohys** [comment]
But in the list, there is not any 'osm_*` tables. Went the `import-osm` step without any error?

**Comment by SitkaCharley** [comment]
> But in the list, there is not any 'osm_*`tables. Went the`import-osm` step without any error?

Unfortunately I didn't saved the log and I can't tell for sure. Usually I always check the final result for errors, but this time I thing my ssh session to the server where I build the tiles has expired and thus all console output has been lost. I will start `import-osm` again, pipe the output to a file and will send you the result later today.

**Comment by SitkaCharley** [comment]
Well, `import-osm` return no errors as seen in [the log](https://github.com/openmaptiles/openmaptiles/files/6553990/import-osm.log). `osm_landcover_polygon` is still missing according to `make psql-list-tables` ([psql-list-tables-2.log](https://github.com/openmaptiles/openmaptiles/files/6554058/psql-list-tables-2.log)).

**Comment by TomPohys** [comment]
In the table list, there is still something wrong. If I run manually all steps on master OMT, there are 3 times more tables [tables.log](https://github.com/openmaptiles/openmaptiles/files/6568584/tables.log).

my steps:
```
make start-db
make download area=albania
make import-data
make import-osm
make import-wikidata
make psql-list-tables > tables.log
```
Do you modify `openmaptiles.yaml` in root folder? Are in `build/mapping.yaml` all the layers?

**Comment by SitkaCharley** [comment]
No, I haven't modified `openmaptiles.yaml`. To verrify that I've run

> git diff openmaptiles.yaml

and it returned nothing. `build/mapping.yaml` is empty.

I recreated your steps on a clean project and the result has 3 times more tables as expected 
[make psql-list-tables > tables.log](https://github.com/openmaptiles/openmaptiles/files/6576188/tables.log). 

But while trying to do the same steps from scrach for `area=europe`, the procedure fails with the error I mentioned above (**ERROR: relation "osm_landcover_polygon" does not exist**).

I'm doing an experiment now. First I will generate the tiles of Albania and in the same project I will append `area=europe` to `import-data` to try generate the tiles of Europe.
