### ISSUE TITLE
quickstart.sh generates near-empty mbtiles

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1117]
From an unmodified openmaptiles checkout, I ran `./quickstart.sh florida`, which after a bunch of processing time produced a 760kb tiles.mbtiles.  Since the Florida pbf file is 300MB in size, it seems that the .mbtiles file is not getting populated.

I'm attaching the quickstart.log and the generates tiles.mbtiles that was produced.

[quickstart.log](https://github.com/openmaptiles/openmaptiles/files/6567537/quickstart.log)
[tiles_mbtiles.zip](https://github.com/openmaptiles/openmaptiles/files/6567538/tiles_mbtiles.zip)

Tested (same behavior) on Ubuntu 20.04 and 21.04.  Attached files are from Ubuntu 20.04 run.

**Comment by ZeLonewolf** [comment]
Apparently the issue is that the default setting is to generate tiles only at zoom 0-7, so that's why the output is so tiny!

**Comment by TomPohys** [comment]
Yes, the `quickstart.sh` generate tiles on zooms 0 - 7 by default. (https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md#set-which-zooms-to-generate)
