### ISSUE TITLE
maxspeed seems to be missing

### ISSUE THREAD

**Issue by maxogden** [openmaptiles/openmaptiles#1124]
Hi, I'm interested in using the `maxspeed` tag (for example https://www.openstreetmap.org/way/723730316) but I don't see it in the schema. If I wanted to open a PR to add this, can someone point me an an example PR I can base mine one? Would it be as straightforward as this one? https://github.com/openmaptiles/openmaptiles/pull/1011/files 

Thanks

**Comment by TomPohys** [comment]
Hi, `maxspeed` tag is very related to navigation maps and I understand that it is essential for this type of map. However, this tag is "too" detailed for base maps. `Transportation` layers are very heavy and adding a new tag could cause a significant rise in tile size. Another problem could be, that `maxspeed` tag will create much more line segments which, even more, rise the tile size.

There is still some work on Contribution layers https://github.com/openmaptiles/openmaptiles/issues/970 which could solve adding extra tags or layers into the project.
