### ISSUE TITLE
Expose concurrent highways in transportation_name layer

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1128]
In the US, occasionally highway routes will overlap for short portions (aka, concurrencies).

Here is an extreme example:
![image](https://user-images.githubusercontent.com/3254090/121891170-22e7e080-cce9-11eb-982b-4f06a5bb5285.png)

In US-centric maps, these are often rendered as shield clusters or shields arrange linearly along the route.

OpenMapTiles currently does not expose highway concurrencies in the vector tiles.  Instead, one of the concurrent routes is chosen for the tile.  Instead, it would be useful if each concurrent route had its own separate transportation_name object.  This might look something like this:

![image](https://user-images.githubusercontent.com/3254090/121891565-9ab60b00-cce9-11eb-9b82-305bb43a2968.png)

I propose to modify the SQL in the transportation_name layer which currently suppresses these concurrencies.

Here is an example of rendering exposed concurrencies:
![image](https://user-images.githubusercontent.com/3254090/121891791-ea94d200-cce9-11eb-81e1-2ce791e37c85.png)

Since route concurrencies are relatively uncommon, this should have only a small size increase in tiles which have a concurrency, and will make the SQL that generates transportation_name objects slightly simpler.

**Comment by ZeLonewolf** [comment]
Here is an in-progress demonstration of a concurrency-per-column implementation, which provides values that can be passed to custom highway-shield generators:
![image](https://user-images.githubusercontent.com/3254090/123194818-1bf16880-d475-11eb-93b7-8b83addff529.png)

**Comment by TomPohys** [comment]
Hi, it looks very good. Based on Slack conversation I assumed, that separate attributes for the road concurrencies are the right approach. The NULL columns in the database are OK and the NULL attribute will not be in the vector tiles. 

Did you figure out the styling? 

The PR for this is very welcome. Thanks!

**Comment by ZeLonewolf** [comment]
We have managed to come up with a styling for this, so far this is the most attractive version: 
![image](https://user-images.githubusercontent.com/3254090/123722623-b4f9f800-d856-11eb-9da3-9b08b91acb65.png)

Once maplibre/maplibre-gl-js#188 is resolved, we'll be able to render the shields upright, rather than rotated along the road.

I've been testing the code for this functionality, and it's exposed a few edge cases due to the complexity of the various route networks in the United States, so I'm working through those issues.  I hope to have a PR ready soon.  Thanks for the support!

**Comment by TomPohys** [comment]
It looks awesome! Looking forward to it.
