### ISSUE TITLE
Store multiple-route concurrency indexes

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1134]
Unblocks #1128
Unblocks #1131

This issue proposes to compute and store the rank-order number of [concurrencies](https://en.wikipedia.org/wiki/Concurrency_(road)) in the `osm_route_member` table, in order from most important multiple-route concurrency to least-important.  

Thus, a hypothetical concurrency between I-90, I-80, and US-6 in the United States would look like this:
I-80: concurrency-index=1
I-90: concurrency-index=2
US-6: concurrency-index=3

This change has four purposes:

1. It is a required change for #1128 to support exposing multiple concurrencies in the `transportation_name` layer.
2. It appears to have better performance than the current approach of using a `ROW_NUMBER()` / `rank` scheme on a table join.
3. It allows us to enforce a specific ranked ordering of concurrency importance (which routes "go first" in an ordered list).
4. It allows for easier troubleshooting of route-related issues such as #1131.

The following changes are proposed:

1. Modify the `osm_route_member` table to add and populate a `concurrency_index` column, which would store rank-ordered route concurrencies in the following sort order:
 - network type (for example, `us-interstate`)
 - network name
 - ref length
 - ref

2. Change the construction of the `osm_transportation_name_network` table to replace the `ROW_NUMBER()` / `rank` table join with a simple join on `osm_route_member` using `concurrency_index=1`.

**Comment by TomPohys** [comment]
Good call, PR is very welcome. Thanks!
