### ISSUE TITLE
Remove unused tags hstore in transportation_name layer table

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1137]
Blocks #1128
Blocks #1131

There is a tags column exposed in the `transportation_name` layer which appears to not be used.  This causes two issues:
1. It takes up unnecessary space and processing time in the database, and hstores can be sizeable
2. There are several `GROUP BY` clauses which use the `tags` hstore, which may be causing unexpected breakage of adjacent highway LineString objects that should otherwise be merged.

Conversely, hstore columns may be useful for debugging.

Example of unnecessarily exposed hstore:

```
openmaptiles=# \d osm_transportation_name_linestring
       Table "public.osm_transportation_name_linestring"
  Column  |        Type        | Collation | Nullable | Default
----------+--------------------+-----------+----------+---------
 geometry | geometry           |           |          |
 osm_id   | bigint             |           |          |
 name     | text               |           |          |
 name_en  | text               |           |          |
 name_de  | text               |           |          |
 tags     | hstore             |           |          |
 ref      | text               |           |          |
 highway  | character varying  |           |          |
 subclass | text               |           |          |
 brunnel  | text               |           |          |
 level    | integer            |           |          |
 layer    | integer            |           |          |
 indoor   | boolean            |           |          |
 network  | route_network_type |           |          |
 z_order  | integer            |           |          |
```

I proposed to remove these unused hstore columns where they're not being used.

**Comment by zstadler** [comment]
The field `tags` holds the `name:*` tags and used by the `{name_languages}` macro.

https://github.com/openmaptiles/openmaptiles/blob/1b0b1fd12131167904b61628c1ea403359f4a6e7/layers/transportation_name/transportation_name.yaml#L99

The list of languages id defined in
https://github.com/openmaptiles/openmaptiles/blob/1b0b1fd12131167904b61628c1ea403359f4a6e7/openmaptiles.yaml#L29-L99

**Comment by ZeLonewolf** [comment]
Thanks for clarifying this.  As usual "it's always more complicated than it looks" !
