### ISSUE TITLE
Get down to daily updates

### ISSUE THREAD

**Issue by stirringhalo** [openmaptiles/openmaptiles#114]
**This is an issue opened to track development and discussion towards daily updates with Imposm3. A PR will be opened when this is ready.** 

The target is to have rolling updates on a daily interval, hourly may be possible. Minutely is probably right out when considering redoing SQL tables that aren't handled by Imposm3.

Challenges:

~~~- [ ] Many layers have to get regenerated, but functions are too slow, and materialized views have to be regenerated fully everytime. Looking to create tables and update them incrementally as their underlying base tables are updated by Imposm3.~~~
- [x] Time, does a reasonably powerful machine fall behind, especially on big updates?
- [ ] How does the database health change over time, can autovacuuming keep up? Is reclustering needed
- [x] Getting expired tiles, and interpreting them correctly to dispose of old tiles, especially at lower zoom levels
- [x] Test updates and their triggers

**Comment by stirringhalo** [comment]
Okay, I have a ballpark number! 9 hours for an update, where "transportation_name", "poi", "water_name" and "osm_water_lakeline" based tables were refreshed. Transportation_name is a major one, so I think that is a good baseline.

I think this was doing minutely, but I don't anticipate daily updates to take long (perhaps 30-40 minutes). So we are well within the daily window.

I think a few minor tweaks are needed, materialized views should be refreshed concurrently, and the materialized views when first created need to be populated with data.

Once this ball gets rolling a bit, we can definitely look into speed improvements.

So tomorrow I will make the few minor changes, and start this all again on a daily updated import with all layers.

**Comment by lukasmartinelli** [comment]
> Okay, I have a ballpark number! 9 hours for an update, where "transportation_name", "poi", "water_name" and "osm_water_lakeline" based tables were refreshed. Transportation_name is a major one, so I think that is a good baseline.

Oh wow that's ok. Yes `transportation_name` is the most expensive. But I guess this is a layer which should be refreshed since new street names get added all the time.

> Step2: call imposm3 diff import

The diff import will already write the expired tiles out into the diff directory.

**Comment by stirringhalo** [comment]
With https://github.com/openmaptiles/openmaptiles/issues/130 resolved, testing is going well. Minor fixes to disable concurrent materialized views for one layer, but concurrent refresh can be enabled later depending on preference. In my large update occurring now, I don't refresh transportation_names, but I will do so for one final test before I generate a PR and open it for review.

Fortunately, these SQL changes shouldn't impact the use while testing on  https://github.com/openmaptiles/openmaptiles/pull/124 finishes.

**Comment by stirringhalo** [comment]
Ready to review in https://github.com/openmaptiles/openmaptiles/pull/131

**Comment by lukasmartinelli** [comment]
Importing 2 months of updates takes 25hrs with imposm3.. but in the end only 7 million tiles need to be updated. So this is a win in the end. We only run the update to get the tilelist effectively - because a reimport would be faster.

I really don't get comfortable with the `imposm3 run`. It has no progress report and sometimes just fails
I think for the old `imposm3 diff` import works quite fine for us (and creating a `osc.gz` file ourselves).
We need to add both the the docker-compose file.

**Comment by stirringhalo** [comment]
Merged and resolved https://github.com/openmaptiles/openmaptiles/pull/131.
