### ISSUE TITLE
Simplify Trans-Canada Highway network code

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1142]
The following is the detection code for setting the `ca-transcanada` network type:
https://github.com/openmaptiles/openmaptiles/blob/1b0b1fd12131167904b61628c1ea403359f4a6e7/layers/transportation_name/update_route_member.sql#L36-L47

This is the current state of Trans-Canada Highway route relations:
http://overpass-turbo.eu/s/198m

Is is complete across the country, except for a section in Quebec which runs through Val d'Or (route 117).  However, the missing Quebec section is also not present in the OpenMapTiles code above.

I propose that this code be simplified to "any route network that begins with `CA:transcanada`", which would include `CA:transcanada:namedRoute`, which is in use in Ontario.

**Comment by TomPohys** [comment]
Thanks! OSM community improved the Trans-Canada Highway significantly! The old way of selection of single networks is now not necessary! Thanks a lot!
