### ISSUE TITLE
Request for clarification: mbtiles spec conformance for TMS scheme

### ISSUE THREAD

**Issue by SahAssar** [openmaptiles/openmaptiles#1145]
I have a quick request for a clarification on the mbtiles exported:

It seems like they are not in the TMS scheme, and the mbtiles spec says 

> The tiles table contains tiles and the values used to locate them. The zoom_level, tile_column, and tile_row columns MUST encode the location of the tile, following the Tile Map Service Specification, with the restriction that the global-mercator (aka Spherical Mercator) profile MUST be used.

> Note that in the TMS tiling scheme, the Y axis is reversed from the "XYZ" coordinate system commonly used in the URLs to request individual tiles, so the tile commonly referred to as 11/327/791 is inserted as zoom_level 11, tile_column 327, and tile_row 1256, since 1256 is 2^11 - 1 - 791.

Is this on purpose and if so can I ask why?

Do mapping tools using mbtiles generally expect TMS or the "normal" scheme these days? I'm just trying to work out if I would be best off following the spec or your implementation for my own tools. Thanks for all your work and taking the time to read my question!

**Comment by birkskyum** [comment]
@SahAssar , I was wondering this too - can you explain how come you closed it?
