### ISSUE TITLE
Expose expressway tagging to the transportation layer

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1148]
Unblocks ZeLonewolf/openstreetmap-americana#22

It is common in North American-style maps to differentiate roads that do not meet all of the criteria for `highway=motorway` but still have expressway-like characteristics.  This need is described in depth in ZeLonewolf/openstreetmap-americana#22. with pictures.

In order to achieve this, I propose that OpenMapTiles consume the tags `motorroad=yes` and `expressway=yes` (combined >200K tags) using the following rule:

1. If a highway class is `trunk`, `primary`, `secondary`, `tertiary` or `unclassified`; and
2. The highway is tagged `motorroad=yes` or `expressway=yes`

Then:

That feature will be rendered in the tile as `subclass=motorroad`  Subclass is currently unused for these road classes.  Expressways versus non-expressways is an appropriate subdivision of these road classes.

The value `motorroad` is selected as the value because is the more common of the two tags `expressway=yes` and `motorroad=yes`.  However, if this is seen as too close to `highway=motorway`, we can use `expressway` as the value instead.

Alternately, if we do not wish to use subclass in this way, we could create a separate `motorroad`/`expressway` column as a boolean to expose this data.

**Comment by zekefarwell** [comment]
I don't think it is a good idea to conflate the `motoroad` key with the `expressway` key.  As I understand it, `motorroad=yes` is a shortcut for a bundle of access restrictions.  While there are plenty of road where both tags would be appropriate, there are plenty of others where only one or the other is.

**Comment by ZeLonewolf** [comment]
> I don't think it is a good idea to conflate the `motoroad` key with the `expressway` key

From a vector tile data perspective, we need to understand what tagging cases a style might care to differentiate.  For example, multiple `highway=` values, e.g. `service`, `residential`, `living_street` all get conflated to `class=minor` in the transportation layer.

Are there cases where we would want to style `expressway` and `motorway` differently?  Or only one but not the other?

**Comment by adamfranco** [comment]
One case where I would think of styling would vary for `motorroad` and `expressway` is for a bicycle-centric map. I haven't looked at how access restrictions are handled in OMT (if at all), but I could imagine a bicycle-style that showed all roads where bicycling was allowed as full-color and desaturated other non-bicycle roads. 

Non-bicycle roads could be identified either via explicit `bicycle=no` or implied where `highway=motorway` or `motoroad=yes`. 

In this regard, I'm feeling like it would make more sense for the OMT key to be `expressway` which is specifically noting the physical structure of the road (and would allow an alternate rendering to highlight its enhanced infrastructure), and shifting any handling of `motorroad` into access-related attributes. If OMT doesn't handle any access restrictions at this point then maybe `motorroad` support should be wrapped into a more wholistic `access` support push.
