### ISSUE TITLE
`bc: command not found` Error quickstart.sh

### ISSUE THREAD

**Issue by Falke-Design** [openmaptiles/openmaptiles#1151]
**Problem:**
When I clone the latest version from git and run `./quickstart.sh` it throws following error:

```
./quickstart.sh: line 134: bc: command not found
xargs: echo: terminated by signal 13
```

**Solution:**
I simply removed in line 143 `bc`:
```
mem=$( grep MemTotal /proc/meminfo | awk '{print $2}' | xargs -I {} echo "scale=4; {}/1024^2" | bc )
```
to:
```
mem=$( grep MemTotal /proc/meminfo | awk '{print $2}' | xargs -I {} echo "scale=4; {}/1024^2")
```
I think this brokes the calucation / command **but** this value is only displayed in the console and has no other usages.

**Suggestion**
Can be checked if `bc` is available else the memory output will skipped?

**Server:**
OS: Ubuntu 20.04.1 LTS   minimal
Kernel: Linux 5.4.0-67-generic

**Comment by TomPohys** [comment]
Thanks! PR is very welcome!
