### ISSUE TITLE
Optimize vector tiles size in sea areas

### ISSUE THREAD

**Issue by claustres** [openmaptiles/openmaptiles#1159]
According to the [original article](https://eprints.ost.ch/id/eprint/536/1/thesis_updatable_vector_tiles_from_openstreetmap.pdf), from which a lot of ideas are now used in this project, an algorithm is presented to save space in generated tiles: all z8 subpyramids containing the same data on all descendant tiles are removed (page 20).

The original tool to do this is probably [mbtoolbox](https://github.com/lukasmartinelli/mbtoolbox#check-mbtiles-for-redundancy). Maybe I am wrong but as far as I can see it is not currently implemented in this project, is there any reason or should it be an interesting feature request to add it to the toolbox ? Could it be related to the fact that all tile servers will not support such a feature ?

Thanks for feedback.

**Comment by nickpeihl** [comment]
I believe [`mbtiles impute`](https://github.com/openmaptiles/openmaptiles-tools/blob/3796c4eab03dd8a317cea2d2c9b0c7dbdce35ac9/bin/mbtiles-tools#L31-L40) function in the openmaptiles-tools repo accomplishes what you're looking for. 

We generate tiles for low to mid level zooms (0-9). Then for zooms 10 to 14, we run `mbtiles impute`. This function finds duplicate tiles from the parent zoom and creates a list of tiles that still need to be generated. Then we use that list file to generate the remaining tiles.

Something like:
```bash
for (( ZOOM=10; ZOOM<=14; ZOOM++ )); do
  LIST_FILE="./tiles_$ZOOM.txt"
  mbtiles-tools impute ./tiles.mbtiles --zoom $ZOOM --output $LIST_FILE
  tilelive-copy --exit --scheme=list --list=$LIST_FILE "pgquery://?database=..." ./tiles.mbtiles
done
```

**Comment by claustres** [comment]
Good to know, I actually tried to run mboptimize  without any success so that I also concluded that tiles were already optimized.

Thanks for feedback.
