### ISSUE TITLE
[transportation] layer :   natural earth  vs osm differences ( z6 vs. z7 )

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#116]
in Hungary  -  the Natural Earth different than OSM  transport layer 

## zoom_level=6 ( Natural Earth ) 

check the roads around `Debrecen` 
https://openmaptiles.github.io/osm-bright-gl-style/#6.83/46.197/24.699

![image](https://cloud.githubusercontent.com/assets/2217320/21587487/577c8d26-d0dd-11e6-857c-64cdff53c3f1.png)

## zoom_level=7  ( OSM )

check the roads around `Debrecen` 
https://openmaptiles.github.io/osm-bright-gl-style/#7.31/46.532/23.816

![image](https://cloud.githubusercontent.com/assets/2217320/21587519/a2d8b34e-d0dd-11e6-8446-5d884b257c00.png)

**Comment by jirik** [comment]
Fixed by https://github.com/openmaptiles/openmaptiles/pull/185 (using only OSM for roads, no NE).
