### ISSUE TITLE
[boundary] layer : natural earth vs osm differences ( z7 vs. z8 ) Cyprus

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#117]
The switch from natural earth to  osm data ( z7 vs. z8  Cyprus )  has a strange differences ... 

### Cyprus  z7  - Border
https://openmaptiles.github.io/osm-bright-gl-style/#7.86/34.813/34.188
![image](https://cloud.githubusercontent.com/assets/2217320/21588002/76d07afc-d0e2-11e6-8faf-4c93fe24eb06.png)

### Cyprus  z8  - Border

check the borders ...

https://openmaptiles.github.io/osm-bright-gl-style/#8.09/34.9251/33.8413
![image](https://cloud.githubusercontent.com/assets/2217320/21588010/9309b260-d0e2-11e6-98c8-d38d12768ae4.png)

**Comment by lukasmartinelli** [comment]
> The switch from natural earth to osm data ( z7 vs. z8 Cyprus ) has a strange differences ...

Natural Earth data is now only used until z3. So these problems should not be visible very well in the future thanks to #135.
