### ISSUE TITLE
tilelive-pgquery fork

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#1170]
Hi, I noticed there is a [fork](https://github.com/openmaptiles/tilelive-pgquery) of my [tilelive-pgquery repository](https://github.com/nyurik/tilelive-pgquery).  I obviously have nothing against forks :), but just curious what was the goal of forking it but never modifying it? It is currently falling behind the origin.  Note that [the dockerfile](https://github.com/openmaptiles/openmaptiles-tools/blob/master/Dockerfile#L127) uses NPM-published version anyway, so the fork is not used.

**Comment by daliborjanak** [comment]
We don't have any plans with this repo now. It is backup. We are used to having backups for all major dependencies somewhere :-)  I updated it
