### ISSUE TITLE
Version property in openmaptiles.yaml not updated

### ISSUE THREAD

**Issue by nickpeihl** [openmaptiles/openmaptiles#1173]
The [version property in openmaptiles.yaml](https://github.com/openmaptiles/openmaptiles/blob/v3.12.2/openmaptiles.yaml#L20) was not updated in the v3.12.2 release. 

I would expect this property to match the current release. Maybe that can be resolved when v3.12.3 is released?

**Comment by TomPohys** [comment]
Yes, this was my mistake that I did not update `openmaptiles.yaml` before release v3.12.2. It will be updated for the next release.
