### ISSUE TITLE
[boundary] layer : Ireland - Northern Ireland : border - z8 is broken ..  

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#118]
### Ireland - Northern Ireland :  border - z8  is broken  ..
https://openmaptiles.github.io/osm-bright-gl-style/#8.79/54.0971/-6.2337
![image](https://cloud.githubusercontent.com/assets/2217320/21588414/ab5e63b6-d0e6-11e6-9598-34a3ecb0b844.png)

the z9 is OK  ..

maybe the length filtering  side effects  ?   `ST_Length(geometry) > 1000`
```sql
CREATE OR REPLACE VIEW boundary_z8 AS (
    SELECT geometry, admin_level
    FROM osm_boundary_linestring_gen5
    WHERE admin_level <= 4 AND ST_Length(geometry) > 1000
);
```
https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.sql#L87

**Comment by lukasmartinelli** [comment]
Fixed by #135 
![screenshot from 2017-01-18 13-28-11](https://cloud.githubusercontent.com/assets/1288339/22064036/013d2130-dd82-11e6-804e-4569c4c8c0b8.png)
