### ISSUE TITLE
[boundary] layer : Guatemala  border - `linestring`  vs osm relation

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#119]
for test case : 

###  Guatemala  z8 border is broken ( from OSM data ) 
https://openmaptiles.github.io/osm-bright-gl-style/#8.02/15.7025/-89.3163

![image](https://cloud.githubusercontent.com/assets/2217320/21588771/3c52c31e-d0ea-11e6-9575-a02e04b62a27.png)

my guess: 
*  probably the current `linestring` based mapping  using the outer line taggings :  http://www.openstreetmap.org/way/414903912#map=11/16.2776/-90.4601

and not the parent - relations!   
http://www.openstreetmap.org/relation/1521463#map=7/15.109/-86.462

![image](https://cloud.githubusercontent.com/assets/2217320/21588827/c74c34f0-d0ea-11e6-8d45-bf38367eacad.png)

probably related to  :  https://github.com/openmaptiles/openmaptiles/issues/115

**Comment by lukasmartinelli** [comment]
Will be fixed by #135 
![screenshot from 2017-01-18 13-27-11](https://cloud.githubusercontent.com/assets/1288339/22064003/dd09dd44-dd81-11e6-9548-a36b35e10204.png)
