### ISSUE TITLE
Readme use the old `make generate-tiles`

### ISSUE THREAD

**Issue by Falke-Design** [openmaptiles/openmaptiles#1198]
In the Readme on [Work on Layers](https://github.com/openmaptiles/openmaptiles#work-on-layers) still the obsolete / deprecated command `make generate-tiles` is used but I think it should be `make generate-tiles-pg`.

> make generate-tiles-pg               # generate vector tiles based on .env settings using PostGIS ST_MVT()
  make generate-tiles                  # generate vector tiles based on .env settings using Mapnik (obsolete)

**Comment by joaokho** [comment]
make generate-tiles-pg  will rewrite (new mbtiles) the zoom level created before.  generate-tiles can add/update other zoom level?
