### ISSUE TITLE
Oslo Wrong Water Multipolygon

### ISSUE THREAD

**Issue by lukasmartinelli** [openmaptiles/openmaptiles#121]
We still face the problem of https://github.com/osm2vectortiles/osm2vectortiles/issues/453
At lower zoom level it does show land now (but only because of the #120 bug).

IMHO this is a OSM data problem. The crudest way how we can fix it in OpenMapTiles without touching OSM is querying explicitely the OSM ID with the wrong waterway tag and simply remove it.

![screenshot from 2017-01-05 15-56-34](https://cloud.githubusercontent.com/assets/1288339/21684937/f2212ba0-d35f-11e6-9bda-54b8302ef948.png)
![screenshot from 2017-01-05 15-59-13](https://cloud.githubusercontent.com/assets/1288339/21684936/f220b986-d35f-11e6-8c58-fc0e51a9ab2a.png)

**Comment by lukasmartinelli** [comment]
I just imported only Oslo to test this issue and it seems it is gone now :astonished: 
So either someone fixed it in OSM or latest imposm3 deals differently with multipolygon inheritance of tags.

(no water is correct)

![screenshot from 2017-01-23 15-20-48](https://cloud.githubusercontent.com/assets/1288339/22207479/997812ec-e17f-11e6-8d5f-764f4a003679.png)
![screenshot from 2017-01-23 15-20-14](https://cloud.githubusercontent.com/assets/1288339/22207478/9977e47a-e17f-11e6-969e-f92c94539f72.png)

**Comment by klokan** [comment]
Great news!

**Comment by klokan** [comment]
To be visually verified on v3.5 rendering - then this ticket can be closed @jirik

**Comment by jirik** [comment]
Visually verified, closing
