### ISSUE TITLE
Raise a helpful error if Natural Earth data is not imported

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1220]
During testing of #1213, it was noted that running `make import-sql` without having previously run `make import-data` causes a somewhat cryptic error message.  Instead, we can add a check to the top of the SQL to verify that the Natural Earth tables are present, and raise a more helpful error message if they're missing.

**Comment by nyurik** [comment]
We could also extend the yaml files to say which tables or functions each layer expects to be present in the DB before it is imported.  This way we can auto-generate the same checks for all layers, and prepend them to the sql files.

**Comment by ZeLonewolf** [comment]
Hi, does openmaptiles/openmaptiles-tools#370 actually fix this issue?  Or are more changes needed on the openmaptiles side to update various yaml files with the Natural Earth dependencies?

**Comment by Falke-Design** [comment]
No this is not fixed. We provided only the funcunality now we need to add the required things in the layer.yaml

**Comment by ZeLonewolf** [comment]
@TomPohys please re-open ticket.

**Comment by Falke-Design** [comment]
@nyurik now we had added a check for the required tables / functions but it is still no helpful error message:
![grafik](https://user-images.githubusercontent.com/19800037/133892964-9888ce2c-00e6-4ba1-85de-018ed1033cf7.png)

It would be better if we show a message like `You need first to create the table with 'make import-data'`

**Comment by nyurik** [comment]
Good point @Falke-Design, i guess we could add a generic error message at the top (simpler than to have a help text for each required table, and deal with duplicate messages, etc).

```yaml
requires:
  helpText: "This layer requires tables generated with 'make import-data' command."
  tables:
    - osm_ocean_polygon
    ...
```


I guess we could wrap the currently-generated code with something like this:

```sql

do $$
begin
  SELECT 'osm_ocean_polygon'::REGCLASS;
exception when others then   -- I think we should use a specific error instead of "others" here
  RAISE EXCEPTION SQLERRM USING HINT = 'This layer requires tables generated with 'make import-data' command.' ;
end;
$$ language 'plpgsql';
```

I think SQLERRM is what contains statement-specific error, and HINT will help with additional information.  I haven't tested the above.
