### ISSUE TITLE
Integrity tests to check the import-diff flow

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#1226]
While the Integrity tests check the `import-osm` flow, they do not test the `import-diff` flow. As a result, the SQL code that performs table updates is not tested.

[Replace materialized view of water by tables with diff update #853](https://github.com/openmaptiles/openmaptiles/pull/853) and similar PRs have continuously increased the complexity of the code that is used only in flows based on `import-diff`. Currently, this code is not tested by the integrity tests, including for typing errors.

Such a test requires finding a source changefile that performs modifications in all OMT tables for a relatively small area.

It would be nice to also add performance measurements for the flow.

Related to comments for b011b27e52726361d352932ad923de7e05893cc4

**Comment by ZeLonewolf** [comment]
This would be a great addition.  I have personally broken the update scripts without realizing it and and not noticed it until weeks later.

**Comment by zstadler** [comment]
Here is a working example for such a test using `area=greater-london`

```
echo DIFF_MODE=true >> .env
rm -fr data build cache
make download-geofabrik area=greater-london
docker-compose run --rm --user=$(id -u):$(id -g) openmaptiles-tools sh -c "wget -O data/greater-london.osm.pbf http://download.geofabrik.de/europe/great-britain/england/greater-london-$(date --date="$(date +%Y-%m-15) -2 month" +'%y%m01').osm.pbf"
./quickstart.sh greater-london
docker-compose run --rm --user=$(id -u):$(id -g) openmaptiles-tools sh -c "osmupdate --base-url=$(sed -n 's/ *\"replication_url\": //p' data/greater-london.repl.json) data/greater-london.osm.pbf data/changes.osc.gz"
make import-diff
make generate-tiles-pg MAX_ZOOM=14
```
