### ISSUE TITLE
borders should be removed each time quickstart is run

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#1228]
When running `quickstart.sh` the `data/borders` folder is not removed if it exists. This can be a problem when a user is running `quickstart.sh` multiple times for different downloads such as Washington and then Arizona:

> ./quickstart.sh washington

This will correctly create borders for Washington in the borders folder.

> ./quickstart.sh arizona

This will use the old borders files that were created for Washington which causes incorrect data to be written for that state, and missing data as well.

**What Needs to be done**

The `data/borders` folder needs to be removed if it exists when running `quickstart.sh`.

**Comment by nyurik** [comment]
i wonder if it would make sense to handle borders the same way we handle downloaded data -- name it something like `<area>-borders` and skip that step if it already exists?  Or it could be an overkill. Perhaps eventually we should really support multiple parallel areas - a way to merge-import areas somehow...  But that's a much bigger task.

**Comment by nnhubbard** [comment]
Does importing borders really take that long? Just wondering if it would be a performance or speed issue to just remove the data if it exists.

**Comment by ZeLonewolf** [comment]
This issue will be fixed by #1213, which removes osmborder and hence the borders folder.  Though I agree that this bug is annoying :)

**Comment by Falke-Design** [comment]
> i wonder if it would make sense to handle borders the same way we handle downloaded data -- name it something like `<area>-borders` and skip that step if it already exists?  Or it could be an overkill. Perhaps eventually we should really support multiple parallel areas - a way to merge-import areas somehow...  But that's a much bigger task.

Maybe I overlook something but importing multiple osm data are very easy. We need only to change in `imposm` to `-appendcache`. I made already an PR for this: https://github.com/openmaptiles/openmaptiles-tools/pull/365

I already working with that and have no problems. The only problematic part was `import-borders` but I simply used the whole planet border file. And with the PR from @ZeLonewolf #1213 this is oboslete too.
