### ISSUE TITLE
Autostart tileserver on server boot

### ISSUE THREAD

**Issue by skydiablo** [openmaptiles/openmaptiles#1232]
hi!
i have running this great tileserver via `sudo make start-tileserver`, all works fine! but now i want to make my server boot save, so i have to run this command at boot time. my first try was just an `crontab` line with:

> @reboot cd /home/map/openmaptiles/ && make start-tileserver > /tmp/tileserver.log

and the output is:

```txt
***********************************************************
* 
* Download/refresh maptiler/tileserver-gl docker image
* see documentation: https://github.com/maptiler/tileserver-gl
* 
***********************************************************
 
docker pull maptiler/tileserver-gl
Using default tag: latest
latest: Pulling from maptiler/tileserver-gl
Digest: sha256:5b984ae848eee0d9ff22c3d882aa936926405146d8663104467e477a4a9a4d56
Status: Image is up to date for maptiler/tileserver-gl:latest
docker.io/maptiler/tileserver-gl:latest
 
***********************************************************
* 
* Start maptiler/tileserver-gl 
*       ----------------------------> check http://localhost:8080 
* 
***********************************************************
 
docker run --rm --user=0:0 -it --name tileserver-gl -v $(pwd)/data:/data -p 8080:8080 maptiler/tileserver-gl --port 8080
```

and now its stucks and no more output and the server didnt started up successfully :(

my next try was to use docker itself to auto-run this container:

```bash
# docker update --restart unless-stopped tileserver-gl
Error response from daemon: Cannot update container > c1cd1c06b89056bd289b9cf352f0a9175a7c9bb12f6f843c0b55f53f385ad4f6: Restart policy cannot be updated because AutoRemove is enabled for the container
```
and yes, this is true, the container is running with param `--rm` ...

maybe with a systemd run-script? or any other ideas?

reagrds, volker.

**Comment by ache051** [comment]
> docker run --rm --user=0:0 -it --name tileserver-gl -v $(pwd)/data:/data -p 8080:8080 maptiler/tileserver-gl --port 8080

I am unfamiliar with using make commands to start tileserver, but this docker line specified port two times, one with -p and one with -port, is it suppose to be like that? And the line doesn't seem to run the container in detached mode?

This should do what you want in one line:
docker run -d --rm -d --restart unless-stopped --user=root -it --name tileserver-gl -v /path/to/your/mbtiles:/data -p 8080:80 maptiler/tileserver-gl

**Comment by skydiablo** [comment]
this is the correct running command:

> # sudo docker run -d --restart unless-stopped --user=root -it --name tileserver-gl -v /home/sws/openmaptiles/data:/data -p 8080:8080 maptiler/tileserver-gl -p 8080

and the dubble assiged port "8080" is nesessary. thx for response!
