### ISSUE TITLE
How to change max_admin_level in import_osmborder_lines.sh

### ISSUE THREAD

**Issue by denishuvelle** [openmaptiles/openmaptiles#1234]
Hello!

I already generates tiles for small and big areas (Europe for example) and did some adaptations like the zoom level in ".env" file but I am looking for a way to have admin_level 2 in bigger level of zoom.

I saw it was managed here: https://github.com/openmaptiles/import-osmborder/blob/master/import/import_osmborder_lines.sh in a parameter named "max_admin_level" but I don't see how I can adapt it: I usually just launch OpenMapTiles with quickstart.sh and I am a beginner with Docker :)

Any how to change that?

Thanks!

**Comment by denishuvelle** [comment]
Maybe my question needs more info :)

When I generate the tiles for Europe (with everything by default except .env with a modification of MAX_ZOOM 14), I only see countries borders at a low level of zoom (everything under zoom 5) but it doesn't seem to be related to my style: the admin_level 2 is not in the tiles themselves.

It's annoying for small countries like Luxembourg: you need to unzoom a lot to see the borders :-/

Do I need to modify boundary.sql? Where can I force to always have the admin_level2 for all the zoom levels?

**Comment by ZeLonewolf** [comment]
See the discussion starting here:
https://github.com/openmaptiles/openmaptiles/pull/1213#issuecomment-914248887

My recommendation for this use case would be to run an overpass query to extract all global boundaries, package it into an .osm.pbf file, and run it through the regular load process.

**Comment by denishuvelle** [comment]
Hi @ZeLonewolf ,

Thanks for your response, I will try that! I will also ensure it's not related to the borders folder which was not clean before my run... Let's see at the next run :)

**Comment by denishuvelle** [comment]
Hi @ZeLonewolf ,

I found enough time to launch again the generation of Europe: this time, I removed the content of the folder "borders" before and I now see the countries borders like expected at all zoom levels :)

Thanks!
