### ISSUE TITLE
quickstart.sh does not generate mbtiles

### ISSUE THREAD

**Issue by ValorNaram** [openmaptiles/openmaptiles#1242]
I am working voluntarily for a non-profit organisation called Trufi Association which provides services around the topic public transportation systems. I currently try to make a mbtile for Hamburg following the instructions at https://openmaptiles.org/docs/generate/generate-openmaptiles/ . But whenever I execute the script I get a bunch of command output but no mbtile (just the meta one).

```
Running all layers test 'null' at zoom 14 (0 tiles) - Empty set, useful for query validation....
Query returned no data after 0:00:00.135762


================ SUMMARY ================
No tiles were generated in 0:00:00.1
 
-------------------------------------------------------------------------------------
====> : Compute bounding box for tile generation
Configuration file data/albania.bbox already exists, no need to regenerate.  BBOX=19.08737,39.64364,21.06285,42.66313
 
-------------------------------------------------------------------------------------
====> : Start generating MBTiles (containing gzipped MVT PBF) using PostGIS. 
      : Output MBTiles: ./data/albania.mbtiles  
      : Source code: https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/generate-tiles 
Starting postgres docker compose target using default image (no recreate if exists)
Starting openmaptiles_postgres_1 ... done
Wait for PostgreSQL to start...
docker-compose run --rm --user=0:0 openmaptiles-tools pgwait
Generating tiles into data/tiles.mbtiles (will delete if already exists) using PostGIS ST_MVT()...
docker-compose run -T --rm --user=0:0 openmaptiles-tools generate-tiles
pgquery://?database=openmaptiles&host=postgres&port=5432&username=openmaptiles&password=openmaptiles&funcZXY=getmvt&maxpool=10&nogzip=1&key=1
Generating zoom 0..7 from 1 servers, using 10 connections per server, 10 parallel streams...
PostgreSQL connection was configured from 
tilelive-pgquery v0.7.3
Server information for postgres:5432:
                 version() = PostgreSQL 9.6.20 on x86_64-pc-linux-gnu (Debian 9.6.20-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
    postgis_full_version() = POSTGIS="3.0.3 6660953" [EXTENSION] PGSQL="96" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 4.9.3, 15 August 2016" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" WAGYU="0.4.3 (Internal)"
                       jit = unrecognized configuration parameter "jit"
            shared_buffers = 128MB
                  work_mem = 4MB
      maintenance_work_mem = 64MB
      effective_cache_size = 4GB
  effective_io_concurrency = 1
           max_connections = 100
      max_worker_processes = 8
      max_parallel_workers = unrecognized configuration parameter "max_parallel_workers"
  max_parallel_workers_per_gather = 0
               wal_buffers = 4MB
              min_wal_size = 80MB
              max_wal_size = 1GB
          random_page_cost = 4
  default_statistics_target = 100
  checkpoint_completion_target = 0.5

Verifying pgquery data source by retrieving a tile at [14,9268,3575] from postgres:5432...
a tile at [14,9268,3575] from postgres:5432 was generated in 231ms and contains 376 bytes (gzipped)
[3.2s] 100.0000%     16/    15 @    5/s | ✓ 15 □ 0 | 0.0s left
Updating generated tile metadata ...
docker-compose run --rm --user=0:0 openmaptiles-tools \
                mbtiles-tools meta-generate "data/tiles.mbtiles" openmaptiles.yaml --auto-minmax --show-ranges
Connecting to PostgreSQL at postgres:5432, db=openmaptiles, user=openmaptiles...
New metadata values in data/tiles.mbtiles
attribution <a href="https://www.openmaptiles.org/" target="_blank">&copy; OpenMapTiles</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>
bounds      19.08737,39.64364,21.06285,42.66313
center      20.1,41.2,1
description A tileset showcasing all layers in OpenMapTiles. https://openmaptiles.org
filesize    425,984
format      pbf
id          openmaptiles
maskLevel   8
maxzoom     7
minzoom     0
name        OpenMapTiles
pixel_scale 256
scheme      tms
tilejson    2.1.0
version     3.12.1
json        (The value is a valid JSON, use --show-json for raw dump)
```

[...]

```
  Zoom    Tile count  Found tile ranges
------  ------------  -------------------
     0             1  0,0 x 0,0
     1             1  1,1 x 1,1
     2             1  2,2 x 2,2
     3             2  4,4 x 4,5
     4             2  8,9 x 8,10
     5             2  17,19 x 17,20
     6             2  35,39 x 35,40
     7             4  70,79 x 71,80
```

[...]

```
====> : (disk space) We have created the new vectortiles ( ./data/albania.mbtiles ) 
      : Please respect the licenses (OdBL for OSM data) of the sources when distributing the MBTiles file.
      : Data directory content:
total 83784
drwxrwxr-x 4 soren soren     4096 Sep 22 13:47 .
drwxrwxr-x 8 soren soren     4096 Sep 22 13:43 ..
-rw-r--r-- 1 root  root        36 Sep 22 13:43 albania.bbox
-rw-r--r-- 1 root  root  44229533 Sep 22 13:43 albania.osm.pbf
drwxrwxr-x 2 soren soren     4096 Sep 21 14:27 borders
drwxr-xr-x 3 root  root      4096 Sep 21 14:24 europe
-rw-r--r-- 1 root  root        35 Sep 22 13:17 hamburg.bbox
-rw-r--r-- 1 root  root  41087232 Sep 22 13:17 hamburg.osm.pbf
-rw-r--r-- 1 root  root      1908 Sep 22 13:47 quickstart_checklist.chk
-rw-r--r-- 1 root  root    442368 Sep 22 13:47 tiles.mbtiles
 
-------------------------------------------------------------------------------------
```

**Comment by Falke-Design** [comment]
It should have generated into the subfolder `data`:
> (disk space) We have created the new vectortiles ( ./data/albania.mbtiles ) 
> ...
> -rw-r--r-- 1 root  root    442368 Sep 22 13:47 tiles.mbtiles

**Comment by ValorNaram** [comment]
```
total 43656
drwxr-xr-x 3 root  root      4096 Sep 22 19:43 .
drwxrwxr-x 8 soren soren     4096 Sep 22 19:38 ..
-rw-r--r-- 1 root  root        36 Sep 22 19:38 albania.bbox
-rw-r--r-- 1 root  root  44229533 Sep 22 19:38 albania.osm.pbf
drwxr-xr-x 2 root  root      4096 Sep 22 19:40 borders
-rw-r--r-- 1 root  root      1543 Sep 22 19:43 quickstart_checklist.chk
-rw-r--r-- 1 root  root    450560 Sep 22 19:43 tiles.mbtiles
```

tiles.mbtiles is just 460.56kb and putting it into the folder where openmaptiles gets its data from and restarting that service does not lead to delivery of  the background map of Albania.

**Comment by Falke-Design** [comment]
But then your title is wrong ... mbtiles are generated but your server don't use it.

How do you start your tile server? Do you run `make start-tileserver` in openmaptiles? It works for me

**Comment by ValorNaram** [comment]
I do not run `make start-tileserver`. We use the following docker compose:

```yaml
openmaptiles:
    image: klokantech/openmaptiles-server
    volumes:
      - "./tiles:/data"
    restart: unless-stopped
    networks:
      - frontend

```

**Comment by Falke-Design** [comment]
I don't know much about docker but be sure that you connect the correct `data` folder outside (with the tiles) with the `data` in docker.

Maybe this works: 
Replace `- "./tiles:/data"` with `- "./data:/data"`
And run your docker in the folder `openmaptiles`

**Comment by ValorNaram** [comment]
It works because we already use some mbtiles we paid for.

**Comment by Falke-Design** [comment]
And the mbtiles are in the data folder?

**Comment by ValorNaram** [comment]
Ok, it works with that.

**Comment by Falke-Design** [comment]
Have you tried to to name the generated tiles same as the paid one?

**Comment by ValorNaram** [comment]
No. Can it serve only one MBTile?

**Comment by Falke-Design** [comment]
Yes it takes always the first one in the folder if not specified. I already run in the same problem

**Comment by ValorNaram** [comment]
Then it tells `Data file "undefined" not found!`

**Comment by Falke-Design** [comment]
Sorry I can't explain what happens to you ...

**Comment by ache051** [comment]
Have you changed the BBOX value in .env to Hamburg's bounding box? If you had and run the quickstart without specifying an area or having an existing pbf file in the data directory, then no tiles will be be generated as quickstart will load Albania by default (as shown in your log)? It will still generate an empty mbtiles though.

**Comment by Falke-Design** [comment]
> Ok, it works with that.

He said the tiles are showing if he use the tileserver of openmaptiles. So the tiles are generated correct but his custom tileserver don't use / load it

**Comment by ache051** [comment]
> > Ok, it works with that.
> 
> He said the tiles are showing if he use the tileserver of openmaptiles. So the tiles are generated correct but his custom tileserver don't use / load it

I am under the impression the problem is the tileserver works with the paid mbtiles but not the self-generated mbtiles?

**Comment by ache051** [comment]
I have generated a [sample mbtiles](https://drive.google.com/file/d/1gOBnlOBXUBZLCK9Ge1yy6v9d-EESbyTi/view?usp=sharing) using this code base. Could you try to serve it through tileserver and tell us if it works?

**Comment by ValorNaram** [comment]
> I have generated a sample mbtiles using this code base. Could you try to serve it through tileserver and tell us if it works?

`Data file "undefined" not found!` same error when implementing

**Comment by ValorNaram** [comment]
> I am under the impression the problem is the tileserver works with the paid mbtiles but not the self-generated mbtiles?

I share the same thoughts

**Comment by ache051** [comment]
It seems that [OpenMapTiles-Server](https://hub.docker.com/r/klokantech/openmaptiles-server/) is sunset already. Maybe you could try [TileServer-GL](https://github.com/maptiler/tileserver-gl) and see if it can serve the self-generated mbtiles?

**Comment by ValorNaram** [comment]
Yep but will take a bit longer so I cannot answer within 15min or more.

**Comment by ValorNaram** [comment]
TileServer-GL does not attempt to work correctly:

I run
```bash
sudo docker run --rm --user=root -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl --mbtiles tiles_hamburg_230921.mbtiles
```
and get in firefox `The connection was reset`. So cannot say if it would work with TileServer-GL. Also SSH yields the same since I am working on a server and tunnel my port 8080 to 80 when connecting.

But it works when I run the following command:
```bash
make start-tileserver
```

See also my response: https://github.com/openmaptiles/openmaptiles/issues/1242#issuecomment-925272286

**Comment by ValorNaram** [comment]
Now I have 
![image](https://user-images.githubusercontent.com/19347636/134513337-2c2df158-07bf-48b6-ac38-6fcaf94f404c.png)

**Comment by Falke-Design** [comment]
Now you need to add a config and a style to show the data. I can give you my config file but I won't be home for the next 4 hours

**Comment by ache051** [comment]
> In the main-directory (where you run the docker tileser-gl command), create a sub-directory with the name `data`. In the data folder you add the mbtiles `tiles_hamburg_230921.mbtiles` .
> 
> Now run in the main directory:
> 
> ```
> sudo docker run --rm --user=root -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl
> ```

I was able to get it working if I run your command inside the directory the mbtiles reside in without config and style files. See if @ValorNaram can see the same.
![Screenshot from 2021-09-24 09-39-49](https://user-images.githubusercontent.com/10702936/134587906-8c89d9a2-5ab1-44ae-b9d1-01df2a08d90f.png)

**Comment by ValorNaram** [comment]
It works. Thank you.

**Comment by ache051** [comment]
Cool! So the problems were location of the mbtiles file and version of tileserver.
Off-topic, the work done by Trufi looks quite interesting. Would love to hear more!

**Comment by saschafoerster** [comment]
I had the same issue and didn't understand the solution here. I had to change the BBOX-entry in .env
```
# BBOX may get overwritten by the computed bbox of the specific area:
#   make generate-bbox-file
# By default, the Makefile will use the content of data/$(area).bbox file if it exists.
BBOX=
```

I used https://boundingbox.klokantech.com and a CSV RAW value of my individual box. 

I expected the file to be named "Albania.mbtiles", but it was "tiles.mbtiles" in the end for all regions I choose.

**Comment by ValorNaram** [comment]
I retried it again on my development machine starting at nearly zero and now it also works on my machine. For my NGO [Trufi Association e.V.](https://github.com/trufi-association) I created a script which you can find at <https://github.com/trufi-association/trufi-server-resources/blob/main/map-data-builder/generate_mbtiles.sh> . This script starts from zero. We cannot use caching here as the nice repo maintainers here suggested because we generate resources for many communities (as it is planned).

**Keep up the good work you're doing here. You help us helping digitizing public transportation in cities in developing countries like Cochabamba and Duitama :+1:**

**Comment by birkskyum** [comment]
Is it intended to have `scheme  = tms` here instead of `zxy`?
