### ISSUE TITLE
error: out of shared memory in tile generation

### ISSUE THREAD

**Issue by RyanDeRose-TomTom** [openmaptiles/openmaptiles#1244]
I'm getting this error in blocks of 10-15 roughly once every second:

[2m 29.3s]   8.7503% 123.8k/ 1.42m @  835/s | ✓ 123.8k □ 0 | 25m 46.0s left
[2m 29.4s]   8.7609% 124.0k/ 1.42m @  835/s | ✓ 124.0k □ 0 | 25m 47.0s left
[2m 29.5s]   8.7706% 124.1k/ 1.42m @  836/s | ✓ 124.1k □ 0 | 25m 45.0s left
[2m 29.6s]   8.7809% 124.3k/ 1.42m @  835/s | ✓ 124.3k □ 0 | 25m 45.0s left
Error getting 13/4199/2984: error: out of shared memory
Error getting 13/4339/2864: error: out of shared memory
Error getting 13/4342/2865: error: out of shared memory
Error getting 13/4336/2864: error: out of shared memory
Error getting 13/4192/2986: error: out of shared memory
Error getting 13/4336/2865: error: out of shared memory
Error getting 13/4181/3001: error: out of shared memory
Error getting 13/4204/2977: error: out of shared memory
Error getting 13/4204/2976: error: out of shared memory
Error getting 13/4192/2991: error: out of shared memory
Error getting 13/4177/2999: error: out of shared memory
Error getting 13/4192/2987: error: out of shared memory
Error getting 13/4176/3001: error: out of shared memory
Error getting 13/4197/2963: error: out of shared memory
Error getting 13/4343/2864: error: out of shared memory
Error getting 13/4337/2866: error: out of shared memory
Error getting 13/4178/3001: error: out of shared memory
Error getting 13/4146/2968: error: out of shared memory
Error getting 13/4192/2985: error: out of shared memory

[2m 29.7s]   8.7886% 124.4k/ 1.42m @  836/s | ✓ 124.4k □ 0 | 25m 44.0s left
[2m 29.8s]   8.7982% 124.5k/ 1.42m @  837/s | ✓ 124.5k □ 0 | 25m 42.0s left
[2m 29.9s]   8.8077% 124.6k/ 1.42m @  837/s | ✓ 124.6k □ 0 | 25m 43.0s left

During the tile generating part of quickstart.sh (other lines shown for context). This machine is running Ubuntu, and has vast amounts of unused RAM, so I'm not sure why this is running out.

**Comment by Falke-Design** [comment]
Can you please share what `.env` you have and for which area you creating tiles

**Comment by RyanDeRose-TomTom** [comment]
It won't let me attach it, so here is the full text:

```
# This file defines default environment variables for all images

# Layers definition and meta data
TILESET_FILE=openmaptiles.yaml

# Use 3-part patch version to ignore patch updates, e.g. 5.0.0
TOOLS_VERSION=5.3

# Make sure these values are in sync with the ones in .env-postgres file
PGDATABASE=openmaptiles
PGUSER=openmaptiles
PGPASSWORD=openmaptiles
PGHOST=postgres
PGPORT=5432

# BBOX may get overwritten by the computed bbox of the specific area:
#   make generate-bbox-file
# By default, the Makefile will use the content of data/$(area).bbox file if it exists.
BBOX=-180.0,-85.0511,180.0,85.0511

# Which zooms to generate in   make generate-tiles
MIN_ZOOM=0
MAX_ZOOM=13

# Use  true  (case sensitive) to allow data updates
DIFF_MODE=false

# Hide some output from Mapnik tile generation for clarity
FILTER_MAPNIK_OUTPUT=1

# Some area data like openstreetmap.fr can contain invalid references
# that must be cleaned up before using it for borders -- set it to true.
BORDERS_CLEANUP=false

# The current setup assumes this file is placed inside the data/ dir
MBTILES_FILE=tiles.mbtiles
# This is the current repl_config.json location, pre-configured in the tools Dockerfile
# Makefile and quickstart replace it with the dynamically generated one, but we keep it here in case some other method is used to run.
IMPOSM_CONFIG_FILE=/usr/src/app/config/repl_config.json

# import-borders temp files - set them here to defaults, and override in the Makefile based on the area
BORDERS_CLEANUP_FILE=data/borders/cleanup.pbf
BORDERS_PBF_FILE=data/borders/filtered.pbf
BORDERS_CSV_FILE=data/borders/lines.csv

# Number of parallel processes to use when importing sql files
MAX_PARALLEL_PSQL=5

# Number of parallel threads to use when generating vector map tiles
COPY_CONCURRENCY=100

# Variables for generate tiles using PGquery
PGHOSTS_LIST=
NO_GZIP=1
USE_KEY_COLUMN=1
```

The machine actually has 120 cores, so setting 100 threads here is not a ridiculous number. I initially tried with 120, and backed off to 100 after getting the memory errors.

**Comment by Falke-Design** [comment]
Hmm ok. Maybe this helps: https://github.com/RobotLocomotion/spartan/issues/369

I would check if docker can use enough space

**Comment by nyurik** [comment]
this looks like a postgreSQL error - you may need to either use a machine with more RAM, or at least adjust the PG settings. See https://github.com/openmaptiles/openmaptiles-tools/blob/master/docs/database.md

**Comment by ache051** [comment]
I ran into similar problems before. Might need to increase max_connections and max_locks_per_transaction in your PG settings.

**Comment by nyurik** [comment]
Closing as this is not really OMT's issue. Eventually we may want to do some additional PG setting detection to help with such issues, but optimizing PG is really outside of the OMT's scope.
