### ISSUE TITLE
Using PL/Python or ORM

### ISSUE THREAD

**Issue by mohammad-babaei** [openmaptiles/openmaptiles#1251]
I was wondering why openmaptiles isn't using PL/Python(or other high level languages or ORMs) instead of raw SQL(or hybrid approach)?
Wouldn't it be more understandable, maintainable and readable? We could have much more complicated algorithms and logic in the project.
Thank you in advance

**Comment by nyurik** [comment]
I'm afraid this is a bit outside of the OMT's issue scope. Do you have any specific changes in mind?  The OMT project is tightly coupled with [Postgis extension](https://postgis.net/), and cannot really be used on any other DB. There would be a significant cost in terms of development and runtime in managing another layer of abstraction on top of PG/postgis.
