### ISSUE TITLE
"make init-dirs" freezes

### ISSUE THREAD

**Issue by mohammad-babaei** [openmaptiles/openmaptiles#1261]
After [this commit](https://github.com/openmaptiles/openmaptiles/commit/ed65036766fa9c7c2a1eb5b61ad61bcb2e0499e2) the command "make init-dirs" is freezing for me, removing it from Makefile fixes it.
Is anybody else facing this issue and if not why am i facing it and how can i solve it without removing the < /dev/null from Makefile

**Comment by TomPohys** [comment]
Hi, are you using Windows? Do you using WSL? I made some instruction for using WSL on Windows (https://github.com/openmaptiles/openmaptiles/issues/1095#issuecomment-817099375). Maybe they could help.

**Comment by mohammad-babaei** [comment]
Hi, I'm actually on fedora

**Comment by TomPohys** [comment]
I am not expert on Fedora, but there is maybe some issue https://unix.stackexchange.com/questions/60083/no-dev-null-on-fedora-17
