### ISSUE TITLE
Add a class `province` to place layer

### ISSUE THREAD

**Issue by mits003** [openmaptiles/openmaptiles#1285]
I am keen to add a class `province` to place layer.

There is state class but some of the countries, including Japan don't have states but have provinces.
As a result of this, web apps that use OpenMapTiles miss the upper district name in some countries.

**Comment by TomPohys** [comment]
Hi @mits003, thank you for pointing this out. I think that adding a new class is not necessary. I think that will be enough to add ` - province` into [mapping.yaml](https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/mapping.yaml#L142) of `osm_state_point`.

then it will be added provinces mainly in Japan and Turkey - https://overpass-turbo.eu/s/1cB2
![image](https://user-images.githubusercontent.com/5182210/139672979-01a8d4fa-c5d6-4c85-9578-c6738e6c1320.png)

The hierarchy of `state` and `provinces` will be the same (class with value `state`) and there is no need to style these two differently.

PR is very welcome.

**Comment by mits003** [comment]
Thank you for your comment @TomPohys !

I will make PR!

**Comment by mits003** [comment]
Hi, @TomPohys 

Following your advice, I added `- province` but it didn't work because of filtering the scalerank at https://github.com/openmaptiles/openmaptiles/blob/ebeafc65fad2352662b9de2a07cfafcebca23082/layers/place/update_state_point.sql#L32

I investigated the scalerank in natural earth and the numbers of states and provinces in OSM.

Many of the countries have lower scalerans including European countries.

![スクリーンショット 2021-11-09 17 03 47](https://user-images.githubusercontent.com/43772370/140885619-c0a09190-1b44-4d33-9295-66e94f03e722.png)


There are 1769 states and 155 provinces in OSM - https://overpass-turbo.eu/s/1cQi (states in OSM)

![スクリーンショット 2021-11-09 17 02 25](https://user-images.githubusercontent.com/43772370/140885208-ab19d201-d923-48b2-abaf-ce18a2102f12.png)

Then I'd like to propose that to import both states and provinces regardless of its scalerank or labelrank.
What do you think?
