### ISSUE TITLE
Release OpenMapTiles 3.13

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles#1287]
We are planning to release a new version of OpenMapTiles before Christmas 2021.

After release 3.12.2 there is a lot of **awesome** [work](https://github.com/openmaptiles/openmaptiles/compare/v3.12.2...master) that deserves to be in the new release.

We would like to announce a feature freeze as soon as possible, but if anyone knows about some cool update or have some unfinished work that would like to bring into release 3.13, we will wait.

If you are aware of an issue that needs to be released in 3.13 please let us know. The last missing tickets are in [milestone 3.13](https://github.com/openmaptiles/openmaptiles/milestone/17)

Thank you all for your contributions to the OpenMapTiles project.

**Comment by ZeLonewolf** [comment]
Yay!

I have two items that I would like to see included in 3.13:

#1190 **Selective rendering of tracks and path** - It just needs some debugging and I I'm pretty sure I have a way forward to handle path/track attributes in a way consistent with the feedback on that ticket.

#1148 **Expressway tagging** - This one is really important to an American map style, and it is intertwined with [2021 US Highway Classification Guidance](https://wiki.openstreetmap.org/wiki/United_States/2021_Highway_Classification_Guidance).  Differentiated expressway rendering is an important component to importance-based highway classification tagging and will help us achieve an attractive render of the American highway system at all zooms.

I'm confident I can get both of these done well within the the planned timeline for 3.13.

**Comment by zstadler** [comment]
I would like PR #1289 to be included in the release.

**Comment by TomPohys** [comment]
Thank you all for your work! All planned enhancements are committed. Now we are starting the testing process before the final release v3.13.

**Comment by hyperknot** [comment]
Important seas are missing from water_name, like Adriatic sea in current master. I think it'd be quite important to fix them before a release.
https://github.com/openmaptiles/openmaptiles/issues/1322
