### ISSUE TITLE
Investigate why update-osm will not update on a daily interval

### ISSUE THREAD

**Issue by stirringhalo** [openmaptiles/openmaptiles#130]
I have a full planet import but cannot update it with update-osm. I suspect it is because the config.json is either supposed to not be included or it has to have all the connection parameters, not a mix of half in the config.json, half in the command call.

**Comment by lukasmartinelli** [comment]
> I have a full planet import but cannot update it with update-osm. I suspect it is because the config.json is either supposed to not be included or it has to have all the connection parameters, not a mix of half in the config.json, half in the command call.

But updating hourly worked for you with imposm-run right?
I also didn't get it to work with daily.

**Comment by stirringhalo** [comment]
I did discover there was a typo in config.json, see 24b0a396ec241.

But even still, no updates, blank output. I accidentally removed last.state.txt in doing some cleanup but I grabbed the old one from http://planet.openstreetmap.org/replication/hour/000/037/ which should correspond to this import.

Could you confirm the format of last.state.txt?

**Comment by stirringhalo** [comment]
Hold on, I'm on a super slow net connection for my processing machine, it's slow grabbing all the changesets. I will report back when I have more info.

**Comment by stirringhalo** [comment]
Okay, daily update is going fine with all the parameters in the config.json. I will try again with the original config.json but I suspect that is fine.

**Comment by stirringhalo** [comment]
I can confirm now that it updates just fine with the mix of parameters in config.json and in the command call. Issue resolved.
