### ISSUE TITLE
Generated tiles look broken

### ISSUE THREAD

**Issue by xinyuluo** [openmaptiles/openmaptiles#1300]
Hi, I'm new to OMT, and not sure if this is the right platform to post this issue: my goal was to generate tiles, serve them and display them on web. I'm using OMT to generate mbtiles from .osm.pbf file and I've followed steps in README. The displayed output looks quite off, and since I was able to display MBTiles from other sources quite nicely, I wonder what I am missing / doing wrongly in generating tiles. I tried multiple regions and all of them have the same issue, so I don't think it's because of corrupted data.

Here's a screenshot of how mbtiles of Singapore looks like when displayed. Many highway lines looks cut off, and when I zoom in further, I don't see more details (like different buildings that I see in other maps).
![image](https://user-images.githubusercontent.com/25223376/141477632-38c3e393-c90f-4f40-8d0e-764f334b87eb.png)

Any help or ideas would be greatly appreciated!

**Comment by TomPohys** [comment]
Hi, yes, this is the right platform for generating vector tiles from OpenStreetMap. It looks like, that the `import-osm` and `import-sql` steps were finished successfully. As the default is in the `.env` file set up `MAX_ZOOM=7` which means, that you generate tiles until zoom 7. All next zooming in a browser was showing over-zoomed tiles. 

As the next step, you can just adjust the `MAX_ZOOM` parameter and generate new vector tiles. You do not have to re-importing data or SQL (steps `import-osm` and `import-sql`), all data is already in the database.

**Comment by xinyuluo** [comment]
@TomPohys thanks for the quick reply! I just tested with `MAX_ZOOM=14` and it looks quite nice : ) just wondering if that's the max zoom level one can go up to in OMT? I tried 18 as well but I see in the logs that it can still only go to 14 maximum.
```
  Zoom    Tile count  Found tile ranges
------  ------------  -----------------------
     0             1  0,0 x 0,0
     1             1  1,1 x 1,1
     2             1  3,2 x 3,2
     3             1  6,4 x 6,4
     4             1  12,8 x 12,8
     5             1  25,16 x 25,16
     6             1  50,32 x 50,32
     7             1  100,64 x 100,64
     8             1  201,128 x 201,128
     9             1  403,257 x 403,257
    10             2  806,515 x 807,515
    11             6  1613,1030 x 1615,1031
    12            20  3227,2060 x 3231,2063
    13            70  6454,4121 x 6463,4127
    14           240  12908,8243 x 12927,8254
```

**Comment by TomPohys** [comment]
You can go deeper than 14. Nevertheless, all the features which are defined in OpenMapTiles (schema) are designed for zooms 0 - 14. It is OK to use over-zooming on zoom 14. Zoom 15 is already discussed (e.g. possibility for adding new features, better precision on geometry, ...)

if you would like to generate deeper zooms, please adjust also `openmaptiles.yaml` then run `make clean`, `make` and then try generating again.
