### ISSUE TITLE
Different mbtile file sizes with make generate-tiles and make generate-tiles-pg

### ISSUE THREAD

**Issue by mohammad-babaei** [openmaptiles/openmaptiles#1302]
Generating the vector tiles file is almost twice the size when using `make generate-tiles-pg` that uses St_AsMVT function.
The legacy `make generate-tiles` on the same osm.pbf file generates the mbtiles that has half the size but i think it's buggy that was addressed in the issues.
Why is this size difference happening, is it a trade off or something?

**Comment by TomPohys** [comment]
Hi @mohammad-babaei, this is very strange. Could you please provide more information like, which area you are using, which OMT and OMT-T release? Could you please find some example tile where is the difference obvious? Thanks
