### ISSUE TITLE
Output location mismatch

### ISSUE THREAD

**Issue by codydaig** [openmaptiles/openmaptiles#1310]
The quickstart script says it's outputting the .mbtiles file to `./data/${area}.mbtiles` however it's currently going to `./data/tiles.mbtiles` everytime. Is there a way to set the output to be area.mbtiles? I want to generate a bunch of areas and would like to prevent having to rename them after every generation. Thanks!

**Comment by TomPohys** [comment]
Hi @codydaig, please comment out the predefined mbtiles name in `.env` file. Then it will take the value from `area=` attribute or, if in `data` folder is only one `pbf`, then will take that name. https://github.com/openmaptiles/openmaptiles/blob/cdff735be10caa5ac7dc26f9309a843499c84bcf/.env#L36

**Comment by codydaig** [comment]
Perfect! Thanks!
