### ISSUE TITLE
Background layer doesn't render 

### ISSUE THREAD

**Issue by kartographinya** [openmaptiles/openmaptiles#1312]
Hello,

We created and embeded the map to the website. The map style is based on the Positron. The problem is that sometimes the background layer does not render at all zoom levels, but when we reload the website, it appears again (see pictures). 

![Снимок экрана от 2021-11-25 11-37-40](https://user-images.githubusercontent.com/58175782/143407470-66e4b1f0-5b0c-48f4-9ee0-99758cbce3f8.png)
![Снимок экрана от 2021-11-25 11-37-56](https://user-images.githubusercontent.com/58175782/143407525-9a9d0ed6-b0b8-41d8-bd54-01c8c8424de7.png)

Unfortunately, we can't share our website yet. 

Have a good day!

**Comment by TomPohys** [comment]
Hi, thank you for your question. The background color is set up for spaces, where is no data. It is not a separate "background" layer. It is odd, that after reloading the website, it will appear again. In the `style.json` you should have something similar as 
```{
  "id": "background",
  "type": "background",
  "paint": {
    "background-color": "rgba(158, 147, 147, 1)"
  },
  "layout": {"visibility": "visible"}
}
```

**Comment by kartographinya** [comment]
> Hi, thank you for your question. The background color is set up for spaces, where is no data. It is not a separate "background" layer. It is odd, that after reloading the website, it will appear again. In the `style.json` you should have something similar as
> 
> ```
>   "id": "background",
>   "type": "background",
>   "paint": {
>     "background-color": "rgba(158, 147, 147, 1)"
>   },
>   "layout": {"visibility": "visible"}
> }
> ```

Hi! Yes, I have it in style.json, it is visible.

**Comment by daliborjanak** [comment]
I think the problem is not with the background but with landuse_residential that overlays over the background in cities. It ends on zoom 16
```
{
  "id": "landuse_residential",
  "type": "fill",
  "paint": {
    "fill-color": "rgb(234, 234, 230)",
    "fill-opacity": {
      "base": 0.6,
      "stops": [[8, 0.8], [9, 0.6]]
    }
  },
  "filter": [
    "all",
    ["==", "$type", "Polygon"],
    ["==", "class", "residential"]
  ],
  "layout": {"visibility": "visible"},
  "source": "openmaptiles",
  "maxzoom": 16,
  "source-layer": "landuse"
}
```

**Comment by kartographinya** [comment]
> 

Thank you! However, we don't use landuse_residential in our map.

**Comment by kartographinya** [comment]
> I think the problem is not with the background but with landuse_residential that overlays over the background in cities. It ends on zoom 16
> 
> ```
> {
>   "id": "landuse_residential",
>   "type": "fill",
>   "paint": {
>     "fill-color": "rgb(234, 234, 230)",
>     "fill-opacity": {
>       "base": 0.6,
>       "stops": [[8, 0.8], [9, 0.6]]
>     }
>   },
>   "filter": [
>     "all",
>     ["==", "$type", "Polygon"],
>     ["==", "class", "residential"]
>   ],
>   "layout": {"visibility": "visible"},
>   "source": "openmaptiles",
>   "maxzoom": 16,
>   "source-layer": "landuse"
> }
> ```

Thank you! However, we don't use landuse_residential in our map.

**Comment by daliborjanak** [comment]
Ok, so we need more information. Link to style or app, javascript viewer etc.

**Comment by TomPohys** [comment]
Hi, did you solved this issue?

**Comment by TomPohys** [comment]
Hi @kartographinya, any update?

**Comment by kartographinya** [comment]
> Hi @kartographinya, did you solve this issue?

No, the problem is the same

**Comment by TomPohys** [comment]
Could you please provide some more information about the problem? Thanks
