### ISSUE TITLE
Generated mbtiles contains `tiles` view instead of table

### ISSUE THREAD

**Issue by Helcaraxan** [openmaptiles/openmaptiles#1317]
Before getting to the core of the reported issue: thank you for this project and the overall open source work, I'm really enjoying using it.

While working on an embedded application using the tilesets generated by the tooling of this project I noticed that the `mbtiles` files do not follow the [exact spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#schema-1).

Specifically it mentions:
> The database MUST contain a table named `tiles`.
>
> The table MUST contain three columns of type `integer`, named `zoom_level`, `tile_column`, `tile_row`, and one of type `blob`, named `tile_data`. A typical `create` statement for the `tiles` table:
> 
> ```
> CREATE TABLE tiles (zoom_level integer, tile_column integer, tile_row integer, tile_data blob);
> ```

However the files that are currently generated instead contain a `tiles` view:
```sql
CREATE VIEW tiles AS
    SELECT
        map.zoom_level AS zoom_level,
        map.tile_column AS tile_column,
        map.tile_row AS tile_row,
        images.tile_data AS tile_data
    FROM map
    JOIN images ON images.tile_id = map.tile_id
```

In general this should not be an issue as one can query views just like tables in SQL. However in the case of my embedded system the more simple (and hence more lightweight) sqlite implementations only support tables and indices.

Is there a specific rationale for deviating from the spec on this point or whether this is something that this is something that might be rectified?

NB: I can always modify my own fork of the project to generate the MBTiles according to spec but it would be good to know if there's interest in upstreaming such a change.

**Comment by nyurik** [comment]
The irony is that Mapbox's own tilelive-copy generates that mbtiles structure. This is not something omt invented. Moreover, the new tile generation method that uses MID_ZOOM param explicitly relies on identical tiles stored efficiently for imputing.

**Comment by pnorman** [comment]
The specification [states](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#database)

> Note: the schemas outlined are meant to be followed as interfaces. SQLite views that produce compatible results MAY be used instead. For convenience, this specification refers to tables and virtual tables (views) as tables.

**Comment by nyurik** [comment]
I stand corrected, it IS being generated as described in the standard. I never noticed that sidenote either.

**Comment by Helcaraxan** [comment]
Thank you for taking the time to answer and providing that pointer @pnorman. I'm closing this issue then.

Like @nyurik I've read through the spec a dozen of times over the past months without ever noticing that sidenote. I'll take the custom road then and adapt my own version of the `openmaptiles-tools` repo to generate an mbtiles with a table and remove other superfluous data to suit my needs.

**Comment by nyurik** [comment]
@Helcaraxan I don't know if it would be possible to fix this with forking - I didn't see any param in [tilelive-copy](https://github.com/mapbox/TileLive) to generate a different SQL structure.  I think one solution is to improve [mbtiles-tools copy](https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/mbtiles-tools) - so that after generating tiles, you run this command with some additional param to copy to a `flat` structure (e.g. `--flat` ?). PR is welcome, seems like a good feature to have.

**Comment by Helcaraxan** [comment]
@nyurik my plan was to work within openmaptiles-tools [here](https://github.com/openmaptiles/openmaptiles-tools/blob/master/openmaptiles/mbtile_tools.py) as this seems to contain the relevant SQL statements that create the DB structures in question.

I have not yet had the time to go over the full stack in detail so if you have particular suggestions on whether this idea is flawed or whether it could be improved upon I am all ears and would welcome your ideas.

As a last resort I can always do a post-generation treatement of the mbtiles files by querying them via a purpose-built script / program to create an entirely new mbtiles file but with the flat SQL structure.

**Comment by nyurik** [comment]
I was actually thinking more of a `--format flat|default|compact` arguments because I am hoping one day to figure out if [this method](https://stackoverflow.com/questions/68684759/storage-optimizing-sqlite-blob-to-act-as-data-or-foreign-key) will give disk and performance savings.

**Comment by nyurik** [comment]
P.S. can you be more specific what other filtering you want to do when copying? We should probably do those (if needed) as separate parameters, as it doesn't sound like they affect the DB structure.

**Comment by Helcaraxan** [comment]
My filter would eliminate any data that is not part of the minimum content (as per spec) of an mbtiles file. So this would remove UTFGrid data and the 5 tables, 8 indices and 2 views associated with it (if counting per the mbtiles file that I generated ~1 month ago as an example to work with).

What would remain would be the two suggested tables and index:
```sql
CREATE TABLE metadata (name text, value text);
CREATE TABLE tiles (zoom_level integer, tile_column integer, tile_row integer, tile_data blob);
CREATE UNIQUE INDEX tile_index on tiles (zoom_level, tile_column, tile_row);
```
