### ISSUE TITLE
BUGFIX: `transportation_name_tags` using original values for `get_basic_names`

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles#1324]
`transportation_name_tags` currently using [`get_basic_names`](https://github.com/openmaptiles/openmaptiles/blob/7838221b163cdcecf7eab81ec18fa73757f024e5/layers/transportation/highway_name.sql#L10) as part of the `SELECT` statement which cause that input values of `tags` are "original"  without the modifications from `osml10n_street_abbrev_all`, `osml10n_street_abbrev_en` or `osml10n_street_abbrev_de`.

So the `get_basic_names` returning `name:latin` and `name_int` as original names without shortening.

v3.12 vs v3.13
![seattle_v3 12](https://user-images.githubusercontent.com/5182210/145068559-e2f7370e-4b2a-4d6d-ad20-85c2f0ced736.png)

![seattle_v3 13](https://user-images.githubusercontent.com/5182210/145068562-27143db4-acb8-4192-b686-271b5dd31486.png)

As a fix, the `get_basic_names` should be removed from `transportation_name_tags` and put back into `layers/transportation_name/update_transportation_name.sql` (as it was removed in https://github.com/openmaptiles/openmaptiles/pull/1295)

**Comment by ZeLonewolf** [comment]
Are you looking for a PR or is it already in the works?

**Comment by TomPohys** [comment]
Thanks, I already running a local test. I will submit a PR.
