### ISSUE TITLE
Include peaks without elevation

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#1328]
Currently, the `mountain_peak` layer excludes peak points with elevation.

https://github.com/openmaptiles/openmaptiles/blob/7d08e5b97e560efd783282d0e09fae4041fb84d7/layers/mountain_peak/mountain_peak.sql#L74-L76

This limits the value of the maps in areas where mapping data is not detailed as in other parts of the world. 
Unlike the default OSM maps, OMT-based maps cannot show peaks if their elevation is unknown.
I also believe that if OSM mappers have added a peak it is likely that this mapping is of value even if the elevation is unknown.

I've already implemented this in my fork and I'll be happy to send a PR.

**Comment by TomPohys** [comment]
Hi, I understand that this is an old issue (and another even older https://github.com/openmaptiles/openmaptiles/issues/761). We should include peak points with a name and without elevation, e.g. as it is now including peak points with elevation without a name.
