### ISSUE TITLE
Problem with new NaturalEarth schema in place-layer

### ISSUE THREAD

**Issue by jhanninen** [openmaptiles/openmaptiles#1329]
Looks like NaturalEarth schema has been changed which breaks down import-sql command in place.sql 

They have removed `gn_ascii` field that is used here: https://github.com/openmaptiles/openmaptiles/blob/7d08e5b97e560efd783282d0e09fae4041fb84d7/layers/place/update_city_point.sql#L26-L27

Removing the column for those two lines resolved the problem on OpenMapTiles v3.12.2. Not sure if there're more problems but at least not in our (a bit customized) setup https://github.com/HSLdevcom/openmaptiles/commit/f4c2c37aedc741838a51d97fbcfcd3bf5f741920.

Link to the changelog of NE: https://github.com/nvkelso/natural-earth-vector/blob/master/CHANGELOG

**Comment by TomPohys** [comment]
Thanks for pointing this out. For release 3.14 is planned to update all layers to Natural Earth 5.

**Comment by TomPohys** [comment]
Solved by https://github.com/openmaptiles/openmaptiles/pull/1409
