### ISSUE TITLE
osm_building_block_gen1_dup of entire planet is very slow

### ISSUE THREAD

**Issue by mmib** [openmaptiles/openmaptiles#1332]
CREATE MATERIALIZED VIEW osm_building_block_gen1_dup AS
SELECT *
FROM osm_building_block_gen1();

This query is running for 124 hours already on bare metal server with Ubuntu 20.04 LTS. This process took 209G of RAM and continue to grow.
Other steps like waterway and transportation seems to take reasonable time but this query is really slow. Any suggestions on how much to wait or what can be tweaked there?

**Comment by TomPohys** [comment]
There was significant speed up by https://github.com/openmaptiles/openmaptiles/pull/1044. There is also a second option and not use building generalization on zoom 13 at all https://github.com/openmaptiles/openmaptiles/issues/938#issuecomment-672252734  and https://github.com/openmaptiles/openmaptiles/issues/938#issuecomment-708486115
