### ISSUE TITLE
Duplicating landcover records at 8th zoom level

### ISSUE THREAD

**Issue by alexey-zakharenkov** [openmaptiles/openmaptiles#1338]
Currently, duplicating records are generated for some landcover features in `osm_landcover_gen_z8` table (file layers/landcover/generalize.sql). In the `CREATE TABLE osm_landcover_gen_z8 AS ...` statement the second subquery of `UNION ALL` operator generates duplicates (not necessarily exact due to cluster-union-dump procedure) for all features except woods and forests.

**Comment by TomPohys** [comment]
Thank you. The landcover layer needs some more work (like https://github.com/openmaptiles/openmaptiles/issues/1351). Any help is very welcome.

**Comment by TomPohys** [comment]
Fixed in https://github.com/openmaptiles/openmaptiles/pull/1413.
