### ISSUE TITLE
Is it possible to merge Planet with custom tileset?

### ISSUE THREAD

**Issue by fmariv** [openmaptiles/openmaptiles#1346]
Hello everyone,
At my company we are currently working in the generation of VT of an specified territory with our own vector data. The fact is that I wonder if we can generate Planet VT with OSM data, in order to have a "planetary basemap", and then merge into that tileset our own and custom tiles, maybe exporting our vector data to the PostGIS database generated with the openmaptiles toolset.

**Comment by nyurik** [comment]
Sure, just add your own custom layer using other layers as a guide. You will need to import your data into PostgreSQL for that. Other ways are also possible, but might be a bit more complex.

P.S. @TomPohys or @klokan - please enable github discussions - might be easier to post questions there.

**Comment by fmariv** [comment]
OK! So we just have to import our data into PostgreSQL following the layers that already exist in the database as a "guide", isn't it? Following the OpenMapTiles scheme.

**Comment by nyurik** [comment]
@fmariv pretty much. You don't even need to follow any kind of PostgreSQL data schema -- it is totally up to you, as long as you can quickly query it by a geo envelope (tile bbox).  The layer yaml file will specify the query to use to get the needed data.

**Comment by TomPohys** [comment]
Hi @fmariv, you can also look into https://github.com/maptiler/foss4g-workshop where it is described how to add a new layer into OMT schema.
