### ISSUE TITLE
Landcover/usage vectorised incorrectly when split into smaller chunks

### ISSUE THREAD

**Issue by ntadej** [openmaptiles/openmaptiles#1351]
Slovenian landcover/usage is split into 2x3 km rectangles. When this is parsed from OSM it causes rendering on small zoom levels as tiles think it's a small polygon.

Can be observed on MapTiler: https://data.maptiler.com/downloads/dataset/osm/europe/slovenia/#7.1/46.155/14.993
<img width="1066" alt="Screenshot 2022-01-10 at 22 06 54" src="https://user-images.githubusercontent.com/805384/153293334-29358a6a-033c-41e1-9c1d-30a97b792583.png">
<img width="1078" alt="Screenshot 2022-01-10 at 22 07 25" src="https://user-images.githubusercontent.com/805384/153293365-0276c4e8-d726-47af-901b-4c03852514db.png">

The third screenshot is OSM directly: https://www.openstreetmap.org/#map=9/46.2064/14.4333
<img width="1040" alt="Screenshot 2022-01-10 at 22 09 54" src="https://user-images.githubusercontent.com/805384/153293384-bccb36e0-c16f-4b5e-acbf-a90c71b05aa6.png">

Should these rextangles be merged in OSM or can something be done here?

**Comment by ntadej** [comment]
Seems to be related to #1035 (but it does not seem to be working for Slovenia).

**Comment by stefanb** [comment]
Merging them in OSM would result in some huuuugeeee multipolygons, making them near impossible to edit.

A similar issue #201 was raised previously and i mentioned Slovenia in the comments, but apparently it fixed only for higher zoom levels.

**Comment by TomPohys** [comment]
Thanks for pointing this out. This should be part of the processing (fixing) landcover layer. Any help is very welcome.

**Comment by farfromrefug** [comment]
@TomPohys do we know how maptiler globallandcover is generated? i feel like somehow the did it better there. maybe check that region to see if we see the same thing there at zoom 9
