### ISSUE TITLE
Overlaps and gaps for adjacent polygons

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/openmaptiles#1356]
At higher zoom levels, overlaps and gaps between adjacent polygons (e.g. buildings) are becoming visible.

**Example:**
https://www.maptiler.com/maps/#bright//vector/21.17/6.4175355/51.4392107

![grafik](https://user-images.githubusercontent.com/20856381/154293226-1d1d88da-818f-446c-b11e-06cdb750f36d.png)

In OSM these nodes are shared by adjacent ways, e.g.:
https://www.openstreetmap.org/node/3465031751

![grafik](https://user-images.githubusercontent.com/20856381/154293415-b9d08408-8df4-4a70-a686-881ce13631fb.png)

Looks like shared nodes in OSM are not retained for OpenMapTiles, resulting in different node positions and thus in overlaps and gaps for adjacent polygons.

**Comment by TomPohys** [comment]
Hi, OpenMapTiles generate vector tiles up to zoom 14, everything higher is overzoom. Vector tile has an inner grid 4096x4096 where the geometry is snapped. This could cause these overlaps and gaps.

**Comment by pathmapper** [comment]
Hi @TomPohys, right, but why are shared nodes snapped to different positions of the inner grid? 

In OSM these adjacent polygons are sharing the same nodes (= same coordinates), so they should be located on the same position of the inner grid when overzooming, right?

**Comment by TomPohys** [comment]
In the database, every building is a separate record. So, when the tile is requested, the points could be snapped into different places.

**Comment by pathmapper** [comment]
> So, when the tile is requested, the points could be snapped into different places.

@TomPohys why would points from different records with exactly same coordinates in OSM be snapped into different places? 

I still think this is an issue....

**Comment by TomPohys** [comment]
This is a common problem with simplification. If you do not have a full topological model, the simplification could break the adjacent polygons.
e. g. 
https://github.com/r-spatial/sf/issues/381#issuecomment-446337813
https://trac.osgeo.org/postgis/wiki/UsersWikiSimplifyPreserveTopology

**Comment by pathmapper** [comment]
This issue becomes very visible for  buildings at high zoom levels (overzoomed z14 tiles), for buildings there are quite often adjacent polygons.

Is there really a need to simplify z14 buildings? 

So we are loosing some nodes for z14 buildings because of simplification. Where does this simplification for z14 take place?

The following one should be only for z13 buildings, right? 

https://github.com/openmaptiles/openmaptiles/blob/1c1231e4309653979ac6d2fa86dd3ef15c531127/layers/building/update_building.sql#L81

**Comment by TomPohys** [comment]
Yes, `update_building.sql` is only for Z13.

There is no simplification for buildings on Z14. Buildings are taken from the view [`osm_all_buildings`](https://github.com/openmaptiles/openmaptiles/blob/1c1231e4309653979ac6d2fa86dd3ef15c531127/layers/building/building.sql#L7) and there is no simplification. 

The simplification is done due to vector tiles grid 4096x4096 as it is in the specs (https://mapbox.github.io/vector-tile-spec/ - Encoding geometry)

This is the image from QGIS where dots are 4096x4096 grid (approx.) of one tile at Z14. 
![image](https://user-images.githubusercontent.com/5182210/181303454-42b05b4c-3e2e-4d98-85ff-1e2fe1756c64.png)

**Comment by pathmapper** [comment]
But nodes with same coordinates should snap on the same grid dot, right?

For me it looks like nodes are missing.

Example: 

Node https://www.openstreetmap.org/node/3465031751

is part of 
- https://www.openstreetmap.org/way/339318265
- https://www.openstreetmap.org/way/981324063 
- https://www.openstreetmap.org/way/981324062

But having a look at https://www.maptiler.com/maps/#bright//vector/22/6.4175596/51.43921424

![grafik](https://user-images.githubusercontent.com/20856381/181358238-d07fd40a-3561-432a-aaa5-ea18161c4771.png)

it looks like the node is only there for 
- https://www.openstreetmap.org/way/981324063 
- https://www.openstreetmap.org/way/981324062

(for both geometries this is a _corner node_ and the topology is correct for these geometries in this area)

and missing for 
- https://www.openstreetmap.org/way/339318265

were this node is NOT a _corner node_.

---

For some reason the geometries are now looking different compared to the screenshot in https://github.com/openmaptiles/openmaptiles/issues/1356#issue-1140151162.

**Comment by pathmapper** [comment]
Turns out that this could be related to simplification done by `ST_AsMVTGeom`, see also 

- https://trac.osgeo.org/postgis/ticket/4149

- https://gis.stackexchange.com/questions/423412/accuracy-loss-in-vector-tiles-generated-with-st-asmvtgeom.

According to the SE post

> this is fixed/improved in PostGIS 3.2.0

This should be the relevant change:
https://github.com/postgis/postgis/pull/463

Looks like currently PostGIS 3.1.0 is used:
https://github.com/openmaptiles/openmaptiles-tools/blob/b8f0ae329f6e295a0abad741e0345e6a4abbaa85/docker/postgis/Dockerfile#L5

So let's wait until `openmaptiles-tools` uses PostGIS 3.2.0 and hopefully the issue is gone :crossed_fingers:

**Comment by pathmapper** [comment]
PostGIS updated to 3.2 in https://github.com/openmaptiles/openmaptiles-tools/pull/413, thanks @TomPohys !

**Comment by TomPohys** [comment]
As nothing more will be done in this matter, could we close this issue? 

Anyway, thanks for investigating!

**Comment by pathmapper** [comment]
Sure, overlaps and gaps are fixed with the PostGIS update. Thanks again!
