### ISSUE TITLE
No labels on raster endpoint of tileserver-gl

### ISSUE THREAD

**Issue by jendrusk** [openmaptiles/openmaptiles#1368]
I've made OMT server with custom style for the visually impaired. The problem is that everything works fine on vector endpoint but I don't have labels on raster endpoint. Could anybody look at this and tell me what's wrong? No errors in logs.

https://osmwcag.voxly.pl/

Style: Tyflo

Thanks in advane

**Comment by TomPohys** [comment]
Hi, issues for Tileserver-GL is in a different repo https://github.com/maptiler/tileserver-gl. But I look at it and I would like to ask about Arial Bold font. Where for the `housenumbers` should be Arial Bold, but is it? For example https://osmwcag.voxly.pl/styles/Tyflomap/?vector#20.33/54.5792143/18.3818888. Rasterization is maybe more strict when it comes to fonts.

**Comment by jendrusk** [comment]
Hi Tom. Thanks for your answer.
What's strange - I've placed missing fonts in data directory mapped by docker. You can download them via www, but I've found there are indeed errors in logs... Maybe I've placed them in wrong place?
```
../data
├── config.json
├── fonts
│   ├── Arial Bold
│   │   ├── 0-255.pbf
│   │   └── 256-511.pbf
│   ├── Noto Sans Regular
│   │   ├── 0-255.pbf
│   │   └── 256-511.pbf
│   └── Verdana Bold
│       ├── 0-255.pbf
│       └── 256-511.pbf
├── poland.bbox
├── poland.osm.pbf
├── quickstart_checklist.chk
├── styles
│   ├── sprite@2x.json
│   ├── sprite@2x.png
│   ├── sprite.json
│   ├── sprite.png
│   ├── tyflomap.json
│   └── tyflomap.json_old
└── tiles.mbtiles
```

**Comment by klokan** [comment]
Not an issue which belongs to this repository. Sorry.
