### ISSUE TITLE
Landuse broken between zoom 6 till 10

### ISSUE THREAD

**Issue by hyperknot** [openmaptiles/openmaptiles#1372]
The landuse layer is broken / polygonized / scattered on layers between 6 till 10.
It looks continuous under 6 and over 10.

z5:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/494223/161382365-96187c1a-c1c5-487e-98c9-8cbe777a8eb5.png">

z6:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/494223/161382377-5e68fc89-d442-4c42-bc72-6b680210d895.png">

z7: 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/494223/161382386-69aaaf66-6c58-416d-a508-f1326b3e23a1.png">

z10:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/494223/161382395-6e0bab60-4617-47e7-8b73-3d39d6b1a20d.png">

**Comment by TomPohys** [comment]
Similar to https://github.com/openmaptiles/openmaptiles/issues/1358
