### ISSUE TITLE
[BUG] Unify ferry tagging in transportation and transportation_name layers

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1373]
In ZeLonewolf/openstreetmap-americana#266, it was noted that ferry lines are tagged differently in the `transportation` and `transportation_name` layers.  I suggest a fix of changing the attributes to `class=ferry` for both layer.  See discussion below:

> Shouldn't the class/subclass on transportation_name match the class/subclass on corresponding lines in transportation?

That would be a sensible assumption, but currently in the tiles transportation has class=ferry while transportation_name has subclass=ferry for some reason.  Seems like this may be a mistake, but hard to say since [the schema docs](https://openmaptiles.org/schema) don't say anything about ferries at all.

![image](https://user-images.githubusercontent.com/281482/161873169-99f6f883-2eb3-4eec-a249-41565370d1ea.png)

_Originally posted by @zekefarwell in https://github.com/ZeLonewolf/openstreetmap-americana/issues/266#issuecomment-1089588133_

**Comment by claysmalley** [comment]
@ZeLonewolf Can you confirm if this is still an issue? I'm seeing `class=ferry` under `#transportation_name`:

![Screenshot from 2022-07-27 19-20-14](https://user-images.githubusercontent.com/1732117/181388910-026ddc5a-d9d1-40b1-a7a3-17dca229814c.png)

**Comment by jleedev** [comment]
That's planetiler; maptiler still has this:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/23022/181390877-917292e4-04fe-433d-a078-2bcacf41ddf4.png">

**Comment by ZeLonewolf** [comment]
@msbarry
