### ISSUE TITLE
Hanging on "Wait for PostgreSQL to start..." 

### ISSUE THREAD

**Issue by ValorNaram** [openmaptiles/openmaptiles#1378]
After commit 22915df78305bf7f2887ed2ec37cea6e7271d93f the generation process broke on my site and yields:

```bash
====> : Start PostgreSQL service using empty database and importing all the data:
      : * Water data from http://osmdata.openstreetmap.de
      :   Data license: https://osmdata.openstreetmap.de/info/license.html
      : * Natural Earth from http://www.naturalearthdata.com
      :   Terms-of-use: http://www.naturalearthdata.com/about/terms-of-use
      : * OpenStreetMap Lakelines data https://github.com/lukasmartinelli/osm-lakelines
      :
      : Source code: https://github.com/openmaptiles/openmaptiles-tools/tree/master/docker/import-data
      :   includes all data from the import-data image
      :
      : Thank you https://www.postgresql.org !  Thank you http://postgis.org !
Starting postgres docker compose target using default image (no recreate if exists)
Creating openmaptiles_postgres_1 ... 
Creating openmaptiles_postgres_1 ... done
Wait for PostgreSQL to start...
docker-compose run --rm --user=0:0 openmaptiles-tools pgwait
Creating openmaptiles_openmaptiles-tools_run ... 
Creating openmaptiles_openmaptiles-tools_run ... done
... gave up waiting for Postgres:   PGHOST=postgres PGDATABASE=openmaptiles PGUSER=openmaptiles PGPORT=5432 pg_isready
1
make: *** [Makefile:308: start-db] Error 1
```

Same issue exists on a different system. I am using quickstart with an area pre-downloaded and pre-processed by scripts I executed beforehand.

**Workaround:**
`git revert 22915df78305bf7f2887ed2ec37cea6e7271d93f`

Docker version: `Docker version 20.10.14, build a224086`
Docker-compose version: `docker-compose version 1.29.2, build 5becea4c`

I removed all openmaptile images and containers beforehand as I did a full clean of the docker files on my host system.

**Comment by ValorNaram** [comment]
I had `TOOLS_VERSION=6.1` in my `.env` file and changed it to `TOOLS_VERSION=latest` and now it works again. Seems 6.1 is not compatible to the said commit from above. But maybe also a wrong conclusion because of lack of my knowledge about "tools".

**Comment by TomPohys** [comment]
Hi, I am glad, that it works now. Yes, for changes in that commit was necessary to use the latest OMT-T where the necessary changes have been applied before OMT (https://github.com/openmaptiles/openmaptiles-tools/pull/403).

**Comment by ondrejlohnisky** [comment]
I know this is not related. But I've got the same error while all config was correct. And even stoping and removing the container did not help.

I had to remove all docker images and containers. At least those that relate.
`docker stop $(docker ps –filter status=running -q)`
`docker rm $(docker ps –filter status=exited -q)`
`docker rmi $(docker images -q)`

I could not find any help on this so i hope it helps someone.

**Comment by DanielJWood** [comment]
Hiya. I'm currently having this same issue on Mac with an M1 chip. I'm wondering if it's a hardware/environment specific issue because when I tried it on an older Intel mac, it get through `make start-db` without a problem. Any suggestions would be appreciated!

**Comment by DanielJWood** [comment]
fwiw, I tried with a different, brand new machine, also an M1 mac, and it also hangs. The output for `make start-db` is as follows: 

```
Using docker compose V1 (docker-compose)
Starting postgres docker compose target using default image (no recreate if exists)
[+] Running 1/0
 ✔ Container openmaptiles-postgres-1  Running                                                                                                                       0.0s
Wait for PostgreSQL to start...
docker-compose run --rm --user=503:20 openmaptiles-tools pgwait
... gave up waiting for Postgres:   PGHOST=postgres PGDATABASE=openmaptiles PGUSER=openmaptiles PGPORT=5432 pg_isready
make: *** [start-db] Error 1
```
