### ISSUE TITLE
Update to Natural Earth 5

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles#1379]
Update Natural Earth 4.1 from 2018 with new version 5.0.1 released in 2022.

Layers affected

- boundary
- landcover
- landuse
- place
- transportation
- water
- water_name
- waterway

EDIT: to new version 5.1.0

**Comment by nvkelso** [comment]
FWIW v5.1.0 will come out this week.

**Comment by TomPohys** [comment]
Awesome! Looking forward to it!

**Comment by nvkelso** [comment]
v5.1.0 has been released

**Comment by TomPohys** [comment]
Solved by https://github.com/openmaptiles/openmaptiles/pull/1409
