### ISSUE TITLE
Borders are not visible

### ISSUE THREAD

**Issue by bilemedimkq** [openmaptiles/openmaptiles#1400]
Hello, I have created mbtiles files of a few countries by using openmaptiles, I publish these with tileserver-gl by merging them with tippecanoe. But some areas on the map only looks gray, borders of the countries are not clear. I don't need the names of other countries and cities to be shown on the map. As long as I can see the borders, it will be enough for me. How can I do this?

<img width="1727" alt="RJ8tJgrgSoG9ejd37HJ_9A" src="https://user-images.githubusercontent.com/42588052/172122057-06f56d8a-3af4-4a5f-a6e3-d102aacb905b.png">

**Comment by bilemedimkq** [comment]
Is there anyone to help?

**Comment by TomPohys** [comment]
Hi @bilemedimkq, sorry for such a delay. The borders up to zoom 4 are taken from Natural Earth (https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.yaml#L13) and are for the whole planet. In the zoom 5 and up are used borders just included in PBF.

If you would like to have Natural Earth borders for the whole planet up to your desired zoom level you can UNION [this section](https://github.com/openmaptiles/openmaptiles/blob/dc1e21fccce7a23a7cf85a5478c3136ae0646005/layers/boundary/boundary.sql#L462:L470) to next zooms.

I hope that it helps.
