### ISSUE TITLE
Generate tile missing part of the area

### ISSUE THREAD

**Issue by guangbinl** [openmaptiles/openmaptiles#1403]
I selected a small piece of OSM data from the official website of openstreetmap (the red part in the picture) and exported it, then executed quickstart.sh, the shape of the tile after generation is like this (the green part in the picture), I checked the range value of bbox, Covers all the scopes, so I don't know what to deal with, would appreciate help
![Original-OSM](https://user-images.githubusercontent.com/18722451/173606512-7b4ebd50-d7ce-4429-b695-4e20bdd45ec1.png)
![osm-tiles](https://user-images.githubusercontent.com/18722451/173606606-d2a7ca0d-46d6-457b-8852-6d58cfac2c7e.png)
![osm-bbox](https://user-images.githubusercontent.com/18722451/173606634-d31107f1-6e68-458e-80a3-6980a535e49e.png)
p

**Comment by TomPohys** [comment]
Hi, did you try to adjust the bbox in `.env` (https://github.com/openmaptiles/openmaptiles/blob/master/.env#L19)?

This is a tiny area, did you try to export and generate a bigger one?

Did you create `make generate-bbox-file` of your export? Were the bbox numbers correct?

Thanks for more details :-)

**Comment by TomPohys** [comment]
Hi, any progress? Thanks
