### ISSUE TITLE
Aeroway Layer: missing lines

### ISSUE THREAD

**Issue by pyrog** [openmaptiles/openmaptiles#141]
Currently, only polygons are selected.
But some runways, taxiways… are linestrings.

Example: **Charles de Gaulle International Airport**

- [aerodrome (polygon)](http://www.openstreetmap.org/way/294032205) 
- [apron (polygon)](http://www.openstreetmap.org/way/319030118)
- [runway (linestring)](http://www.openstreetmap.org/way/158944815)
- [taxiway (linestring)](http://www.openstreetmap.org/way/231837522)

**Comment by stirringhalo** [comment]
Great, thanks! Should be easy to handle! Not sure if we want to ST_Buffer in the DB or push the width decision to the Style. 

I vote for doing it in DB with an assumed width so the styles don't need to get more complicated.

**Comment by pyrog** [comment]
> I vote for doing it in DB

👍

**Comment by tinoue** [comment]
Also, airport name(node) should be handled as POI.
