### ISSUE TITLE
Quickstart.sh Is Getting Stuck, Not Generating MBTiles

### ISSUE THREAD

**Issue by SuhailRafi** [openmaptiles/openmaptiles#1417]
I'm trying to run quickstart.sh on docker version 20.10.17, build 100c701 & docker-compose version 1.29.2, build 5becea4c. The script gets stuck here. 

```====> : Pulling or refreshing OpenMapTiles docker images 

Refreshing docker images... Use NO_REFRESH=1 to skip.
POSTGIS_IMAGE=openmaptiles/postgis-preloaded \
	docker-compose pull --ignore-pull-failures --quiet openmaptiles-tools generate-vectortiles postgres
```

Later after aborting, this is the message I get. 

`make: *** [Makefile:585: refresh-docker-images] Error 1
`

![Screenshot from 2022-09-05 18-25-56](https://user-images.githubusercontent.com/45854938/188448920-f34b703c-f8b3-4fa1-9a6b-232fb5119620.png)

It was supposed to execute the script and generate MBTiles.

**Comment by TomPohys** [comment]
Hi @SuhailRafi, there is `--quiet` statement, which hides all statements, but if you download the images from docker hub the `postgis-preloaded` has 2.1GB, openmaptiles-tools has 400MB, postgres has 240MB...

So, could you please check also your Network traffic in System Monitor?

**Comment by TomPohys** [comment]
I could not replicate this behavior with `quickstart.sh`. If there is still a problem, please provide more information and reopen this issue. 

Thanks
