### ISSUE TITLE
quickstart.sh and make are failing running generate-tm2source

### ISSUE THREAD

**Issue by jhony1104** [openmaptiles/openmaptiles#1419]
`./quickstart.sh` and `make` are failing with the following error:

```
====> : Code generating from the layer definitions ( ./build/mapping.yaml; ./build/sql/* )
      : The tool source code: https://github.com/openmaptiles/openmaptiles-tools 
      : But we generate the tm2source, Imposm mappings and SQL functions from the layer definitions! 
docker-compose run --rm --user=1000:1000 openmaptiles-tools bash -c \
        'generate-tm2source openmaptiles.yaml > build/openmaptiles.tm2source/data.yml'
Usage:
  generate-tm2source <tileset>
                     [--pghost=<host>] [--pgport=<port>] [--dbname=<db>]
                     [--user=<user>] [--password=<password>]
                     [--host=<host>] [--port=<port>] [--database=<db>]
  generate-tm2source --help
  generate-tm2source --version
make: *** [Makefile:262: build/openmaptiles.tm2source/data.yml] Fehler 1
```

Docker Version 20.10.17
Docker Compose version v2.6.0

**Comment by TomPohys** [comment]
Hi, what version of the OMT do you use (master? or 3.13.1?)? Do you make any changes in the `layers` folder? The error could be written in the file `data.yml`.

**Comment by jhony1104** [comment]
I didn't make any changes (to any file).

And both master and 3.13.1 area affected.

**Comment by TomPohys** [comment]
Sometimes is the error message in `./build/openmaptiles.tm2source/data.yaml`. 

Could you please run `make clean` and then `make init-dirs`? if it is OK, then `make build-sql`?

Also, what operating system do you use?

**Comment by TomPohys** [comment]
Ohh.. this is maybe also related to the https://github.com/openmaptiles/openmaptiles/issues/1422. Do you install the Docker compose as a plugin or as a standalone? Please try the `docker-compose --version` command.

**Comment by jhony1104** [comment]
I am runnig docker compose as plugin, but i have a 'alias', which also alows it to run like the standalone.

It does not seem connected since containers are started and commands are run inside of them.

**Comment by jhony1104** [comment]
After some more inverstigation it seems the following comment war right.

> Ohh.. this is maybe also related to the #1422. Do you install the Docker compose as a plugin or as a standalone? Please try the `docker-compose --version` command.

my alias used `docker compose $@` instead of `docker compose "$@"`
