### ISSUE TITLE
Tools to remove an old layer/Insert a new one

### ISSUE THREAD

**Issue by stirringhalo** [openmaptiles/openmaptiles#142]
In order to avoid complete re-tiling jobs, I'd like to see tools to remove an old layer from the DB and associated MBTiles and then insert a new layer.

Do you think this will be useful?

- Identify tables/functions/views to remove, remove them. This may need to be explicitly listed in the $layer.yaml
- Insert just that layer with import-osm
- Do the associated SQL work with import-sql
- Remove the layer from the MBTiles
- Insert the layer into the MBTiles

**Comment by ImreSamu** [comment]
>Do you think this will be useful?

yes,  

imho: 
* this is solves lot of future problems 
* we have more flexibility in creating layers 

question:  the final  MBTiles size will be equal ?

**Comment by stirringhalo** [comment]
> question: the final MBTiles size will be equal ?

Should be, I don't see why not.

> this is solves lot of future problems
> we have more flexibility in creating layers

I agree, otherwise it gets very painful to do mapping updates as that can be a significant time impact.

Further thoughts:

- Do almost all in a Makefile. Something like `make delete $layer` and `make insert $layer`
- SQL to delete is in a separate file (delete.sql). That way it is trivial to cleanup using a psql based container
- Insert simply runs a stripped down openmaptiles.yaml with just $layer. Then that is imported through normal steps.

- Deleting/Inserting from MBTiles may be a bottleneck
- 

-

**Comment by ImreSamu** [comment]
After the community feedback, probably we can create an **OpenMapTiles RoadMap for 2017**
but this proposal is very good candidate for **a long time future proof architecture.**

As I know,  the current alternative: 
* Reloading every layers - in every ~3 month ...    
   *  `import-water`
   *  `import-natural-earth`
   *  `import-lakelines`
   *  `import-osmborder`
   *  `import-osm`

>Deleting/Inserting from MBTiles may be a bottleneck

This is a new technology ( at least for me );  so it will be a critical factors.
And we have to start to create a minimal  prototype for demonstration and testing ...
As I know, no similar utilities yet https://github.com/mapbox/awesome-vector-tiles#cli-utilities

After we have a prototype ,and some experience  -  we can start re-design the architecture ...  
  *  But I would like more time to design  ... and compare the alternatives ...   ( if possible )
