### ISSUE TITLE
The "make" command returns "docker-compose" not found even when it is installed

### ISSUE THREAD

**Issue by douglasdcm** [openmaptiles/openmaptiles#1422]
Hi, how are you? It is the first time I'm using the tool. I'm facing a problem while running the "make" command. It seems the docker-compose is not found. However, I installed it and the current version is  v.2.10.2. Notice the command has been changed in docker documentation from "docker-compose" to "docker compose" (without dash). I'd say it is breaking the "make" process. Check the log bellow where I print the "make" and the "docker compose" results. The ./quickstart.sh is suffering of the same problem.

```[root@localhost openmaptiles]# make
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
/bin/bash: .env: No such file or directory
make: Warning: File `Makefile' has modification time 22940680 s in the future
docker-compose run --rm --user=0:0 openmaptiles-tools bash -c \
	'generate-tm2source openmaptiles.yaml > build/openmaptiles.tm2source/data.yml'
/bin/bash: docker-compose: command not found
make: *** [build/openmaptiles.tm2source/data.yml] Error 127
[root@localhost openmaptiles]# docker compose version
Docker Compose version v2.10.2
[root@localhost openmaptiles]# 
```

https://docs.docker.com/compose/install/linux/

**Comment by StephenAtty** [comment]
I think that the docker docs have changed and now compose is installed as a plugin rather than stand alone.

https://docs.docker.com/compose/install/other/#install-compose-standalone

But make is still using the "dash compose syntax"

On my linux box

 docker-compose  -v
docker-compose version 1.29.2, build 5becea4c

docker compose version
Docker Compose version v2.10.2

**Comment by TomPohys** [comment]
Hi, thanks for pointing this out. PR for adjusting documentation is very welcome! Thanks

**Comment by sukamare** [comment]
For those who are using the docker compose plugin this link might help:

https://stackoverflow.com/questions/72099653/how-to-alias-docker-compose-to-docker-compose/72187587#72187587
