### ISSUE TITLE
Suggest: Increate shm_size for postgres in docker-compose

### ISSUE THREAD

**Issue by develth** [openmaptiles/openmaptiles#1426]
Hello,

got an issue through quickstart, when it came to a "No space left on device" message during `make generate-tiles-pg`
I wondered, because there where 400GB Disk-Space, 120GB of memory and a lot of inodes available. 

I debugged, and recognized, that default shm_size for postgres was set to 64M. 
after adding `shm_size: 1g` in docker-compose.yml beneath the following line, it worked!

```
  postgres:
    image: "${POSTGIS_IMAGE:-openmaptiles/postgis}:${TOOLS_VERSION}"
```

Maybe it would be a quick win to others, that get this problem through their first steps with this awesome project.

**Comment by develth** [comment]
Thought about a PR, but didn´t know if this is a problem because no one here reported about. 
If i could provide an example in the compose, what could be a proper size for the shm_size?
I currently worked with a single Country (DE).

**Comment by TomPohys** [comment]
Yes, It could be just a comment in `docker-compose.yml`. Thank you.

**Comment by develth** [comment]
fixed by #1432

**Comment by tisis2** [comment]
somehow it does not help when i add that line to my docker-compose... is there more needed than adding that line and restart make generate-tiles-pg?

**Comment by develth** [comment]
> somehow it does not help when i add that line to my docker-compose... is there more needed than adding that line and restart make generate-tiles-pg?

Sorry for no reply on this.. Hope you solved it.
IMHO you need to do an rebuild, like 

    docker-compose up --build
