### ISSUE TITLE
Aeroway Layer: missing fields

### ISSUE THREAD

**Issue by pyrog** [openmaptiles/openmaptiles#143]
Fields `name` and `name_en` (at least) are missing.

Also, for aerodromes:
`icao` and `iata` fields are useful for pilots, passengers… 😉
See also  useful fields [aerodrome:type](https://taginfo.openstreetmap.org/keys/aerodrome:type#values) (and [aerodrome](https://taginfo.openstreetmap.org/keys/aerodrome#values)) i.e. to display the appropriate symbols.

Example: **Charles de Gaulle International Airport**

- [aerodrome (polygon)](http://www.openstreetmap.org/way/294032205) 
- [apron (polygon)](http://www.openstreetmap.org/way/319030118)
- [runway (linestring)](http://www.openstreetmap.org/way/158944815)
- [taxiway (linestring)](http://www.openstreetmap.org/way/231837522)

**Comment by stirringhalo** [comment]
Sounds good, is there a minimum list to expect? Not a pilot, and I don't want to bloat the MBTiles

**Comment by pyrog** [comment]
`icao` seem mandatory (but small glider or private airfields don't have it).
`name`  are mandatory too.

Passenger don't care about military, private of gliders airfields, so try to keep `aerodrome:type` if possible 😄 

I saw somewhere that it's possibly to build "specialized" vector tiles in other projects 😉

**Comment by klokan** [comment]
I would like to propose @pyrog implements a layer aeroway - with tileset defined in aeroway.yaml - similar to our sample hiking.yaml tileset mentioned in #151 (the process of how to create "specialized" vector tiles should be documented under this ticket).

If this is implemented in a fork of openmaptiles, it runs well and pass tests, we would love to review a Pull Request and possibly include this in the official OpenMapTiles schema - or recommend the fork to people who need to make the maps for pilots.
