### ISSUE TITLE
Clarification on licensing

### ISSUE THREAD

**Issue by mtangoo** [openmaptiles/openmaptiles#1430]
We are considering hosting our own map server and during searching we found this. It was such an interesting thing until I wanted to download and test it before I could present it a viable project. Then I hit the pricing thing and free plan is for non commercial. I believe I have misunderstood something. Tried to read more and I still couldn't figure thing out. It may not be clear or I may just be dumb, whatever way it is, I would like to hear the project's owners/contirbutors as to what is it: Free for commercial or not? If free under which terms?

Sorry if something is already asked and answered, I could not find it. May be I used wrong key-word.

Thanks for your time and fo such an interesting project!
- Stefano

**Comment by TomPohys** [comment]
For commercial usage is free only option 1. MapTiler Data for commercial usage is paid service (one-time purchase or subscription).

**Comment by mtangoo** [comment]
Thank you for your time and great answers. Very helpful!
