### ISSUE TITLE
Aeroway Layer: objects are visible only from zoom level 12

### ISSUE THREAD

**Issue by pyrog** [openmaptiles/openmaptiles#144]
Large airports (international, military air base…) could be visible at lower zoom levels.

On OpenStreetMap, [airport labels are visible at zoom 10](http://www.openstreetmap.org/#map=10/49.0005/2.5626).

**Comment by jirik** [comment]
Runways and taxiways are now visible at zoom level 11. See https://github.com/openmaptiles/openmaptiles/pull/192
