### ISSUE TITLE
BBOX problem for FRANCE islands

### ISSUE THREAD

**Issue by 2803media** [openmaptiles/openmaptiles#1448]
Hi all I use only the FRANCE data to build my map and France have some islands outside the bbox provided by geofabrik (Martinique, La Réunion...), so how can I change the BBOX to allow the display of those islands?

![Screenshot 2022-12-11 at 11 11 35](https://user-images.githubusercontent.com/642545/206897768-eb386c41-1279-4dab-b746-bc0dc60ef045.jpg)

Thanks for your help

**Comment by 2803media** [comment]
As you see here http://download.geofabrik.de/europe/france.html martinique, réunion, ... are part of the pbf but not in the bbox any idea to make this works?

Thanks

**Comment by TomPohys** [comment]
Hi, you can use https://boundingbox.klokantech.com/ - set format CSV and then update the `.env` file.

https://github.com/openmaptiles/openmaptiles/blob/168e8300c0e973d12272a3b9501cac34acf36ba1/.env#L19

If in `.evn` is default `BBOX=-180.0,-85.0511,180.0,85.0511` then it will look if there is a file e.g. `france.osm.pbf` and correspondent `france.bbox`. If yes, then the BBOX is taken from this file. If you change the BBOX in `.env` then it is used BBOX from `.env`

**Comment by 2803media** [comment]
And after that I must recreate the mbtitles with the command `./quickstart.sh france` is that right?

**Comment by TomPohys** [comment]
`make import-osm` and `make import-sql` are independent on BBOX (they depend on `openmaptiles.yaml`). So `make generate-tiles-pg` is enough to get the desired area.
