### ISSUE TITLE
Water(way) layer: basin are missing

### ISSUE THREAD

**Issue by pyrog** [openmaptiles/openmaptiles#145]
OSM tag [landuse=basin](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dbasin) is used for area containing water.
This tag is also used for lock chambers on canals. See drawing in [Key:lock](https://wiki.openstreetmap.org/wiki/Key:lock)

**Basins** are point objects in openmaptiles (poi layer). The issue is that 99% of them are polygons, so they are not displayed.

http://overpass-turbo.eu/s/lmp

**Comment by pyrog** [comment]
Example:
- [way 314123668](https://www.openstreetmap.org/way/314123668) seen on [Maputnik](https://maputnik.github.io/editor/#19.04/49.9897264/3.6507159)

**Comment by ZeLonewolf** [comment]
This appears to be already implemented:

https://github.com/openmaptiles/openmaptiles/blob/45d825e2121608cf1760cb9309741138d7aad61a/layers/water/mapping.yaml#L86-L90

Is this issue still a problem?

**Comment by TomPohys** [comment]
Yes, added in #876.
