### ISSUE TITLE
 can we create rastertiles from this project

### ISSUE THREAD

**Issue by toqeer786** [openmaptiles/openmaptiles#1455]
Hello ,i  have a question can we create rastertiles from this project i had created mbtiles files and also extract in tiles folder format  but it still give me an  fatal error reading pnf file :not a png file  
: 
![image](https://user-images.githubusercontent.com/115454250/208025426-ed38c984-831d-4918-8a7a-61dc8375c761.png)
is there any way to create raster images from this project or doing any changes in config.json files that can return us  raster formats   ,kindly help

**Comment by TomPohys** [comment]
Hi, OpenMapTiles is focused on vector tiles, and directly it is not possible to rasterize. The rasterization provide e.g. [Tileserver GL](https://github.com/maptiler/tileserver-gl)
