### ISSUE TITLE
Lack of details in the rendered Map - tileserver-gl vs openmaptiles-tools postserve

### ISSUE THREAD

**Issue by Javaxiss** [openmaptiles/openmaptiles#1461]
Hi,

I'm using Docker and I followed [the steps described ](https://github.com/openmaptiles/openmaptiles) to generate a tiles file (tiles.mbtiles) :

- make import-data
- make download area=italy (I tried as well to download manually italy.osm.pbf from GeoFabrik and put it into /data folder)
- make import-osm area=italy
- make import-wikidata area=italy (this step logged that about 40 Wikidata IDs were not found)
- make generate-bbox-file area=italy
- make import-sql area=italy
- make generate-tiles-pg area=italy

As I did not customize .env, mapping.yaml ... generated files and paths keep their default values.
The last command generates the tiles file and put it into /data folder (tiles.mbtiles), its size (~3000 KB) is "lighter" that it is supposed to be I think (I compared that to a generated hambourg.tiles shared by someone here). However, after running the tileserver-gl container, the map is just rendering minimal aspects: I mean street names do not render, airports are not drawed, building as well ... as  showed in the followings:

![image](https://user-images.githubusercontent.com/3315024/209139578-62163a24-323d-41ed-87a3-f45585a69343.png)
And
![map](https://user-images.githubusercontent.com/3315024/209139648-309b1495-2696-4355-98ee-8d6f7ac6f962.png)

Am I missing a step or a configuration before generating the tiles file ?

I'm confused, and do not really understand the difference between serving a tiles.mbtiles file by tileserver-gl and running openmaptiles/openmaptiles-tools postserve. What is the difference between them and when to use one and not the other ?

**Comment by Javaxiss** [comment]
> By default, .env only renders down to zoom 7. Change this to zoom 14 and you should see all the detail (but it will take longer to render).

Thanks ! It is in progress :hourglass: 

I would underline that all details are rendered when I run: `make start-postserve` the generated json at http://localhost:8090 contains all the detail.
Otherwise, do you know **the diffrence** between serving an **mbtiles by tileserver-gl**  and serving  tiles by **openmaptiles/openmaptiles-tools postserve (docker-compose up -d postserve)** ?. Other question :sweat_smile:  : **a tileset yaml file should be provided to postserve** (so it is possible to define new layers or simply specify only the ones we want to keep). It that possible when using tileserver-gl ?

**Comment by TomPohys** [comment]
The main difference between tileserver-gl and postserve is, that postserver serves tiles directly from PostgreSQL based on `openmaptiles.yaml` where in the `layer.yaml` is defined `datasource: query`. This query depends on function e.g `layer_boundary()` which is created during `import-sql` step. The Tileserver-gl serving tiles from generated `tiles.mbtiles`.

For tileserver-gl you can specify in `openmaptiles.yaml` which layers you would like to include (also for postserve; also your own - https://github.com/maptiler/foss4g-workshop) and then generate the tiles. Or maybe you can modify the metadata table in mbtiles and remove some layers from `json`.

**Comment by TomPohys** [comment]
@Javaxiss, is there anything else we can help with?
