### ISSUE TITLE
Font not allowed 

### ISSUE THREAD

**Issue by Javaxiss** [openmaptiles/openmaptiles#1463]
Hello,

I'm trying to change the default font of the tileserver-gl. SO, I generated fonts as described at (https://github.com/openmaptiles/fonts), put them into fonts directory as declared in the config.json and then in style.json I changed the text-font properties to point to Roboto. However, the server is logging : GET /fonts/Roboto%20Bold/0-255.pbf 400
In the browser http://localhost:8080/fonts/Roboto%20Bold/0-255.pbf 400 is showing the following message: 
`Font not allowed: Roboto Regular`. Same thing for the other generated fonts...

An idea about that ?

**Comment by memarv** [comment]
Set `"serveAllFonts": true` in tileserver-gl config
https://tileserver.readthedocs.io/en/latest/config.html

**Comment by TomPohys** [comment]
@Javaxiss is did solved?

**Comment by SsZzzz** [comment]
> Set `"serveAllFonts": true` in tileserver-gl config https://tileserver.readthedocs.io/en/latest/config.html

it works

**Comment by TomPohys** [comment]
Thanks!
