### ISSUE TITLE
Missing place=borough from OSM

### ISSUE THREAD

**Issue by jameswestman** [openmaptiles/openmaptiles#1469]
Places tagged [`place=borough`](https://wiki.openstreetmap.org/wiki/Tag:place%3Dborough) don't appear to show up in OpenMapTiles at all. This affects, for example, Berlin: https://openmaptiles.org/inspect/#11.63/52.5140/13.3794. As I understand it, boroughs are about the same importance as [`place=suburb`](https://wiki.openstreetmap.org/wiki/Tag:place%3Dsuburb) or possibly more important; I'm not entirely clear what the difference is, but I think it's mostly administrative.

**Comment by ZeLonewolf** [comment]
I believe this can be accomplished with a simple addition in two places

Adding `borough` to the mapping here:
https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/mapping.yaml#L175-L183

Adding `borough` to the enumerated list here:
https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/types.sql#L7
