### ISSUE TITLE
Buildings shape

### ISSUE THREAD

**Issue by 2803media** [openmaptiles/openmaptiles#1471]
I just compare OSM and openmaptiles for buildings shape and I notice some weird shape, do you know where those errors come from?

OSM
![Screenshot 2023-01-03 at 17 49 57](https://user-images.githubusercontent.com/642545/210403458-2221b09e-fc77-43c6-8ac6-f42d2810bd57.jpg)

Openmaptiles
![Screenshot 2023-01-03 at 17 49 49](https://user-images.githubusercontent.com/642545/210403428-52641c1a-c3d7-4509-b348-a4bde3be0c3b.jpg)

**Comment by TomPohys** [comment]
Hi, this is duplicated with https://github.com/openmaptiles/openmaptiles/issues/1356 - PostGIS < 3.2 was simplifying geometry for ST_AsMVT. In OpenMapTilers-Tools v7 is used PostgreSQL 14 with PostGIS 3.2 which is based for OpenMapTiles v3.14.

**Comment by pathmapper** [comment]
https://github.com/openmaptiles/openmaptiles/issues/1356 is was about overlaps and gaps, this is fixed.

The "weird shapes" are coming from the "snap to grid" and it becomes especially visible when overzooming the tiles - I think the only thing which might help here is generating the tiles also for higher zoom levels than 14 (zl 16 might be enough).
