### ISSUE TITLE
.mbtiles file license

### ISSUE THREAD

**Issue by maciejla** [openmaptiles/openmaptiles#1478]
Hi! I have two questions:
- If I understand everything well, I can share (for both personal and commercial use) tiles generated by me with openmaptiles toolkit and served by tileserver-gl with `© OpenMapTiles © OpenStreetMap contributors` attribution. Am I correct?
- Can I share the .mbtiles file on the same principle, with `© OpenMapTiles © OpenStreetMap contributors` attribution?

I'm not really asking about the `© OpenStreetMap contributors` part (I'm a OSM contributor myself :), more about the `© OpenMapTiles` part :)

Thank you!
Maciej

**Comment by klokan** [comment]
Yes you can do both legally. You must ensure that whenever the OpenMapTiles vector tiles or schema are used - the attribution with link is visible on the final map.

Maintenance, improvement and data hosting of this project are supported by revenue created from the pre-generated data which people who do not contribute to the code of the project can purchase.

**Comment by maciejla** [comment]
Thank you so much for your response, have a nice day! :smile:
