### ISSUE TITLE
Is OpenMapTiles still open?

### ISSUE THREAD

**Issue by timprepscius** [openmaptiles/openmaptiles#1490]
Hey there,

Is OpenMapTiles still open?  All I see on the web site is paid options, and no clear way to get the api key and download data.

I want to run this: docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/openmaptiles-server
with the least amount of time overhead of messing with the website.

Is OpenMapTiles open, or it is not?

**Comment by ZeLonewolf** [comment]
Yes, OpenMapTiles is "open" and you can build your own tileserver by checking out the repository and running the `quickstart.sh` script.

**Comment by timprepscius** [comment]
Just out of curiosity, in the case of OpenMapTiles, what does "open" mean?

**Comment by ZeLonewolf** [comment]
See: https://github.com/openmaptiles/openmaptiles/blob/master/LICENSE.md

**Comment by timprepscius** [comment]
For a browsable electronic map based on OpenMapTiles and OpenStreetMap data, the credit should appear in the corner of the map. For example:

Seems to conflict with the general affect of the website.

So for instance, if I make a commercial product X, and the product credits, attributes as specified in the license just linked..
Is that enough?

Am I misunderstanding the website?  Or am I misunderstanding the license?  Or both?

**Comment by ZeLonewolf** [comment]
I'm just a contributor, not a lawyer. However, attribution is already required for OpenStreetMap data, so adding attribution for OpenMapTiles is not really a burden.  See how we handle it in: https://zelonewolf.github.io/openstreetmap-americana

**Comment by timprepscius** [comment]
Yes, I'm really asking if attribution is the lone requirement, or whether there are others?

**Comment by klokan** [comment]
If you use the source code and/or cartographic schema developed in this GitHub organization to **generate the vector tiles yourself**, then you are limited only by the license. It is open and permissive BSD + CC-BY with requirement of the visible credit in the corner of the map.
https://github.com/openmaptiles/openmaptiles/blob/master/LICENSE.md

> attributes as specified in the license just linked.. Is that enough?
No. It must be a visible credit and link in the corner of the map. This is also required from the side of OpenStreetMap.

BTW Be sure the map styles you use (JSON with colors etc. applied on top of the vector tile schema) are openly licensed too. The styles pushed in the OpenMapTiles github repos has always LICENSE.md - these are open - see https://github.com/openmaptiles/?q=gl-style

Premium planet data and map styles at maptiler.com are available with a commercial license.
In such case, start with https://www.maptiler.com/server/ which comes with ready-to-use map styles and data packages.

**Comment by timprepscius** [comment]
Could you rename the company, "NotAsOpenStreetMaps?"
Sort of like OpenAI should be named Open_JK_AI..

I think it is clearly a case of false advertising.
Or at least start a different company.  Why sully a name like "*Open*StreetMaps"
