### ISSUE TITLE
Some boundaries missing from zoom levels 0-4

### ISSUE THREAD

**Issue by brewin** [openmaptiles/openmaptiles#1492]
Some of the borders of Kansas, Colorado, California, and possibly other states/provinces are missing from zoom levels 0-4. The borders exist in commit 1c1231e, but not in the latest commit 624cf7a.

1c1231e
![Screenshot 2023-02-13 at 3 27 49 PM](https://user-images.githubusercontent.com/1248685/218580461-8879093a-1fd8-44aa-8568-4cc4ed96415a.png)
624cf7a
![Screenshot 2023-02-13 at 3 27 15 PM](https://user-images.githubusercontent.com/1248685/218580459-b0267dea-1e37-465e-b0f7-d649a8838f77.png)

**Comment by ZeLonewolf** [comment]
Confirmed here on my live tileserver:
https://6ug7hetxl9.execute-api.us-east-2.amazonaws.com/data/planet-low-zoom/#3/35.74/-95.22

**Comment by brewin** [comment]
The Ohio/Pennsylvania border is also missing, as well as the borders of several Australian states and Canadian provinces. All the missing borders I've noticed are straight lines.

**Comment by brewin** [comment]
Appears to be correct now.
