### ISSUE TITLE
Issues about area label change

### ISSUE THREAD

**Issue by raintygao** [openmaptiles/openmaptiles#1503]
Hi all, my team uses a past version of openstreet map tiles. When we select `ZH` language, the label of Taiwan is `中華民國`, this label seems a little unsuitable for our product.
Today I see this label has been updated to `台湾` in [your page](https://www.maptiler.com/maps/#style=basic&lang=zh&mode=2d&position=2.96/31.03/104.44),  i I presume this is the latest version and your team updated the label in upgrade, right?  
I want to find out in which version the update was made to guide our openstreet map tiles upgrade, but I searched all over repo, issues, pull request, changelogs and docs and couldn't find the specific version that started to take effect.  Can you give me some help? Thank you!🙏

**Comment by TomPohys** [comment]
Hi, OpenMapTiles using languages from [OSM](https://www.openstreetmap.org/relation/449220/history), and if there is Wikidata and in OSM missing some languages than are added from [Wikidata](https://www.wikidata.org/wiki/Q865).

**Comment by raintygao** [comment]
> Hi, OpenMapTiles using languages from [OSM](https://www.openstreetmap.org/relation/449220/history), and if there is Wikidata and in OSM missing some languages than are added from [Wikidata](https://www.wikidata.org/wiki/Q865).

Thank you for responding. I can see `alt_name`, `name`,`old_name`,`official_name` in  [OSM](https://www.openstreetmap.org/relation/449220/history), do you know which one of these are applied in pbf data?

**Comment by TomPohys** [comment]
Any `name:"iso_code"` listed in https://github.com/openmaptiles/openmaptiles/blob/624cf7a8a30e5c9625da0194eafdcf88d9c104b4/openmaptiles.yaml#L29-L107
