### ISSUE TITLE
Docs: Add a new layer

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#151]
We need to add into www.openmaptiles.org/docs/ an article about how to add a new layer with custom OSM data into OpenMapTiles.

The steps are:
- fork the OpenMapTIles repo
- decide whether you want to adjust existing layers or add your specific layer
- code it (imposm3, sql, layer.yaml)
- test it on extracts
- make a Pull Request back to the main project.

Basic example is done in the "hiking" layers - with custom hiking.yaml font. We should describe it on POIs, as this is easiest.

https://github.com/klokantech/openmaptiles/tree/hiking 

Idea is that people can generate their own MBTiles with only the extra staff they need - and use in their style two MBTiles sources - one with official OpenMapTiles, and second with their domain specific features.

**Comment by stephent** [comment]
Petr - would this cover the steps required to generate tiles with additional info such as peak names/summit information (http://wiki.openstreetmap.org/wiki/Tag:natural%3Dpeak)?

**Comment by klokan** [comment]
Yes, but it is meant now primarily as an example of how to create a specialised custom vector tileset, and participate on development of the OpenMapTIles as a community project.

We may merge the hiking.yaml tileset into the official OpenMapTiles schema in future.

**Comment by stephent** [comment]
Understood - so, to confirm, if there are OSM elements that aren't currently part of the official OpenMapTiles schema, I'd need to follow these directions to create a custom tileset that included them?

**Comment by klokan** [comment]
Yes. You can generate only small tileset - with only the extras you need (possibly for whole world) - and use it with TileServerGL to serve your extras together with stable OpenMapTiles to your applications and custom GL styles.
This would be a temporary independent solution for how to immediately make your own map application with your own selection of OSM tags, which you need.
We hope people will propose an extension of the OpenMapTiles schema in a form of Pull Requests with similar improvements, and together with the community we can improve the schema and add missing things which most people needs - or at least recommend public forks with specialised extra tilesets extending the OpenMapTiles schema with a domain specific map features.

If we have a business case and a customer who require similar improvement on top of standard OpenMapTiles schema - we can develop it and ensure such private extensions are maintained and updated as part of the Production package and our update service.

**Comment by jirik** [comment]
@stephent FYI Peaks are now part of the schema: https://github.com/openmaptiles/openmaptiles/pull/180 To be rendered soon.

**Comment by klokan** [comment]
See my presentation at SOTM 2018:
https://www.maptiler.com/blog/2018/08/highlights-from-the-openstreetmap-conference.html
