### ISSUE TITLE
Any plan to publish a .tm2source project template to be used with the .tm2 styling project in MapBox Studio ?

### ISSUE THREAD

**Issue by nouryf** [openmaptiles/openmaptiles#152]
Hi,

Great stuff published in 'openmaptiles'. I used previously https://github.com/kartotherian/osm-bright.tm2source as the start data sources project for postgress stored osm tables and osm bright .tm2 styles https://github.com/kartotherian/osm-bright.tm2 as styling project. Now my understanding is 'osm-bright.tm2source' might/is not open source and hence, I believe, this new open project. Cool stuff.

Is there any plan to publish a template .tm2source like it was done in the past  https://github.com/kartotherian/osm-bright.tm2source and as it is done for tm2 style here https://github.com/openmaptiles/mapbox-studio-osm-bright.tm2/ ?

My understanding is may be one can use docker to generate the .tm2source project, but I'm not sure that the steps explained for Docker apply to Windows OS ....They seem to apply to non Windows OS. I use Windows.

Thanks
Noury

**Comment by klokan** [comment]
You can use the openmaptiles-tools to generate the .tm2source files.

See `generate-tm2source` at https://github.com/openmaptiles/openmaptiles-tools

We could probably attach the .tm2source file to each release, if it would help people.
The idea is that you use the directory structure of openmaptiles to edit the layers and SQL and mapping from OSM data - and then generate various configuration scripts for different tools. One of them is also Mapbox Studio Classic (.tm2source).

BTW Docker run on Windows very well.

**Comment by lukasmartinelli** [comment]
@nouryf Each release has a `build.zip` which contains the build artifacts.
The tm2source is contained there as well.

https://github.com/openmaptiles/openmaptiles/releases

**Comment by nouryf** [comment]
Great. Thank you very much for the prompt responses. I'll give Docker another try to Windows.
