### ISSUE TITLE
"./quickstart.sh planet" failing with Error 124

### ISSUE THREAD

**Issue by himby** [openmaptiles/openmaptiles#1524]
I'm following the quickstart tutorial (commit 6f2b39e, latest at the time of writing )

default .env file except for:
```
MIN_ZOOM=0
MAX_ZOOM=10
```

Step failing:
**make import-sql             # create / import sql functions** 

Output:
```
CREATE INDEX
Time: 181.119 ms
CREATE VIEW
Time: 33.894 ms
CREATE VIEW
Time: 18.440 ms
CREATE VIEW
Time: 46.467 ms
CREATE VIEW
Time: 50.039 ms
CREATE VIEW
Time: 13.296 ms
CREATE VIEW
Time: 3.229 ms
CREATE VIEW
Time: 3.071 ms
CREATE FUNCTION
Time: 8.374 ms
DO
Time: 0.106 ms
Time: 5196554.719 ms (01:26:36.555)
make: *** [Makefile:453: import-sql] Error 124
```

No other error or indication of what's going wrong.

I'm running this on a linux machine with 128gb RAM, 10TB SSD, AMD EPYC 7443P 24-Core Processor

Could be related to: https://github.com/openmaptiles/openmaptiles/issues/1115

**Comment by TomPohys** [comment]
Hi, could you please post a `quickstart.log`?

**Comment by EarlThorfinn** [comment]
Hi, I'm getting the same errors using a freshly cloned copy of the openmaptiles repo with default env file, running the quickstart for the ireland-and-northern-ireland area (257MB .osm.pbf) with `./quickstart.sh ireland-and-northern-ireland`

Log file: [quickstart.log](https://github.com/openmaptiles/openmaptiles/files/11190498/quickstart.log)

I have the same error message reported by @himby in the log after `psql:/sql/parallel/transportation__transportation_name.sql:396: ERROR:  null value in column "ref" of relation "transportation_route_member_coalesced" violates not-null constraint`

I've successfully run the quickstart for the scotland and wales areas with MAX_ZOOM=14, but haven't been able to complete the quickstart for the england and ireland-and-northern-ireland areas, even with the lower MAX_ZOOM=7 setting.

Can anyone please advise if they know if this is a general issue with OpenMapFiles? Thanks

**Comment by ZeLonewolf** [comment]
It does sound like a bug, I'm going to run that here to confirm. I"m surprised there's a still a constraint violation after #1501 was merged but there might be an issue I missed.

**Comment by himby** [comment]
I can confirm that it works with «norway». Tested with 0 to 10. Maybe the tests should use a dataset with Ireland or Great Britain, which seems to have some special handling when it comes these routes.

**Comment by digital195** [comment]
generating dach region works fine, also getting the error when generating europe. 

`[Makefile:453: import-sql] Error 124`

getting the exect same error as https://github.com/openmaptiles/openmaptiles/issues/1524#issuecomment-1496464640

**Comment by digital195** [comment]
https://github.com/openmaptiles/openmaptiles/issues/1524#issuecomment-1501973286


testet with great britain, same error.
[quickstart-great-britain.log](https://github.com/openmaptiles/openmaptiles/files/11214168/quickstart.log)


testet with ireland also same error.
[quickstart-ireland.log](https://github.com/openmaptiles/openmaptiles/files/11214191/quickstart.log)


hope these informations / logs will help :)

**Comment by Peetzer** [comment]
With clean checkout master, tested with 'netherlands'

MIN_ZOOM=0
MAX_ZOOM=14

running quickstart,

make: *** [Makefile:453: import-sql] Error 124

running make import-sql

psql:/sql/parallel/water__waterway.sql:992: ERROR:  column "source_ids" of relation "osm_important_waterway_linestring" does not exist
LINE 1: ...INTO osm_important_waterway_linestring (geometry, source_ids...

**Comment by benedikt-brandtner-bikemap** [comment]
Hey, sorry for taking so long to post here have this was introduced by me and should be addressed and fixed by #1537

**Comment by benedikt-brandtner-bikemap** [comment]
> It does sound like a bug, I'm going to run that here to confirm. I'm surprised there's a still a constraint violation after #1501 was merged but there might be an issue I missed.

Yeah I have introduced this error when refactoring the materialized view to a table in [8321574](https://github.com/openmaptiles/openmaptiles/commit/83215745659291496c1f0fbdf56a95a1665cd1ac) and did not consider this constraint and only encountered the error when importing planet wide data slightly_frowning_face

**Comment by ZeLonewolf** [comment]
Awesome!  Thanks for getting to the bottom of this.

**Comment by himby** [comment]
I have now tested with https://github.com/openmaptiles/openmaptiles/commit/91dd853a89492e81987a717e3fcfe1b50836fc94 using "planet". I then end up with a 33mb file containing Alaska only. I tried with europe, and that seems fine (2,2GB at 0-11).

**Comment by TomPohys** [comment]
Thanks @benedikt-brandtner-bikemap for the fix!
