### ISSUE TITLE
quickstart.sh does not generate complete mbtiles

### ISSUE THREAD

**Issue by frnck** [openmaptiles/openmaptiles#1528]
When using quickstart.sh it does n longer generate a valid mbtiles. The mbtiles file is very small (incomplete). This has been tested with multiple areas. This is true for at least main and v3.14.

**Comment by TomPohys** [comment]
Hi, was it helpful?

**Comment by KRKnet** [comment]
The current master branch seems to have the same problem with a completely virgin setup. `/data/tiles.mbtiles` is not generated with `quickstart.sh` while there are no obvious errors reported in the output. The .env file is also unchanged from the current master.

**Comment by TomPohys** [comment]
Hi @KRKnet, thanks for posting `quickstart.log`. Based on the log, there is successfully generated `albania.mbtiles` with size 466944 and 16 generated tiles. Your mentioned test is testing zoom 14,which is not in quickstart as default. But it tested, if the `getmvt` function is working correctly.

**Comment by KRKnet** [comment]
Hi @TomPohys, thanks for your help. tileserver-gl is expecting tiles.mbtiles to be there. When I copy over my albania.mbtiles file he is not failing anymore but not able to show me anything in the viewer.
Am I missing something? Are more steps required?

**Comment by TomPohys** [comment]
It is possible, that there are no data for zooms e.g. 0 - 3, but if you zoom more over Albania, you should see something.

**Comment by TomPohys** [comment]
Please, if you have further questions, feel free to reopen the issue or create a new issue.
