### ISSUE TITLE
Make import-osm leaner

### ISSUE THREAD

**Issue by lukasmartinelli** [openmaptiles/openmaptiles#153]
Looking again at `import-osm` https://github.com/openmaptiles/import-osm
I think we should move the utils introduced by https://github.com/openmaptiles/import-osm/pull/1 (geofabrik and pgclimb) into separate containers.

They don't really fit into import-osm which should only be the imposm3 container.

What do you think @ImreSamu?

**Comment by ImreSamu** [comment]
Refactoring always welcome :)

my retrospective: 

(past time) sometimes it is WAS very useful  the `make import-osm-dev`  and run everything from this container :   imposm3 import, imposm3 diff, ...  psql.sh , ...   

My ideas: 
* for my personal debugging purpose, I NEED the [./psql.sh](https://github.com/openmaptiles/import-osm/blob/master/psql.sh)  in the 
   *  `import-osm` , 
   *  `import-sql`  ( sometimes  )
* I WOULD LIKE  the  2 small (  `alpine:3.5` ) based images : 
   *  `openmaptiles/download-geofabrik` 
      *   ( referenced in the `docker-compose.yml` , because needs for testing )
   *  `openmaptiles/pgclimb`   
       *   ( this is referenced only the Makefile )
* And I WOULD LIKE  a same libgeos version everywhere ! ( now:  `3.4.2` vs. `3.6.0` ) ( latest: [3.6.1](https://github.com/libgeos/libgeos/releases) )
```bash
docker-compose run --rm import-osm geos-config --version
3.4.2
docker-compose run --rm postgres geos-config --version
3.6.0
```

From the above: 
*  the  `./psql.sh` in the `import-osm`   is  a MUST for me   :)  

And maybe ( in the future )
*  we can use the `openmaptiles/postgis:2.3`  as a base image for the `import-osm` image !  
    *  with the [imposm3 static releases](https://imposm.org/static/rel/)


Side note:    Probably we should wait the  [PostGIS 2.3.2](http://osgeo-org.1560.x6.nabble.com/PSC-Vote-PostGIS-2-2-5-and-PostGIS-2-3-2-release-in-next-2-3-weeks-but-before-next-PostgreSQL-micro--td5302405.html)  bugfix release

**Comment by ImreSamu** [comment]
as I see
*  imposm3 pre-build using the `GEOS_VERSION=3.5.1`
*  the `osmosis` the biggest in size ( JVM! )  - probably not need  ...
*  I am using the `osmctools`  for query the osm.pbf data ... 
   *  moving to `openmaptiles/download-geofabrik` ?

**Comment by TomPohys** [comment]
Thanks @nyurik, `import-osm` is now part of [`openmaptiles-tools`](https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/import-osm).
