### ISSUE TITLE
Quickstart vs manual: .mbtiles file has different size

### ISSUE THREAD

**Issue by koufopoulosf** [openmaptiles/openmaptiles#1533]
Hello,

Has anyone experienced different size in .mbtiles file when executing the ```./quickstart.sh <area>``` versus the manual commands:
```
make start-db
make import-data
make import-osm 
make import-wikidata
make generate-bbox-file
make import-sql
make generate-tiles-pg
```

?

In the first case, the generated .mbtiles file is ~100mb smaller in size than the manual way.

I don't know why this happens, however which method you would suggest as a more robust/secure way to follow?

Thanks in advance for your valuable time!

**Comment by TomPohys** [comment]
Hi, 
could you please try `./quickstart.sh --empty <area>` ? Then the quickstart will use the empty database instead of [`preloaded`](https://github.com/openmaptiles/openmaptiles-tools/tree/master/docker/postgis-preloaded) one.

**Comment by koufopoulosf** [comment]
I guess that would work, thanks!
