### ISSUE TITLE
Max Connections / Production Tutorial

### ISSUE THREAD

**Issue by koufopoulosf** [openmaptiles/openmaptiles#1534]
Hello,

Has anyone implemented this solution for a production system with potentially, thousands of concurrent users?

On a docker image I noticed a value "max_connections = 100" and I was wondering, how we can deploy these vector tiles to potentially many more users. Is there any specific configuration that should be done when generating those .mbtiles other than the hardware requirements of the linux servers?

I would really appreciate any suggestions on that matter.

Best Regards.

**Comment by pnorman** [comment]
I believe the max connections you are referring to is the number of PostgreSQL connections, not the number of users.

Max connections should not generally exceed 2-3 times the number of hardware threads the server has.

**Comment by koufopoulosf** [comment]
Thanks for your valuable reply. My bad, I actually meant the number of users. I mean, how do I estimate how many concurrent users a given configuration and some hardware resources of the server(s) can handle?

Thanks for your feedback!

**Comment by pnorman** [comment]
If you're prerendering tiles to a mbtiles file PostgreSQL doesn't matter.

**Comment by koufopoulosf** [comment]
@pnorman Well I recently came across to this one: https://github.com/maplibre/martin

Have you used it? It accepts PostGIS, PMTile and MBTile files. Which option do you think would scale more effectively? I lean towards to MBTiles to avoid the PostgreSQL/PostGIS overhead, but I'd like your opinion as well on that matter.

Regarding the scalability, I meant if there was any specific configuration we should follow upon creating the MBTiles file.

Thanks again for your time!

**Comment by StephenAtty** [comment]
mbtiles and a tileserver (we use tileserver.php) - just scales with the webserver

**Comment by koufopoulosf** [comment]
Awesome, thank you!

**Comment by StephenAtty** [comment]
We regenerate our maptiles for the UK once a month (takes just under 2 hours) and then serve that 1.7GB mbtiles file through tileserver.php using php-fpm, opcache and apache2 running the event mpm.

**Comment by koufopoulosf** [comment]
Have you tried tileserver-gl? You can give it a try :)

**Comment by StephenAtty** [comment]
Why use Node when  tileserver.php is doing what we need - we have PHP installed for other parts of the site.

**Comment by koufopoulosf** [comment]
Oh then great. My use case does not require php so tileserver-gl works fine for the basemap.

**Comment by TomPohys** [comment]
Hi @koufopoulosf, can this issue be closed? Thanks.

**Comment by koufopoulosf** [comment]
@TomPohys Sure, thanks for the reminder.
