### ISSUE TITLE
River Humber Problem

### ISSUE THREAD

**Issue by jdeboer-geoplan** [openmaptiles/openmaptiles#154]
Hi, Amazing project guys!
The river humber looks wrong between z9 and z11, it's fine above and below that. 
See it at lat 53.7 long -0.44
The reason is because at z8 it's ocean and at z12 rivers become polygons and are back to the right width.  Would it be right for rivers of a certain width to be polygons at z9-11? 
The old osm2vectortiles project didn't have this issue?
![humberzoom8](https://cloud.githubusercontent.com/assets/23341752/22285918/6c3039ba-e2e5-11e6-8179-299497fd135a.png)
![humberzoom9](https://cloud.githubusercontent.com/assets/23341752/22285920/6c35a86e-e2e5-11e6-89e8-afe1bc073dfc.png)
![humberzoom11](https://cloud.githubusercontent.com/assets/23341752/22285919/6c35963a-e2e5-11e6-801a-744f92f8f7a0.png)
![humberzoom12](https://cloud.githubusercontent.com/assets/23341752/22285921/6c3672b2-e2e5-11e6-82e6-abf73f52f34c.png)

**Comment by lukasmartinelli** [comment]
Thanks. It's because waterway polygons where hidden accidentally. Fixed in #120.

**Comment by jdeboer-geoplan** [comment]
Superb!
Thanks, really impressed with this project.
