### ISSUE TITLE
Vector working, Rasters not working!

### ISSUE THREAD

**Issue by chebourne** [openmaptiles/openmaptiles#1543]
Any idea why Rasters on my own styles might have suddenly stopped working?

Vector on own styles works.

Default styles supplied e.g. OSM Bright all work with vector or raster.

**Comment by TomPohys** [comment]
Hi, probably the wrong repository. Openmaptiles/openmaptiles repository defines vector schema. This repo does not deal with serving the tiles or any other style than `OSM OpenMapTiles style`.
