### ISSUE TITLE
Sprite conversion fails for some SVG icons

### ISSUE THREAD

**Issue by HandyMenny** [openmaptiles/openmaptiles#1549]
After running `make build-sprite`, the resulting sprite.png contains black squares for some icons:

![sprite](https://github.com/openmaptiles/openmaptiles/assets/3463028/a63c983e-3490-40ee-8713-7f711adfcee3)

I think the problem are these 11 icons embedding a png as base64:
```
beach.svg
beach_coarse.svg
rock_overlay.svg
scree_overlay.svg
scrub.svg
wetland.svg
wetland_bog.svg
wetland_mangrove.svg
wetland_marsh.svg
wetland_reed.svg
wetland_swamp.svg
```

**Comment by istvanszoboszlai** [comment]
I am in the process of creating a PR to solve this. I do not have a better idea than to try and convert the png based svg resources to real vector svg with inkscape.
(Actually it was the idea of Brian ZeLonewolf)

**Comment by ZeLonewolf** [comment]
In Inkscape, you can save them as "Optimized SVG" and they'll be smaller in the repo.

**Comment by istvanszoboszlai** [comment]
Okay, I saved them all as optimized SVGs. It did reduce size, but only by like 25% or less.

**Comment by ZeLonewolf** [comment]
That's okay, they will get rasterized anyways when they get converted into a sprite sheet.

**Comment by HandyMenny** [comment]
This is another good tool for svg optimization: https://jakearchibald.github.io/svgomg/
