### ISSUE TITLE
Slack link referenced in readme does not exist

### ISSUE THREAD

**Issue by duaneking** [openmaptiles/openmaptiles#1559]
Just as an FYI, your readme links to a dead Slack instance and that makes this look unsupported or unmaintained.

Is this active?

**Comment by ZeLonewolf** [comment]
The Slack is active. https://slack.openstreetmap.us

Channel #openmaptiles

**Comment by duaneking** [comment]
Yeah the official readme is linking to a herokuapp link.

**Comment by ZeLonewolf** [comment]
It was fixed in #1494.

**Comment by TomPohys** [comment]
Thanks for pointing this out. I fixed it in `readme.md`.
