### ISSUE TITLE
Building using Windows Docker Toolbox

### ISSUE THREAD

**Issue by nouryf** [openmaptiles/openmaptiles#156]
Hi,

I'm using Windows Docker Toolbox and now trying to follow the steps outlined at section 'Develop' (https://github.com/openmaptiles/openmaptiles).
- Docker version 1.12.6, build 78d1802
- docker-compose version 1.9.0, build 2585387
- I have installed 'openmaptiles-tools' 
(Requirement already satisfied: openmaptiles-tools in c:\python27\lib\site-packages
Requirement already satisfied: docopt in c:\python27\lib\site-packages (from openmaptiles-tools)
Requirement already satisfied: pyyaml in c:\python27\lib\site-packages (from openmaptiles-tools)
Requirement already satisfied: graphviz in c:\python27\lib\site-packages (from openmaptiles-tools))

Now I'm at step 'Build'. I tried to use the docker to build 'openmaptiles-tools':
On the docker terminal command line:
$ docker run -v $(pwd):/tileset openmaptiles/openmaptiles-tools make
make: *** No targets specified and no makefile found.  Stop.

The command execution failed with the error above ("make: *** No targets specified and no makefile found.  Stop.").

I must be missing some thing ? Any one used Windows Docker toolbox to build and eventually follow the step to produce a sample .mbtiles ?

Any help is appreciated.

Thanks
Noury

**Comment by lukasmartinelli** [comment]
I think `$(pwd)` does not work on Windows without a bash shell.
With `docker run -v C:\\your-openmaptiles-dir:/tileset openmaptiles/openmaptiles-tools` make it should work.

**Comment by nouryf** [comment]
Thank you. I copied 'openmaptiles' folder to root folder of f:. Then I typed:
docker run -v f:\\openmaptiles:/tileset openmaptiles/openmaptiles-tools make

--> C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: invalid bind mount spec "f://openmaptiles:/tileset": invalid mode: /tileset.

It looks like it's not finding the folder..or some thing else is missing

**Comment by lukasmartinelli** [comment]
Seems a Docker issue https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/6
You need to enable shared drives and use a different notation for the folders from a quick glance.

I see - this is really hard on non UNIX systems...

**Comment by ImreSamu** [comment]
( Sorry for the noise )  
The troubleshooting is also interesting: 
https://docs.docker.com/docker-for-windows/troubleshoot/#troubleshooting

**Comment by nouryf** [comment]
I'm using docker toolbox that seems to be different from docker for windows. Last one requires Windows 10 Pro...

As it stands it looks like building 'openmaptiles' or using it seems not straightforward on Windows. Thanks though for trying to help.

**Comment by lukasmartinelli** [comment]
> As it stands it looks like building 'openmaptiles' or using it seems not straightforward on Windows. Thanks though for trying to help.

But Windows 10 with the Ubuntu subsystem should make such interactions easier in the future is my hope.

**Comment by nouryf** [comment]
I have Windows 10 Pro and when I tried to install 'Docker for Windows' the installer complains that i need Windows 10 Pro. I opened a ticket on 'Docker for Windows'. I reverted back to 'Docker toolbox'.

To work around this 'windows' docker issue, would using images for the sequence of actions (postgress data import, sql import, generate vector tiles) available as images in Kitematic ?

**Comment by lukasmartinelli** [comment]
> To work around this 'windows' docker issue, would using images for the sequence of actions (PostgreSQL data import, sql import, generate vector tiles) can be done through Kitematic. Or if those are available as images, may be it would be more complicated to run the sequence through Kitematic ?

Well if the system supports docker-compose it should actually still be one command.
What was failing now for you was simply the make process.

What if you unpack `build.zip` https://github.com/openmaptiles/openmaptiles/releases/download/v3.4/build.zip into the `build` folder within `openmaptiles` (what should be produced by the build).
And then run `docker-compose up -d postgres` and `docker-compose run import-water`?

**Comment by nouryf** [comment]
Thanks.
Running 'Docker-compose up -d postgress":

$ docker-compose up -d postgres
[33mWARNING[0m: The MIN_ZOOM variable is not set. Defaulting to a blank string.
[33mWARNING[0m: The MAX_ZOOM variable is not set. Defaulting to a blank string.
[33mWARNING[0m: The BBOX variable is not set. Defaulting to a blank string.
Creating network "openmaptiles_default" with the default driver
Creating volume "openmaptiles_pgdata" with default driver
Creating volume "openmaptiles_cache" with default driver
Pulling postgres (openmaptiles/postgis:2.3)...
2.3: Pulling from openmaptiles/postgis

[0B066cd84a: Pulling fs layer
[0B80b38d38: Pulling fs layer
[0B06823821: Pulling fs layer
[0B7ac202a9: Pulling fs layer
[0Bb383ba3d: Pulling fs layer
[0B418b46ce: Pulling fs layer
[0Bd41b7758: Pulling fs layer
[0B9522dd30: Pulling fs layer
[0B548f9635: Pulling fs layer
[0Bf7ef2ee5: Pulling fs layer
[0B2ce02828: Pulling fs layer
[0Be816084c: Pulling fs layer
[0Bb701c5e3: Pulling fs layer
[0B1cb8eb53: Pulling fs layer
[0B52800a0a: Pulling fs layer
[0B56f37f65: Pulling fs layer
[6Be816084c: Extracting [=======================>                           ] 71.86 MB/154.3 MBB
------------------------------------------------------------------------------------------------------------
Similar message when running 'import-water'..

Is this mean that it will try to pull all osm world data ? Should i define the BBOX and MINZ and MAXZ some where to limit my area of test ? I guess the BBOX define the target area to pull the data from OSM Geofabrik and MINZ and MAXZ are for the final vector tiles zoom ranges ?

Thanks

**Comment by nouryf** [comment]
I went ahead on run the other steps until 'import-osm'. The execution seems to run but it halt with an error at the end:

$ docker-compose run import-osm
[33mWARNING[0m: The MIN_ZOOM variable is not set. Defaulting to a blank string.
[33mWARNING[0m: The MAX_ZOOM variable is not set. Defaulting to a blank string.
[33mWARNING[0m: The BBOX variable is not set. Defaulting to a blank string.
Pulling import-osm (openmaptiles/import-osm:0.3)...
0.3: Pulling from openmaptiles/import-osm

[0Bbd298390: Already exists
[0B728aad85: Already exists
[0B0ec20bf5: Already exists
[0B81f75ff6: Pulling fs layer
[0Bb52886d8: Pulling fs layer
[0B5ee63bd6: Pulling fs layer
[0Beec6f44b: Pulling fs layer
[0B0cca838f: Pulling fs layer
[0B0db14f3d: Pulling fs layer
[0B52cfd242: Pulling fs layer
Digest: sha256:2da38b09f38e3ee94669f08578c678a04215b30a7d7836ca6ea307984310577418.71 kB/18.71 kBB
Status: Downloaded newer image for openmaptiles/import-osm:0.3
[31mERROR[0m: Cannot create container for service import-osm: invalid bind mount spec "F:\\test\\openmaptiles\\data:/import:rw": invalid volume specification: 'F:\test\openmaptiles\data:/import:rw'
--------------------------------------------------------

I looked at my file system and there was no 'data' folder under 'F:\test\openmaptiles' so that might be a valid error (and not Docker windows mount access issue). Is 'data' folder supposed to be created by the previous steps ? The previous steps run fine without errors (only warning about BBOX, MIN_ZOOM and MAX_ZOOM).

**Comment by lukasmartinelli** [comment]
That's actually missing in the docs I see. In the `data` folder you should put the downloaded OSM PBFs (like from GeoFabrik http://download.geofabrik.de/). This will then be imported into the db.

But it looks like compose abstracts away some difficulties.

**Comment by nouryf** [comment]
I downloaded http://download.geofabrik.de/africa/comores-latest.osm.pbf and stored in 'data' folder then re-run the import:
[33mWARNING[0m: The MIN_ZOOM variable is not set. Defaulting to a blank string.
[33mWARNING[0m: The MAX_ZOOM variable is not set. Defaulting to a blank string.
[33mWARNING[0m: The BBOX variable is not set. Defaulting to a blank string.
[31mERROR[0m: Cannot create container for service import-osm: invalid bind mount spec "F:\\test\\openmaptiles\\data:/import:rw": invalid volume specification: 'F:\test\openmaptiles\data:/import:rw'

The error seems to persist.

**Comment by nouryf** [comment]
It looks like this is a Docker toolbox windows issue and not 'openmaptiles' one. Thanks for the help. I'm closing this ticket. I managed to use 'Ubuntu' on virtual box to run the docker images.

**Comment by zstadler** [comment]
This is for everyone who, like me, uses [Docker Toolbox](https://docs.docker.com/toolbox/overview/) on Windows and installs `openmaptiles` on a different Windows drive.

By default the docker host has access only to `C:\Users` as `/c/Users`. Other directories can be shared using VirtualBox settings.

In order for the docker container to get access to the `openmaptiles` installation directory, anywhere on the `F:` drive, the virtual machine needs access to `F:\` as `/f`. In order to accomplish that run the following commands in the Docker Quickstart Terminal.

```
PATH=${PATH/':/c/Program Files/Oracle/VirtualBox'/}":/c/Program Files/Oracle/VirtualBox"
docker-machine stop default
VBoxManage sharedfolder add default --name f --hostpath 'F:\' --automount
docker-machine start default
VBoxManage showvminfo default | grep "Host path"
```

The last command shows the shared folders:
```
Name: 'c/Users', Host path: '\\?\c:\Users' (machine mapping), writable
Name: 'f', Host path: 'F:\' (machine mapping), writable
```

To remove the access to `F:\` run the following commands:
```
PATH=${PATH/':/c/Program Files/Oracle/VirtualBox'/}":/c/Program Files/Oracle/VirtualBox"
docker-machine stop default
VBoxManage sharedfolder remove default --name f
docker-machine start default
VBoxManage showvminfo default | grep "Host path"
```

The last command shows the remaining shared folder:
```
Name: 'c/Users', Host path: '\\?\c:\Users' (machine mapping), writable
```

**NOTE:**    
**Adding or removing access to the drive involves powering-off the virtual machine and turning it on again!**

Ref:
- https://docs.docker.com/toolbox/toolbox_install_windows/#optional-add-shared-directories
- https://www.virtualbox.org/manual/ch08.html#vboxmanage-sharedfolder
