### ISSUE TITLE
Regression: Changing `PGPORT` in `.env` does not change port used in `postgres` container

### ISSUE THREAD

**Issue by severin-lemaignan** [openmaptiles/openmaptiles#1565]
**Version of openmaptiles**: fresh git clone as of 20/07/2023 (commit 90ca096938ecda1d2078e73af9173657200e362d2) 

**Issue**: I run another `postgres` instance on my server on port `5432`. After changing `PGPORT` in `.env` from `5432` to `5433` and running `make start-db`, the container fails with:

```
$ make start-db
Using docker compose V1 (docker-compose)
Starting postgres docker compose target using default image (no recreate if exists)
Starting openmaptiles_postgres_1 ... 
Starting openmaptiles_postgres_1 ... error

ERROR: for openmaptiles_postgres_1  Cannot start service postgres: driver failed programming external connectivity on endpoint openmaptiles_postgres_1 (4b9ef54636a13721439e97877cebe8a9d3f71d5bbafb22cad28fff417b91140b): Error starting userland proxy: listen tcp4 0.0.0.0:5432: bind: address already in use

ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint openmaptiles_postgres_1 (4b9ef54636a13721439e97877cebe8a9d3f71d5bbafb22cad28fff417b91140b): Error starting userland proxy: listen tcp4 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:337: start-db-nowait] Error 1
```

 `docker-compose` pulled `openmaptiles/postgis:7.0`

This issue is the same as #1354, fixed in #1363. So it appears that this is a regression.

**Comment by wsamipw** [comment]
I have encountered same issue.

**Comment by pjanetzek** [comment]
Hello - is there a good way to work around this issue?

**Comment by pjanetzek** [comment]
https://github.com/openmaptiles/openmaptiles/blob/master/docker-compose.yml#L22
should be `- "${PGPORT:-5432}:5432"`
and I had to run `docker-compose down --remove-orphans` to resolve the issue after the error occured.

**Comment by TomPohys** [comment]
Thanks @pjanetzek for digging into this. Could you please make a PR? Thanks a lot!

**Comment by TomPohys** [comment]
On the other hand, if you change the `PORT` in `.env` before you start database it runs smoothly and I could run two OMT project databases on different ports. The docker container does not change the port after it is created and if you first run `make start-db` (which ends up by error) and then change the port, you have to delete the `openmaptiles/postgis` container first.

**Comment by TomPohys** [comment]
I would like to close this issue, since the PostgreSQL port had been changed before the container was created, everything should works OK. If the port is changed after the container is created (with an error), it is enough to just remove the container and create a new one with the correct port. 

No problem to reopen this issue if I misunderstood the problem.

Thanks
