### ISSUE TITLE
asyncpg.exceptions.UndefinedTableError: relation "water_z0" does not exist

### ISSUE THREAD

**Issue by pakastin** [openmaptiles/openmaptiles#1566]
Trying to run postserve and tileserver-gl after imports but when browser is requesting pbfs it's throwing this error:

```
asyncpg.exceptions.UndefinedTableError: relation "water_z0" does not exist
```

**Comment by TomPohys** [comment]
Could you please provide more information regards `after imports`? (e.g [list in readme](https://github.com/openmaptiles/openmaptiles#workflow-to-generate-tiles))

**Comment by pakastin** [comment]
Ah yes, did planet import according to readme:

```
make clean
make
make start-db
make import-data
make download area=planet
make import-osm
make import-wikidata
make import-sql
make start-postserve
make start-tileserver
```

**Comment by TomPohys** [comment]
It looks like some error during `import-sql` step. Do you have some logs from this step? Did you solve the problem already? Thanks

**Comment by TomPohys** [comment]
If you have any more questions, please feel free to reopen the issue or create a new one.
