### ISSUE TITLE
subjoin (U+17D2) in Khmer scripts does not get rendered correctly

### ISSUE THREAD

**Issue by MakaraSok** [openmaptiles/openmaptiles#1570]
The image below is from `https://express.grab.com/track/`. Drag the map to any where with Khmer text to see the subjoin (aka Coeng, U+17D2) rendered as a plus sign underneath the base character.

![image](https://github.com/openmaptiles/openmaptiles/assets/28331388/7d051235-4c9a-4997-84e3-41a1579f8c5c)
![image](https://github.com/openmaptiles/openmaptiles/assets/28331388/6394115a-9230-4d05-92c8-c35bd8a39b07)

When reporting a visual problem on a map please provide:

- Clear description of the problem: Texts with subjoin (U+17D2) in Khmer scripts does not get rendered correctly. Instead of the expected rendering of the subjoin, a plus sign is shown underneath its base character.
- URL / link to the specific location in a live map demo where the bug is visible: see the screenshot above.
- Zoom level(s) at which the bug appears: Anywhere with texts in Khmer script
- Screenshot of the problem is very beneficial! It's permanent and browser-independent. Drag&drop an image to the report.
- Check our GL styles (https://openmaptiles.org/styles/) and list the affected one (OSM Bright, Basic, Terrain, Positron, etc).

**Comment by TomPohys** [comment]
Hi, could you please check if this is incorrectly in data (https://openmaptiles.org/inspect/#1.04/-0.0/0.0) or it is problem with font? Thanks

**Comment by TomPohys** [comment]
Hi @MakaraSok, any progress here? Thanks.

**Comment by MakaraSok** [comment]
Hi @TomPohys,

The maps look pretty clean. I was able to locale the location in the screenshot above and it looks OK with nice rendering of Khmer text for the label.

<img width="1910" alt="image" src="https://github.com/openmaptiles/openmaptiles/assets/28331388/1ee0e9fe-8dbe-4f83-943b-ade2d061bf94">

This seems to be Grab's issue.

**Comment by TomPohys** [comment]
Thanks for the confirmation. It looks like a problem with the font. Please, try to use another one.
