### ISSUE TITLE
Some paths and tracks are shown at z13 while some are not

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#1571]
I am testing this with Connecticut and you can view the issue by browsing to `/#13/42.00451/-73.47254`. 

I problem I am seeing is that some `paths` and `tracks` are shown at `z13` while other paths and tracks are not. There seems to be no rhyme or reason to which ones are shown or not shown.

This is using new checkout of openmaptiles and zoom set to 14 in .env.

![ezgif com-video-to-gif](https://github.com/openmaptiles/openmaptiles/assets/30858/1124d7b9-c495-402f-a80b-141fcbe8b224)

**Comment by TomPohys** [comment]
Hi, the logic of what is shown in z13 and not is in `transportation.sql`

https://github.com/openmaptiles/openmaptiles/blob/a7a50d84bc7e5117453d6e1c179a8a36f105d73b/layers/transportation/transportation.sql#L381-L387

**Comment by TomPohys** [comment]
Hi @nnhubbard, any progress here? Thanks.

**Comment by nnhubbard** [comment]
> Hi @nnhubbard, any progress here? Thanks.

Thanks. This can be closed.
