### ISSUE TITLE
Error 124 while import-sql with planet extract

### ISSUE THREAD

**Issue by armingheorghina** [openmaptiles/openmaptiles#1582]
Hello,

I am trying to generate mbtiles for a planet extract and I am running in this issue at make import-sql.

>\psql:/sql/parallel/housenumber.sql:64:psql:/sql/parallel/poi.sql:182: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
psql:/sql/parallel/poi.sql:182:  fatal: connection to server was lost
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
psql:/sql/parallel/housenumber.sql:64: fatal: connection to server was lost
psql:/sql/parallel/transportation__transportation_name.sql:400: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
psql:/sql/parallel/transportation__transportation_name.sql:400: fatal: connection to server was lost
xargs: sh: exited with status 255; aborting
ERROR: 124
make: *** [Makefile:453: import-sql] Error 124

I am using the latest version of openmaptiles and generating on a country based works as expected, the issue appears while trying to generate on a planet pbf.

What am I missing ? Is the issue related to memory ?

**Comment by TomPohys** [comment]
Hi, the server went down (`This probably means the server terminated abnormally`). Did you try https://pgtune.leopard.in.ua and adjust the PostgreSQL settings? You can also set the pgdata into current folder by adjust the docker file for more easy config update.

```diff
- pgdata:/var/lib/postgresql/data 
+ ./pgdata:/var/lib/postgresql/data 
```

**Comment by TomPohys** [comment]
Please, if you have further questions, feel free to reopen the issue or create a new issue.
