### ISSUE TITLE
New ids are missing encoded OSM type

### ISSUE THREAD

**Issue by zbycz** [openmaptiles/openmaptiles#1587]
Hi @TomPohys, 👋 

Since yesterday i am seeing that large number of layers with OSM IDs are not encoding the OSM type properly.
It used to be `$OSMID+'0'` = node, `$OSMID+'1'` = way, `$OSMID+'4'` = relation on most of the layers (i can tell you which), but now the vector feature `id` is just `$OSMID`.

Is this some known change? or a mistake? Can you suggest some alternative approach perhaps?

It broke the clickable poi map on [osmapp.org](https://osmapp.org/#15.72/40.5880/-73.6605), it tries to remove the last number in vector feature id and use it as osm type, so almost none pois are clickable anymore. City names still works the old way, but almost all pois are wrong. (I suspect cache is making it stilll work in CZ)

**Comment by TomPohys** [comment]
Thanks, I have to check it!

**Comment by zbycz** [comment]
Hi @TomPohys - could I prehaps help you somehow? :) I looked at the OMT repo, but there are no related changes. I guess that has to be bronek at the comerecial maptiler stack, right?

**Comment by TomPohys** [comment]
Hi, sorry for the delay! The glitch in MapTiler infrastructure was identified and fixed. POI with OSM ID should be OK now. This bug has no relation to the OMT schema. Sorry for the inconvenience and thank you for pointing this out.

**Comment by zbycz** [comment]
Hi @TomPohys, no worries. Thank you very much for resolving it. 🙂  I will close the issue once I see the correct data again (some cache is probably in place).

**Comment by TomPohys** [comment]
Thanks! Yes, there is a cache, but the [point in US](https://osmapp.org/node/1089053983#15.72/40.5880/-73.6606) works.

**Comment by zbycz** [comment]
Oh-la-la! Somewhere it really works 😃

**Comment by zbycz** [comment]
HI @TomPohys, it seems that most of sourceLayers are fixed now, but there are still some returning the ID without type. I tried it both in CZ and US, it seems that cache isn't the issue now. Do you think you can look at those please?

Here is the list (i will edit if i find more):
- `sourceLayer:place` - click any name of a city or part
- `sourceLayer:building` - can't find example now
- `sourceLayer:poi, class:castle` - here [palác](https://osmapp.org/50.09030,14.39722)
- `sourceLayer:poi, class:garden` - here [botanická](https://osmapp.org/50.11872,14.41567)

-------

Also i found several layers, which are not clickable yet, but id is correct, only missing is the encoded osm_type. Do you think, you could fix those as well? But it is probably missing also in OMT, we can leave it for another issue:
eg.:
- `sourceLayer:aerodrome_label` - [SFO airport](https://osmapp.org/37.62118,-122.38341)
- `sourceLayer:transportation_name` - any street name, eg [minor](https://osmapp.org/50.11829,14.41734) or [trunk](https://osmapp.org/50.113859,14.430729)
- `sourceLayer:waterway` - any river name, eg [vltava](https://osmapp.org/50.11348,14.40656)
- btw, on every click, you can find the sent id in chrome console, eg.: `clicked map feature (id=36287252):` + also an object with the sourceLayer and class

**Comment by TomPohys** [comment]
Hi, I just made a quick look on [Arcibiskupský palác](https://www.openstreetmap.org/relation/295830#map=18/50.09028/14.39730) and the osm_id is correct (295830 * 10 + 1) based on https://github.com/openmaptiles/openmaptiles/blob/dfd20c647c1a20e45e5ac869d3769289db17979b/layers/poi/poi.sql#L76

the buildings have a clear (no modification) osm_id based on https://github.com/openmaptiles/openmaptiles/blob/dfd20c647c1a20e45e5ac869d3769289db17979b/layers/building/building.sql#L99

I remember the issue https://github.com/openmaptiles/openmaptiles/issues/792 about adding more layers with osm_id.

**Comment by zbycz** [comment]
ad castle) I think you have a mistake here -  the id for "Arcibiskupský palác" in MVT is really (295830 * 10 + 1), but that should mean it is a `way`. Although as visible here https://www.openstreetmap.org/relation/295830 it is a relation .. 🤔

**Comment by zbycz** [comment]
Hi @TomPohys,

thanks for fixing most of this bug, but we still have two issues:

1)  a few categories end incorrectly with `1` (way), even though they are relations and should end with `4`:
    - `sourceLayer:poi, class:castle` - here [palác](https://osmapp.org/50.09030,14.39722) 
    - `sourceLayer:poi, class:garden` - here [botanická](https://osmapp.org/50.11872,14.41567)
    - `sourceLayer:poi, class:collage` - here [FTVS](https://osmapp.org/50.09186,14.33350)
    - `sourceLayer:poi, class:cemetery` - here [hřbitov](https://osmapp.org/50.09342,14.32847)
    - `sourceLayer:poi, class:park` - here [riegrovy sady](https://osmapp.org/50.08008,14.43926)
    - `sourceLayer:poi, class:museum` - here [národní](https://osmapp.org/50.078983,14.430931)

2) `sourceLayer:place` are missing the type encoding at all. Eg. [Hradčany](https://osmapp.org/50.09118,14.39604) have id `29789663`, but it is a node, so it should end with `0`.

Could you please take a look at it? I hope it will be just one small modification somewhere. 🤞 I would be glad to help/pair on it, if needed. 🙂

**Comment by zbycz** [comment]
Hi @TomPohys – looking forward to those fixes, just wanted to ask if everything goes well? Thanks

**Comment by laem** [comment]
Hi, I'm having the same issue on a similar map. Not being able to link OMT ids to OSM ids is a big problem :/

**Comment by zbycz** [comment]
bump.. this is still an issue. 🙂 Could we possibly help you by fixing the OMT code? Or is this really hidden in some private maptiler part? thx

**Comment by TomPohys** [comment]
Sorry for such a delay! Could you please provide more specifics on which OSM ID does not match the OMT logic? It will allow me to debug more straightforwardly.

If I look at your list e.g. [palác](https://osmapp.org/50.09030,14.39722) - If I will assume, that you think [Arcibiskupský palác](https://www.openstreetmap.org/relation/295830#map=19/50.09028/14.39730) which is the relation with OSM ID 295830 (you were right that is not a way so the logic is `WHEN osm_id < 0 THEN -osm_id * 10 + 4`) and when I look up for the ID (MapTiler Customize) 

![image](https://github.com/openmaptiles/openmaptiles/assets/5182210/8d9c15be-0dd5-416b-ae13-a09e1ee0b9d9)

Also the [botanická](https://osmapp.org/50.11872,14.41567) I assume that you mean https://www.openstreetmap.org/relation/2412566

![image](https://github.com/openmaptiles/openmaptiles/assets/5182210/30c6b17e-4e51-4899-a42c-0a89a0f9e800)

On the `place` layer I will have to look at it, but probably the same glitch as for POI and we have to fixed on our side.

Thank you

**Comment by zbycz** [comment]
Hi @TomPohys, thanks for you care. 👍

It looks that the POI layer is already fixed 🎉  All the examples above (point 1.) with `sourceLayer:poi` works fine now. Everyhing has correct encoding of relation etc.

So the only thing left in this issue is the broken `sourceLayer:place` (point 2.)
Eg. 
|  | osm id | wrong Maptiler Planet id | should be
|--|--|--|--
| Hradčany | node/297896637 | 297896637 | 2978966370
| Pardubce | node/1585113445 | 1585113445 | 15851134450
| Praha | node/1601837931 | 1601837931 | 16018379310

**Comment by zbycz** [comment]
Hi @TomPohys, i think we may have a regression on poi items. These poi of type `way` are incorrectly encoded as `relation` (suffix `4`).

| osm link | maptiler data | should be
| -- | -- | -- |
| https://osm.org/way/56043862 | <img width="360" alt="image" src="https://github.com/openmaptiles/openmaptiles/assets/385047/61a0f121-dd81-4ac1-a622-5e9a307e597d"> | 56043862**1**
| https://osm.org/way/16146611 | <img width="398" alt="image" src="https://github.com/openmaptiles/openmaptiles/assets/385047/80e5a256-b994-49cc-83e4-1af64451865f"> | 16146611**1**

**Comment by laem** [comment]
Related issue : I'm now building my own OMT PMTiles and I had to modify Tilemaker's process-openmaptiles.lua file to include a new "feature_type" attribute. 

https://github.com/systemed/tilemaker/issues/740

**Comment by zbycz** [comment]
Hi! Good job, ya all! ❤️  🎉 

Everything which was broken/reported is fixed now. I have been observing the correct IDs ca. from mid August, and it didn't change. If I found some more, I will open another issue.
