### ISSUE TITLE
Tile server no longer working after #1523

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#1588]
`make start-tileserver` is no longer functional after #1523

This is because the tile server expects to read `data/tiles.mbtiles`, which is no longer available.

To reproduce:
1. Run `./quickstart.sh`
2. Run `make start-tileserver`
3. Wait a few seconds
4. Run `docker-compose ps` to confirm that the tile server is not running
```
$ docker-compose ps
NAME      IMAGE     COMMAND   SERVICE   CREATED   STATUS    PORTS
```
5. Check the log file
```
$ docker-compose logs tileserver-gl
openmaptiles-tileserver-gl-1  | Starting tileserver-gl v4.6.2
openmaptiles-tileserver-gl-1  | Using specified config file from /style/config.json
openmaptiles-tileserver-gl-1  | Starting server
openmaptiles-tileserver-gl-1  | Listening at http://[::]:8080/
openmaptiles-tileserver-gl-1  | ENOENT: no such file or directory, stat '/data/tiles.mbtiles'
openmaptiles-tileserver-gl-1  | Starting tileserver-gl v4.6.2
openmaptiles-tileserver-gl-1  | Using specified config file from /style/config.json
openmaptiles-tileserver-gl-1  | Starting server
openmaptiles-tileserver-gl-1  | Listening at http://[::]:8080/
openmaptiles-tileserver-gl-1  | ENOENT: no such file or directory, stat '/data/tiles.mbtiles'
```

Attn: @wcedmisten, @TomPohys

**Comment by nilsbentlage** [comment]
Same here! 
The corresponding File is empty ...

**Comment by TomPohys** [comment]
Oh, I did not realize that `style-header.json` and `config.json` for styles depend on name `tiles.mbtiles`

**Comment by andymilga** [comment]
mv data/${region_name}.mbtiles data/tiles.mbtiles as quick fix works

**Comment by NguyenDuc141** [comment]
Because need 2 two domain for it
