### ISSUE TITLE
Missing transportation_name layer

### ISSUE THREAD

**Issue by manhcuongincusar1** [openmaptiles/openmaptiles#1593]
# Missing transportation_name layer
I have attempted to build an Mbtile file using quickstart.sh about five times. However, in all five resulting files, the transportation_name is missing.

## Command:
`./quickstart.sh area=vietnam`

## Env:
MIN_ZOOM=0
MAX_ZOOM=12

## Result:
<img width="704" alt="Screenshot 2023-10-30 at 15 36 19" src="https://github.com/openmaptiles/openmaptiles/assets/63287450/fba7299b-0d93-4f91-9f91-f3a4b533eb88">
<img width="1682" alt="Screenshot 2023-10-30 at 15 37 03" src="https://github.com/openmaptiles/openmaptiles/assets/63287450/dd1afde5-8499-4bb9-b704-b4d29e5bbead">

## Log File:
[quickstart.log](https://github.com/openmaptiles/openmaptiles/files/13202860/quickstart.log)

**Comment by TomPohys** [comment]
Hi, thanks for sharing `log`. Based on `analyzing` there are `134301` records in table `public.osm_transportation_name_linestring` could you please adjust BBOX in `.env` file for smaller area and re-generate tiles up to zoom 14 (update `.env` and then run just `make generate-tiles-pg`, no need to run again `make import-*`)?

Thanks

**Comment by manhcuongincusar1** [comment]
@TomPohys Thank you for support. I changed to 14 max zoom and it worked.

**Comment by TomPohys** [comment]
Great to hear!
