### ISSUE TITLE
problem with "James Bay" in water_name (water label)

### ISSUE THREAD

**Issue by phanecak-maptiler** [openmaptiles/openmaptiles#1595]
There is a problem with https://github.com/openmaptiles/openmaptiles/pull/1457 in regards to "James Bay" (possibly others) as following changes:

* https://github.com/openmaptiles/openmaptiles/pull/1457 , e.g. `natural: bay` and `... straight` added into mappings
* https://github.com/openmaptiles/openmaptiles/pull/1457/files#diff-201daa1c61c99073fe3280d440c9feca5ed2236b251ad454caa14cc203f952d1R76 , e.g. `WHEN zoom_level >= "rank" AND "rank" IS NOT NULL THEN TRUE`

clash with:

* https://github.com/openmaptiles/openmaptiles/blob/master/layers/water_name/update_marine_point.sql#L21,L22 , e.g. `LEFT JOIN ne_10m_geography_marine_polys AS ne ON lower(trim(regexp_replace(ne.name, '\\s+', ' ', 'g'))) IN (lower(osm.name), ...`

In OpenMapTiles 3.14 that name matching works OK (since only `place: ocean` and `... sea` are in mappings), but in current `master` it means that thanks to https://www.openstreetmap.org/relation/13360255 being listed in Natural Earth with "rank: 3", several other much smaller "James Bay" points/nodes get "rank: 3" too, for example:

* https://www.openstreetmap.org/node/1385157299

Which means that we get on Z3 more than we should/want to:

![Screenshot from 2023-11-23 22-10-03](https://github.com/openmaptiles/openmaptiles/assets/115141505/00ca8290-d8dd-4f23-8da8-a34e4a9ec068)

I'm not sure about how to tackle this properly, so I'd would like some help with that, say from @ZeLonewolf or maybe @TomPohys or others.

**Comment by pnorman** [comment]
> * LEFT JOIN ne_10m_geography_marine_polys AS ne ON lower(trim(regexp_replace(ne.name, '\\s+', ' ', 'g'))) IN (lower(osm.name), ...

When I had to do this [elsewhere with cities](https://github.com/pnorman/meddo/blob/8a6c82d6a1ad1a1682b28f411251f65e18a961a2/data.yml#L488-L497) I did it on what was effectively `ARRAY[pg_catalog.lower(unaccent(osm.name)), pg_catalog.lower(unaccent(o.names->'en'))] && ARRAY[pg_catalog.lower(unaccent(ne.name)), pg_catalog.lower(unaccent(ne.namepar)), pg_catalog.lower(unaccent(ne.namealt)), pg_catalog.lower(unaccent(ne.nameascii))] AND ST_DWithin(ne.way, osm.way, 50000)`

These days I'd probably use a [non-deterministic collation](https://github.com/openstreetmap/openstreetmap-website/pull/4405#issuecomment-1865979238) to do the compare which takes care of all the accents, cases, and different normal forms.

Keep in mind there still could be duplicates within 50km, but it's unlikely as feature names tend to be unique in the surrounding area. Your code needs to at least not error in this case.

**Comment by phanecak-maptiler** [comment]
> When I had to do this [elsewhere with cities](https://github.com/pnorman/meddo/blob/8a6c82d6a1ad1a1682b28f411251f65e18a961a2/data.yml#L488-L497) I did it on what was effectively ...

Thank you. I've used that for the fixes:

- OpenMapTiles: https://github.com/openmaptiles/openmaptiles/pull/1621
- planetiler-openmaptiles: https://github.com/phanecak-maptiler/planetiler-openmaptiles/pull/35
