### ISSUE TITLE
Compilation Failure on master branch

### ISSUE THREAD

**Issue by SeanHub** [openmaptiles/openmaptiles#1597]
I have condensed this into barebone steps:

Install Ubuntu (22.04.3) on VirtualBox
Open terminal and add user to sudoers file then install git and docker then run the following commands:

cd ./Downloads
git clone https://github.com/openmaptiles/openmaptiles.git
cd ./openmaptiles directory
sudo make

I am then presented with the following error:

http: invalid Host header
make: *** [Makefile:275: build/openmaptiles.tm2source/data.yml] Error 1

**Comment by TomPohys** [comment]
It is probably some issue with docker itself - please try to look at https://github.com/docker/compose/issues/11154 or similar topics (some docker versions could cause trouble)

**Comment by SeanHub** [comment]
Thank you for your help, installing docker in a different way was the solution.

For those who stumble upon this in future, you should install docker using the apt repository (do not use Ubuntu snap).

For a step by step guide see here: [https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)

**Comment by ZeLonewolf** [comment]
Should we document this somewhere in the project documentation rather than here in this ticket?

**Comment by TomPohys** [comment]
Yes, it could be beneficial. PR for updating documentation is welcome.
