### ISSUE TITLE
Error - failed to create network openmaptiles_default

### ISSUE THREAD

**Issue by dreadedhamish** [openmaptiles/openmaptiles#1603]
First time installer - I cloned the repo and ran quickstart.sh and it throws an error establishing a network connection:

Downloading albania into data/albania.osm.pbf from any source
 Network openmaptiles_default  Creating
 Network openmaptiles_default  Error
failed to create network openmaptiles_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
make: *** [Makefile:373: download] Error 1

Full quickstart.log: https://gist.github.com/dreadedhamish/d83ea6579cdfb3ba25e2c947d68fcc9a

The same error occurs running make.

I'm using Manjaro (based on Arch) with everything up-to-date.

Any hints on getting past this?

**Comment by ImreSamu** [comment]
Hi @dreadedhamish ,

> "Error response from daemon: could not find an available, non-overlapping IPv4"

Based on the error message, 
please check out this StackOverflow thread : 
 * https://stackoverflow.com/questions/43720339/docker-error-could-not-find-an-available-non-overlapping-ipv4-address-pool-am

**Comment by dreadedhamish** [comment]
@ImreSamu Thanks!

I just solved it (temporarily?) by stopping a few containers and running 'docker network prune', but as I understand it that may just be a temporary fix until I use up more of the default networking space.
