### ISSUE TITLE
Two small issues in extracting building height in building.sql

### ISSUE THREAD

**Issue by sfkeller** [openmaptiles/openmaptiles#161]
Just stumbled over two small issues when extracting building height in /layers/building/building.sql (https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/building.sql ), line 18:

`  greatest(5, COALESCE(height, levels*3.66,5))::int AS render_height,`

1. COALESCE is IMHO not necessary there; GREATEST is already doing the job. 
2. My heuristics based on whole Switzerland extract indicate that the mean height per level is 3.0 meters, not 3.66 (from where is yours?).

So my proposition is to change line 18 (and 19) to:

`  greatest(5, height, levels*3.0)::int AS render_height,`

(Assuming height and levels are type integer).

**Comment by stirringhalo** [comment]
Hi @sfkeller !

There's some fairly substantial changes in https://github.com/openmaptiles/openmaptiles/pull/157/files that should be coming soon.

I use COALESCE there as I have seen building:parts where the height is < 5, leading to incorrect drawing (eg: http://www.openstreetmap.org/relation/3364031). So COALESCE is preferred without GREATEST.

I went with 3.66 m based on some number I saw somewhere, I'm not against using 3.0!
