### ISSUE TITLE
Cable cars are neither rendered nor exported into mbtiles

### ISSUE THREAD

**Issue by ststeiger** [openmaptiles/openmaptiles#1616]
Visual Problem: 
There are no cable cars. 
e.g. Bergbahnen Malbun AG 

When you go to google, you see there is a cable-car from Malbun (FL) to Sareis. 
https://www.google.com/maps/@47.1013631,9.6129315,17.5z?entry=ttu

When I go to osm, it is also there:
https://www.openstreetmap.org/#map=17/47.10169/9.61503

These are the tags/layers
https://www.openstreetmap.org/way/31129919#map=17/47.10182/9.61511&layers=D

But when I render the map from openmaptiles mbtiles with mapbox-gl, there is no cable car. 
This is presumably because the aerialway layer is not put into data. 

Location (lat,long): 47.10070981833037, 9.610534262261723

```
Tags
aerialway	chair_lift
aerialway:bubble	no
aerialway:occupancy	4
name	Sareis
oneway	no
ref	C
```
The rendering is done using C# VectorTile-Server:
https://github.com/ststeiger/VectorTileServer/blob/master/VectorTileServer3/wwwroot/index.htm#L219

[![Bad][1]][1]
[![Good][2]][2]

I suppose this is because the layer aerialway	is not in openmaptiles.yaml.
Plus lacking config in the json-styles-config-files.

  [1]: https://i.stack.imgur.com/TDact.png
  [2]: https://i.stack.imgur.com/Ln8fo.png

**Comment by TomPohys** [comment]
Hi, when I check the inspect on https://openmaptiles.org/inspect/#17/47.10177/9.61487 the `chair_lift` is there.

It is part of `transportation` layer.

**Comment by ststeiger** [comment]
The one that comes with git clone https://github.com/openmaptiles/openmaptiles.git
In openmaptiles.yaml it says version: 3.14.0. 

If it is in the data, then it is possible that it is not rendered with mapBoxGL though.

**Comment by TomPohys** [comment]
Possibly just not included in `style.json`. For OpenMapTiles Style it is https://github.com/openmaptiles/openmaptiles/blob/e29827d76c431a6fb13e9073f3f88dfa90a92b9f/layers/transportation/style.json#L7621-L7690

**Comment by ststeiger** [comment]
Apparently, the class was renamed from cable_car to aerialway.
