### ISSUE TITLE
Roads on upper zoom levels are too segmented.

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles#1639]
Current [state of OMT](https://github.com/openmaptiles/openmaptiles/pull/1631) has too segmented `transportation_name` layer, leading to extended shields rendering, for example on the zoom 7.

![image](https://github.com/openmaptiles/openmaptiles/assets/5182210/ca2edfa7-de9a-44fb-9a14-b883c889bfb6)

QGIS: https://www.openstreetmap.org/way/37230873#map=15/41.7065/-112.1879

![image](https://github.com/openmaptiles/openmaptiles/assets/5182210/0395c69a-a4ce-4868-b66f-39caa7377385)

![image](https://github.com/openmaptiles/openmaptiles/assets/5182210/a170eecd-2ccb-46be-835a-1ef2726e9308)

![image](https://github.com/openmaptiles/openmaptiles/assets/5182210/d35629f0-dd8b-49d5-8d24-277beba4eb94)

---

Then the length condition also deletes bridges 

https://github.com/openmaptiles/openmaptiles/blob/9f891b625aabc009f0df7d3e14d7d4052c26204f/layers/transportation_name/transportation_name.sql#L143

---

Inserting data into `osm_transportation_name_linestring_genX` has to process merging LineStrings better 

https://github.com/openmaptiles/openmaptiles/blob/9f891b625aabc009f0df7d3e14d7d4052c26204f/layers/transportation_name/update_transportation_name.sql#L428-L458

![image](https://github.com/openmaptiles/openmaptiles/assets/5182210/88f65572-9b77-4e2b-a852-0978a0e76b19)

---

@ZeLonewolf, could you please look at it as you worked on https://github.com/openmaptiles/openmaptiles/pull/1579 and https://github.com/openmaptiles/openmaptiles/pull/1620?

**Comment by ZeLonewolf** [comment]
The intended behavior is that the little bridges should combine, so it looks like that's not happening somehow.
