### ISSUE TITLE
Update the pathway to Wayson Auto Sdn Bhd

### ISSUE THREAD

**Issue by NasMerican** [openmaptiles/openmaptiles#1658]
I updated map on Google maps for this shop. Can you please update the path to go to this shop follow the same as Google maps?

The current maps on the openmaptiles to the Wayson Auto Sdn Bhd is not accurate. The final drop place is in the middle of the main road. 
![SmartSelect_20240513_132925_Maps](https://github.com/openmaptiles/openmaptiles/assets/169636729/47ad3bed-e3a1-4d67-87a5-84dbfa275372)

Let me know if any additional details required to get this fixed. Thanks!

**Comment by NasMerican** [comment]
This is the current location Wayson Auto inside openmaptiles 
![SmartSelect_20240513_141552_Grab](https://github.com/openmaptiles/openmaptiles/assets/169636729/e59cd844-b1ad-4a48-aa02-a6d9fa8d4bc5)

**Comment by TomPohys** [comment]
Please add your shop and path to OSM map - https://www.openstreetmap.org/#map=19/2.860875/101.688658

Thanks!

Please, if you have further questions, feel free to reopen the issue or create a new issue.
