### ISSUE TITLE
Landcover: some forests are missing

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#167]
Around Bergen, Norway there are forests on the standard OpenStreetMap map which are not visible in our vector tiles.

See:
http://www.openstreetmap.org/#map=13/60.4054/5.3485

<img width="1088" alt="screen shot 2017-02-07 at 14 47 51" src="https://cloud.githubusercontent.com/assets/59284/22693763/e990a868-ed44-11e6-8352-143adca7325d.png">

and compare with inspect mode at:
https://editor.openmaptiles.org/?style=https://rawgit.com/openmaptiles/klokantech-terrain-gl-style/master/style.json#12.13/60.3979/5.3377

**Comment by ImreSamu** [comment]
this 2  `natural=wood` relations ?  
*  http://www.openstreetmap.org/relation/4824384 
*  http://www.openstreetmap.org/relation/4824250

**Comment by klokan** [comment]
Yes, these polygons do not seem to be available in our vector tiles...

**Comment by ImreSamu** [comment]
```
<tag k="natural" v="wood"/>
<tag k="type" v="multipolygon"/>
```

No `area=yes`  so maybe a simple `area_tags: `  -  will solve ...
https://imposm.org/docs/imposm3/latest/mapping.html#areas
 
just add this part to the final `mapping.yml`
```
areas:
  area_tags: [buildings, landuse, leisure, natural, aeroway]
  linear_tags: [highway, barrier]
```

**Comment by klokan** [comment]
Good point. Could you please test on an extract the effect of these changes @ImreSamu ?

It influences the availability of polygon / linestring for all listed tags - and therefore may produce quite a different visual results. Is there going to be a regression on some of the existing features?

**Comment by ImreSamu** [comment]
>It influences the availability of polygon / linestring for all listed tags - and therefore may produce quite 
>a different visual results. Is there going to be a regression on some of the existing features?


Probably 
*  need a deep research to find all `area_tags` and `linear_tags` 
   * my other good candidates for: `area_tags` 
     * `wetland=` 
     * `amenity=` 
     * `boundary=national_park`
     * .... 
*  need a full  `osm_id` vs.  `osm_id`  database comparisons for every tables  
.. and manually check the differences ...

>Could you please test on an extract the effect of these changes

it is a big change ...  I don't know when I can start and finish.
But if somebody has more times and  want to start -  just notify here  to avoiding double works ..

**Comment by jirik** [comment]
The problem was probably only missing `wood` value of `natural` tag in `mapping.yaml`
