### ISSUE TITLE
Hours on 99%

### ISSUE THREAD

**Issue by develth** [openmaptiles/openmaptiles#1674]
Hello,

im running openmaptiles on latest version on a fresh debian maschine. 
Currently the state is since 3 hours like that:
![Bildschirmfoto 2024-07-22 um 18 04 16](https://github.com/user-attachments/assets/af15c2b8-c9f6-48c5-af36-c1b0eae9e54d)

Process moves between 99.82xxx to 99.999 and then repeats.

Any ideas?
Thanks!

**Comment by TomPohys** [comment]
:-( never hit this behavior. Did you find a solution?

**Comment by develth** [comment]
I think it was regarding the size of zoom level i built. Did some changes in config and it worked. Need to be tested again. 
Will keep it open until next rerun.

**Comment by TomPohys** [comment]
Ohh.. I see that you tried to generate tiles up to a zoom 19. The beauty of vector tiles is in overzoom (vector tiles have a grid of 4096x4096). You do not have to generate vector tiles up to the desired zoom level (in your case, zoom 19) like for raster tiles. For street level detail is enough zoom level 14.

**Comment by develth** [comment]
> The beauty of vector tiles is in overzoom (vector tiles have a grid of 4096x4096).

I learned about it a few minutes later :D
The library / mapview i used first did not supported it, but after change it was easy. 
thanks

**Comment by TomPohys** [comment]
If you have any more questions, please feel free to reopen the issue or create a new one.
