### ISSUE TITLE
The area mbtile size i generate using the openmaptile quickstart tool is bigger than the one i download from openmaptiles.org

### ISSUE THREAD

**Issue by JINCHUNGEUN** [openmaptiles/openmaptiles#168]
I generated the south korea mbtile file using the openmatile quickstart tool , but the size of the mbtile is bigger than the one i download from the official website [https://openmaptiles.org/downloads/](url)

the size of mbtile i generate is 277M, and provided by the website is 185M

i set the minzoom=0 and maxzoom=14 and didn't set the bbox variable

**Comment by ImreSamu** [comment]
>I generated the south korea mbtile file using the openmatile quickstart tool , 
>but the size of the mbtile is bigger than the one i download from the official website

Thank you for your question!

imho:  
*  Never will be equal size
*  It is normal 

Main reason: 
* The `/quickstart.sh˙ is for quick testing and local development .. 
  *  using latest data,  from different extract, with different bbox, 
  *  and generated by the latest `master` source code

### Website https://openmaptiles.org/downloads/
* Data Source = OpenStreetMap Planet  ( And as you see :  from 11/28/2016 )
* Different bbox and cutting algorithm 
   *  see:  https://github.com/openmaptiles/extracts 
* Different Source code (git) version
  *  maybe the https://github.com/openmaptiles/openmaptiles/releases/tag/v3.3

### Development  `./quickstart.sh˙  
* Data Source = Geofabrik latest extract ( probably yesterday ) 
   * http://download.geofabrik.de/asia/south-korea.html 
   *  you can check in the log (`quickstart.log`)
* bbox is generated dynamically from  actual Geofabrik extract with a simple min,max algorithm 
   *   The calculated bbox - can be seen in the log  (`quickstart.log`)
   *   You have to known that Geofabrik extract is changed :  http://blog.geofabrik.de/?p=397
* Source code  version  - latest development  ( master )
   *  https://github.com/openmaptiles/openmaptiles/commits/master

**Comment by JINCHUNGEUN** [comment]
Thanks for the answer
