### ISSUE TITLE
I made changes to the data in PostgreSQL but the output vector tiles did not reflect the changes

### ISSUE THREAD

**Issue by nainglinnphyo** [openmaptiles/openmaptiles#1684]
After executing the following commands:
`make download area=albania`
`make import-osm`
`make import-wikidata`
`make import-sql`
I made changes to the data in PostgreSQL and ran make generate-tiles-pg, but the output vector tiles did not reflect the changes I made.

**Comment by TomPohys** [comment]
Hi, if you made a change in any `mapping.yaml` or any `sql` file, you have to also run `make clean` and `make` again. This will refresh the `build` folder from which the `make import-osm` and `make import-sql` running all the code.

**Comment by TomPohys** [comment]
Please, if you have further questions, feel free to reopen the issue or create a new issue.
