### ISSUE TITLE
[Question] What are the steps to increment zoom

### ISSUE THREAD

**Issue by develth** [openmaptiles/openmaptiles#1691]
Hey,

just wanted to know what the steps are to start with a zoom of 0/7 and work up to 0/14?
Just after each modify `./quickstart.sh area=europe` or using the separate make commands. If its the second case, which i need to run?

Maybe we should add this into the docs.

Thanks!

**Comment by TomPohys** [comment]
Hi, the range of zooms are setup in `.env` file. 

https://github.com/openmaptiles/openmaptiles/blob/8a8aa1a78b8c3927277e8ef93cb93d49a209688a/.env#L21-L23

It is mentioned in https://github.com/openmaptiles/openmaptiles/blob/8a8aa1a78b8c3927277e8ef93cb93d49a209688a/QUICKSTART.md?plain=1#L388-L396

**Comment by develth** [comment]
Hey @TomPohys,
i´m aware of this, but what to do after increasing it?
Running quickstart again?

**Comment by TomPohys** [comment]
You do not need to re-run all the import stages. You already have a filled database with all data and all generalized tables up to zoom 14 (if you do not modify the layers' SQL definitions), so you can just run `make generate-tiles-pg`.

Please be aware, that running `make generate-tiles-pg` will delete previous generated mbtiles (setup in `.env` https://github.com/openmaptiles/openmaptiles/blob/8a8aa1a78b8c3927277e8ef93cb93d49a209688a/.env#L33

**Comment by develth** [comment]
Ok, so just increase max_zoom and for each increment run `make generate-tiles-pg`
thanks!

**Comment by TomPohys** [comment]
Yes, if you change `MAX_ZOOM` in `.env`, you don't have to re-import all the data into the database. The other way.. the `MIN/MAX_ZOOM` will not influence `import-data`, `import-osm`, `import-wikidata`, or `import-sql` steps.
