### ISSUE TITLE
How to point to own produced .mbtiles in the style .json ?

### ISSUE THREAD

**Issue by nouryf** [openmaptiles/openmaptiles#170]
Hi,

I used the steps to produce an .mbtiles dataset. I tried to display it on browser following the doc at https://openmaptiles.org/docs/website/mapbox-gl-js/
 I downloaded locally https://openmaptiles.github.io/osm-bright-gl-style/style-cdn.json and edited
_"sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "https://free.tilehosting.com/data/v3.json?key=RiS4gsgZPZqeeMlIyxFo"
    }
  }_

to:
_"sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "http://localhost:3000/tiles/{z}/{x}/{y}.pbf"
    }
  }_

http://localhost:3000/tiles/{z}/{x}/{y}.pbf is my local url that serve the .pbf stored in the 'tiles.mbtiles'.

When I open the .html that display the map, the map tiles are not visible. 

I'm missing some thing to be able to display the tiles ?

Thanks

**Comment by klokan** [comment]
`"url"` must point to TileJSON.

Replace:
`"url": "http://localhost:3000/tiles/{z}/{x}/{y}.pbf"`
with:
`"tiles": ["http://localhost:3000/tiles/{z}/{x}/{y}.pbf"]`

or use TileServerGL or TileServerPHP which gives you the TileJSON endpoint.

Related documentation:
https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-vector
https://www.mapbox.com/mapbox-gl-js/example/third-party/

**Comment by nouryf** [comment]
Great. Thank you. It worked.

**Comment by NasH5169** [comment]
I've done multiple mbtiles but with one TileServer **for each mbtiles file**

So, add another source into the style.json like:

"sources": {
    "country1": {
      "type": "vector",
      "url": "http://localhost:8101/data/country1.json"
    },
    "country2": {
      "type": "vector",
      "url": "http://localhost:8102/data/country2.json"
    }
  }

**Comment by michaelknave** [comment]
Thank you for help. But if I use this approach, I am not able to get right style for second dataset. Can you please upload some sample style.json file?
