### ISSUE TITLE
'Place' layer text is 'name_en' but text is not English

### ISSUE THREAD

**Issue by nouryf** [openmaptiles/openmaptiles#172]
Hi,

https://editor.openmaptiles.org/?style=https://rawgit.com/openmaptiles/osm-bright-gl-style/master/style.json#9.13/31.5113/-8.2616

Looking at the labels displayed for 'place-town', the text field used is {name_en} but the displayed text is both 'English/French and Arabic'. I thought that its {name} that has a combination of languages in it... and {name_en} would have only English name (latin).

Is this means that osm dataset has in {name_en} a wrong attribute encode or may be its the produced .mbtiles that is storing in {name_en} the name coming from {name} ?

I was trying to work around a limitation for supporting Arabic in text labels to use {name_en} thinking it would have just the English name.

Thanks

**Comment by ImreSamu** [comment]
name_en =    [name:en](http://taginfo.openstreetmap.org/keys/name:en) the english name  (if available, otherwise same as [name](http://taginfo.openstreetmap.org/keys/name))



the `name`  is the local name - and sometimes mixed languages ..
* https://wiki.openstreetmap.org/wiki/Multilingual_names
* Morocco:   https://wiki.openstreetmap.org/wiki/Multilingual_names#Morocco

**Comment by jirik** [comment]
In case of some objects `name_en` is set to `name` if `name:en` is not defined (this is the case of this node: http://www.openstreetmap.org/node/3215639008#map=14/31.7125/-8.3162). However in case of other objects `name_en` is not set if `name:en` is not defined.

This disunity appears also outside of `place` layer. I am not sure if it was done by purpose. Probably not.

**Comment by jirik** [comment]
https://github.com/openmaptiles/openmaptiles/blob/e406537025ff9229d99957cf575d36d8d2666fe5/layers/place/city.sql#L16

**Comment by jirik** [comment]
@nouryf 
> Is this means that osm dataset has in {name_en} a wrong attribute encode or may be its the produced .mbtiles that is storing in {name_en} the name coming from {name} ?

Both can be correct. If the `name:en` is not defined, then `name` is used.

I have unified rules for `name_en`: https://github.com/openmaptiles/openmaptiles/pull/190
