### ISSUE TITLE
running quickstart -> Error: Postgis Plugin: timeout expired

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/openmaptiles#173]
Hi,

while running "./quickstart.sh germany" the process stopped with "Error: Postgis Plugin: timeout expired":

[quickstart_log.txt](https://github.com/openmaptiles/openmaptiles/files/765817/quickstart_log.txt)

Generating of vector tiles worked before using .quickstart.sh with other extracts (albania and duesseldorf-regbez) and also with zoom level 0 -14. Changes to the successful run before were the use of the germany-extract and modifications in the [water_sql.txt](https://github.com/openmaptiles/openmaptiles/files/765853/water_sql.txt) for the coastlines.

Any idea what causes the timeout?
Thanks!

**Comment by ImreSamu** [comment]
>Any idea what causes the timeout?

my guess:
* Check the postgres service ( logs,  stopped  or not ) ? 
  *  see docker documentation ! 
* Do you have enough disk space for the docker containers ?  
   *  `df -h /var/lib/docker/`

**Comment by pathmapper** [comment]
> Check the postgres service ( logs, stopped or not ) ?

The postgres service was used while running ./quickstart.sh germany before the error appears, right?

After this error I did a run with zoom level min = 0 and max = 9 and this worked for ./quickstart.sh germany.

> Do you have enough disk space for the docker containers ?

Yes:

 -h /var/lib/docker/
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/dm-1       225G    169G   45G   80% /

**Comment by pathmapper** [comment]
I did several runs without the timeout. Seems like it was a temporary local issue.
