### ISSUE TITLE
Using Docker tileserver-gl does not list styles under 'STYLES' but list 'OpenMapTiles' under 'DATA'

### ISSUE THREAD

**Issue by nouryf** [openmaptiles/openmaptiles#174]
Hi,

https://openmaptiles.org/docs/host/tileserver-gl/

I used Docker sequence of commands:
docker pull klokantech/tileserver-gl
docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl

Then opened http://localhost:8080 in browser window.

Under 'STYLES' section no style is listed. Under 'DATA' I have 'OpenMapTiles'. Clicking on it, display the data ok, but no label texts. 

Thanks

**Comment by ImreSamu** [comment]
>https://openmaptiles.org/docs/host/tileserver-gl/
>I used Docker sequence of commands:

Have you downloaded the xxxxxx.mbtiles ? 
*  see  this part :   `curl  https://..... /zurich_switzerland.mbtiles` 


in the openmaptiles  dev environment,  the data int the `./data/tiles.mbtiles`
use the: 
```
./quickstart.sh  
make start-tileserver
```

or modify the directory 
` docker run -it --rm -v $(pwd)/data:/data -p 8080:80 klokantech/tileserver-gl`

**Comment by nouryf** [comment]
Thanks.

I have 'tiles.mbtiles' in ./data folder. The data are displayed ok but not the styles. I just retried the command:
docker run -it --rm -v $(pwd)/data -p 8080:80 klokantech/tileserver-gl

And noticed the following warning/error:
----------------------------------------------------------------------------------------------------
Starting tileserver-gl v1.4.1
No MBTiles specified, using tiles.mbtiles
Automatically creating config file for tiles.mbtiles
Style klokantech-basic requires OpenMapTiles version 3.x but mbtiles is version undefined
Style osm-bright requires OpenMapTiles version 3.x but mbtiles is version undefined
Run with --verbose to see the config file here.
Starting server
Listening at http://:::80/
-------------------------------------------------------------------------------------------------------------------

in The 'data' folder I have two files: the original osm.pbf and tiles.mbtiles that I created using 'OpenMapTiles' docker.

**Comment by ImreSamu** [comment]
>I have 'tiles.mbtiles' in ./data folder. The data are displayed ok but not the styles.
> I just retried the command:
>docker run -it --rm -v $(pwd)/data -p 8080:80 klokantech/tileserver-gl

imho:   You have mixed 2 different tutorial ..

it is important, where is your data ! 

IF  you have  :  `./tiles.mbtiles`
THEN use ˙docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl` 

IF  you have  :   `./data/tiles.mbtiles`
THEN use ˙docker run -it -v $(pwd)/data:/data -p 8080:80 klokantech/tileserver-gl` 


>  I have 'tiles.mbtiles' in ./data folder. 

Just  use  the `make start-tileserver`  ! 
* It is working ?  
* Please add a screenshot ..

**Comment by nouryf** [comment]
I produced the .mbtiles using 'openmapstiles' docker-compose run generate-vectortiles steps and last step was: docker-compose run generate-vectortiles

This went fine and I have tiles.mbtiles that I can display ok and see the tiles using 'mapbox gl js'. Eventually I run into an Arabic text display issue (https://github.com/openmaptiles/openmaptiles/issues/171). In that reference ticket, it was stated that a fix for the issue was committed to tileserver-gl.

So this is the background why I'm trying 'tileserver-gl' to display the data and verify the fix.

To use 'tileserver-gl', I'm using the steps as outlined in https://openmaptiles.org/docs/host/tileserver-gl/

When I execute: 'make start-tileserver', i get the same warning as if I did directly 'docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl'

If I do 'docker run -it -v $(pwd)/data:/data -p 8080:80 klokantech/tileserver-gl', I get an error 'invalid bind mount spec'.

Attached is a screen shot when I execute 'make start-tileserver'. It shows also the browser view without  any 'STYLE' listed.
![screenshot](https://cloud.githubusercontent.com/assets/18246160/22835632/674b36a8-ef87-11e6-9de6-7ba6fe875e9b.png)

**Comment by ImreSamu** [comment]
thank you,

>I produced the .mbtiles using 'openmapstiles' docker-compose run generate-vectortiles 
>steps and last step was: docker-compose run generate-vectortiles

The `./quickstart.sh` contains all configurations  and it should works with `make start-tileserver`

My guess,  that some important post-processing is missing , for example the metadata settings 
see "Add special metadata to mbtiles! " part in the `./quickstart.sh` source code

If you are testing the  latest  "master"  branch 
please use the`./quickstart.sh` source code as a tutorial    and it should works!  
 
We use the `./quickstart.sh`   in the [./travis test](https://github.com/openmaptiles/openmaptiles/blob/master/.travis.yml)  so it is always up-to-date.

**Comment by nouryf** [comment]
Thanks. I followed all the steps as outlined in https://github.com/openmaptiles/openmaptiles
and I did not use './quickstart.sh' as I wanted to see the steps running one by one.
May be the steps as outlined are missing as you mentioned a step for metadata settings ?

It took 4 days to produce the .mbtiles so it would be long to run './quickstart.sh' just for metadata encoding in the .mbtiles... I guess I can't use ''tileserver-gl' for my purpose of testing Arabic fix. I'll wait until that fix is propagated to 'Mapbox gl js' and see if it has the Arabic names truncated as explained in https://github.com/openmaptiles/openmaptiles/issues/171

**Comment by ImreSamu** [comment]
>May be the steps as outlined are missing as you mentioned a step for metadata settings ?

You are right,  the final  metadata creation process is missing.   
Now the https://github.com/openmaptiles/extracts  process do now.
 

The  `./quickstart.sh`  is a simplified workflow for testing and  these command line do this:   
```
echo "====> : Add special metadata to mbtiles! "
docker-compose run --rm openmaptiles-tools  generate-metadata ./data/tiles.mbtiles
docker-compose run --rm openmaptiles-tools  chmod 666         ./data/tiles.mbtiles
```

Or you can use the `openmaptiles-tools` version.  
*   See : https://github.com/openmaptiles/openmaptiles-tools#add-simple-metadata-to-mbtiles-file

**Comment by nouryf** [comment]
Thanks. Should that command also added to https://github.com/openmaptiles/openmaptiles
Just after the following text: ?
-------------------------------------------------------------------------------------------------------------------
: Now you are ready to generate the vector tiles. Using environment variables you can limit the bounding box and zoom levels of what you want to generate (docker-compose.yml).

docker-compose run generate-vectortiles
-------------------------------------------------------------------------------------------------------------------

**Comment by ImreSamu** [comment]
>Will the command be then:
>docker-compose run generate-metadata ./data/tiles.mbtiles

`docker-compose` using the  [docker-compose.yml](https://github.com/openmaptiles/openmaptiles/blob/master/docker-compose.yml) service definition file, and no `generate-metadata` service exist yet.  So probably your command will not work.

if you  want to use docker-compose you have to call from the `openmaptiles-tools` service
`docker-compose run --rm openmaptiles-tools  generate-metadata ./data/tiles.mbtiles`
*  `--rm` =    Remove container after run.
*  SERVICE = `openmaptiles-tools` 
   *  ( https://github.com/openmaptiles/openmaptiles/blob/master/docker-compose.yml#L77 )
*  COMMAND =  `generate-metadata`
   * ( https://github.com/openmaptiles/openmaptiles-tools#add-simple-metadata-to-mbtiles-file )
*  ARGS = `./data/tiles.mbtiles`

see : 
* docker-compose documentation:  https://docs.docker.com/compose/ 
* docker-compose run :   https://docs.docker.com/compose/reference/run/
  *  run [options] [-e KEY=VAL...] SERVICE [COMMAND] [ARGS...]

The `generate-metadata ./data/tiles.mbtiles`  command
*  set BBOX metadata as a planet [  ... -180, 180 .. ]
*  and using the `QUICKSTART_MIN_ZOOM` and `QUICKSTART_MAX_ZOOM`  environment variables for `min_zoom` and `max_zoom`.
see current algorithm:  https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/generate-metadata#L97

if this values not perfect for you, you can modify by any sqlite editor.

**Comment by nouryf** [comment]
Thanks.

I tried the command 'docker-compose run --rm openmaptiles-tools generate-metadata ./data/tiles.mbtiles'

And I got an error:
-----------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 10, in <module>
    from docker.errors import APIError
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 6, in <module>
    import requests
ImportError: No module named requests
-------------------------------------------------------------------------------------------------------------------

using 'SQLiteStudio', I opened another .mbtiles (donwloaded from openmaptiles.org) to look at its metadata table and it has multiple columns (ex. mtime, scheme, format, json, minzoom, maxzoom, id, center, name, bounds, ...).

Is all what is needed here is to add a table named 'metadata' and add at minumum: minzoom, maxzoom and bounds fields with their data ? or I need to replicate all the fields from the example .mbtiles ?

Thanks

**Comment by ImreSamu** [comment]
>I tried the command 'docker-compose run --rm openmaptiles-tools generate-metadata ./data/tiles.mbtiles'
>And I got an error:

imho:  something wrong with your environment.
and I can't replicate.

in my machine : 
```$ docker-compose run --rm openmaptiles-tools generate-metadata ./data/tiles.mbtiles
WARNING: The MIN_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The MAX_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The BBOX variable is not set. Defaulting to a blank string.
Update metadata ./data/tiles.mbtiles
```

Your error maybe a docker-compose related
*  `/usr/local/lib/python2.7/dist-packages/docker/api/client.py`
*  https://github.com/docker/compose/search?q=%2Fusr%2Flocal%2Flib%2Fpython2.7%2Fdist-packages%2Fdocker%2Fapi%2Fclient.py&type=Issues&utf8=%E2%9C%93

so if you are not using the latest docker-compose please upgrade: https://github.com/docker/compose/releases

>Is all what is needed here is to add a table named 'metadata' and add at minumum: minzoom, maxzoom 
>and bounds fields with their data ? or I need to replicate all the fields from the example .mbtiles ?

imho:  it is better to add all fields 
Please check the full code : https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/generate-metadata#L61

**Comment by jirik** [comment]
Closing as stale.
