### ISSUE TITLE
positron style: parks in water layer visible

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/openmaptiles#175]
Hi,

with the positron style starting from zoom level 6 there are several parks visible in the water layer.

Example:
![park_water](https://cloud.githubusercontent.com/assets/20856381/22832537/ae031436-efae-11e6-8122-3949c884eaf7.png)

https://editor.openmaptiles.org/?style=https://rawgit.com/openmaptiles/positron-gl-style/master/style.json#6/53.841/12.338

**Comment by pathmapper** [comment]
These three are the following: 


relation with boundary=national_park:
http://www.openstreetmap.org/relation/1138522

way with leisure=nature_reserve:
http://www.openstreetmap.org/way/178089830


way with leisure=nature_reserve:
http://www.openstreetmap.org/way/178089832
way with boundary=protected_area and leisure=nature_reserve:
http://www.openstreetmap.org/way/178087256


It seems like this is no issue of the vector tiles and style related which could be fixed with changing the layer order. Should I close this here and post it on https://github.com/openmaptiles/positron-gl-style?

**Comment by klokan** [comment]
Thanks for the PR @pathmapper!  Merged.

**Comment by lukasmartinelli** [comment]
Just as sidenote. In certain styles it can make sense to show protected
areas over water e.g. boundary=national_park since there are entire marine
areas around islands that are protected marine national parks.
But then only the outline should be styled.
