### ISSUE TITLE
How can I specify MAX/MIN_ZOOM and BBOX by .env file ?

### ISSUE THREAD

**Issue by tinoue** [openmaptiles/openmaptiles#177]
I added the following lines into .env file.

```
BBOX=7.4090275764,43.7247581482,7.4398708344,43.7519340515
MIN_ZOOM=0
MAX_ZOOM=14
```
Then I did "rm -r ./data; ./quickstart.sh monaco" then cat "data/docker-compose-config.yml". It shows:

```
version: "2"
services:
  generate-vectortiles:
    environment:
      BBOX: " 7.3830115, 43.5163330, 7.5003330, 43.7543525"
      OSM_MAX_TIMESTAMP : "2017-02-12T21:31:07Z"
      OSM_AREA_NAME: "monaco"
      MIN_ZOOM: "0"
      MAX_ZOOM: "7"
```

The MIN/MAX_ZOOM and BBOX I set in .env seems to be ignored. What's wrong ?

**Comment by pathmapper** [comment]
I think there is a "QUICKSTART_" missing for the zoom levels in the .env file:

QUICKSTART_MIN_ZOOM=0
QUICKSTART_MAX_ZOOM=14

I don't know if it is possible to change the BBOX used by quickstart.sh with the .env file. You could try adding also a QUICKSTART_" there.

**Comment by ImreSamu** [comment]
Now  -  only the `QUICKSTART_MIN_ZOOM` and `QUICKSTART_MAX_ZOOM` supported in the `./quickstart.sh`
see:  https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md#change-min_zoom-and-max_zoom

The BBOX calculated from the actual   `.osm.pbf`  file

If you want your own settings -  replace the `-f ./data/docker-compose-config.yml ` 
in the [code]( https://github.com/openmaptiles/openmaptiles/blob/95e4fc5ce5d1661395df577648108d1220efc3c8/quickstart.sh#L258)  to other config file : for example:   `-f ./my-simple openmaptiles-config.yml `

**Comment by tinoue** [comment]
Thanks for your reply. The BBOX set by default tends to be bigger (sometimes 2x mbtiles size) so I'll check your advice.
