### ISSUE TITLE
openmaptiles and openlayers performance

### ISSUE THREAD

**Issue by nejcd** [openmaptiles/openmaptiles#178]
I have downloaded .mbtiles setup tileserver-gl with docker. Provided example at localhost with leaflet looks greate! 

Now I am trying to do it with openlayers, I followed the example code for openlayers. (https://openmaptiles.org/docs/website/openlayers3/). I tried all renderMode (image, hybrid, vector) for ol.layer.VectorTile, to get better performane. But perforomance is not as good as i would like, and defentliy not comaprable wityh leaflet. Does anyone have any suggestions how to improve performance in openlayers with openmapvector tiles ?  

Is it possiable that styling of layer is cause of bed performance:

`fetch('https://openmaptiles.github.io/osm-bright-gl-style/style-cdn.json').then(function(response) {
  response.json().then(function(glStyle) {
    console.log(glStyle);
    olms.applyStyle(layer, glStyle, 'openmaptiles').then(function() {
      map.addLayer(layer);
    });
  });
});`

**Comment by klokan** [comment]
The Leaflet example uses raster tiles...
If you load in OpenLayers the raster tiles too, then you get the same performance as in Leaflet now.

In OpenLayers use XYZ layer and load the server generated raster tiles from TileServer GL.

**Comment by klokan** [comment]
An action on this ticket: improve documentation of "openlayers" section - mention it is possible to load the raster tiles.

**Comment by nejcd** [comment]
Aren't .pbfs vector tiles (http://localhost:8080/data/v3/9/278/181.pbf?style=klokantech-basic) ?

**Comment by jirik** [comment]
Yes, but you can use raster tiles instead served by [tileserver-gl](https://github.com/klokantech/tileserver-gl). [Leaflet example](https://openmaptiles.org/docs/website/leaflet/) uses raster tiles served in this way.

**Comment by jirik** [comment]
Yes, but you can use raster tiles generated by [tileserver-gl](https://github.com/klokantech/tileserver-gl). Leaflet example at [Viewers page](https://openmaptiles.org/viewers/) uses these raster tiles.
