### ISSUE TITLE
Alternative projections (4326 / WGS84; LAEA Arctic etc)

### ISSUE THREAD

**Issue by MattBlissett** [openmaptiles/openmaptiles#179]
Hi,

Thanks for all the work on this project, it's been a huge help.

I've been working on creating vector tiles in other projections.  Initially, EPSG:4326 (WGS84 plate carée), with the aim also to have one or more LAEA Arctic projections (at least EPSG:3575, maybe others from 3571..3576) and an Antarctic one (probably EPSG:3031).

Here's an example of EPSG:4326 — only Norway is rendered beyond zoom level 4: http://maps.labs.gbif.org/base/4326/

Producing that required:
* Setting the database to use 4326, and importing the data in that projection
* Regenerating the OSM border in 4326
* Changing layer definitions to have measurements in degrees or square degrees, rather than metres or square metres. Measurements are used in area filters, tolerances and simplification parameters.
* Using Tilestache instead of Tilelive to produce the tiles.  I found [a comment](https://github.com/mapbox/tilelive-mapnik/issues/89) saying Tilelive didn't support non-Mercator projections, Tilestache does, though some similar metres/degrees assumptions needed changing.

Adapting the docker images and scripts so the database is *either* Mercator or WGS84 would be more work, and would make the scripts more complicated.  *Unless anyone is particularly interested in having this in the OpenMapTiles repository, I'll work with forks of the components. Please let me know if you would be interested!*

Our plan is to generate the tiles once, and share the result, but we generally won't need to regenerate them unless national borders change. They'll be used on pages like this: https://demo.gbif.org/species/2441055

Thanks!

**Comment by klokan** [comment]
Thanks for the message and report of progress on your side @MattBlissett 

We do already generate the vector tiles in different spatial reference systems with the existing OpenMapTiles workflow, schema and dockers. There is no need to switch the renderer, adapt the schema or change any of the components. All the open styles are even directly reusable!

All what must be done is to reproject the imported data into an appropriate Proj4 defined SRS in Posgres and run the rendering of the vector tiles.

We are going to release the OpenStreetMap world tiles in EPSG:4326 soon, if people are interested...
First version was done already in November last year.

See a preview:
![img1](https://pbs.twimg.com/media/CzAgutwXUAEDhQE.jpg "img1")
![img2](https://pbs.twimg.com/media/CzAgvs1XgAA5lW9.jpg "img2")
![img3](https://pbs.twimg.com/media/CzAgwSIWgAEkE9j.jpg "img3")

On request (if people cover a few working hours on our side) we can render vector tiles of any part of the world in any coordinate system of choice and document the workflow:
https://openmaptiles.com/different-coordinate-systems/

**Comment by wootapa** [comment]
Thanks for an awesome project. I've used the docker approach and successfully generated the mbtiles. I then reprojected to EPSG:2019 successfully and tried generating again, but tiles.mbtiles is empty. In QGis the projection is detected and looks ok. Any hints or additional steps that needs to be taken?
