### ISSUE TITLE
Missing islands in Finland near Oulu city

### ISSUE THREAD

**Issue by MartinMikita** [openmaptiles/openmaptiles#182]
There are some islands in OpenStreetMap missing in our vector tiles.

![screenshot 2017-03-06 at 19 17 30](https://cloud.githubusercontent.com/assets/2283182/23623259/b2dd9692-02a1-11e7-9474-1171e49d0828.png)

https://www.openstreetmap.org/way/241082668

Probably related with #167

**Comment by jirik** [comment]
Private note: fix probably by adding `- wood` to `natural`
https://github.com/openmaptiles/openmaptiles/blob/a6353e2360193d16cbdb563fd9a6e3e28e77382a/layers/landcover/mapping.yaml#L78 and check/edit SQL

**Comment by jirik** [comment]
Fixed by 70170b2e54194ec922781c6b6fd4df52a62bbd07
