### ISSUE TITLE
Country layer needs cleanup

### ISSUE THREAD

**Issue by jaakla** [openmaptiles/openmaptiles#195]
See attached image (zoom 5, data file osm-2017-01-23-planet.mbtiles) - I think no people (except  Vít Jedlička perhaps) would put country called **Liberland** to the map. I suggest to use more stable source for countries than OSM - this is known to have such vandalism from time to time and it is highly visible in county level. It can be politically extremely sensitive.

![screen](https://www.dropbox.com/s/r2iq9liugn2gwhg/Screenshot%202017-03-21%2022.48.38.png?dl=1)

**Comment by lukasmartinelli** [comment]
> See attached image (zoom 5, data file osm-2017-01-23-planet.mbtiles) - I think no people (except Vít Jedlička perhaps) would put country called Liberland to the map. I suggest to use more stable source for countries than OSM - this is known to have such vandalism from time to time and it is highly visible in county level. It can be politically extremely sensitive.

Vandalism is a problem - nonetheless it is the best source for multilingual labels for countries.
Changes to cities are monitored for vandalism - but it is hard.

However if someone would provide a stable list of countries in the spirit of OpenStreetMapData, very welcome.

**Comment by jaakla** [comment]
We've been using own compiled Natural Earth data for example to resolve similar issues, with manual mix from OSM for labels if needed. Additional method to resolve it would be to fix it in your database and stop automatic updates for certain critical zooms and layers. Countries do not change that often.

**Comment by jaakla** [comment]
ps. Do you have multilingual labels in your tiles?

**Comment by lukasmartinelli** [comment]
> We've been using own compiled Natural Earth data for example to resolve similar issues, with manual mix from OSM for labels.

Make sure you comply to the ODBL regarding mixing data 😉

**Comment by klokan** [comment]
Fixed in v3.6 - OpenStreetMap database has been corrected.

**Comment by klokan** [comment]
Fixed in v3.5 release - OpenStreetMap database has been corrected.
