### ISSUE TITLE
Improve roads on zoom 7

### ISSUE THREAD

**Issue by MartinMikita** [openmaptiles/openmaptiles#200]
Transportation layer showing roads on zoom 7 is now filtering only `motorway` and `trunk` type.
In some countries (for example France, Slovakia) there are large gaps between large roads.

It could be better to display already `primary` type on zoom 7, and try to merge them together with `motorway` and `trunk` roads.

**Comment by stirringhalo** [comment]
Can you show a specific case?

**Comment by klokan** [comment]
https://openmaptiles.github.io/osm-bright-gl-style/#7.9/48.146/-3.536

**Comment by stirringhalo** [comment]
See https://github.com/openmaptiles/openmaptiles/pull/213 . I will be generating a whole bunch of PRs and then reviewing them all at once.
