### ISSUE TITLE
Generalize and merge landcover layer on zoom 8-9

### ISSUE THREAD

**Issue by MartinMikita** [openmaptiles/openmaptiles#201]
Merging landcover and simplify geometry could decrease tile size and MBTiles size.

Landcover layer is now very detailed on zoom 8 and 9

**Comment by stirringhalo** [comment]
Do you have any ideas of how to tackle merging? Drop small features?

**Comment by jirik** [comment]
We can 
- merge (st_union) adjacent polygons of the same type
- generalize it's borders
Question is performance of st_union on a huge number of features - this should be tested.

**Comment by stirringhalo** [comment]
I already took a similar approach for building merging, and it was impossibly slow. See https://github.com/openmaptiles/openmaptiles/pull/64

Though, it may be more achievable here with less features in landcover at z8 and z9.

Another option, use Zres to drop features that are too small. https://github.com/mapbox/postgis-vt-util

**Comment by stirringhalo** [comment]
Need to reassess this in light of the ZRes support which changes the detail levels at all zooms.

**Comment by klokan** [comment]
Related to ZRes #210 - let's make minimal changes in this regards now.

Merging and improved generalisation of the deeper zoom levels 8 and 9 on landcover a future milestone.

**Comment by jirik** [comment]
Features that are too small are already dropped by sql_filter. See https://github.com/openmaptiles/openmaptiles/pull/214/files#diff-f445439c8566a0be9ddf94270afa8f15, https://github.com/openmaptiles/openmaptiles/commit/a68ccc42ee174ecfce37a3dcd18bc2d0fb9f0641#diff-f445439c8566a0be9ddf94270afa8f15
Another try can be merging.

**Comment by stefanb** [comment]
This would also improve areas (rendering appearance+tile size) composed of adjacent landuse polygons, such as https://openmaptiles.org/languages/sl/#8.85/46.5131/14.7148 :
![image](https://user-images.githubusercontent.com/319826/36680820-23b95b6a-1b17-11e8-94b5-fda3c793cb5f.png)
These are 2x3km rectangles which seems that are simplified individually which separates them visually, despite sharing the borders. Example of such rectangles:
* https://www.openstreetmap.org/relation/6761884
* https://www.openstreetmap.org/relation/6829692

It has an effect also on other levels:
* level 7-8: the individual 2x3km polygons are too small to be shown (if they would be merged they would be big enough to be included and shown)
* level 9-14: some parts are too small to be included, emphasising the rectangle borders, eg https://openmaptiles.org/languages/sl/#13.95/46.25591/14.95119 (zoom in just slightly to level 14+ to hide the rectangle border): 
![image](https://user-images.githubusercontent.com/319826/36682322-15faee04-1b1b-11e8-92a7-5f1aef2f360d.png)

These 2x3km rectangles are the result of landuse import: https://wiki.openstreetmap.org/wiki/Slovenia_Landcover_Import_-_RABA-KGZ which tries to keep the polygons in manageable sizes for human editors (reducing chances of conflicts, keeping OSM objects

**Comment by TomPohys** [comment]
Merging of landcover was done in https://github.com/openmaptiles/openmaptiles/pull/1035. Simplification was done by [Visvalingam-Whyatt algorithm](https://postgis.net/docs/ST_SimplifyVW.html). For zoom level 7 to 9 there is merging of all adjacent polygons. For zoom levels 10 - 13 there is a selection of polygons based on a number of edge points, which determines the demands of the polygon. Statistics in PR https://github.com/openmaptiles/openmaptiles/pull/1035.
