### ISSUE TITLE
Needed map zoom to do Generating?

### ISSUE THREAD

**Issue by joaokho** [openmaptiles/openmaptiles#203]
Hi,

I'm process own Australia data to osm format and then become aus.osm.pbf.
Because it's too large, so i try to process/generate tile level 0-5, and then level 10.
When i try it's already cover to zoom level 20?

So, I'm here want to make sure, if I want to serve map level from 0-20, which level
need to generating?

I'm still configure to configure same layer, that not shown correctly like (cadastre layer)
before using osm2vectortiles , i already success to configure all layer shown correctly,
because still new in openmaptiles, i don't know how to configure it, because I run tileserver
using docker, so I don't know how to change the layer setting that inside docker image (cmiiw)

Thank in advance.

Best Regards, 
Joao Kho

**Comment by stirringhalo** [comment]
> So, I'm here want to make sure, if I want to serve map level from 0-20, which level
need to generating?

If I understand correctly, you need to render at least 0-14. Depending on the server, it will "over-zoom" the data and show the previous zooms at the higher zooms. IIRC, POIs are at the lowest zoom.

**Comment by jirik** [comment]
Yes, level 14 contains "everything" - meaning there are no other features that will appear at higher zoom levels.
