### ISSUE TITLE
feature request: region-specific zooms

### ISSUE THREAD

**Issue by kodonnell** [openmaptiles/openmaptiles#204]
It would be nice to be able to specify varying zoom levels across the map - for example, I want to render a specific country to zoom level 19, but I also want the rest of the world visible in the map - though that may only need to be to zoom level 4. (So when you zoom far out on the country, it's place in the world map is visible.)

If I had heaps of resource, I'd just do the entire planet at zoom level 19 (I'm trying it now, to see how long it'll take.)

I have the feeling this may be a common use case - but I also am pretty new to this stuff, so I might be missing something obvious. There may be different ways of achieving this too - I imagine one could do it easily enough in the database queries, but you could also e.g. run the full world at zoom level 4, and the specific country at zoom 19, and then somehow merge the .mbtiles . (Oh - found [this](https://jeromegagnonvoyer.wordpress.com/2015/08/06/merging-multiple-mbtiles-together/).)

**Comment by jirik** [comment]
For achieving this, you still need to download and import the whole OSM planet that takes some time. But if you do it, then you can now in three steps:
- render the whole planet for zoom levels 0-4
- render the region for 5-14**
- merge two output .mbtiles

Even now, if you use quickstart and render only specific region, you get some basic features at lower zoom levels for the whole world (e.g. water, country boudaries). These features come from another sources like Natural Earth.

** OpenMapTiles are used to render only till zoom level 14 (there are no other features that will appear at higher zoom levels).

**Comment by kodonnell** [comment]
Unless there's great demand for it, the above solution is fine, so I'll close this issue for now. (I'll test it myself, and report back if it doesn't work.)

> there are no other features that will appear at higher zoom levels

Sorry - does this mean you ignore some information, or that all information is included as zoom level 14?

**Comment by jirik** [comment]
Well, not all information is included at zoom level 14 (it is not 1:1 copy of OpenStreetMap), but we are encoding every feature at zoom level 14 that we want to show even at higher zoom levels. So, if you render tiles for higher zoom levels, you will probably not find there any extra features that you would not find at zoom level 14.

**Comment by pathmapper** [comment]
> For achieving this, you still need to download and import the whole OSM planet that takes some time. But if you do it, then you can now in three steps:

> render the whole planet for zoom levels 0-4
> render the region for 5-14**
> merge two output .mbtiles

@jirik, what do you mean exactly with "merge"?
Reference the two output .mbtiles in one style or "really" merge them, so the output is one .mbtile?
If you mean the latter, how to merge two .mbtiles?

**Comment by jirik** [comment]
@pathmapper I meant merging mentioned by @kodonnell : https://jeromegagnonvoyer.wordpress.com/2015/08/06/merging-multiple-mbtiles-together/
@MartinMikita knows more about merging .mbtiles
