### ISSUE TITLE
Missing tiles for unpopulated areas

### ISSUE THREAD

**Issue by jaakla** [openmaptiles/openmaptiles#206]
I'm using osm-2017-01-31-planet.mbtiles (seems to be the latest right now?). It does not have all world tiles, two examples:
a) tile URL 8/100/63 should be `zoom_level=8 and tile_column=100 and tile_row=192`. It is [around here](http://bboxfinder.com/#66.581034,-37.908325,67.009574,-36.727295) , in Greenland. 
b) tile URL 10/405/280  should be `zoom_level=10 and tile_column=405 and tile_row=192`, this is somewhere in the ocean.

There seems to be pattern that empty areas are skipped in the database. Also free-0.tilehosting.com seems to give 404 for same tiles, and your "Inspect" function with mapbox-gl shows white map for both locations. 

How do you suggest to render these locations? I could use some color fill these tiles, but I don't know which case there is - desert or ocean and in usual maps these should be rendered differently.

**Comment by sfkeller** [comment]
Just to be sure: I assume you are aware that there are plenty of empty tiles when there's nothing new above maskLevel (here: 8, as announced in the metadata .json)? 

P.S. Welcome here, Jaak, at OpenMapTiles! Are you using it at Nutiteq?

**Comment by jaakla** [comment]
Ok, this should explain. BTW, https://free.tilehosting.com/data/v3.json?key= does not have the maskLevel set, maybe this the reason why online tiles (including your own client) gives white map for the greenland desert?

**Comment by klokan** [comment]
@jaakla thanks for reporting this issue.

On the free.tilehosting.com is now the latest v3.5 version of the world rendered just during last week, exactly for the purpose to discover the problems like this end ensure we fix our new cluster based rendering workflow which runs also with weekly updates - before we announce the data and make it available in production hosting and for download.

Missing `maskLevel: "8"` at https://free.tilehosting.com/ with latest data should be now fixed.
Our process is improved now - so the new MBTiles and extracts should not have this problem anymore.

**Comment by jaakla** [comment]
Not sure if it is related to same, but the iOS app has (still) similar issue - when you zoom into the open ocean, then it ends up with white map.

**Comment by jaakla** [comment]
Can you explain a bit more how the maskLevel exactly works in your implementation, is there 'official' spec for it ? One way to understand is that server/file should have all the tiles up to maskLevel (zoom 8), and if tile is e.g. zoom 9 and contents is exactly same as parent tile in zoom 8, then the tile in zoom 9 is redundant and is removed. Currently I see that also zoom 7 does not have all the tiles in planet mbtiles (should have 16384, has 16363), and zoom 8 has quite a bit missing (should have 65536, has 52516; including the missing tile 8/100/63 in Greenland I mentioned above). Also, it seems that corresponding zoom-8 tile of missing tile is not always the same as the missing tile, especially for the land cases; for sea case I have not seen issues with this.

**Comment by daliborjanak** [comment]
This is fixed now in today's dataset.
