### ISSUE TITLE
MAX_ZOOM vs QUICKSTART_MAX_ZOOM

### ISSUE THREAD

**Issue by kodonnell** [openmaptiles/openmaptiles#208]
I've followed [this](https://openmaptiles.org/docs/generate/generate-vector-tiles/) tutorial - all I'm running is

```sh
# MIN_ZOOM=0 MAX_ZOOM=14 ./quickstart.sh new-zealand
```

However, when viewing the tiles (as per [here](https://openmaptiles.org/docs/host/tileserver-gl/)), I don't to be seeing anything detailed - e.g. most of the roads aren't displayed. In addition, the mbtile file is only around 300kb - and this size doesn't change much when I change `MAX_ZOOM` to e.g. `10`. Both seem to indicate that I'm somewhow missing high-zoom data - is this correct? If so, how to fix it? It's entirely possible I may have done something silly ...

Output: [EDIT: deleted as it took a lot of space and wasn't relevant]

**Comment by tinoue** [comment]
Use QUICKSTART_MAX_ZOOM in .env

**Comment by kodonnell** [comment]
Ah - OK, will try that. Should I leave this open as a bug, as it doesn't seem to align with the documentation? Will remove the above log output ...

**Comment by tinoue** [comment]
It is documented in QUICKSTAR.md
I asked similar question in issue #177 :-)

**Comment by kodonnell** [comment]
Good point - but `MAX_ZOOM` also appears (confusingly). And, when you run the script, it complains if `MAX_ZOOM` is not set, which again is confusing if it's meant to be `QUICKSTART_MAX_ZOOM`.

**Comment by ImreSamu** [comment]
@kodonnell 
I will try to refactor the `MAX_ZOOM` vs `QUICKSTART_MAX_ZOOM`  problems, and fix some design problems.  (  this part was written by me and it was a quick&dirty bottom-up style design.)

**Comment by kylebarron** [comment]
Was this ever resolved?

**Comment by eva-j** [comment]
It seems like it was not. Feel free to make pull request.

**Comment by TomPohys** [comment]
Close by #915
