### ISSUE TITLE
Housenumber points optimization

### ISSUE THREAD

**Issue by edpop** [openmaptiles/openmaptiles#209]
Hello.
I want to share my thoughts about the `ST_PointOnSurface` function.
I got some stats from buildings of by region.

```sql
SELECT is_simple, count(*)
FROM (
  SELECT ST_NPoints(the_geom) = 5 AS is_simple
  FROM building
) t
GROUP BY is_simple
```
Quadgranular polygons: 299 095, other: 43 439.
The `ST_Centroid` function is good for quadgranular polygons with exeption of some rare cases of buildings like:
![housenumber](https://cloud.githubusercontent.com/assets/13479292/24786924/5421f09c-1ba8-11e7-97f5-136a344e1587.png)
So i tested the speed of two queries:
```sql
SELECT count(p)
FROM (
  SELECT CASE WHEN ST_NPoints(the_geom) = 5
           THEN ST_Centroid(the_geom)
           ELSE ST_PointOnSurface(the_geom)
         END AS p
  FROM building
) t
```
vs
```sql
SELECT count(p)
FROM (
  SELECT ST_PointOnSurface(the_geom) AS p
  FROM building
) t
```

Result: 6.5s vs 34.5s.

More accurate way (if you want) is:
```sql
SELECT count(p)
FROM (
  SELECT CASE WHEN ST_NPoints(ST_ConvexHull(the_geom)) = ST_NPoints(the_geom) -- there is not ST_IsConvex function, so...
           THEN ST_Centroid(the_geom)
           ELSE ST_PointOnSurface(the_geom)
         END AS p
  FROM building
) t
```
Time: 8.4s.

What do you think?

**Comment by jirik** [comment]
@edpop Thanks, this makes perfect sense to me. It would be great if you can prepare a pull request.
I think the first method is sufficient:
```sql
SELECT count(p)
FROM (
  SELECT CASE WHEN ST_NPoints(the_geom) = 5
           THEN ST_Centroid(the_geom)
           ELSE ST_PointOnSurface(the_geom)
         END AS p
  FROM building
) t
```

**Comment by stirringhalo** [comment]
@edpop  Nice! Any samples of the difference in housenumber appearance on a complex building?

**Comment by edpop** [comment]
I deployed this housenumbers today on development and compared with production: there is no **any** difference. It can be only on non-convex quadgranular buildings, but I did not found no one. Unfortunatelly, I'm on holidays for two weeks since today, so I can't show you even a screenshots (of two equal maps) for now.

**Comment by edpop** [comment]
I think this trick is useful for POI too, because poi_polygon are buildings in most cases. So maybe we need a common function somewhere, something like _common.FastPointOnSurface_.

**Comment by lukasmartinelli** [comment]
This is an amazing observation @edpop!
I recommend you make a PR to https://github.com/mapbox/postgis-vt-util/blob/master/src/ToPoint.sql.
so all projects doing point calculations benefit!

We recently changed in this project from `ToPoint` to `ST_PointOnSurface` #48 #136 but one could switch back for this reason.

**Comment by stirringhalo** [comment]
As a note, I moved Postgis-vt-utils earlier, into the Postgis docker images so that it may be used for ZRes in https://github.com/openmaptiles/openmaptiles/pull/214

**Comment by stirringhalo** [comment]
@edpop Would you like to add the PR to https://github.com/mapbox/postgis-vt-util/blob/master/src/ToPoint.sql ?

**Comment by edpop** [comment]
I'll do it after next week, when I get out of holidays.
It will be something like _building_to_point_ separate function.
The most direct solution for all objects would probably be if there was a `ST_IsConvex` function in postgis.

**Comment by stirringhalo** [comment]
No worries! Other option is we could simply have a custom function in the housenumber SQL as our case is not completely generic.

**Comment by stirringhalo** [comment]
@edpop Would you rather put the SQL logic into the buildings SQL? That way it's easier for us to manage and update? It will probably be slow getting Mapbox's attention :bat: :flashlight:

**Comment by stirringhalo** [comment]
Done, thanks!!

**Comment by lukasmartinelli** [comment]
Oh but I did merge it into postgis-vt-util.
It is now part of the ToPoint function.

**Comment by stirringhalo** [comment]
@lukasmartinelli  True, but the advantage of the approach here is no assumption is made that 5 point polygons are simple. Buried in postgis-vt-util it may lead to gotchas where the function is being applied to polygons which may not fit the assumption that 5 points = simple polygons.
The Convex Hull algorithm is Graham Scan, which is rather cheap and doesn't add much overhead for some small guarantees.

**Comment by lukasmartinelli** [comment]
> Buried in postgis-vt-util it may lead to gotchas where the function is being applied to polygons which may not fit the assumption that 5 points = simple polygons.

Yep we went with the consideration that it is good enough for default labelling purposes.
It doesn't guarantee you the best label position. You have to fallback to `ST_PointOnSurface` explicitly if you want that (or preferably get your own nice labelling point data set).
