### ISSUE TITLE
Multilingual vector tiles

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#211]
We want to add support for several languages to have them directly included in the vector tiles.

Priority is the most used languages (maybe 30 or 40?) according to https://taginfo.openstreetmap.org/search?q=name%3A and especially all European languages: http://publications.europa.eu/code/en/en-5000800.htm in this phase. Later (next release) we can add more.

We will use the fact that if a key has a value set to `null` it is not added into the vector tiles. The attributes for each language are therefore going to be present in a vector tile only if there are place names in OSM.

Fallback and definition of order of preference for label language must be implemented in the GL style. This should be possible with the Existential filters: https://www.mapbox.com/mapbox-gl-js/style-spec/#types-filter - but we must test it.

With this approach the tiles will by default contain all languages - and will be directly usable. No need to have a new logic on the server side (like the required JSON decoding in WikiMedia maps).

If people are interested in minimizing the vector tiles for their maps or use on mobile apps, we have developed the [TileShrink](https://openmaptiles.com/tileshrink/) utility - which removes from vector tiles all layers, features and attributtes which are not used by a given JSON GL style at different zoom levels.
This utility will run very well on the proposed language attributtes too.

Let's implement a first sample language set this way - modify a GL style - to verify the whole proposed workflow here is correct.

**Comment by go2coffee** [comment]
Hi, is Chinese considered to be included in V3.6 as well? If not, is there ETA for us as a reference?

**Comment by jirik** [comment]
@go2coffee We would like to, but it is not sure now. I will start to work on this issue next week. If you are willing to cover some costs of implementing Chinese, please contact us at info@klokantech.com

**Comment by jirik** [comment]
Work in progress: https://github.com/klokantech/openmaptiles/tree/multilinguality

**Comment by lukasmartinelli** [comment]
> Priority is the most used languages (maybe 30 or 40?) according to https://taginfo.openstreetmap.org/search?q=name%3A and especially all European languages: http://publications.europa.eu/code/en/en-5000800.htm in this phase. Later (next release) we can add more.

> If people are interested in minimizing the vector tiles for their maps or use on mobile apps, we have developed the TileShrink utility - which removes from vector tiles all layers, features and attributtes which are not used by a given JSON GL style at give zoom levels.

This needs to be combined with some shrinking/shaving utility.
30 fields in the vector tiles containing languages will make the vector tiles for places explode.

btw. website seems to be down https://openmaptiles.com/tileshrink/

**Comment by stirringhalo** [comment]
@jirik Looks amazing! I wouldn't worry about the tileshrink utility yet. Check tile sizes with https://github.com/stirringhalo/tile_size to see how bad the situation is.

**Comment by jirik** [comment]
First tests with about 50 languages show about 2% increase of .mbtiles size that seems acceptable (Belgium Z0-12).

Example of both latin and nonlatin names in one map. First row is name:cs if available, otherwise name:latin. Second row is name:nonlatin.

![screenshot_20170511_130116](https://cloud.githubusercontent.com/assets/2271850/25946484/a38a9478-364b-11e7-8ce9-c110f5e3ab55.png)

**Comment by sfkeller** [comment]
I'm looking at your nice work from a OSMNames and a more generic perspective. At least in OSMNames we're going to add translations from Wikidata sooner or later. In general I'd expect a higher increase. 

BTW slightly related to this issue: Are you aware that the buffer for labels/names outside tiles seems to be more than the size of a tile (buffer =~ 1.5 * tile_width )?

**Comment by lukasmartinelli** [comment]
> First tests with about 50 languages show about 2% increase of .mbtiles size that seems acceptable (Belgium Z0-12).

It depends whether you actually have 50 distinct values for these translations or whether all features have the same latin/nonlatin fallback value.

**Comment by lukasmartinelli** [comment]
> BTW slightly related to this issue: Are you aware that the buffer for labels/names outside tiles seems to be more than the size of a tile (buffer =~ 1.5 * tile_width )?

Place labels need a very large buffer since they are most prone of cut off labels. We have tried less/more before. 128px seems to be a good balance.

**Comment by sfkeller** [comment]
![omt_pfaffikon_z12_5_m100000](https://cloud.githubusercontent.com/assets/43340/25999627/2286e594-3726-11e7-858b-a390277837ea.gif)
At last place has been increased to 256 https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/place.yaml . Looking at the labels the buffer seems like 384...

**Comment by jirik** [comment]
We increased the buffers during v3.5 rendering to minimize issues with cut off labels at raster tiles' borders. I do not remember numbers, but it did not increased size of final MBTiles dramatically.

Most places do not have 50 distinct values for name. Furthermore, fallback for language attributes like name:cs is in style, not in .mbtiles. Meaning if there is no name:cs tag, then there is no name:cs attribute in mbtile. I will add documentation when this is finalized.

@sfkeller Actually adding translations from Wikidata sounds really good. It will mean bigger size of mbtiles - question is, how big will be the difference. Do you have an idea when this is going to happen?

**Comment by sfkeller** [comment]
> Do you have an idea when this is going to happen?

Joining Wikidata translations to OSMNames? I don't know. I don't expect it this year anymore.

**Comment by jirik** [comment]
Some notes about languages. This change introduces
* names in 57 languages covering Europe languages + major world languages
* `name:latin` and `name:nonlatin` attributes
* `name_int` attribute

Language attributes come directly from [name:&lt;lg&gt;](http://wiki.openstreetmap.org/wiki/Key:name) OSM tag (for example `name:cs` or `name:en`). For these languages there is no fallback in the data for name in another language even if available. In other words, if there is no `name:cs` tag, there is no `name:cs` attribute. However you can create fallback to another name by GL style.

Attribute `name:latin` comes from `name:en`, `int_name`, or `name` if it contains at least one [a-z] character. Attribute `name:nonlatin` comes from `name` if it does not contain any [a-z] character.

Attribute `name_int` comes from `int_name`, `name:en`, or `name`.

Attribute `int_name` is considered to be filled in most cases. On the other hand, 57 language attributes + `name:latin` and `name:nonlatin` are expected to be missing in many cases, so if you use them, you should create appropriate fallback in GL style. As a fallback values you can consider `name`, `name_int`, or `name_en` (do not confuse with `name:en`).

**Comment by lukasmartinelli** [comment]
> Language attributes come directly from name:<lg> OSM tag (for example name:cs or name:en). For these languages there is no fallback in the data for name in another language even if available. In other words, if there is no name:cs tag, there is no name:cs attribute. However you can create fallback to another name by GL style.

Just saying - for getting good enough  translation coverage you really want the labels from wikidata since OSM is much more hesitant to adding translations if there is no ground truth evidence for it.

**Comment by jirik** [comment]
@sfkeller @lukasmartinelli Thanks for mentioning Wikidata. Just created separate ticket: https://github.com/openmaptiles/openmaptiles/issues/251

**Comment by ashutoshmimani** [comment]
would be good to have the documentation at https://openmaptiles.org/schema/ updated to indicate availability of name:latin and name:nonlatin also. and also specify the right fallback order from which name_en, name_de, name:latin, name:nonlatin are selected.

**Comment by DoktorDrehAmRad** [comment]
Hello, is there a documentation of the current state of multilangual settings? 
I was trying to get a map to dipslay in Italian and English at the same time but I do not seem to manage that with the three settings lang langAlts and langLatin. 
Thank you!

**Comment by klokan** [comment]
Review the code of:
https://github.com/klokantech/openmaptiles-language
or https://openmaptiles.org/languages/

Try: https://cloud.maptiler.com/customize/#basic/1.45/0/11.2
set the language, save the style, download it as JSON and have a look there

Feel free to prepare a more friendly documentation for beginners - and link it from here.
It would be for sure welcome by the community...

**Comment by mits003** [comment]
I have a question about the data source of the name of the places.

Dose it use any datasource other than OSM nor wikidata?

When it comes to Japanese, there are chinese character and latin are shown.
Even though, if it's same chinese character express but pronunciation (same as latin) are not the same.
ex. 日本 is sometimes 'nippon' and sometimes 'nihon'

I found a wrong latin label is shown in OpenMapTiles but there were no latin tag in OSM.
So, I'd like to make sure the data source.
