### ISSUE TITLE
Planet with all data but fewer zoom levels

### ISSUE THREAD

**Issue by buntin** [openmaptiles/openmaptiles#212]
I have a unique requirement to have global coverage of OSM data on a local machine without running a tile server.  I really like your project.  I can unpack your mbtiles and render the pbf files just fine in my client.  However, unpacking your planet file is not going to work :)

My thought is to create my own planet z0-z12 file that still contains most of the layers in your z0-z14 file.  I don't need POIs or housenumbers so I would take them out.  The unpacked pbfs would be much more manageable and still contain all of the data I need.  I assume I can just modify the SQL a bit and leave the imposm3 mappings alone.

So, my questions.  Is it as simple as I think it is?  Is this a terrible idea?

**Comment by stirringhalo** [comment]
All you need to do is take out the layers out of https://github.com/openmaptiles/openmaptiles/blob/master/openmaptiles.yaml, change the max zoomand then rerun quickstart.sh with the planet.pbf!

**Comment by buntin** [comment]
Ah, I left out an important detail. I want all of the data that would be included in the z14.  Basically packing my z12 with finer resolution data than normal.  I suppose my renderer will have to work harder but this will be run on high quality machines and speed isn't critical.  Thoughts on that?

**Comment by stirringhalo** [comment]
Hmm, interesting but may be difficult. Your tile sizes at z12 will be pretty high as you are including much more detail than is typically shown, so it may slow down the viewing (though you aren't too concerned, but something to think about).

An easier approach is to ignore z14, and move the detail higher (z12 or so). That way, you only have approximately 16,777,216 files as opposed to 268,435,456 tiles on disk (without subtracting empty ocean tiles, probably about 70%).

But a bigger issue is...

Why the interest in unpacking tiles? The big problem is, you will run out of inodes on your file system long before you run out of space. On my standard EXT4 file system of 86GB, I can store 5,709,824 files (well inodes, but same idea). So, I'd actually run out of inodes long before I run out of space holding the <50GB file(s). The total space on disk for individual tiles should be about the same as the equivalent mbtiles. Removing the POIs or housenumbers won't change that as you still have the same number of files. You can create filesystems with a bigger inode capacity given the same filesystem size, but then you tend to have more overhead and thus waste.

**Comment by MattBlissett** [comment]
I recommend not unpacking tiles to a filesystem — I accidentally generated all of zoom 12 during some testing, and then I could only read them back from the disc at about 30/second, so it was quicker to re-render them.  (4TB disc, ext4, 244M inodes).

I've had "rm -rf" running over the weekend, and it's still running...

mb-util may be useful for experimenting: https://github.com/mapbox/mbutil/blob/master/mb-util

**Comment by buntin** [comment]
Thanks for the suggestions and comments.  The client is not requiring the tiles be unpacked.  They do not want dependencies like apache, php, node, etc on their system because of the extra approvals and configurations they require.  Every dependency is a battle with them.  I haven't been able to find a simple way to get the tiles from an mbtiles db into the browser without such dependencies.  That's why the "unpack to filesystem" solution is so attractive to them.  I should also mention this is all running on Windows :)

@MattBlissett Thanks for the input but I'm thinking our NTFS SSDs should easily handle the over 16 million files that will be generated.

So I think I'm going to try moving the z14 detail up to z12.  I'll let you know how it goes.  I assume I just need to modify the SQL for each layer.  Is that right?

**Comment by stirringhalo** [comment]
> So I think I'm going to try moving the z14 detail up to z12. I'll let you know how it goes. I assume I just need to modify the SQL for each layer. Is that right?

Yep

**Comment by musicformellons** [comment]
@buntin Just curious, how did it go?

**Comment by buntin** [comment]
I was able to convince the client to embed a tiny web server [CivetWeb](https://github.com/civetweb/civetweb) to serve up the mbtiles.  So unpacking the tiles was no longer necessary.  I'd still like to try what was discussed in this thread however it's fallen very far down on the priority list.
