### ISSUE TITLE
Don't use length filters in waterway.sql

### ISSUE THREAD

**Issue by pnorman** [openmaptiles/openmaptiles#22]
In general length filters don't work because a waterway can be split into multiple parts without changing the meaning. When you use a length restriction, you get parts of the waterway not rendering.

As an example, in London much of the Thames is in sections under 1km long, and the z8 length restriction is 10km, which is 6% of a tile. Even closer to the water, the sections are still under 10km.

**Comment by stirringhalo** [comment]
From what I can see this is resolved?
