### ISSUE TITLE
Consider merging separate import images

### ISSUE THREAD

**Issue by stirringhalo** [openmaptiles/openmaptiles#220]
What are the thoughts of moving much of the import steps to be part of the tile schema? 

I'm not a huge fan of these import steps as:
a) They hide the schema for those layers away from the user. A user cannot easily modify how these layers are shown.
b) They don't get updated during "update-osm"
c) We don't have tight control over them, leading to issues like: https://github.com/openmaptiles/openmaptiles/issues/117 or inconsistencies between zooms. Vector Tiles have seamless zooming, so big jumps between data sources is jarring.

My assessment of difficulty to move import steps into OpenMapTiles.

- [x] Import-lakelines - Easy
- [x] import-water - Easy
- [x] import-osmborders - Medium, would integrate the SQL stages into our layer schema like other layers.
- [x] import-naturalearth - Hard

Only significant issue I can see if one is doing a sub-planet rendering, the vector tiles won't look nice as only those parts of the PBF will be included in the mbtiles.

This would be for v3.7 or so.

**Comment by TomPohys** [comment]
All import-* are part of OpenMapTiles-Tools and will be merged into `import-data` image in https://github.com/openmaptiles/openmaptiles-tools/pull/188
