### ISSUE TITLE
add a possibility to generate mbtiles with no pbf compression (direct access to Geojson tile data)

### ISSUE THREAD

**Issue by ddrmax** [openmaptiles/openmaptiles#222]
Hello, as the title says, is it possible to modify the code or the docker subsystem to add the possibility to generate mbtiles that doesnt have the PBF tile compression to have access to direct geojson data, since I'm working with C++ builder 2009, it's impossible decode the pbf data (no possible protobuff support).
for an easy way to use it, we could use like a --nopbf or --nopbfoutput?
Is it possible in the actual release to deactivate the pbf compression by modifying the quickstart.sh?

**Comment by ImreSamu** [comment]
> access to direct geojson data,  since I'm working with C++ builder 2009, 
> it's impossible decode the pbf data (no possible protobuff support).

Have you checked the  (C++) vector-tile parsers ?
https://github.com/mapbox/awesome-vector-tiles#parsers--generators

or you can use the `tippecanoe-decode` utility.
`The tippecanoe-decode utility turns vector mbtiles back to GeoJSON. You can use it either on an entire file:`  https://github.com/mapbox/tippecanoe#tippecanoe-decode

**Comment by stirringhalo** [comment]
Consider the newly added https://github.com/openmaptiles/postserve (it's part of the standard quickstart.sh now)

You should be able to modify ST_AsMVT with http://www.postgis.net/docs/ST_AsGeoJSON.html and apply a BBOX as part of the generated query.

I don't see a major reason to include it as a function in postserve at the moment, but I'm open to it in the future.
