### ISSUE TITLE
Sometimes housenumbers are missing or wrong

### ISSUE THREAD

**Issue by arnekaiser** [openmaptiles/openmaptiles#228]
In the following example the housenumbers are missing and the five visible housenumbers are wrong. The geometries of the buildings look also a bit strange:
![omt](https://cloud.githubusercontent.com/assets/5116350/25331648/15a7d6da-28e4-11e7-8a4d-7a0d79109af2.PNG)
https://openmaptiles.github.io/klokantech-basic-gl-style/#17/51.97611/7.63128

In OpenStreetMap the housenumbers are available:
![osm](https://cloud.githubusercontent.com/assets/5116350/25331632/0800c4e2-28e4-11e7-87fc-e1654ad29186.PNG)
https://www.openstreetmap.org/#map=18/51.97610/7.63132

**Comment by stirringhalo** [comment]
I think there might be an issue with the mapping, but I need @klokan 's input, is this using the latest schema? It looks like the mapping may be missing it or it may be missing in the SQL. All the missing buildings are "building=house"

**Comment by klokan** [comment]
The free.tilehosting.com is generated with the latest schema and the latest OpenStreetMap data. 
See the TileJSON link - and check values in JSON keys "version" for schema version, and "planettime" for OSM data timestamp.

**Comment by stirringhalo** [comment]
Buildings (and associated housenumbers as parts of relations) will need to be better handled, major undertaking. Pushing to 3.7

**Comment by stirringhalo** [comment]
Two components to this:

- [ ] Housenumbers
- [ ] Buildings

Buildings are fixed (but some corruption) in https://github.com/openmaptiles/openmaptiles/pull/284

Tracking the validity issue separately.

**Comment by jirik** [comment]
With the current openmaptiles master, house numbers are imported correctly. Maybe because we are now using later imposm3:
https://github.com/openmaptiles/openmaptiles/commit/1a324aaf223c83db5ef200a8c2d66704f2d3352e#diff-4e5e90c6228fd48698d074241c2ba760
