### ISSUE TITLE
Checklist for ClearTables content

### ISSUE THREAD

**Issue by pnorman** [openmaptiles/openmaptiles#23]
I'd open this in the CT repo, but this one is still private.

This is a checklist to make sure that ClearTables has the required content to produce the current layers. I've done the same thing with MB Streets, imposm default, and Geofabrik shapefiles to see if there's anything missing on the CT side.

* [ ] boundary
* [x] building
* [x] highway
* [x] highway_name
* [x] housenumber
* [ ] landcover
* * [ ] farmland
* * [ ] ice
* * [x] wood
* * [x] wetland
* [ ] landuse
  * [ ] park
  * [x] school
  * [ ] landuse
* [x] place
* [ ] poi
* [x] railway
* [x] water
* [x] water_name
* [x] waterway

**Comment by klokan** [comment]
@pnorman do you know of an implementation of OpenMapTiles schema on top of ClearTables?

(this ticket can be closed, right?)
