### ISSUE TITLE
Generate countries, major cities

### ISSUE THREAD

**Issue by megastef** [openmaptiles/openmaptiles#231]
The example with the swiss map includes cities around the world. When I generate tiles for luxembourg, then I don't get any city in other countries. Where could I configure to get the cities in the map? 

I would like to generate a simple world map like the demo map for swiss. 

A second question: Is there a flag to generate the tiles for the whole world, e.g. limited to zoom level 10 to reduce the data. `quickstart.sh planet` does not work as expected ;)

**Comment by lukasmartinelli** [comment]
The approach here is to include/patch tiles from lower zoom levels from the planet file into your tiles with high zoom levels.

I thought when we generate the country extracts (or cities?) we merge the zoom 1-7 automatically into the extract.

**Comment by megastef** [comment]
Here is the result, running 'quickstart.sh luxembourg'
http://51.15.46.117:8081/styles/osm-bright/?vector#4.81/51.287/6.696

**Comment by megastef** [comment]
@lukasmartinelli could you provide a guide what would need to be changed? Or share configs used for the demo / swiss map that has the cities plus country borders? 

I have no idea where this definitions take place.

**Comment by lukasmartinelli** [comment]
Someone else needs to look at this but if you share the same schema patching works like this
http://osm2vectortiles.org/docs/own-vector-tiles/

Optional: Merge lower zoom levels (z0 to z5) into extract (prerequisite: sqlite3 installed)

Download lower zoom level extract *change link to OpenMapTiles country or city extract - shouldn't matter which.

```
wget -P ./export/ https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v2.0/planet_z0-z5.mbtiles
```

Download the patch.sh script from the Mapbox mbutil project.

```
wget https://raw.githubusercontent.com/mapbox/mbutil/master/patch
chmod +x patch
```

Merge lower zoom levels into extract.

`./patch "./export/planet_z0-z5.mbtiles" "./export/zurich.mbtiles"`

**Comment by jirik** [comment]
It's as Lukas said. Every country/city mbtiles at https://openmaptiles.com/downloads/planet/ is extended with zoom level 0-7 from the planet, so you have nice world map for lower zoom levels. The extension is done using merging (patching).
