### ISSUE TITLE
Missing Rail Stations

### ISSUE THREAD

**Issue by lincomatic** [openmaptiles/openmaptiles#232]
Bus stops are included, so it seems that rail stations should be included as well?

**Comment by stirringhalo** [comment]
I agree. you interested in making a PR?

**Comment by lincomatic** [comment]
I'm not sure I understand well enough how to do it properly, but I will try

**Comment by lincomatic** [comment]
Which layer should rail stations go? Transportation or POI?

**Comment by stirringhalo** [comment]
I'm leaning towards POI, @ImreSamu  @klokan ?

**Comment by jirik** [comment]
+1 for rail stations in POI layer if POI attributes are sufficient for rail stations (name, name_en, name_de, class, subclass, rank).

**Comment by lincomatic** [comment]
I'm having trouble figuring out how to do this. Rail stations have

> railway=station

*sometimes* they have

> station=subway
> station=light_rail

but often not, even if they are subway or light rail stations.  I tried cloning the logic for aerialway stations, and all I end up with in the POI layer is class=station, subclass=station.

First of all, we need to decide on a proper mapping.

should we go with

> class=railway
> subclass=station

or

> class=rail_station
> subclass=rail_station or subway or light_rail

**Comment by lincomatic** [comment]
I think the rank should be lower than bus stations.. how about using 40?

**Comment by stirringhalo** [comment]
@lincomatic I wouldn't worry about maintaining the differences between rail station types, just label them all stations. The schema divides all the rail types into two main categories. https://github.com/openmaptiles/openmaptiles/blob/master/layers/transportation/class.sql

That sounds good for the ranking. Generate a PR so I can see what you got so far!

**Comment by jirik** [comment]
See https://github.com/openmaptiles/openmaptiles/pull/239

**Comment by klokan** [comment]
Would be good to distinguish http://wiki.openstreetmap.org/wiki/Tag:station%3Dsubway
if not done yet...

**Comment by jirik** [comment]
Fixed by #255
