### ISSUE TITLE
./quickstart.sh us fails, cannot find us-latest.osm.pbf

### ISSUE THREAD

**Issue by kjschiroo** [openmaptiles/openmaptiles#233]
After running `./quickstart.sh us`, I get the following error message.
```
Error!!! http://download.geofabrik.de/north-america/us-latest.osm.pbf not exist
```

Navigating to `http://download.geofabrik.de/north-america/` in browser confirms the file cannot be found there.

**Comment by ImreSamu** [comment]
Thank you, 
I will remove the "us" from the [QUICKSTART.md](https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md) list
