### ISSUE TITLE
Admin boundaries visible over lakes

### ISSUE THREAD

**Issue by hyperknot** [openmaptiles/openmaptiles#246]
I'm finally evaluating the new project. So far a looks quite good, however there are some really big, distracting admin boundaries drawn over lakes.

It is present in Basic and Bright.

https://openmaptiles.github.io/osm-bright-gl-style/#11.12/46.8200/17.5940

![screen shot 2017-05-12 at 01 16 31](https://cloud.githubusercontent.com/assets/494223/25975858/1d68f180-36b1-11e7-89a4-f444d520f1e6.jpg)

**Comment by stirringhalo** [comment]
Thanks! There's a whole pile of political boundaries through there. https://www.openstreetmap.org/query?lat=46.7970&lon=17.6114

**Comment by ImreSamu** [comment]
The [osmborder](https://github.com/pnorman/osmborder) data  has different logic.
* 'The admin_level **is the lowest admin_level value of the parent relations.** '


As I see in this case the lowest admin_level value    
* `admin_level=5`  ( NUTS-2)
  * http://www.openstreetmap.org/relation/22783
* sometimes `admin_level=7`  (LAU-1)  
  * http://www.openstreetmap.org/relation/2376281
  * http://www.openstreetmap.org/relation/2376985

And the "admin_level"= '5' and the '7' is missing from the  styles:  
```json
      "filter": [
        "all",
        [
          "in",
          "admin_level",
          4,
          6,
          8
        ],
```
* bright: https://github.com/openmaptiles/osm-bright-gl-style/blob/master/style.json#L3136
* basic: https://github.com/openmaptiles/klokantech-basic-gl-style/blob/master/style.json#L999


Maybe this can be a problem in other European Countries ( Germany, France, ... )
*  https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative

**Comment by ImreSamu** [comment]
Sometimes,  **the lowest admin_level value** is `admin_level=3`   so not so easy to fix.
* `Western Slovakia`  http://www.openstreetmap.org/relation/946157
* `Eastern Slovakia` http://www.openstreetmap.org/relation/946159

And we need to re-check the special values:
* `admin_level=0` https://taginfo.openstreetmap.org/tags/admin_level=0
* `admin_level=1`  https://taginfo.openstreetmap.org/tags/admin_level=1

**Comment by jirik** [comment]
Fixed by https://github.com/openmaptiles/osm-bright-gl-style/commit/2497595ec4c1917f03f7a3a26b79bde939d2a186
