### ISSUE TITLE
Docker 17.04.0-ce compatibility issue

### ISSUE THREAD

**Issue by kjschiroo** [openmaptiles/openmaptiles#248]
Looks like there might be an interesting bug here. Running `./quickstart.sh` with Docker version 17.04.0-ce, build 4845c56 I eventually run into this error
```
====> : Start importing OpenStreetMap data: ./data/us-midwest.osm.pbf -> imposm3[./build/mapping.yaml] -> PostgreSQL
      : Imposm3 documentation: https://imposm.org/docs/imposm3/latest/index.html 
      :   Thank you Omniscale! 
      :   Source code: https://github.com/openmaptiles/import-osm 
      : The OpenstreetMap data license: https://www.openstreetmap.org/copyright (ODBL) 
      : Thank you OpenStreetMap Contributors ! 
The BBOX variable is not set. Defaulting to a blank string.
The MAX_ZOOM variable is not set. Defaulting to a blank string.
The MIN_ZOOM variable is not set. Defaulting to a blank string.
[May  4 00:15:11] dial tcp 198.105.244.23:5432: getsockopt: connection timed out
```
Uninstalling docker and reinstalling with Docker version 1.12.3, build 6b644ec everything works again.

**Comment by ImreSamu** [comment]
thank you for reporting this.

2 days ago it is worked for me, so I can't replicate.

```bash
====> : OpenMapTiles quickstart! [ https://github.com/openmaptiles/openmaptiles ]
      : This will be logged to the ./quickstart.log file (for debugging) and to the screen
      : Area             : hungary
      : Git version      : a4a7ca95c6419cdee3eb80c3d6583c10ae169276
      : Started          : 2017-05-09T10:26+0000
      : Your bash version: 4.3.46(1)-release
      : Your OS          : linux-gnu
Docker version 17.04.0-ce, build 4845c56
docker-compose version 1.13.0, build 1719ceb
```


#### my debugging tip:

`[May  4 00:15:11] dial tcp 198.105.244.23:5432: getsockopt: connection timed out`
Probably this is a `postgres` service connection problem. ( imposm3 try to connect to the Postgres service)
possible problems:
* postgres service stopped? 
   * check: `docker logs openmaptiles_postgres_1` 
* disk space problem?  
* docker Storage Driver problem?   
* docker network problem? 
* ... 


Can you re-test with  `Docker version 17.05.0-ce`?
Can you replicate with re-installing `Docker version 17.04.0-ce`?
  * If yes:  please give more information about your system, and please attach the `./quickstart.log` and the `docker info`  output.
