### ISSUE TITLE
Water polygon error

### ISSUE THREAD

**Issue by hyperknot** [openmaptiles/openmaptiles#249]
A different error on water, this time on Thames:
http://demo.tileserver.org/styles/klokantech-basic/?vector#11.68/51.4811/-0.0078

<img width="497" alt="screen shot 2017-05-13 at 01 13 17" src="https://cloud.githubusercontent.com/assets/494223/26019893/66890152-3779-11e7-9787-8f940490543a.png">

**Comment by jirik** [comment]
Already fixed:
https://openmaptiles.github.io/klokantech-basic-gl-style/#11.68/51.4811/-0.0078
