### ISSUE TITLE
Road ramps problem

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#250]
Reported originally by @ianthetechie on #79

Another issue to note is roads which are marked as ramps. These are quite prominent in the industrial northern US cities. I've attached a few examples of where there are some rather wide gaps in the road.

![screen shot 2017-01-23 at 22 39 02](https://cloud.githubusercontent.com/assets/2140440/22233383/087fe1fe-e1be-11e6-9389-46d574f2c107.png)
![screen shot 2017-01-23 at 22 45 33](https://cloud.githubusercontent.com/assets/2140440/22233386/0d383430-e1be-11e6-8b71-014d1b4a5e39.png)

**Comment by jirik** [comment]
These **ramps** are actually highway **links**. We want to show `highway:*_link` at lower zoom levels.
