### ISSUE TITLE
Import wikidata translations

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#251]
The translations available in OSM database has a lower coverage then Wikidata.

Wikidata can be used in the import to extend the number of translations for different places.

This ticket is about implementing wikidata import and binding - and filling the translations for more complete multilingual coverage - in #211

**Comment by klokan** [comment]
@nyurik what process and data dump would you recommend for regularly importing the wikidata IDs + various translations of placenames into Postgres?

**Comment by klokan** [comment]
New repo:
https://github.com/openmaptiles/import-wikidata

Official dumps:
https://www.wikidata.org/wiki/Wikidata:Database_download#JSON_dumps_.28recommended.29
https://dumps.wikimedia.org/wikidatawiki/entities/

Relevant info:
http://wiki.openstreetmap.org/wiki/Wikidata

**Comment by nyurik** [comment]
@klokan I'm currently experimenting with importing Wikidata & OSM data into a local Blazegraph  (rdf db) instance.  The Wikidata import is relatively simple - you download the turtle file, and run two scripts to import it.  There is even an autoupdater script - running it keeps local wikidata always up to date. But this is not very convenient if you are trying to generate vector tiles using postgis. So for your usecase, it might be better to have a different script that downloads JSON dump and imports it directly into postgres, where you can do joins.  Once a ..., you can re-download/re-import/re-gen the whole thing.

**Comment by stirringhalo** [comment]
@nyurik That sounds like a good idea, having an updater script (like the "update-osm") that runs continuously. Vector tiles can be generated off the join. Might be better to do a refresh of a materialized view to avoid too many big joins.

**Comment by klokan** [comment]
Related comment: https://github.com/OSMNames/OSMNames/issues/58#issuecomment-304661743

**Comment by klokan** [comment]
https://www.mapbox.com/blog/streets-arabic-portuguese/
(greetings to @lukasmartinelli at Mapbox)

**Comment by jirik** [comment]
Pull request opened: https://github.com/openmaptiles/openmaptiles/pull/358

**Comment by jirik** [comment]
Closed by https://github.com/openmaptiles/openmaptiles/commit/741be6d92109191a082c28959bc86bffe1568ba6
