### ISSUE TITLE
Transliteration / latinisation of non-latin names

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#252]
Transliteration a la 
http://wiki.openstreetmap.org/wiki/Names#Avoid_transliteration
More at:
https://www.openstreetmap.de/karte.html - https://www.openstreetmap.de/germanstyle.html

We could theoretically reuse functions from:
https://github.com/giggls/mapnik-german-l10n

The license conditions must be cleared with @giggls, if we are allowed to use the code without a need to change the license of whole openmaptiles project (AGPL is not compatible with BSD+CC-BY).

**Comment by giggls** [comment]
The Idea of using AGPL was that I wanted people using this code in their Web-Map Services to give back the extensions they add to it to the public. They might even have better ideas for producing localized names than I did.

The whole stuff is currently bound to PostgreSQL as a data source. Adding the extension to PostgreSQL and using it will not interfere with the license of your stuff in any way.
If you don't use PostgreSQL as a data source but e.g. raw Openstreetmap data you will need to extract the local name generation state machine from my code and rewrite it in another programming language anyway, as my stuff is mostly written in PL/pgSQL.

I already thought about re-writing this stuff in C++ to be usable in conjunction with libosmium instead of PostgreSQL, but this is currently nothing more than an idea.

**Comment by klokan** [comment]
Sven, thanks for jumping in, it is great to have you here. Thank you also for your work on the OSM l10n code! We are keen to produce multilingual OpenStreetMap vector tiles - as described in #211. We do use PostgreSQL in this project...

We would like to reuse your code, improve it, and release our improvements of your code under an open-source license of your choice - so the code remains to be available to the OSM community and anybody else interested.

The copyleft clause 5.c) of [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html) force us to publish our whole complete work (so our software!) under AGPL license, according to my understanding. It seems this was not your intention.
 
Could you please grant the OpenMapTiles project an exception on your assigned license?

- Can our project use (and depend on) your code, but keep our existing license?

This under the condition that our modifications of your code are going to be publicly available on GitHub under https://github.com/openmaptiles/mapnik-german-l10n - and the OpenMapTiles / KlokanTech team provide you with the copyright on such modifications  - so you can release them under a license of your choice.

Sven Geggus, @giggls, could you please confirm such exception is granted? Thank you!

**Comment by giggls** [comment]
IANAL, but I don't think that AGPL of my Project would make yours AGPL as well. This is not C-code thus I did not add a link extension. But still, my intention was that only the l10n code itself should be protected by copyleft. Even using it in a proprietary map project would be OK for me as long as the l10n stuff and extensions to it will stay open and that is what I choose the copyleft licence for.

Correct me if I'm wrong, but removing my code from your project would just make it non localized and not unusable thus there would be no strong dependency on my code in your project.

I thought I already made this clear in https://github.com/giggls/mapnik-german-l10n/blob/master/LICENSE.txt

**Comment by klokan** [comment]
Thanks @giggls - for clarification!

This is a clear message:
> my intention was that only the l10n code itself should be protected by copyleft. Even using it in a proprietary map project would be OK for me as long as the l10n stuff and extensions to it will stay open and that is what I choose the copyleft licence for.

We are going to use the fork in OpenMapTIles generator... cool!
Our project will not have a strong dependency on your code.

**Comment by jirik** [comment]
Work in progress: https://github.com/klokantech/openmaptiles/tree/osml10n
It seems it works well both for South Korea and Morocco (testing regions).

**Comment by guyisra** [comment]
"Our project will not have a strong dependency on your code."

@klokan Seems that this is no longer the case as without the extension the sql queries do not work

**Comment by giggls** [comment]
Unfortunately there is no LGPL version of the AGPL. I do not consider _using_ my psql extension a derived work. The sole reason for using a viral licence for my code is that I want latinisation improvements to be open. I already made this clear in https://github.com/giggls/mapnik-german-l10n/blob/master/LICENSE.txt
