### ISSUE TITLE
Layer CADASTER not BUILDING, display problem?

### ISSUE THREAD

**Issue by joaokho** [openmaptiles/openmaptiles#253]
I have layer Cadaster, but i put tag building=yes, but did not display properly, maybe because building is top level layer that can overlapped park area and water area.

How to define our own layer that will display like building but did not overlap park & water area?
Any suggestion and help ?

Thanks..

**Comment by stirringhalo** [comment]
I'm not sure what you're asking here? Can you show a sample of the tile schema and what you're hoping to have?

**Comment by joaokho** [comment]
See the screen capture below (this is cadaster layer on different zoom-level): at 12.89 because still not showing building layer it's correct, all water area  and park area is not overlap by building polygon. but after zoom above 12.89, some water area and park are overlap by building polygon. That's why I think need to create new layer (something like "cadaster=yes") that will show like building, but has lower priority (below to park/water area) , so that will not overlap. But i don't know how to define and change the style to include this using: docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl data/tiles.mbtiles

![klokantech-basic-zoom-level 12 89](https://cloud.githubusercontent.com/assets/943439/26333760/679909d4-3f8a-11e7-9ecf-ca74224a2538.png)
![klokantech-basic-zoom-level 13 23](https://cloud.githubusercontent.com/assets/943439/26333761/67cf1d58-3f8a-11e7-9b70-d4d002c2b671.png)
![klokantech-basic-zoom-level 17 28](https://cloud.githubusercontent.com/assets/943439/26333762/67dd96ee-3f8a-11e7-8a4b-fbe9f1287831.png)

**Comment by stirringhalo** [comment]
How are you importing PSMA data? And what does the table for the PSMA data look like? You will need to make sure the PSMA data is different from the building data (in a different table from it).

**Comment by joaokho** [comment]
for Cadaster is like building / property layer, only polygon.
I importing using ogr2osm with my translation code. 
The structure of cadaster is very simple (cad_pid, parcel_type_code), what translation code is to do adding tag "building"->"yes". Because this tag is not shown properly on map (overlap water area, park etc.). So I want to define new tag for it, something like "cadaster"=>"yes", but I don't know how to do it will process by openmaptiles generating data.

I only need advise on creating new layer like building layer, but it's lower display level than water, park. so it can display properly on map tiles, and how to do on define the default json style on tileserver.

**Comment by stirringhalo** [comment]
Which step is adding the the "building" = "yes" for the Cadaster data? Is it the ogr2osm or your translation code?

Option 1)
I would skip that, and instead use http://www.gdal.org/drv_pg.html and ogr2ogr to dump straight into database in a new table (called "cadastre" or something). That way you get fine grain control of what exactly is happening.

And then, add a new layer (see https://github.com/openmaptiles/openmaptiles/tree/master/layers/park for a layer example - I would add some new tables+indexes with simplifications of your cadastre data - and add the layer to https://github.com/openmaptiles/openmaptiles/blob/master/openmaptiles.yaml). 

-----

Option 2)
You could continue to use ogr2osm, but from what I can tell without seeing your translation code, you would also need to make sure it's tagged as cadastre in the OSM xml you generate and a suitable Imposm3 mapping is added to the layer. More complicated than above.

-----

Once you go with one of your options, you will also need to modify the style you use, with a new layer group for Cadastre data. Make sure the Cadastre layer is at the appropriate spot so it only overlaps the layers you want. The later it is in the style, the later it is draw and further on top it is.

**Comment by joaokho** [comment]
Thank you very much @stirringhalo . I will try 2 options. :+1:

**Comment by stirringhalo** [comment]
Depending on what format the Cadastre data comes in, you can use shp2pgsql which is a really nice and straight forward tool to use.

**Comment by joaokho** [comment]
Cadastre data come in in Mapinfo Tab format. but it's easy to convert via ogr2ogr.
