### ISSUE TITLE
Refactoring quickstart.sh workflow

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#261]
This is a detailed plan of refactoring `quickstart.sh` workflow ( prevous:  https://github.com/openmaptiles/openmaptiles/issues/208 )

The current quickstart.sh workflow is not optimal, 
Now as the system less moving,  it is a good time to fix.

Planned :

- [x] Refactoring quickstart zoom settings.
  * QUICKSTART_MIN_ZOOM  -> MIN_ZOOM
  * QUICKSTART_MAX_ZOOM -> MAX_ZOOM

No need 2 ZOOM settings, it is confusing
The QUICKSTART_(MIN/MAX)_ZOOM - will be removed everywhere, and the MIN_ZOOM,  MAX_ZOOM will be used.

- [ ] removing current quickstart warnings.
```
The MIN_ZOOM variable is not set. Defaulting to a blank string.
The MAX_ZOOM variable is not set. Defaulting to a blank string.
```
- [x] Better bring your own data (BYOD)  support  https://github.com/openmaptiles/openmaptiles/issues/227

- [ ] `nohup quickstart.sh`  support  https://github.com/openmaptiles/openmaptiles/issues/166

- [ ] Moving 'osm2vectortiles/mapbox-studio ' definitions from the `docker-compose.yml`  to the `Makefile`, so no need to download the docker images for simple testing.  
The `make start-mapbox-studio` function will be preserved.

**Comment by TomPohys** [comment]
I think that this issue could be closed, as `QUICKSTART_MIN_MAX` was resolved (#915) and `mapbox-studio` was removed in #506.
