### ISSUE TITLE
Replacing map areas and merging mbtiles questions

### ISSUE THREAD

**Issue by alexmipego** [openmaptiles/openmaptiles#263]
Hi, I've managed to setup an environment to generate maps and I would like to request some help identifying the best procedures to replace areas on the mbtiles. I'm limited experience generating map tiles. 2 scenarios:

1) If I want to replace one or more layers by my own how/where should this be done? For example, given a planet mbtiles (max zoom), I want to replace the roads in Portugal only, without touching Spain's road for example.

2) (Assuming) tilelive-copy arguments work correctly and I'm able to generate different parts of the map on different machines, how do I merge them? E.g. given 16 mbtiles files can I simply merge them using https://raw.githubusercontent.com/mapbox/mbutil/master/patch or should I follow another procedure?

Thanks!

**Comment by alexmipego** [comment]
Anyone?

**Comment by klokan** [comment]
ad 1)
If you want your own layers - the best is to generate the vector tiles just with these layers and use them in the style separately from OpenMapTiles. This is supported via the whole mapping stack (web, mobile SDK, raster tiles). There can be multiple "source" records in the JSON style.
Next to that - a server can concatenate multiple vector tiles into a single binary blob - if you want to save HTTP request. Details at https://openmaptiles.org/docs/generate/custom-vector/

ad 2)
MBTiles are just SQLite - you can implement the merge of independent areas with standard SQL commands.

I hope this answers your questions @alexmipego.
I will close this ticket - as there is no action to be done in the code of this repository.

In case you are interested in getting support from the authors of this project - it is offered at https://openmaptiles.com/support/
