### ISSUE TITLE
Check `tags: load_all: true` in buildings

### ISSUE THREAD

**Issue by jirik** [openmaptiles/openmaptiles#266]
Currently, there is
```yaml
tags:
  load_all: true
```
in `layers/building/mapping.yaml`.
Do we need it? I prefer to specify list of tags we want to load instead of loading all of them.

Probably introduced by
https://github.com/openmaptiles/openmaptiles/commit/199095a2baa4d18bc65ee8aee3f381d1c432bec3
https://github.com/openmaptiles/openmaptiles/pull/157

Maybe related to #225

**Comment by ImreSamu** [comment]
The brand new imposm3 `v0.4` has removed some limitation
* "Automatically include tags from relation and relation_member tables. No need for load_all anymore "
   *   https://github.com/omniscale/imposm3/milestone/1?closed=1

**Comment by stirringhalo** [comment]
@jirik You're right, I introduced it with #157 to get the fields for relation and relation_member.

I didn't know about imposm3 v0.4, so now with that, it should certainly be removed. Thanks @ImreSamu !

**Comment by jirik** [comment]
I have started to work on it:
- use latest version of imposm3
   - https://github.com/openmaptiles/import-osm
- remove function `slice_language_tags` (this function was there for removing loaded tags that we didn't need, i.e. most of them)
   - https://github.com/openmaptiles/openmaptiles-tools/tree/issue-266
- remove `load_all` and usages of `slice_language_tags`
   - https://github.com/klokantech/openmaptiles/tree/issue-266

It seems to work.

@ImreSamu Do you thing we can use [the latest imposm3](https://github.com/omniscale/imposm3/tree/9be1e5abc3eb7a0b3cff145d30d96608e280de14) in master?

**Comment by ImreSamu** [comment]
>Do you think we can use the latest imposm3 in master?

yes,  it is an improved and accepted patch!   So it should work!
