### ISSUE TITLE
upgrade imposm3 to v0.4 + patch "filter - reject/require"

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#267]
The brand new imposm3 v0.4 has removed some limitation, but need some testing.
* https://github.com/omniscale/imposm3/milestone/1?closed=1

related issues:
* https://github.com/openmaptiles/openmaptiles/issues/266
* https://github.com/openmaptiles/openmaptiles/issues/225

**Comment by jirik** [comment]
Work in progress: https://github.com/openmaptiles/openmaptiles/issues/266#issuecomment-343213799

**Comment by jirik** [comment]
Closed by https://github.com/openmaptiles/openmaptiles/commit/1a324aaf223c83db5ef200a8c2d66704f2d3352e
