### ISSUE TITLE
missing leisure polygons

### ISSUE THREAD

**Issue by jaakla** [openmaptiles/openmaptiles#272]
Currently these seem to be missing from vector tiles:

- [x] **leisure=garden** http://wiki.openstreetmap.org/wiki/Tag:leisure=garden , e.g. http://www.openstreetmap.org/way/29977602#map=17/58.38484/26.72129
- [x] **leisure=track**. Instance sample: http://www.openstreetmap.org/way/8036490
- [x] **tourism=zoo**, e.g. http://www.openstreetmap.org/way/9393789#map=16/52.5085/13.3396&layers=D 
- [ ] Generally please make sure to include **name** tags for all these.
- [ ] **leisure=park** polygons seems to be included in landcover layer, but these have lost **name tags** in zooms below 14. It seems to be present in poi level for zoom 14, but for larger parks it may be not enough, like http://www.openstreetmap.org/way/372975520

**Comment by jirik** [comment]
Gardens added to landcover by https://github.com/openmaptiles/openmaptiles/commit/e1ab498936aef378f769b2feeeaf90ecc20324e7

**Comment by jirik** [comment]
Zoo added to landuse by https://github.com/openmaptiles/openmaptiles/commit/050051bce620ee243f45e4a46a8028e29f940e43

**Comment by TomPohys** [comment]
Resolved by #521 and #525
