### ISSUE TITLE
serve mbtiles without any server

### ISSUE THREAD

**Issue by zafrii** [openmaptiles/openmaptiles#276]
Hi! Just wondering, if there is a way to server mbtiles without the need of PHP/nodeJS.
Actually I want to run the tiles offline on browser without any server, Is there any Javascript libraries which can help in this case?
In short, can we get pbf files out of mbtiles using only the Javascript without any PHP/nodeJS?

**Comment by zafrii** [comment]
I've tried [mbutil ](https://github.com/mapbox/mbutil) to extract mbtiles into pbf format, but these pbf files are not working. I've checked a file, which I extracted by mbutil, its ~7kb in size, but if I open the same file in url using tileserver-php, and download the file, its size is ~11kb.
Seems like mbutil is not capable of extracting mbtiles produced by openmaptiles

**Comment by MattBlissett** [comment]
You may need to uncompress the file you extract, as it is probably GZip compressed.

An example using the CLI interface for an SQLite database, I assume mbutil is doing something similar:
```
sqlite3 nassau_bahamas.mbtiles 'select quote(tile_data) from tiles where zoom_level = 0 and tile_column = 0 and tile_row = 0' | cut -d\' -f2 | xxd -r -p | gunzip > tile_0_0_0.pbf
```

I have this shell function defined in my `.bashrc`, using https://github.com/mapbox/vector-tile-spec
```
vtd () {
        protoc --proto_path ~/Workspace/vector-tile-spec/2.1/ --decode vector_tile.Tile ~/Workspace/vector-tile-spec/2.1/vector_tile.proto
}
```

So:
```
sqlite3 nassau_bahamas.mbtiles 'select quote(tile_data) from tiles where zoom_level = 0 and tile_column = 0 and tile_row = 0' | cut -d\' -f2 | xxd -r -p | gunzip | vtd
```
shows the layers (features, keys etc).

**Comment by klokan** [comment]
See
https://github.com/klokantech/vector-tiles-sample#host-the-vector-tiles-without-any-server-at-all

and a sample vector tile map hosted completely serverless directly on github:

http://klokantech.github.io/mapbox-gl-js-offline-example/
https://github.com/klokantech/vector-tiles-sample
https://github.com/klokantech/mapbox-gl-js-offline-example

**Comment by klokan** [comment]
Also - if you want hosting on Amazon S3 or Google Cloud Store - you can just open the MBTiles from OpenMapTiles in MapTiler (http://www.maptiler.com) - and it has a direct upload to these cloud services, which will even generate you a sample map viewer for the unpacked and hosted individual tiles.
All you have to do is to provide key and secret for your account. It is also one of the fastest way how to upload large number of tiles to bucket, especially if you start the upload directly on a virtual machine in the Amazon / Google. Uploading from command line is possible with MapTiler available via docker: https://hub.docker.com/r/klokantech/maptiler/

**Comment by zafrii** [comment]
@klokan Thank you so much for your response, it helped a lot. 
Now, I've unzipped pbf files, and I'm trying to add the link of these pbf files directory in the style file like below
`"openmaptiles": {
      "type": "vector",
      "url": "http://localhost:8081/tiles_pbf/{z}/{x}/{y}.pbf"
    }`
but it keeps on giving this error
`Object {type: "error", target: t, isSourceLoaded: false, source: Object, sourceId: "openmaptiles"}`

Can you please confirm that the pbf files can work for openmaptiles style, I'm currently trying the osm bright style

**Comment by zafrii** [comment]
okay, I've resolved it, by changing _url_ with _tiles_

**Comment by jmarcos-cano** [comment]
So i've generated from mbtiles (2017-07-03_planet_z0_z14.mbtils using osm-liberty-style) and uncompressed all pbf files into a folder called countries/ however I believe im lost in how to properly generate/create the style mentioned in mapbox-gl-js-offline-example

`The  attached style (embeded in the JavaScript code of index.html) is handmade based on the instructions at: https://www.mapbox.com/mapbox-gl-style-spec/`

perhaps I need to use this style.json and just modified it?  https://maputnik.github.io/osm-liberty/style.json

I need some guidance, thanks in advance

**Comment by Vrq** [comment]
@klokan is it possible to convert the vector tiles from https://openmaptiles.com/downloads/dataset/osm/#0.23/0/-26 to raster tiles and then put them on S3?

**Comment by daliborjanak** [comment]
You can seed it with script from e.g. tileserver-gl but this is not best practice. The file size is too big (impossible with the world on deep zooms)
