### ISSUE TITLE
ERROR: function delete_empty_keys(hstore) does not exist

### ISSUE THREAD

**Issue by wardo001** [openmaptiles/openmaptiles#277]
Hi Openmaptiles,

I have successfully installed tileserver-gl and I am now looking forward to creating my own tiles. Great effort on the server software - you guys really are pushing the mapping platform forward!

I am going through the process to create my own OpenMapTiles following the guide:

https://openmaptiles.org/docs/generate/generate-openmaptiles/

Everything goes well until the last step:

./quickstart.sh

This generates the error below. The full log is attached. 

[quickstart-log.zip](https://github.com/openmaptiles/openmaptiles/files/1052979/quickstart-log.zip)

I have searched around but not found any relevant fixes. I am a bit reluctant to just comment out the offending lines in tileset.sql!

I am running on ubuntu 16.04, in a kvm shell.

Any help is greatly appreciated. Many thanks.
 
-------------------------------------------------------------------------------------
====> : Start SQL postprocessing:  ./build/tileset.sql -> PostgreSQL 
      : Source code: https://github.com/openmaptiles/import-sql 
The MIN_ZOOM variable is not set. Defaulting to a blank string.
The MAX_ZOOM variable is not set. Defaulting to a blank string.
The BBOX variable is not set. Defaulting to a blank string.
Timing is on.
CREATE FUNCTION
Time: 40.761 ms
CREATE FUNCTION
Time: 9.542 ms
CREATE FUNCTION
Time: 8.308 ms
CREATE FUNCTION
Time: 12.382 ms
CREATE FUNCTION
Time: 31.748 ms
CREATE FUNCTION
Time: 12.360 ms
CREATE FUNCTION
Time: 33.387 ms
CREATE FUNCTION
Time: 10.562 ms
CREATE FUNCTION
Time: 10.019 ms
CREATE FUNCTION
Time: 12.295 ms
CREATE FUNCTION
Time: 9.665 ms
CREATE FUNCTION
Time: 12.275 ms
CREATE FUNCTION
Time: 9.846 ms
CREATE FUNCTION
Time: 12.153 ms
CREATE FUNCTION
Time: 9.874 ms
CREATE FUNCTION
Time: 12.388 ms
Timing is on.
psql:/sql/tileset.sql:4: ERROR:  function delete_empty_keys(hstore) does not exist
LINE 3:     SELECT delete_empty_keys(slice(tags, ARRAY['int_name', '...
                   ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Time: 2.860 ms

**Comment by ImreSamu** [comment]
@wardo001  Thank you for reporting,   I can replicate.

**Comment by wardo001** [comment]
@ImreSamu Again, thanks for the quick response. OK, good, you can replicate. I will sit tight.

**Comment by wardo001** [comment]
@ImreSamu I have also gone through the process to create some custom vector tiles (https://openmaptiles.org/docs/generate/custom-vector/) from a postgis database and seen the same error. I have posted below.

Also, I am not sure why I am seeing warnings regarding MIN_ZOOM, MAX_ZOOM and BBOX variables not being set. I have set those values in the data/docker-compose-config.yml file?

====================================

wardo@shuttle004:~/software-installs/openmaptiles$ sudo docker-compose run --rm import-sql
WARNING: The MIN_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The MAX_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The BBOX variable is not set. Defaulting to a blank string.
Timing is on.
CREATE FUNCTION
Time: 7.609 ms
CREATE FUNCTION
Time: 11.284 ms
CREATE FUNCTION
Time: 6.397 ms
CREATE FUNCTION
Time: 5.354 ms
CREATE FUNCTION
Time: 5.944 ms
CREATE FUNCTION
Time: 4.454 ms
CREATE FUNCTION
Time: 49.539 ms
CREATE FUNCTION
Time: 14.911 ms
CREATE FUNCTION
Time: 11.068 ms
CREATE FUNCTION
Time: 10.979 ms
CREATE FUNCTION
Time: 11.067 ms
CREATE FUNCTION
Time: 11.087 ms
CREATE FUNCTION
Time: 10.971 ms
CREATE FUNCTION
Time: 11.101 ms
CREATE FUNCTION
Time: 11.428 ms
CREATE FUNCTION
Time: 10.493 ms
Timing is on.
psql:/sql/tileset.sql:4: ERROR:  function delete_empty_keys(hstore) does not exist
LINE 3:     SELECT delete_empty_keys(slice(tags, ARRAY['int_name', '...
                   ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Time: 3.189 ms

**Comment by ImreSamu** [comment]
>Also, I am not sure why I am seeing warnings regarding MIN_ZOOM, MAX_ZOOM and BBOX variables
> not being set. I have set those values in the data/docker-compose-config.yml file?

it is a known problem/issue ( https://github.com/openmaptiles/openmaptiles/issues/261 )
sorry for the misunderstandings.

> ERROR: function delete_empty_keys(hstore) does not exist

I hope we can resolve this issue in the next 24h.

**Comment by jirik** [comment]
@wardo001 Thanks for reporting.
`delete_empty_keys` is probably related to my work on #211 #252 I will look at it today.

**Comment by wardo001** [comment]
@ImreSamu / @jirik - many thanks for the help. I will go through the related issues and see if there is any useful info. Let me know if there is anything I can do to test / help resolve, although I wont be back onto the Ubuntu machine until late tonight, uk time.

**Comment by ddrmax** [comment]
I can do some testing since I have the same problem (I'm creating a new Openmaptiles and Overpass server), and I can launch some tests between now and 17:00 GMT and between 18:00 and 23:00 GMT

**Comment by jirik** [comment]
I think the problem is that [docker-compose.yml](https://github.com/openmaptiles/openmaptiles/blob/master/docker-compose.yml#L78) contains reference to `openmaptiles/openmaptiles-tools:latest` that is now under development related to #211 #252.
Replacing reference with `openmaptiles/openmaptiles-tools:0.5` and removing the previous image should help. I am going to try it

**Comment by jirik** [comment]
Please try this PR: https://github.com/openmaptiles/openmaptiles/pull/278 It should work

**Comment by wardo001** [comment]
Great, Thanks @jirik. I will try and give it a test later this evening.

**Comment by wardo001** [comment]
Yes, that sorted it. Thank you for the quick fix @jirik / @ImreSamu .
