### ISSUE TITLE
Level (z-dimension) tags missing

### ISSUE THREAD

**Issue by jaakla** [openmaptiles/openmaptiles#280]
We'd need z-level tags to know order of roads for crossings. Current brunnel=bridge/tunnel approach becomes too limited for complex cases.

**Comment by klokan** [comment]
Here we are:
https://openmaptiles.github.io/osm-bright-gl-style/#15.4/52.5108/-1.8639

![gravelly_hill_interchange](https://user-images.githubusercontent.com/59284/26950865-7f255130-4c9f-11e7-88fc-7758cb9544ec.jpg)

**Comment by stirringhalo** [comment]
I've toyed with better z-order sorting in https://github.com/stirringhalo/openstreetmap-mapboxgl/blob/master/osm-v1.json . Effectively, I had to tag with unique numbers https://github.com/stirringhalo/openstreetmap-carto-vector-tiles/blob/master/project.yaml#L610 and then build up lines with data-driven styling. It was less than ideal.

**Comment by jaakla** [comment]
Right, this intersection does not luckily have as many single-level intersections as the map tries to show :) 
![screenshot 2017-06-09 13 55 02](https://user-images.githubusercontent.com/5609650/26972678-74a94460-4d1b-11e7-86b5-92db8389ecc7.png)

**Comment by jirik** [comment]
We already implemented experimental `indoor`, `level`, and `layer` attributes for steps and footways in v3.7: https://github.com/openmaptiles/openmaptiles/commit/e95f2d476b1697324416135abdb97b1a601c3503
Currently it's expecially for testing purposes.
