### ISSUE TITLE
Different zoom level and multiple extracts

### ISSUE THREAD

**Issue by kechap** [openmaptiles/openmaptiles#285]
Is it possible to export tiles for something like the following:

- planet with zoom 0-7
- europe with  zoom 0-14

I tried by running the quickstart again with a custom data folder and enabling the diff mode but I think it doesn't do what I am trying to do. 

Quickstart always deletes previously generated tiles and is dropping the previously imported tables so if you want to go from zoom 0-7 to zoom 0-14 it means that you have to import 0-7 again. 

Is there a way to avoid the import again? Cause it is taking too much time.

**Comment by stirringhalo** [comment]
In principal you could, but you'd have to merge the .mbtiles with your own tool (I don't know anything off the top of my head). Since the .mbtiles is just an sqlite file, you could do it with a bit of python!

**Comment by jirik** [comment]
> Is there a way to avoid the import again?

You can run quickstart step by step, since it's a bash script.
