### ISSUE TITLE
Artifacting in buildings part of associatedstreets or street relations.

### ISSUE THREAD

**Issue by stirringhalo** [openmaptiles/openmaptiles#286]
Linestrings are converted by st_asmvt(geom) into some multilinestrings. Leads to validity issues even with latest postgis.

**Comment by stirringhalo** [comment]
![screenshot](https://user-images.githubusercontent.com/14035518/27940052-642a4d10-6296-11e7-800e-5da943fc602e.png)
Screenshot at #18.99/46.75173/7.61054/-21.6/35 but may only exist in postserve.

**Comment by klokan** [comment]
It seems there are no artefacts on the buildings if Mapnik is used as the MVT generator:
http://editor.openmaptiles.org/?style=https://rawgit.com/openmaptiles/klokantech-3d-gl-style/master/style.json#19.19/46.75173/7.61052/-21.6/35

**Comment by stirringhalo** [comment]
Good to know, I'm closing this then. Postserve is good for quick dev, but not ideal for prod stuff.
