### ISSUE TITLE
Add useful fields for aerodrome tags

### ISSUE THREAD

**Issue by otherjason** [openmaptiles/openmaptiles#288]
Airports are complex features, often made up of several runways, taxiways, buildings, etc, all stored as nodes with the key `aeroway=*` in the OpenStreetMap data. OpenMapTiles uses the `aerodrome`, `heliport`, `runway`, `helipad`, `taxiway`, and `apron` values for the `aeroway` key to select features.

It would be useful if the `aerodrome` type, [which refers to the airport as a whole](https://wiki.openstreetmap.org/wiki/Tag%3Aaeroway%3Daerodrome) was enhanced to add some additional fields when importing into the OpenMapTiles schema. Particularly useful fields that would be good to add are:

- `name` (and/or names in other languages, e.g. `name:de` or `name:en`)
- `iata`
- `icao`
- `ele`
- `aerodrome:type`

Without these details (especially the name and/or IATA/ICAO codes), airports are essentially invisible in the current OpenMapTiles schema (the runways and buildings obviously render fine, but there are no labels for the airport itself).

The same argument could be made for the [`aeroway=heliport` tag type](https://wiki.openstreetmap.org/wiki/Tag%3Aaeroway%3Dheliport). The additional metadata would be useful when styling a map to show these locations.

I would create a PR for this myself, but I'm not sure how to implement this change in the proper way. It looks like `layers/aeroway/mapping.yaml` and `layers/aeroway/` would need to be edited, but I'm not sure how to implement this only for `aeroway=aerodrome` tags.

**Comment by stirringhalo** [comment]
Indeed aerodromes are complicated, I will look into this.

**Comment by stirringhalo** [comment]
Same as https://github.com/openmaptiles/openmaptiles/issues/143
