### ISSUE TITLE
How to generate .mbtiles files with additional OSM data?

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#290]
I am a bit confused about how to do this. Is there a way to generate a `.mbtiles` files with additional OSM data that doesn't seem to be imported or styled using the defaults? Is there an import spec that we can tell the imported to import additional types?

**Comment by stirringhalo** [comment]
Yes, it's entirely possible to import more data! What layers are you trying to import?

See here for the layers to understand what's happening:

https://github.com/openmaptiles/openmaptiles/tree/master/layers

**Comment by nnhubbard** [comment]
I was just curious about the process. Maybe something like `glaciers`?

**Comment by stirringhalo** [comment]
I added glaciers here https://github.com/openmaptiles/openmaptiles/commit/15ff070abd79ef97cf898cf7ab55820b3c77c918

To add layers, you have to modify the mapping.yml, and relevant SQL files. See https://github.com/openmaptiles/openmaptiles/blob/master/layers/landcover/landcover.sql for an example of how this would work.

**Comment by klokan** [comment]
@nnhubbard - in case you have your own vector data to generate, you can make the output into a separate MBTiles.

The documentation of the process is available at: https://openmaptiles.org/docs/generate/custom-vector/

If you do modifications based on OpenStreetMap data, which could be beneficial to the user community of the OpenMapTiles project - please work on the fork and make a pull request - so we can review your changes and add them to the next release of OpenMapTiles.

**Comment by nnhubbard** [comment]
Thank you!

**Comment by karakostis** [comment]
> @nnhubbard - in case you have your own vector data to generate, you can make the output into a separate MBTiles.
> 
> The documentation of the process is available at: https://openmaptiles.org/docs/generate/custom-vector/
> 
> If you do modifications based on OpenStreetMap data, which could be beneficial to the user community of the OpenMapTiles project - please work on the fork and make a pull request - so we can review your changes and add them to the next release of OpenMapTiles.

@klokan In case I have one mbtile file with the OSM vector tiles and another mbtile with my data (converted from shp to vector tiles), how would I combine these two in my OL application? They would overlap unless if I display them in different zoom level. Is there a way that I actually merge these two mbtiles files into one?
