### ISSUE TITLE
Quickstart does not generate docker-compose-config.yml when using  custom OSM data

### ISSUE THREAD

**Issue by mathieudebrito** [openmaptiles/openmaptiles#296]
Hi guys !

I'm following [these instructions](https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md#using-your-own-osm-data) to use my own OSM data (my own PBF file).

But when I run `./quickstart.sh my_osm_file`, [quickstart.sh](https://github.com/openmaptiles/openmaptiles/blob/8ff5d10e8b8dca10ab9a8dff89da3c270437f8bd/quickstart.sh#L138-L157) does recognize that I use my own OSM file and do not generate `docker-compose-config.yml` since it seems that this file is generated right after the download from geofabrik.

So the script continues but when it comes to use the `docker-compose-config.yml`, it fails because it does not exist.

How can I generate the `docker-compose-config.yml` file please ?

Thanks, keep up the good work :)

**Comment by ImreSamu** [comment]
Sorry,  we have only a temporary workaround, see here: 
*  https://github.com/openmaptiles/openmaptiles/issues/227#issuecomment-297190664

The refactoring is planned here:
*  https://github.com/openmaptiles/openmaptiles/issues/261

**Comment by otherjason** [comment]
@ImreSamu When following the workaround mentioned in #227, is that process intended/optimized for use with a full planet file? I thought I had seen a mention somewhere (although I can't find it now) that generating tiles for a full OSM planet file took approximately 1-2 days given a reasonably powerful system. I tried following the procedure described in #227 on a 16-core server with >200GB of RAM, and it's reporting more like an expected 35-day runtime. Is there some other procedure that should be used for large extracts?

**Comment by ImreSamu** [comment]
@otherjason:   

> is that process intended/optimized for use with a full planet file?  ....

For a planet rendering see:  #299   #242  #159
