### ISSUE TITLE
 high-resolution images for printing

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/openmaptiles#297]
According to https://openmaptiles.org/about/ it is possible to turn map tiles in high-resolution images for printing. 

Is there any tutorial available or what would be the workflow for this?

**Comment by klokan** [comment]
TileServer GL supports Static Maps API - where you can set HighDPI / Retina raster output to get rasters with DPI 600 or even higher.

**Comment by pathmapper** [comment]
@klokan thanks! I'll check it out.
