### ISSUE TITLE
Rendering vector tiles directly from Postgres - without Mapnik

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#3]
https://lists.osgeo.org/pipermail/postgis-devel/2016-October/025973.html
https://git.osgeo.org/gogs/postgis/postgis/pulls/5

This is very interesting - as it may save a lot of data transfers and reparsing between Postgres and Mapnik workers - which could mean a significant boost in the speed of the vector tile rendering (of the planet)

It plays well with the openmaptiles "layer-catalog" structure we have discussed - where tm2source is just one of the generated outputs. We could have a lightweight generator with core functionality done directly in SQL - especially for the microtiles sets.

**Comment by stirringhalo** [comment]
Support added with https://github.com/openmaptiles/postgis/pull/4

**Comment by pnorman** [comment]
That's not support - that's a function that builds MVTs, not something which responds to an xyz request with a tile or something that pre-renders a bunch of xyz tiles.

**Comment by stirringhalo** [comment]
I have that already, just needs some minor tweaking https://github.com/openmaptiles/postserve :grinning:

**Comment by stirringhalo** [comment]
PR https://github.com/openmaptiles/openmaptiles/pull/240 for the small changes needed to OpenMapTiles to support postserve. Needs the postserve image added to Docker Hub

**Comment by 2803media** [comment]
@stirringhalo could you please share your varnish set up I'm a bit lost in the config of it with openmaptiles!

Thanks a lot
