### ISSUE TITLE
Error forced-clean-sql: Postgres v9.6, Drop and Recreate PostgreSQL public schema

### ISSUE THREAD

**Issue by tds4u** [openmaptiles/openmaptiles#301]
Moved to a new test server:
- Ubuntu 17.04 64bit
- PostgreSQL 9.6

git clone https://github.com/openmaptiles/openmaptiles.git
./quickstart.sh germany
```
====> : Drop and Recreate PostgreSQL  public schema
docker-compose run --rm import-osm /usr/src/app/psql.sh -c "DROP SCHEMA IF EXISTS public CASCADE ; CREATE SCHEMA IF NOT EXISTS public; "
The MIN_ZOOM variable is not set. Defaulting to a blank string.
The MAX_ZOOM variable is not set. Defaulting to a blank string.
The BBOX variable is not set. Defaulting to a blank string.
... Gave up , No connections with :  pg_isready -d openmaptiles -h postgres -U openmaptiles
Makefile:85: recipe for target 'forced-clean-sql' failed
make: *** [forced-clean-sql] Error 1
```

**Comment by ImreSamu** [comment]
the normal './quickstart.sh'  is working?

**Comment by ImreSamu** [comment]
> Moved to a new test server:
> * Ubuntu 17.04 64bit
> *  PostgreSQL 9.6

NOW './quickstart.sh' is tested, and should work only with [`openmaptiles/postgis`](https://hub.docker.com/r/openmaptiles/postgis/)  docker image.

If you want to use with your own Database server ( `PostgreSQL 9.6` ) then you should modify the ./quickstart.sh; docker-compose.yml ; Makefile,  etc ..  files.

**Comment by tds4u** [comment]
So, PostgreSQL v9.6 and PostGIS v2.3 are not supported yet? Ubuntu 17.04 is shipping with it. Others will follow. Which postgis version are you using - 2.2 or 2.3?

**Comment by ImreSamu** [comment]
please re-check the  [QUICKSTART.md](https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md)
* for a `quickstart.sh` -  no need your own PostgreSQL 9.6 server. 
* check the "First experiment - with albania ( small extracts! ) "
* and if you have some problem, please attach your `./quickstart.log`

>  So, PostgreSQL v9.6 and PostGIS v2.3 are not supported yet? 

We are using [this](https://hub.docker.com/r/openmaptiles/postgis/)  Docker Image : 
*  the source code:  https://github.com/openmaptiles/postgis
    *  Postgres:9.6 ; POSTGIS_VERSION=2.4dev ; GEOS_VERSION=3.6.0 , and lot of special extension, customisation.

**Comment by smellman** [comment]
@tds4u 
https://github.com/openmaptiles/openmaptiles/blob/master/quickstart.sh#L190
Add sleep command before ```make forced-clean-sql```

```bash
sleep 120
make forced-clean-sql
```

In my case (Azure and docker in external storage), sleep command is need.
It seem storage speed issue because my thinkpad X220 with SSD doesn't raise this error.

**Comment by fire-stone** [comment]
It helped to actually restart the whole server.

`init 6`

After that i could restart the quickstart.sh <<region>>
