### ISSUE TITLE
Country code property missing in v3 on countries layers

### ISSUE THREAD

**Issue by nicooprat** [openmaptiles/openmaptiles#305]
Hi,

I just switched from v2 to v3, and it looks like the country layers doesn't contain the `code` property anymore. Is it intentional? Any way to get this behavior back? 

Thanks!

**Comment by jirik** [comment]
Related to https://github.com/openmaptiles/openmaptiles/issues/306

PR welcome. I am wondering which code is more suitable. ISO 3166-1 alpha-2 or ISO 3166-1 alpha-3?

**Comment by nicooprat** [comment]
Oh, right, didn't found this one. I'm pretty noob at carto stuff so I'll just close this issue and follow the other one.

In my case I'm using the `cca2` field lowercased: https://github.com/mledoze/countries/blob/master/countries.json

Thanks!

**Comment by jirik** [comment]
Just fo clarity, `cca2` is ISO 3166-1 alpha-2.
