### ISSUE TITLE
Feature Request: add abbreviation fields for country/state points

### ISSUE THREAD

**Issue by otherjason** [openmaptiles/openmaptiles#306]
When zoomed out on a map, it can be useful to utilize abbreviations for country/state labels when appropriate, especially for those with small area. The Natural Earth dataset contains an `abbrev` field that is useful for this purpose. Is it feasible to merge this in with the `place` nodes that have class `country` or `state`?

**Comment by jirik** [comment]
@otherjason Thanks for suggestion. Yes, it is feasible. Dou you want to look at it? It means to create new `abbrev` attribute in `place` layer and to fill it with NE data for lower zoom levels. It should be quite straightforward.

**Comment by otherjason** [comment]
I'm willing to give it a look if you can provide some pointers to where
that might be done. All I see in the repository are layer mapping
definitions for the schema; I'm assuming that the merging of Natural Earth
data is done elsewhere.

**Comment by jirik** [comment]
@otherjason Sorry for confusion, country names are completely taken from OSM now, so it is better to take the new attribute from OSM data.

Some hints:
https://www.openstreetmap.org/node/424310601
- you are probably interested in `ISO3166-1` or `country_code_iso3166_1_alpha_2` tag (whichever gets you better result)

https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/mapping.yaml
- [add mapping for the tag](https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/mapping.yaml#L41) (e.g. `ISO3166-1`)

https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/layer.sql
- [add new attribute `abbrev`](https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/layer.sql#L6)
- [use value of the OSM tag for `abbrev` attribute in case of countries](https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/layer.sql#L23)
- set `null` values for `abbrev` attribute for other places

https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/place.yaml
- [add `abbrev` to query](https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/place.yaml#L56)
- [add description of `abbrev`](https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/place.yaml#L19)

Finally you need to do some testing. Run quickstart.sh to generate tiles, start tileserver-gl and use inspect mode to see if the new `abbrev` attribute.
You should use also maputnik to change some style to show the new abbrev attribute as a final visual check. Printscreen would be fine.

**Comment by nicooprat** [comment]
Glad to see this feature coming back! But I still can't find iso names in `https://free.tilehosting.com/data/v3.json?key=...`, so I guess it's waiting some release? How can we now when it will be available? Thanks.

**Comment by jirik** [comment]
Yes, we are waiting for 3.7 release and deploy. We are already working on it, should be available till December 10 at free.tilehosting.com

**Comment by nicooprat** [comment]
Working great, thanks!
