### ISSUE TITLE
A 3d building too large

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#307]
Today I have seen a huge building covering large area at:

![screen shot 2017-07-14 at 09 56 27](https://user-images.githubusercontent.com/59284/28204081-c0745606-687c-11e7-98e5-092a721dd8f0.png)

Is it import problem or OSM data problem?

An example case for QA check @jirik

**Comment by jirik** [comment]
https://openmaptiles.github.io/klokantech-3d-gl-style/#14.03/47.3434/8.5786/13.6/60

**Comment by jirik** [comment]
![image](https://user-images.githubusercontent.com/2271850/28211386-afb79fec-689c-11e7-9649-2db2b462217e.png)

**Comment by jirik** [comment]
Seems like a problem in [data](https://www.openstreetmap.org/relation/3188477#map=15/47.3404/8.5747). According to [wiki](https://wiki.openstreetmap.org/wiki/Relation:building), 

> relations with type=building are used to group elements that form a building.

This is obviously not building or building part. This relation is there unchanged for almost 4 years.

**Comment by jirik** [comment]
Actually, here is the building that was probably meant to be mapped:
https://www.openstreetmap.org/relation/3188477#map=19/47.33593/8.58038

**Comment by jirik** [comment]
Fixed in the data.
