### ISSUE TITLE
Displayable tile size ...

### ISSUE THREAD

**Issue by Tom-Cuthill** [openmaptiles/openmaptiles#309]
Hi,

I am using tileserver-gl to serve up the openmaptiles offering for Australia.  I've found that the internal coordinate system of the tiles is 4096 by 4096, and I assumed that the tiles were meant to be displayed at 256 by 256 bytes.  So it is a simple matter of dividing the coordinates by 16 to render to pixels on the display.

Something strange is happening though.  When I compare the images seen in my program to what Maputnik produces, next to one another on the same display, Maputnik is behaving as if the tile display size was 1024 by 1024, not 256 by 256.

Here is a side by side comparison, to consider the size of things:

![image](https://user-images.githubusercontent.com/24502866/28299049-83325100-6ba9-11e7-9bc6-d18574c539e6.png)

The left image is from Maputnik and in Chrome I can use the developer tools to verify that the tiles being displayed are downloaded at zoom level 11.  The image on the right is from my program, where I am displaying tiles at zoom level 13, and I am definitely displaying each tile in a clipped 256 by 256 pixel extent.  The sizes of the water bodies are close, although there appears to be some vertical distortion.

I am at a loss to explain what is going on.  What is the display size of the tiles coming down from the OpenMaptiles data?

Any insights greatly appreciated,

Tom Cuthill

**Comment by klokan** [comment]
I am sorry but your question is unrelated to this repository (which defines OpenMapTiles layers and features contained in the vector tiles).

You have mentioned TileServer GL, but it seems you work on your own rendering application - "my program"?

Vector tiles are vector - described geographic area follows Spherical Mercator:
http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/

but Mapbox internally made a decision to work by default with 512 tiles. Check related ticket:
https://github.com/klokantech/tileserver-gl/issues/144
