### ISSUE TITLE
Documentation : choose a style

### ISSUE THREAD

**Issue by christopheblin** [openmaptiles/openmaptiles#314]
In the documentation at https://openmaptiles.org/docs/, the third step "choose your style" does not say how to do it with tileserver-gl

The problem is that if I follow the docker path, I correctly have the tileserver-gl with osm bright and Klokantech Basic but how do i add another theme.

The other page https://openmaptiles.org/styles/ does not help either.

I'd just like some indication here to get started

**Comment by jirik** [comment]
You can find it in documentation of TileServer-GL:
http://tileserver.readthedocs.io/en/latest/config.html#styles
http://tileserver.readthedocs.io/en/latest/config.html#referencing-local-files-from-style-json

If you have more specific question about configuration of TileServer-GL, please ask at https://github.com/klokantech/tileserver-gl repo.
