### ISSUE TITLE
run generate-changed-vectortiles timeout

### ISSUE THREAD

**Issue by loosi** [openmaptiles/openmaptiles#317]
Hi,

anyone having trouble with timeouts at `generate-changed-vectortiles` ?
v3.6.2 is checked out

```
[33.5s]   9.9719%    497/  5.0k @   15/s | ✓ 497 □ 3 | 5m 2s left
/usr/local/lib/node_modules/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^
Error: Copy operation timed out
    at Timeout.<anonymous> (/usr/local/lib/node_modules/tilelive/lib/tilelive.js:390:22)
    at Timeout.wrapper (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```
I actually tried a completely fresh start in a new repository but I'm still struggling with the updates. 
Complete vector generating (`generate-vectortiles`)works fine, imposm imports etc also fine. 

`run update-osm`works fine with daily updates. 
No messages at postgres container

tiles.txt looks like 
`14/8645/5603
14/8593/5436
`

 Timeouts always occur after approx. 30 sec. (30-35). 
Anyone else having that problem? Im unsure how to debug, there are no messages anywhere and no debug flag for tilelive-copy. What about running it manually with debug flags in a self-spawned container without docker-compose  ?

Thx

**Comment by MartinMikita** [comment]
Increase timeout value, environment variable `TILE_TIMEOUT` in [docker-compose.yml](https://github.com/openmaptiles/openmaptiles/blob/master/docker-compose.yml#L111).
Default value is 1800000 ms => 1800 s => 30 m.

Use the latest version (3.9) and probably you would need better hardware machine with fast disks for PostgreSQL - the database SQL query may take longer for some regions.

**Comment by NasH5169** [comment]
Thanks for your answer. I'm already using OpenMapTiles v3.9 version.

I've done some tests still with france.osm.pbf with increasing the timeout to 7200000 ==> 2 hours and same issue --> Timeout.

My hardware is not the best but not the worst too: i7 4.7 GHz / 16 GB / SSD

In my case, the timeout appears at the very end of the process and 2 tilecopy remaining processes seem to work a long time... More than 2 hours for now. Perhaps to build first zoom tiles with no really must data but, you're right, big queries...

Continuing my tests by decrease concurrency option from 10 to 6.

Thanks again.

**Comment by MartinMikita** [comment]
Hmm, another idea - are you using a correct bounding box (`BBOX`) for the extract you have imported?
Try to set the [value in `.env`](https://github.com/openmaptiles/openmaptiles/blob/master/.env#L10) to bounding box of France, for example [see **Bounds** here](https://openmaptiles.com/downloads/europe/france/).

Note, the only working concurrency option is max 4, mapbox-tile-live-copy does not support higher values now.

**Comment by NasH5169** [comment]
My BBOX is quiet the same and a little more smaller.

I will force to 4 the concurrency option because the default value with the generate-vectortiles docker image is 10: https://github.com/openmaptiles/generate-vectortiles/blob/v0.1.1/export-local.sh

Speaking of generate-vectortiles image, the targeted version by OpenMapTiles project is 0.1.1. There is a newer tag 0.1.2 but the tilecopy script seems to be the same.

Another funny thing is the MAX_ZOOM option in the tilecopy command line. In my .env file, I put 12 but the command line uses 13:

![htop](https://user-images.githubusercontent.com/6979479/52178417-88993900-27ce-11e9-8f09-d3ddd8eb6ee2.png)

```
BBOX=-5.6,41.1,9.9,51.5
MIN_ZOOM=0
MAX_ZOOM=12
TILE_TIMEOUT=7200000
COPY_CONCURRENCY=6
```

**Comment by NasH5169** [comment]
_Update_

I've found the docker-compose-config.yml in the data folder with the max_zoom 13 so i reduce to zoom 12. The generation duration is about 18~19 minutes so 10 minutes less. With 4 concurrency tasks, i still have 2 remaining processes taking 100%CPU for 14 hours now...

I will test the same configuration on a professional server hardware.

```
[18m 4.182000000000016s]  99.9604%  30.3k/ 30.3k @   28/s | ✓ 30.3k □ 10.8k | 0s left
[18m 4.260999999999967s]  99.9901%  30.3k/ 30.3k @   28/s | ✓ 30.3k □ 10.8k | 0s left
```
![htop2](https://user-images.githubusercontent.com/6979479/52200103-1e34d700-2868-11e9-91cb-a30ae5ba20fa.png)

**Comment by NasH5169** [comment]
_The story continues..._

New test with a dedicated server Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz and 32 GB RAM.

Same issue: 2 remainings tilelive-copy processes taking each 100% CPU.

The last logs:

> [1h 50m 14.438000000000102s]  99.9893% 196.1k/196.1k @   29/s | ✓ 196.1k □ 71.8k | 1s left
> [1h 50m 14.457000000000335s]  99.9908% 196.1k/196.1k @   29/s | ✓ 196.1k □ 71.8k | 1s left
> [1h 50m 14.556999999999789s]  99.9985% 196.1k/196.1k @   29/s | ✓ 196.1k □ 71.8k | 0s left

**Comment by NasH5169** [comment]
Finally get working it by update the generate-vectortiles Dockerfile:

(i've certainly cleaned it too much but no more timeout and the export-local.sh run perfectly)

```
FROM node:8
MAINTAINER Lukas Martinelli <me@lukasmartinelli.ch>
WORKDIR /usr/src/app

RUN npm_config_user=root npm install -g \
        @mapbox/mbtiles \
        @mapbox/tilelive \
        tilelive-tmsource

VOLUME /tm2source /export
ENV SOURCE_PROJECT_DIR=/tm2source EXPORT_DIR=/export TILELIVE_BIN=tl
COPY . /usr/src/app/
CMD ["/usr/src/app/export-local.sh"]
```

**Comment by NasH5169** [comment]
Hi all,

Coming back on this closing issue.

My update of generate-vectortiles dockerfile is still great. No more issue.

Do you (OpenMapTiles team) think it will be ok to sent a pull request on the generate-vectortiles repository?

**Comment by AnSmol** [comment]
+1. I also have faced this issue

**Comment by AnSmol** [comment]
@NasH5169 you dockerfile did the job, thank you!

@MartinMikita I think this issue should be reopened.  
Increasing TILE_TIMEOUT and decreasing COPY_CONCURRENCY=4 do not fix it.
