### ISSUE TITLE
how to use mapbox studio classic styles with mapbox resource links?

### ISSUE THREAD

**Issue by hellowtisch** [openmaptiles/openmaptiles#318]
When I try to use e.g. Klokantech's 3d style with the openmaptiles stack, through an edited style.json file, there are numerous errors that the sprites cannot be found under the mapbox:/ URL.
The same problem occurs after uploading the style to mapnik, adding my mapbox api public key and exporting it afterwards.
Please add documentation on how to get this done.

**Comment by jirik** [comment]
Replied at https://github.com/openmaptiles/klokantech-3d-gl-style/issues/3
