### ISSUE TITLE
Proposed Road & Under Contruction Road

### ISSUE THREAD

**Issue by joaokho** [openmaptiles/openmaptiles#321]
There is any tag for proposed road and under contraction road on openmaptiles styles

**Comment by jirik** [comment]
Neither proposed roads nor under construction roads are handled rin the schema right now. Related tags:
- https://wiki.openstreetmap.org/wiki/Key:construction
- https://wiki.openstreetmap.org/wiki/Tag:highway%3Dproposed
- https://wiki.openstreetmap.org/wiki/Key:proposed

**Comment by MartinMikita** [comment]
see [description of lifecycle](https://wiki.openstreetmap.org/wiki/Key:highway?uselang=en-US#Lifecycle).

An example: [The bridge `Honk-Kong-Zhuhai-Macao`](https://www.openstreetmap.org/way/572611768/history) has been tagged incorrectly as completed, but fixed later, now it is not visible in OSM vector tiles.

It could be probably as a separate layer, with other "proposed" or "under construction" items in OSM.
To be researched.

Pull requests are welcome, if you are able to compare the sizes and counts, @joaokho

**Comment by eva-j** [comment]
https://github.com/openmaptiles/openmaptiles/pull/677 merged, thanks.

**Comment by golubev** [comment]
Thanks, @eva-j

**Comment by golubev** [comment]
Can someone update docs and schemas, please? That PR has brought some changes.

Also, it would be great if someone could check whether the docs had been updated correctly in the https://github.com/openmaptiles/openmaptiles/pull/677.

/cc @eva-j @nyurik

**Comment by zvukoper** [comment]
Thank you, @golubev !!!

**Comment by nyurik** [comment]
@golubev `make generate-devdoc` is your friend :) Just make sure you run `docker pull openmaptiles/openmaptiles-tools` to get the latest docker image.  Pushed updated images as https://github.com/openmaptiles/openmaptiles/commit/73c7290893255ae49c122a158083944f5964d658 

We should somehow make validation of the docs as part of the make file (should be fairly straightforward)

**Comment by golubev** [comment]
Thanks, @nyurik! See https://github.com/openmaptiles/openmaptiles/pull/700.
