### ISSUE TITLE
Transnistria and other states with limited recognition

### ISSUE THREAD

**Issue by MattBlissett** [openmaptiles/openmaptiles#322]
Transnistria, a self-proclaimed state with very limited recognition, is rather prominent on the 3.6.1 tileset. It blocks out Moldova's label.

Likewise, South Ossetia blocks out Georgia. Abkhazia, the Nagorno-Karabakh Republic and the Turkish Republic of Northern Cyprus are also shown, as is Kosovo -- although Kosovo has much wider recognition than any of the others.

The Sahrawi Arab Democratic Republic and Somaliland are *not* shown.

It would be helpful to have consistency here, to avoid the appearance of recognizing some of these over others.

See https://en.wikipedia.org/wiki/List_of_states_with_limited_recognition

**Comment by klokan** [comment]
Thanks for the report; Any chance to work on a pull request improving the current situation @MattBlissett ?

See: https://github.com/openmaptiles/openmaptiles/tree/master/layers/boundary

**Comment by nvkelso** [comment]
Suggest looking at new v4-beta Natural Earth (on github) which has min_label property for this purpose. Are you reading counties from NE or  a join onto OSM? If join, I should look at wikidata concordances (like localities, and also regions).

**Comment by klokan** [comment]
@jirik are we going to be able to improve this and prevent similar issues in the future releases of OMT?

Partly a regression on #195

**Comment by nvkelso** [comment]
v4 Natural Earth will be released in next 2 weeks and will have the `min_label` property you can use for this.

@ImreSamu What do you think about doing a similar join for all the Natural Earth counties to get Wikidata IDs? Is that the best way to effect the OMT join?

**Comment by jirik** [comment]
Fixed by https://github.com/openmaptiles/openmaptiles/commit/b88b34c98d9e04c23d799922d7754c1daf62b066. Tested on South Ossetia and Abkhazia.

@MattBlissett The Sahrawi Arab Democratic Republic is not tagged as place=country, as well as Somaliland.
