### ISSUE TITLE
Bad lake polygon in New Jersey

### ISSUE THREAD

**Issue by nspringer-alk** [openmaptiles/openmaptiles#323]
There is a water:lake polygon at 41.0000/-74.5000 that is incorrect and should be removed.  It seems to be a landcover:wood:wood polygon that somehow got added to the water layer.  This is not a problem in the latest OSM data at openstreetmap.org

There also seems to be an associated watername:lake point associated with this polygon called "Hibernia Ponf" (not a typo).

FWIW it seems like the OSM wood poly has issues too in the base data: https://www.openstreetmap.org/#map=12/40.9958/-74.4722&layers=H

![image](https://user-images.githubusercontent.com/7513188/29632243-66f1e6d0-8810-11e7-9f7e-ea9beae6ea23.png)
![image](https://user-images.githubusercontent.com/7513188/29632294-936d98c6-8810-11e7-91ec-129c2d432b35.png)
![image](https://user-images.githubusercontent.com/7513188/29632258-7212250c-8810-11e7-8ea9-f22d1dafaf02.png)
![image](https://user-images.githubusercontent.com/7513188/29632462-146c3bd0-8811-11e7-80f6-4ab4680012b1.png)

**Comment by jirik** [comment]
Actually the relation exists in OSM data:
http://www.openstreetmap.org/relation/279304#map=12/40.9721/-74.3843&layers=H

**Comment by jirik** [comment]
On March 31 2017 natural was changed from wood to water:
https://osmlab.github.io/osm-deep-history/#/relation/279304
@nspringer-alk Could you please fix it in OSM?

**Comment by nspringer-alk** [comment]
Fixed in OSM.
https://www.openstreetmap.org/changeset/51410334
https://www.openstreetmap.org/changeset/51410427

**Comment by jirik** [comment]
For some reason, update process of OMT does not take into account changes in water relations (polygons). Probably related to older [Iberian peninsula issue](https://github.com/klokan/openmaptiles.com/issues/285).

**Comment by jirik** [comment]
Tested on current New Jersey extract, the bad lake is not there. I am closing this issue. It will be deployed after deploy of OMT v3.7.
