### ISSUE TITLE
Is there an openmaptiles-server dockerfile?

### ISSUE THREAD

**Issue by grudda** [openmaptiles/openmaptiles#324]
Maybe not the best place to ask this question, but I don't found a better one. We tried to install your image from https://hub.docker.com/r/klokantech/openmaptiles-server/ in our infrastructure, but the OS is currently not supported by our IAAS provider. So I'm asking if it would be possible to get the dockerfile from you, to create an image based on a different OS?

**Comment by klokan** [comment]
What OS image do you need?
What is the IAAS provider restricting you on the Docker base image?

BTW Feel free to install our TileServer GL with open-source code and Dockerfile available at  https://github.com/klokantech/tileserver-gl

**Comment by grudda** [comment]
Currently they support following OS https://docs.jelastic.com/docker-supported-distributions, probably to be able to handle all maintenance aspects and ensure service and support. 
That's why we currently would need a Debian 8 image, but as I also talked to them, in the beginning of September they will upgrade the platform to the next version, which will be also able to handle Debian 9. So we will wait until then and no further actions are needed from your side. Anyhow thanks for the hint to TileServer GL.
