### ISSUE TITLE
Oneway tag?

### ISSUE THREAD

**Issue by andreasflind** [openmaptiles/openmaptiles#325]
The oneway tag seems to have disappeared, can anyone confirm the same issue?

**Comment by jirik** [comment]
I can see it in the schema and in the data. Could you please be more specific?

**Comment by andreasflind** [comment]
I must have messed up my layers, oneway and ramp just seems to have disappeared from transportation.
I was just sure i hadn't touched it so i had to make sure you guys saw it in your data before trying to fix it on my end.
