### ISSUE TITLE
Boosting performance

### ISSUE THREAD

**Issue by dtarnawczyk** [openmaptiles/openmaptiles#327]
Hi,
We are facing performance issues while generating complete world db. According to our estimates it would take 86 days on infrastructure class tier1, 4cpus, 4GB RAM. From our experiments the bottleneck of the whole process is db access with only 4 threads working. Could you have any solution or hints how to speed up generation ?

Best regards,
Dominik

**Comment by setaou** [comment]
I am facing the same performance limit of 4 threads, but on a way more powerful machine (28 cores, 128GB RAM, SSD). I would be happy to know if there is a way to use more threads and finally use all the ressources of my hardware.

**Comment by MartinMikita** [comment]
This is expected (optimistic) generating time duration for the whole planet.

We offer the generating of tiles for the whole planet on our cluster as a service (with our hardware setup it is done in one day): https://openmaptiles.com/cluster-rendering/
The complete latest planet is also available at as part of the Production package: https://openmaptiles.com/production-package/ - delivered with weekly updates! (every week you can download a new MBTiles with latest OpenStreetMap data).

This ticket is a duplicate to #242 #299.
Closing.
