### ISSUE TITLE
Maintain Building-Information from zoom 10 - zoom 14

### ISSUE THREAD

**Issue by devtim123** [openmaptiles/openmaptiles#329]
I am editing the layerdefinitions and want to maintain all buildings from z10 - z14. Here is the magic code:
```
CREATE OR REPLACE FUNCTION layer_building(bbox geometry, zoom_level int)
RETURNS TABLE(geometry geometry, osm_id bigint) AS $$
    SELECT geometry, osm_id
    FROM (
        -- etldoc: osm_building_polygon -> layer_building:z14_
        SELECT DISTINCT ON (osm_id)
           osm_id, geometry
        FROM osm_all_buildings
        WHERE zoom_level >= 10 AND geometry && bbox
    ) AS zoom_levels
    ORDER BY ST_YMin(geometry) DESC;
$$ LANGUAGE SQL IMMUTABLE;
```

For any reason some of the buildings disapear at zoom level 12, more on 11 and even more at zoom 10, even though i edit the layerdefinition. It looks like that too small polygon-information is not rendered on certain zoom levels. Can you give me a hint what the reason could be?

**Comment by ImreSamu** [comment]
> and want to maintain all buildings from z10 - z14. 
>. It looks like that too small polygon-information is not rendered on certain zoom levels.
> Can you give me a hint what the reason could be?

The reason may be in the  [vector tiles specification](https://www.mapbox.com/vector-tiles/specification/)
You want high precision - but the vector tiles is a space-efficient encoding format with simplification and roundings.

You can check the format here: https://github.com/mapbox/vector-tile-spec/tree/master/2.1
_"A layer MUST contain an **extent** that describes the width and height of the tile in integer coordinates. "_
You have to focus: "extent" value,     Now the default is 4096;  so everything rounded to 4096x4096 in that tiles.
