### ISSUE TITLE
Feature-Request: Create .mbtiles only with selected layers (plus filters)

### ISSUE THREAD

**Issue by fawick** [openmaptiles/openmaptiles#335]
For the moment, the quickstart.sh extract is always feature-complete, but restricted to a certain area. I'd love to be able to fetch the whole world, but only a few (potentially filtered) layers from it. As a user, I would like to be able to generate a .mbtiles with this project that only contains certain layer and even these layers with filters. 

For example, in my personal use case, I would like to create an .mbtiles for a world-wide base map, i.e. it only contains oceans, rivers, boundaries with admin_level==2, and some populated places.

**Comment by jirik** [comment]
@fawick To render only some layers using quickstart, you can simply delete/comment layers you don't want in https://github.com/openmaptiles/openmaptiles/blob/master/openmaptiles.yaml
For more detailed filters, you can edit SQL or yaml files of appropriate layers.

Another approach would be to delete unwanted layers/features from existing .mbtiles using tools such as https://openmaptiles.com/tileshrink/

**Comment by fawick** [comment]
@jirik Thanks for the suggestions. But that would still import the whole geofabrik file. My idea was to already limit the data that is brought in from the OSM rawdata

**Comment by fawick** [comment]
Does openmaptiles.yaml support adding filters to the layers?

**Comment by jirik** [comment]
Actually this approach limits also amount of data imported from geofabrik into PostgreSQL database.

openmaptiles.yaml does not support adding filters to the layers. You can filter out features of one layer inside layer definition. For boundaries with admin_level=2, you should edit https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.sql

**Comment by fawick** [comment]
Oh, cool, thanks for the clarification!
