### ISSUE TITLE
Regenerate mbtiles after changing area.osm.pbf or max_zoom

### ISSUE THREAD

**Issue by fawick** [openmaptiles/openmaptiles#336]
I wonder what steps from quickstart.sh I could skip after changing MAX_ZOOM envvar or after downloading another area.

My guess was that only the calls to import-osm, import-sql, generate-vectortiles, generate-metadata and the chmod to 666 would be needed again (so I don't have to download naturalearth, osmborder and water each time). 

I replaced albania-latest.osm.pbf with andorra-latest.osm.pbf and set MAX_ZOOM to 14. However, starting from zoom level 11 it does always give me 404 Not Found in tileserver.

**Comment by jirik** [comment]
Your guess is correct, but before these steps, you should run also
```
docker-compose run --rm openmaptiles-tools make clean
docker-compose run --rm openmaptiles-tools make
```

**Comment by fawick** [comment]
@jirik Thank you, again!

For the sake of completeness and a reference for others: I found than when I exchanged the area `.osm.pbf` by hand that I would need to rewrite/regenerate `data/docker-compose-config.yml`. Either manually or by calling the relevant commands from https://github.com/openmaptiles/import-osm/blob/3d88dae9b28eb2d244a5c46d22c08f0945a2f897/download-geofabrik.sh#L24 up to end of the script:

```shell
osmconvert  --out-statistics  ${AREA}.osm.pbf  > ./osmstat.txt

lon_min=$( cat osmstat.txt | grep "lon min:" |cut -d":" -f 2 )
lon_max=$( cat osmstat.txt | grep "lon max:" |cut -d":" -f 2 )
lat_min=$( cat osmstat.txt | grep "lat min:" |cut -d":" -f 2 )
lat_max=$( cat osmstat.txt | grep "lat max:" |cut -d":" -f 2 )

cat > $DOCKER_COMPOSE_FILE  <<- EOM
version: "2"
services:
  generate-vectortiles:
    environment:
      BBOX: "$lon_min,$lat_min,$lon_max,$lat_max"
      OSM_MAX_TIMESTAMP : "$timestamp_max"
      OSM_AREA_NAME: "$AREA"
      MIN_ZOOM: "$QUICKSTART_MIN_ZOOM"
      MAX_ZOOM: "$QUICKSTART_MAX_ZOOM"
EOM
```

**Comment by jirik** [comment]
`make download-geofabrik area=<area>` should do it automatically

**Comment by fawick** [comment]
I needed to run the commands by hand as I was eventually working with `planet.osm.pbf`, which cannot be obtained with `download-geofabrik`
