### ISSUE TITLE
Coastline + borders outdated

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#337]
The coastline in the vector tiles is outdated now - because the data are backed into the docker image...

We should consider update of the data/dockers for the next release

esp.
https://github.com/openmaptiles/import-water
https://github.com/openmaptiles/import-osmborder

> From: Sam Brown from https://twitter.com/env_analytics
> I've worked out the problem: the changeset (http://www.openstreetmap.org/changeset/50896332) is 3 months old whereas the openmaptiles/import-water:0.5 image on the Docker hub was built 4 months ago, and bakes in old data. Everything works fine if I clone the source repo and docker-build myself, but you might want to consider rebuilding the Docker hub images periodically.

**Comment by jirik** [comment]
@klokan I am working on `import-water`. The second one, `import-osmborder`, needs to be done in server.

**Comment by jirik** [comment]
Water updated: https://github.com/openmaptiles/openmaptiles/commit/1244c8dacd4fa39939dc8ac78b43d843ca0557f7

**Comment by MartinMikita** [comment]
OSMBorder data updated, [commit in this repo](https://github.com/openmaptiles/openmaptiles/commit/c11a4cd99892121531e4f03b5671a119807cbf08), [osmborder:v0.4](https://github.com/openmaptiles/import-osmborder/releases/tag/v0.4), using OSM Planet 2017-11-20

**Comment by jirik** [comment]
Great, thanks.
