### ISSUE TITLE
Layers refer to obsolete natural-earth relations

### ISSUE THREAD

**Issue by amatissart** [openmaptiles/openmaptiles#352]
With latest natural-earth data (v4.0.0), some layers (such as "boundary") use sql tables that do not exist anymore.

For instance `ne_10m_admin_1_states_provinces_lines_shp` has been removed.
(see https://github.com/nvkelso/natural-earth-vector/blob/v4.0.0/CHANGELOG#L136)

This may be due simply to an unnecessary "_shp" suffix : https://github.com/nvkelso/natural-earth-vector/issues/123

**Comment by nvkelso** [comment]
Technically v3 Natural Earth removed the _shp theme, so you’re certainly in for an update to v4!

**Comment by amatissart** [comment]
So I am confused about why the "boundary" layer still refer to "_shp" : 
https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.sql#L44

As far as I understand, `ne_10m_admin_1_states_provinces_lines_shp` was part of the natural-earth distributed data (v3) even if it was supposed to be removed.

**Comment by nvkelso** [comment]
It may still be downloadable, but it hasn’t been part of the set for a while - since Unicode utf8 conversionof the SHP negated the need for GeoDB master.

**Comment by amatissart** [comment]
Ok thanks, 
so I suppose it's the openmaptiles "boundary" layer that needs to be updated ?

**Comment by nvkelso** [comment]
Yes. There's also a new `min_zoom` property that you can use to throttle
how many boundaries are displayed per zoom to not clog up the tiles with
things that are too dense to show.
