### ISSUE TITLE
Tag disputed country names

### ISSUE THREAD

**Issue by jaakla** [openmaptiles/openmaptiles#364]
Can you tag disputed country names separately (**disputed = 1** perhaps, like with borders)? For example this map view has already 3 of them, and we have user reports sending official letters. I know it may be not that simple as OSM does not have consistent tagging. Maybe stop taking country names from OSM, and rely on other sources, so take only name contents (for translations), but listing from own controlled/UN sources?

![screenshot 2017-11-17 15 00 53](https://user-images.githubusercontent.com/5609650/32948568-5e38a066-cba8-11e7-9e9c-19d03aad1b50.png)

**Comment by MattBlissett** [comment]
This relates to #322 .

I worked around the issue using a stylesheet matching for these names and replacing/hiding them.

**Comment by jaakla** [comment]
Closing this issue as it is really duplicate of #322
