### ISSUE TITLE
M6 Toll UK Motorway

### ISSUE THREAD

**Issue by chebourne** [openmaptiles/openmaptiles#366]
In the UK the M6 motorway is split in two - 'M6' and 'M6 Toll'. M6 Toll is effectively a separate motorway.

At present the ref tag in OpenMapTiles for both is M6. Can this be changed to M6 Toll where appropriate.

OSM tags have the ref as M6 Toll but that is not coming through to the OpenMapTiles vector layers Ref.

**Comment by klokan** [comment]
Pull request with the relevant code for this modification is welcome.

If you don't code - you can get support from the OpenMapTiles team to make this happen at https://openmaptiles.com/support/

**Comment by chebourne** [comment]
Well that's a challenge!

Yes, I do code - i'll get things setup.

One thing - the 'M6 Toll' label woul dhave a reflen of 7 but the sprites in styles like OSM_Bright are only setup for reflen of 6 maximum. Should I transform the label to 6 characters i.e. 'M6Toll', or should I not worry about affecting styles and leave that to style designers to sort out?

**Comment by jirik** [comment]
I thing you should leave it to style designers or -- better -- create icon also for reflen 7 ;-)

**Comment by klokan** [comment]
Any update @chebourne ? We are just reviewing changes for v3.9.
If you let us know within a week we may bring it in for next version...

**Comment by chebourne** [comment]
I have not managed to do anything on this i'm afraid.


________________________________
