### ISSUE TITLE
How can I use my own styles on openmaptiles-server? 

### ISSUE THREAD

**Issue by gmuc** [openmaptiles/openmaptiles#371]
Is there any documentation? I assume it's work over -v $(pwd):/data. But how?

**Comment by gmuc** [comment]
Is there any documentation? I assume it's work over -v $(pwd):/data. But how?

**Comment by klokan** [comment]
Use the web wizard - choose "Advanced options" on the "Styles" page and upload your own JSON style directly to the web interface.

This will create the config for you and store the style in your data volume.

**Comment by gmuc** [comment]
It work! Great! But how can I this without wizzard, if I want start server in batch?

**Comment by bravecow** [comment]
@klokan Does this mean that uploaded styles can't contain icons?

**Comment by klokan** [comment]
From JSON of the style, you can link any asset you want (it is just URL to a public web server).
