### ISSUE TITLE
Tiles generation errors are not logged

### ISSUE THREAD

**Issue by Duke74** [openmaptiles/openmaptiles#373]
There is no way to be sure that all tiles have been successfully generated.
There is some info in the quickstart.log but there is no difference between skipped tiles and failed ones.

`100.0000% 275.3k/275.3k @ 107/s | ? 275.3k ? 100.6k`

Here for example there is 100.6k skipped or failed tiles but we are not sure if it is because it was empty tiles or because there was an issue generating the tiles.

I noticed this issue while trying to create my own layers, when I saw that there was some missing tiles on the map. It finnaly seems that I had to increase the buffer_size. (Maybe someone can help me understand why ? I don't understand precisely what is the role of the buffer_size parameter)

Maybe this should be corrected directly on tilelive/tilelive-copy ?https://github.com/mapbox/tilelive/blob/master/bin/tilelive-copy
If that's the case I'll just close the issue and I'll open a new one there.

**Comment by unibasil** [comment]
https://www.mapbox.com/help/studio-classic-sources/#data-layer-options

> When you import a data source using Add layer, you can set the buffer size for the source. A buffer on a layer allows you to include extra data around the outside of each tile. Depending on the data and desired styles this can be necessary to ensure seamless rendering across tile boundaries. Tile buffers are set individually for each layer; different layers have different requirements and it’s important to make boundaries no larger than necessary in order to keep the size of your vector tiles to a minimum.
> 
> The buffer setting is measured in pixels (assuming that the vector tile is rendered at 256×256 pixels).
> 
> General guidelines when setting the buffer size:
> 
> - Buffers for label layers should be quite large — often 128 pixels.
> - Buffers for line and polygon layers should be at least half the width of the widest stroke you think you’ll want to draw.

**Comment by jirik** [comment]
The buffer_size works as described. Questions about tilelive logs and difference between skipped tiles and failed ones belong to the tilelive repo. If you get there relevant answer, please put a reference here. Thanks.
