### ISSUE TITLE
Is there any way that we can self-host openmaptiles server running HTTPs (to serve vector tiles)

### ISSUE THREAD

**Issue by nguyendh2601** [openmaptiles/openmaptiles#377]
0down votefavorite | I was following https://openmaptiles.com/server/ guide to self-host a vector tiles server by using Docker (Kitematic), it was working well but i couldn't find the way to configure to run the server on HTTPs (since my application is running on HTTPs and it's not allowed to request to get tiles from HTTP server)Please help to advise on this matter? Thanks in advance!
-- | --

**Comment by unibasil** [comment]
You should use front-end server, for example Nginx, so you can configure HTTPs transport via Nginx configuration.
