### ISSUE TITLE
Better indoor

### ISSUE THREAD

**Issue by nlehuby** [openmaptiles/openmaptiles#384]
We should allow to filter (or provide better styling) on indoor elements such as the individual artwork inside museum or individual shops in a multi-level train station.
We may provide the layer, level and maybe indoor tag in the poi layer.

Some artwork in the Louvre museum :
![screenshot-2017-12-8 maputnik](https://user-images.githubusercontent.com/919962/33776048-82f74cf6-dc40-11e7-8681-375b0366bd63.png)

Some shops and amenity inside the Gare de Lyon train station :
![screenshot-2017-12-8 maputnik 1](https://user-images.githubusercontent.com/919962/33776055-87f3335a-dc40-11e7-9b27-3152e3d2259a.png)

As a first step, can we replicate what has been done on the transportation layer for footways ?

**Comment by jirik** [comment]
I like this idea, it should be quite straightforward, since it is already implemented for footways. It's about adding following tags to POIs:
- indoor
- level
- layer

PR is welcome.

**Comment by nlehuby** [comment]
NB : The artworks in the Louvre museum are not visible anymore: they are now tagged as `exhibit=artwork` (which is not loaded as a poi).

PR #435 add layer, level and indoor tags on the poi layer.
