### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by oliverbienert** [openmaptiles/openmaptiles#386]
Hello,

After having tested with quickstart.sh script and Berlin (Germany) area a couple of days before, I now tried to import the whole planet:
```
docker-compose run --rm openmaptiles-tools make clean
docker-compose run --rm openmaptiles-tools make
docker-compose up -d postgres
make forced-clean-sql
docker-compose run --rm import-water
docker-compose run --rm import-osmborder
docker-compose run --rm import-natural-earth
docker-compose run --rm import-lakelines
wget -P data https://planet.osm.org/pbf/planet-latest.osm.pbf
docker-compose run --rm import-osm
```
After some time the following SQL-Error occured:
```
[Dec  9 09:39:02] [INFO] Writing OSM data took: 17h24m45.081618826s                                                                       
[Dec  9 09:39:02] [INFO] [17h24m45s] C: 0/s ( 0.0%) N: 67500/s (100.0%) W: 10600/s (100.0% R: 230/s (100.0%)
[Dec  9 09:41:33] [INFO] [PostGIS] Generalizing osm_boundary_linestring into osm_boundary_linestring_gen5 took: 2m31.172747338s
[Dec  9 09:41:38] [INFO] [PostGIS] Generalizing osm_aeroway_polygon into osm_aeroway_polygon_gen1 took: 5.097993352s
[Dec  9 09:42:19] [INFO] [PostGIS] Generalizing osm_boundary_linestring into osm_boundary_linestring_gen3 took: 3m17.277499073s
[Dec  9 09:44:48] [INFO] [PostGIS] Generalizing osm_park_polygon into osm_park_polygon_gen1 took: 2m28.285001885s
[Dec  9 09:46:01] [INFO] [PostGIS] Generalizing osm_boundary_linestring into osm_boundary_linestring_gen1 took: 4m22.817158574s
[Dec  9 09:47:06] [INFO] [PostGIS] Generalizing osm_waterway_linestring into osm_waterway_linestring_gen1 took: 8m4.510194764s
[Dec  9 09:47:08] [INFO] [PostGIS] Generalizing osm_shipway_linestring into osm_shipway_linestring_gen1 took: 1.385229606s
[Dec  9 09:48:43] [INFO] [PostGIS] Generalizing osm_boundary_linestring into osm_boundary_linestring_gen2 took: 3m55.307113726s
[Dec  9 09:48:58] [INFO] [PostGIS] Generalizing osm_boundary_linestring into osm_boundary_linestring_gen4 took: 2m56.497894117s
[Dec  9 09:49:41] [INFO] [PostGIS] Generalizing osm_railway_linestring into osm_railway_linestring_gen1 took: 57.95364651s
[Dec  9 09:49:41] [INFO] [PostGIS] Generalizing osm_aerialway_linestring into osm_aerialway_linestring_gen1 took: 97.952931ms
[Dec  9 10:09:02] [INFO] [PostGIS] Generalizing osm_highway_linestring into osm_highway_linestring_gen1 took: 20m4.193147392s
[Dec  9 10:09:02] [INFO] [PostGIS] Creating generalized tables took: 29m59.784649714s
[Dec  9 10:09:02] SQL Error: pq: GEOSTopologyPreserveSimplify: IllegalArgumentException: RobustDeterminant encountered non-finite numbers  in query CREATE TABLE "import"."osm_highway_linestring_gen1" AS (SELECT "osm_id",
ST_SimplifyPreserveTopology("geometry", 38.218514) as "geometry",
"highway",
"ref",
"network",
"z_order",
"layer",
"level",
"indoor",
"name",
"name_en",
"name_de",
"short_name",
"is_tunnel",
"is_bridge",
"is_ramp",
"is_ford",
"is_oneway",
"is_area",
"service",
"usage",
"public_transport" FROM "import"."osm_highway_linestring" WHERE highway IN ('motorway', 'trunk', 'primary', 'secondary', 'tertiary', 'motorway_link', 'trunk_link', 'primary_link', 'secondary_link', 'tertiary_link') AND NOT is_area)
```
Is this because I don't use a file from geofabrik? But they don't have a planet file, have they?
Can I use your tools to import continents instead? One after another?

Regards Oliver

**Comment by freeman40** [comment]
This is happening for me too, importing planet-171204.osm.pbf.  It did not happen with previous planet files, and so I'm putting this down to a data error in the planet file.  Suggest either using an older planet extract, or waiting for next week's one (no guarantees...)

**Comment by freeman40** [comment]
The problem is caused by https://www.openstreetmap.org/way/543677292 and looks like it may have been fixed.
One idea to make the import-osm part of openmaptiles pipeline more robust against this sort of thing would be to add ST_IsValid(...) clauses for the generalised tables.  Like so:

in /layers/transportation/mapping.yaml
  highway_linestring_gen1:
    source: highway_linestring
    sql_filter: highway IN ('motorway', 'trunk', 'primary', 'secondary', 'tertiary', 'motorway_link', 'trunk_link', 'primary_link', 'secondary_link', 'tertiary_link') AND NOT is_area **_AND ST_IsValid(geometry)_**
    tolerance: ZRES12

**Comment by pathmapper** [comment]
> The problem is caused by https://www.openstreetmap.org/way/543677292 and looks like it may have been fixed.

@freeman40 great! This was causing probably also https://github.com/openmaptiles/openmaptiles/issues/381

**Comment by sfkeller** [comment]
Hi everybody. 
Just to be sure I'd like to point to the following:
This solution drops this geometry, so it's lost for the output.
There is also the function ST_MakeValid() or this buffer trick: ST_Multi(ST_Buffer(wkb_geometry,0)) (see http://revenant.ca/www/postgis/workshop/equality.html ).
This would of course need to be applied elsewhere before the mappings (mapping.yaml).

**Comment by freeman40** [comment]
@sfkeller: Yes, good point.

Perhaps the generation of the generalised tables could be done manually (i.e. taken outside of the imposm3 import, and done afterwards with some SQL statements).  Then, one would be free to use ST_MakeValid() or the buffer trick.

**Comment by jirik** [comment]
Fixed by https://github.com/openmaptiles/openmaptiles/commit/5c67f2769e5861076df0dbb872ffe8f163407a47 as suggested by @freeman40 - thanks!
