### ISSUE TITLE
Add surface for highways

### ISSUE THREAD

**Issue by pertile** [openmaptiles/openmaptiles#389]
Hi, I think it would be great getting surface key in the tiles. In non-developed countries is a very useful tag to make a difference between paved and unpaved ways.

**Comment by jirik** [comment]
It seems reasonable. We can generalize it into two values only: paved and unpaved.

Pull request is welcome.

**Comment by TomPohys** [comment]
close by https://github.com/openmaptiles/openmaptiles/pull/570
