### ISSUE TITLE
Porting an existing tm2 style

### ISSUE THREAD

**Issue by webmap2015** [openmaptiles/openmaptiles#390]
Hi,

I want to port an existing TM2 style (https://github.com/mapbox/mapbox-studio-osm-bright.tm2) to OpenMapTiles (https://github.com/openmaptiles/mapbox-studio-osm-bright.tm2/) by myself.

Is there any tutorial or software?

Thanks.

**Comment by jirik** [comment]
You can use maputnik editor at https://editor.openmaptiles.org/ for building or adjustign existing GL style.

By the way, there already exists [OSM Bright](https://github.com/openmaptiles/osm-bright-gl-style) GL style, so maybe it's what you are looking for. Other public styles are at https://openmaptiles.org/styles/ And there are also premium styles: https://www.tilehosting.com/#maps
