### ISSUE TITLE
Native text (Bengali) does not show correctly

### ISSUE THREAD

**Issue by nafis042** [openmaptiles/openmaptiles#394]
I used openmaptiles in order to generate vector tiles. In OSM data there are some road names in native language (Bangla). TIleServer gl  doesn't seem to show these. I have tried some different Bangla Unicode Fonts (Noto Sans Bangla UI etc) those are showing texts but not correctly.  Here is the correct osm road name-
[http://www.openstreetmap.org/#map=16/23.7806/90.3741](url)
![openstreetmap](https://user-images.githubusercontent.com/26213218/34462960-fafb730e-ee78-11e7-95b1-b1bfbaed9d10.png)

I also tried Klokantech Noto Sans font but that also doesn't work. I changed the style file a litte bit:-
   {
      "id": "road_major_label",
      "type": "symbol",
      "source": "openmaptiles",
      "source-layer": "transportation_name",
      "filter": [
        "all",
        [
          "==",
          "$type",
          "LineString"
        ],
        [
          "!has",
          "name:en"
        ]
      ],
      "layout": {
        "symbol-placement": "line",
        "text-field": "{name}", /// changed here 
        "text-font": [
	  "Klokantech Noto Sans Regular"   /// changed here
        ],
        "text-transform": "uppercase",
        "text-letter-spacing": 0.1,
        "text-size": {
          "base": 1.4,
          "stops": [
            [
              10,
              8
            ],
            [
              20,
              14
            ]
          ]
        },
        "text-rotation-alignment": "map"
      },
      "paint": {
        "text-color": "#000",
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 2
      }
    }
Is this a problem of vector tiles? I can't figure out where the problem is and how to solve it.

Here are 2 more screenshots:
1st one when font is Klokantech Noto Sans Regular
![11](https://user-images.githubusercontent.com/26213218/34463699-926c983e-ee8e-11e7-9c9c-2858cd5ca503.png)

and 2nd one when font is Noto Sans Bangla UI which shows text but not correctly
![image](https://user-images.githubusercontent.com/26213218/34463706-d3947732-ee8e-11e7-9f32-57b85b6b047c.png)

**Comment by MattBlissett** [comment]
It looks to be correct (as far as I can tell) on the background map on https://openmaptiles.org/ -- maybe try with the downloaded vector tiles to compare?

**Comment by nafis042** [comment]
as it turns out there is no support complex bangla unicode text yet.
