### ISSUE TITLE
Administrative boundaries with admin_level=7 are not rendered

### ISSUE THREAD

**Issue by boldtrn** [openmaptiles/openmaptiles#396]
I had a look at the bright render theme and saw that boundaries with admin_level=7 are not rendered, compare the screenshots below (the same is true for the basic theme as well).

![openmaptiles-osm](https://user-images.githubusercontent.com/1553525/34511093-5976b3ea-f0ad-11e7-903a-d41cbb112731.png)
![openmaptiles](https://user-images.githubusercontent.com/1553525/34511094-59af386e-f0ad-11e7-8537-507f0989b6b9.png)

One example would be [this boundary](http://www.openstreetmap.org/way/193501800).

The screenshot was taken at about `49.93354,9.90348`.

**Comment by jirik** [comment]
The boundary is encoded in tiles, but it's not shown by style (it has admin_level=7):
https://github.com/openmaptiles/osm-bright-gl-style/blob/a517f3e5f74af068867685e89c8d67e2f5be684a/style.json#L3449

I am not sure why there are only even admin levels used in the style. Maybe @lukasmartinelli knows. I think we should extend the filter to admin_level in (4,5,6,7,8).

**Comment by jirik** [comment]
Related ticket: #246

**Comment by jirik** [comment]
Fixed by https://github.com/openmaptiles/osm-bright-gl-style/commit/2497595ec4c1917f03f7a3a26b79bde939d2a186
