### ISSUE TITLE
[Raster] Circular boundary is missing from some tiles

### ISSUE THREAD

**Issue by boldtrn** [openmaptiles/openmaptiles#397]
I have seen an issue with the bright style using raster tiles. A circular boundary was partly missing in some tiles and some zoom levels.

Have a look at these screenshots:
![openmaptiles-circular-closer](https://user-images.githubusercontent.com/1553525/34511696-65125836-f0b1-11e7-9424-a8fb239e68e3.png)
![openmaptiles-circular](https://user-images.githubusercontent.com/1553525/34511697-654a051a-f0b1-11e7-9b38-c61eb9ee4948.png)

It is [this boundary](http://www.openstreetmap.org/way/30047245). Located at about `54.37535,7.71171`.

**Comment by boldtrn** [comment]
This also happens for other boundaries, for example here: `-24.46465,153.32519`.

![openmaptiles-circular2](https://user-images.githubusercontent.com/1553525/34511905-e3f6e33c-f0b2-11e7-90d0-df7d290c4233.png)

**Comment by jirik** [comment]
As @petrsloup stated, it can be related to PNG quantisation. It would make sense, because it seems that affected tiles contain only maritime boundary and see, nothing more (no land, no labels).

**Comment by jirik** [comment]
This one is related just to tilehosting.com raster rendering, not to OpenMapTiles schema.
