### ISSUE TITLE
Does OMT service also provide a link with .mvt ?

### ISSUE THREAD

**Issue by musicformellons** [openmaptiles/openmaptiles#399]
When using mapzen vector tiles I could use a .mvt link. It looks like the json link of OMT  can not be used together with the attribution field in mapbox style sheet. For more detail please see [this issue](https://github.com/mapbox/mapbox-gl-js/issues/5936).

**Comment by klokan** [comment]
This is a usage request - it should be at https://stackoverflow.com/questions/tagged/openmaptiles
Please do not ignore our recommendations!

The answer to your question:

Open your TileJSON (a link like https://free.tilehosting.com/data/v3.json?key=mySecretKey) in web browser. Inside you find the `tiles` field - which you can copy&paste directly into your JSON style under the source.
