### ISSUE TITLE
Schema misses transportation#class=ferry

### ISSUE THREAD

**Issue by boldtrn** [openmaptiles/openmaptiles#402]
The [schema](https://openmaptiles.org/schema/) misses class=ferry, even though ferries are returned, for example [here](https://openmaptiles.org/inspect/#17.24/-33.85461/151.21788).

**Comment by jirik** [comment]
Thanks, we need to update documentation at openmaptiles.org

**Comment by jirik** [comment]
Updated:
- https://github.com/openmaptiles/www.openmaptiles.org/commit/56cf18c9b8b95b40bc49ba4ed572b1b079fab742
- https://openmaptiles.org/schema/
