### ISSUE TITLE
Wrong class on water river polygon to z11

### ISSUE THREAD

**Issue by daliborjanak** [openmaptiles/openmaptiles#407]
Layer **water** polygon.
River polygon which has class "river" on zooms 11-14 has a class "lake" on zooms up to 11. You cannot display only lakes now. See:

Zoom 7,5
![image](https://user-images.githubusercontent.com/1891090/34824803-3992bcbc-f6d0-11e7-8e7c-ccf18cee1ce7.png)

Zoom 9
![image](https://user-images.githubusercontent.com/1891090/34824474-df58b982-f6ce-11e7-9c81-390ae93f74f8.png)

zoom 11
![image](https://user-images.githubusercontent.com/1891090/34824497-ff5f2a4a-f6ce-11e7-8572-41d56fe9d7a4.png)

We need to use class "river" also on zooms < 11

**Comment by jirik** [comment]
This should be quite easy, only use water_class function also for Z6-Z10:

https://github.com/openmaptiles/openmaptiles/blob/89ee0de23bf9582d5f1f127ed85488f6975d6383/layers/water/water.sql#L92

**Comment by jirik** [comment]
Fixed by https://github.com/openmaptiles/openmaptiles/commit/1093dcece8513f530438b737b7fb07756161b529
