### ISSUE TITLE
How to launch without Docker?

### ISSUE THREAD

**Issue by fresm** [openmaptiles/openmaptiles#408]
I don't want to get dockerized and loose control about what my server does.

@jirik May you please provide some information how to run this directly on a generic Linux system?

This would please all Gentoo, Arch, etc. people!

**Comment by freeman40** [comment]
I strongly urge you to use the docker containers.  If you really don't want to, then what you need to do is look in the docker files for each of the containers, from there you can make sure that you have the same dependencies installed on your "generic Linux system", then unpick what the docker container does, turning it all into hand-crafted scripts for your linux system.  Some of the containers have data baked into them, so you will have to download that data independently.  It will be much easier to just use the docker containers!

**Comment by klokan** [comment]
If you speak about the OpenMapTiles generators - feel free to install all the tools natively.
If you study the Dockerfile for each of the Docker containers we use - you see there what is installed and how exactly. The same steps may be reproduced on your favourite linux distro - it will just take more time. 

If you speak about hosting the maps, then install our open-source TileServer GL which runs just fine when installed directly into a Linux distribution of your choice. Check https://www.youtube.com/watch?v=rOg4VnSAnI4 and http://tileserver.readthedocs.io/en/latest/.
On some distros, you may need to compile the dependencies yourself - typically MapBox GL Native with binding for node.js.
TileServer GL is just the rendering component - for complete map hosting you may use it with caching, behind proxy or CDN and with a proper config setup.

We are available to assist our customers with production setup and complete workflows:  https://openmaptiles.com/support
