### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by Revo86** [openmaptiles/openmaptiles#409]
I just tried the manual on how to install OpenMapTiles and I got the following error:

> git clone git@github.com:openmaptiles/openmaptiles.git

```
Cloning into 'openmaptiles'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by daliborjanak** [comment]
Use ```git clone https://github.com/openmaptiles/openmaptiles.git```
