### ISSUE TITLE
Why is there no sand or beach

### ISSUE THREAD

**Issue by boldtrn** [openmaptiles/openmaptiles#410]
I think this is a very important tag, but I couldn't find it?

**Comment by jirik** [comment]
It seems reasonable to add it into landcover. Pull request is welcome.

**Comment by jirik** [comment]
Already implemented: https://github.com/openmaptiles/openmaptiles/commit/51d4558ea8c7002be704674180f61f77d215f728#diff-aeed953ebcdeefcc353f5ee25b00fe65

It will be available in the next release.
