### ISSUE TITLE
Using Openmaptiles as source in Tangram

### ISSUE THREAD

**Issue by nafis042** [openmaptiles/openmaptiles#411]
I have tileserver-gl running which serves vector tiles. Currently for styling I am using osm bright which is working fine. I recently explored tangram and I liked their styling which is actually called scene file like bubble wrap, cinnabar, tron style etc. I tried using those styles( by changing source as suggested in the openmaptiles website) but that wont work. I get that because the layers are different. I wonder is there any way to convert those scene file so that I can use in tileserver-gl or any implementation on those styles(specially bubble-wrap or cinnabar style) where openmaptiles used as source.

**Comment by jirik** [comment]
There is probably no such tool. You can recreate the style manually using https://editor.openmaptiles.org You can start with empty style, or you can adjust existing style, e.g. osm bright or klokantech basic.

**Comment by nlehuby** [comment]
You may want to check out this blog post:
https://stevebennett.me/2017/08/23/openstreetmap-vector-tiles-mixing-and-matching-engines-schemas-and-styles/
