### ISSUE TITLE
"WARNING No directory is mapped to the /data volume."

### ISSUE THREAD

**Issue by ArthurRoodenburg** [openmaptiles/openmaptiles#412]
Hi,

After installing the docker image with docker cloud, the OpenMapTiles server Wizard gives the following error message:

"WARNING No directory is mapped to the /data volume." Any data you download and the created configuration will be lost once you stop the docker container.

![error](https://user-images.githubusercontent.com/35568495/35102405-2f9f9be2-fc63-11e7-9a99-0a9c765566e9.png)

We have 2 volumes (one created by ourselves, but one is the /data folder)

How do I get this straight? I'm not sure how to map a directory to this volume. 

Thanks in advance.

![volumes](https://user-images.githubusercontent.com/35568495/35102507-6f292030-fc63-11e7-8c55-0a948c3bc176.png)

Arthur

**Comment by petrsloup** [comment]
The wizard reads the contents of /data volume, so you need to map your directory as the /data volume into the container (replacing the default content), not /osmdata.

**Comment by ArthurRoodenburg** [comment]
We tried to, but we don't know how. By default it is wrong.
the /osmdata was one of the later tries, it never works.

**Comment by petrsloup** [comment]
If you write "/data" everywhere instead of "/osmdata" what is the issue? Is there any error message?

**Comment by ArthurRoodenburg** [comment]
If we do a clean install, with only a /data folder, we get this message.

**Comment by Chappie74** [comment]
Click on the data folder 
![image](https://user-images.githubusercontent.com/21108487/45457763-84a13900-b6be-11e8-9630-d4fd3fac4e17.png) 
and then enable volume
