### ISSUE TITLE
Issue with zoom 14+

### ISSUE THREAD

**Issue by RevanScript** [openmaptiles/openmaptiles#417]
Hello,

I created an mbtile with MIN_ZOOM=0 and MAX_ZOOM=14, but when i try to use it with Mapbox Native GL, i can't zoom deeper than 14, it just renders nothing: https://youtu.be/5Y7OmNSUhDg

mbtiles from openmaptiles.org works fine. Did i miss something?

**Comment by jirik** [comment]
You can compare metadata of the two mbtiles using sqlite3 and look for properties that differ and can be related to your problem (e.g. `maxzoom`).
