### ISSUE TITLE
Bug: underground station as overground building

### ISSUE THREAD

**Issue by Lorzer** [openmaptiles/openmaptiles#419]
At Berlin Alexanderplatz the subway station is tagged as a building; I can't find a way  to style it different from other buildings:
![bildschirmfoto 2018-01-30 um 10 40 37](https://user-images.githubusercontent.com/2046444/35559084-1049dd0c-05aa-11e8-9203-1bc541a22048.png)

The marked red area should be under ground.

https://maputnik.github.io/editor/#16.61/52.52088/13.41440

**Comment by jirik** [comment]
Well, it's tagged as building in OSM:
- https://www.openstreetmap.org/relation/2678660
- `type=building`

If you think it's a bug, please fix it in OpenStreetMap by removing `type=building`.
