### ISSUE TITLE
Missing volcanos

### ISSUE THREAD

**Issue by ladislavhorky** [openmaptiles/openmaptiles#420]
Hello,

when using the tiles through tilehosting.com, we noticed that `mountain_peak` layer contains only OSM features with `natural:peak` tag and not with `natural:volcano` tag. As noted in OSM [volcano definition](https://wiki.openstreetmap.org/wiki/Tag:natural=volcano?uselang=en-US#Relation_to_natural.3Dpeak), there is a certain distinction on how volcano vs peak features are placed but the way it is currently done in OSM database causes many very significant peaks (e.g. [Etna](https://www.tilehosting.com/#topo//vector/12.58/14.99829/37.75015)) to have no label if only `natural:peak` features are used.

Proposed solution is to either add volcanos to `mountain_peak` layer and possibly add a tag to distinguish them from normal peaks, or create a completely new layer with volcanos. Seeing that other layers contain whole groups of features, the first option could be more appropriate.

**Comment by jirik** [comment]
+1 for adding volcanoes to `mountain_peak` layer. PR is welcome

**Comment by ladislavhorky** [comment]
Hi @jirik ,

do you know if there has been any progress regarding this issue?

**Comment by jirik** [comment]
I don't know about any progress on this issue, we have currently other priorities. Anyway, pull request is welcome.
