### ISSUE TITLE
path, footway, cycleway ambiguity

### ISSUE THREAD

**Issue by chen-ye** [openmaptiles/openmaptiles#422]
There's still a lot of ambiguity in OSM about how different kinds of paths should be coded (see: https://wiki.openstreetmap.org/wiki/Path_controversy). 

There's also a wide variety of features coded as "paths" that should probably be differentiated from each other, especially on non-automotive maps (maps for cycling, hiking, etc): https://wiki.openstreetmap.org/wiki/Path_examples.

To differentiate these, could OMT include the bicycle/foot/horse and surface: tags from OSM?

**Comment by klokan** [comment]
Yes it could - make a proposal for modification of the schema please.

**Comment by Phyks** [comment]
Hi,

I am interested in this issue as well, and this would likely solve https://github.com/openmaptiles/openmaptiles/issues/512.

Concerning the surface, I would add a `surface` field to the transportation layer. I can make a PR for this.

Is adding the bicycle/foot/horse fields as well fine? I guess these should be added only on path highways?

Thanks

**Comment by MartinMikita** [comment]
Hello @Phyks,

Yes, you can add a new attribute `surface` to distinguish these types in the `transportation` layer. Bicycle, foot, horse should be enough for now.

Please, prepare a PR, and we would appreciate, if you could compare what would be the final effect - the size of MBTiles, size of the database, time of importing and rendering (before and after your change).
You could start with smaller states like Albania, and probably prepare and compare the results on Switzerland or Czech Republic, these have a lot of bicycle ways.

This could help us to decide if we would include it in the official OpenMapTiles scheme in the next release (v3.10).

**Comment by zstadler** [comment]
The approach for handling `bicycle = designated` implemented in https://github.com/openmaptiles/openmaptiles/pull/573 is different than the approach requested in issue #512. 

As @nnhubbard [noted](https://github.com/openmaptiles/openmaptiles/issues/512#issuecomment-430982350), the different values of the bicycle tag should be preserved so they can be styled differently if needed.
