### ISSUE TITLE
Geometry Coordinates for cities (place_city) or other map symbols/points etc?

### ISSUE THREAD

**Issue by charliecode** [openmaptiles/openmaptiles#423]
Is it possible to get the lng/lat coordinates for symbols/points/etc on the openmaptiles map? I don't see these as options in the GeoJSON openmaptiles schema. I'm using openmaptiles served with tileserver-gl. Client side using mapbox-gl. As an example, is there a way to get the exact coordinates of the place_city symbols on the map. If not this may be a good option to add to the GeoJSON. Thanks much

**Comment by sfkeller** [comment]
Don't know what your use case is. Bu you probably first take a look at following: 
* https://www.mapbox.com/vector-tiles/specification/
* https://github.com/Leaflet/Leaflet.VectorGrid
* http://plugins.qgis.org/plugins/vector_tiles_reader/

**Comment by charliecode** [comment]
Thanks a bunch @sfkeller. I'll take a look over these. Appreciate your time putting this together for me.
