### ISSUE TITLE
transportation_name layer missed

### ISSUE THREAD

**Issue by impVA** [openmaptiles/openmaptiles#426]
I`ve created mbtiles via 'quickstart.sh central-fed-district' with no any errors, but when i started tileserver there was no any named street. Maputnik Inpect mode see no transportation_name source, so how I have to make tileset with this source?

![image](https://user-images.githubusercontent.com/36696413/36476444-f5c9c5de-170e-11e8-917a-45443bbe4105.png)

**Comment by eva-j** [comment]
Hi @impVA, did you solve this issue or do you still need help?
