### ISSUE TITLE
Duplicated features are causing styling issues

### ISSUE THREAD

**Issue by sds-dubois** [openmaptiles/openmaptiles#427]
I noticed that some features are duplicated and that it messes up the map rendering. A good example is the screenshot below where you can see the squares in the water.

When inspecting with Maputnik, I do see `water x2` (or x4) at these locations. Although this is particularly problematic with the water layer since we can see the tile boundaries, I found many other cases where a single feature (eg road or rail track) was duplicated and made the lines wider or more opaque.

So I guess there are two possible problems here and I'm not sure which one can/should be fixed:
- some features are duplicated (shown as `[feature] x [n]` in Maputnik)
- when features are duplicated, only one should be rendered instead of adding up

![screenshot](https://user-images.githubusercontent.com/7746635/36610360-dda5e8f8-1884-11e8-8487-73f4b119ba62.jpg)

Steps to reproduce: 
- Go to [editor.openmaptiles.org/#8.47/37.7634/-74.8447](https://editor.openmaptiles.org/#8.47/37.7634/-74.8447)
- Select Positron style
- Change water layer opacity to `0.5`

Another [example](https://editor.openmaptiles.org/#5.47/43.756/-83.196) where it's not only the tile borders (notice the darker gray near the "Michigan" label):

![screenshot2](https://user-images.githubusercontent.com/7746635/36611014-f0ac04ee-1886-11e8-851c-e5bcb2804715.jpg)
  
  
This seems related to #308 and [maputnik/editor#41](https://github.com/maputnik/editor/issues/41).

**Comment by pathmapper** [comment]
I think the lines on your first image are the split boundaries of the water polygons which are becoming visible when the opacity is reduced because the water polygons are overlapping each other. 
This is related to https://github.com/openmaptiles/openmaptiles/issues/308.

On your second example, the darker gray area is only visible for zoom level = 5. 
Looking at the [ETL diagram](https://raw.githubusercontent.com/openmaptiles/openmaptiles/master/layers/water/etl_diagram.png), it could be related to the `ne_10m_lakes` data:



![image](https://user-images.githubusercontent.com/20856381/36615549-f3bbe3d4-18e0-11e8-8b80-1c02851e6ae2.png)

**Comment by sds-dubois** [comment]
Thanks for your comment @pathmapper. I also read the thread at openmaptiles/positron-gl-style#6 and played with the `fill-antialias` property but it didn't solve the problem in my case. Did you have another possible fix for that? 

Re the second example, my point was more that it's a general problem and not just restricted to the water polygons. I've noticed many times that roads or rail tracks were duplicated, and every time it makes the lines look thicker. I've used Mapbox before and have never had this problem - I'm wondering if it's because they fixed duplicates in the data or if they prevent duplicates to be rendered twice..

**Comment by pathmapper** [comment]
> Did you have another possible fix for that?

Unfortunately not, but I wonder why you would like to reduce the opacity of the water layer. 
Do you have a layer below the water layer which you want to shine through? Otherwise just use `1` for `fill-opacity` of the water layer to avoid this effect.

> I've noticed many times that roads or rail tracks were duplicated, and every time it makes the lines look thicker. 

Could you please provide an example where this happens?

**Comment by jirik** [comment]
> I've noticed many times that roads or rail tracks were duplicated, and every time it makes the lines look thicker.

Yes, please, an example would be helpful.

**Comment by sds-dubois** [comment]
>  I wonder why you would like to reduce the opacity of the water layer

@pathmapper I was using a pattern for the water layer with transparent background and an underlay - but was actually able to fix this by incorporating the underlay as the pattern background and set the water layer opacity to 1. It works but it's less flexible.

Re the duplicated roads/rail-tracks I actually think this happens because two lines become very close when zooming out, and thus it looks like one thicker line. So I guess it's not a bug.

You can see an example [here](https://editor.openmaptiles.org/#12.49/48.87421/2.41932) with the OSM bright style, and try zooming in/out.

![2018-03-29_11h35_01](https://user-images.githubusercontent.com/7746635/38106961-748b9ada-3345-11e8-9ede-76345785eacc.jpg)


If you want to set an opacity less than 1 though, the overlap is visible, eg:

![2018-03-29_11h25_01](https://user-images.githubusercontent.com/7746635/38106699-af573cba-3344-11e8-9006-cb5c34f3aa3f.jpg)

To reproduce:
 - [open the editor](https://editor.openmaptiles.org/#16.87/37.765455/-122.416478)
 - select OSM bright style
 - modify `highway-minor` layer with `opacity: 0.5` and `color: rgba(181, 27, 27, 1)`

**Comment by jirik** [comment]
> Re the duplicated roads/rail-tracks I actually think this happens because two lines become very close when zooming out, and thus it looks like one thicker line. So I guess it's not a bug.

Yes, it's expected behaviour. Same in case of semitransparent roads (you need layer opacity, that is not yet implemented: https://github.com/mapbox/mapbox-gl-js/issues/4090).
