### ISSUE TITLE
Fail to raise the tiles size

### ISSUE THREAD

**Issue by maxmayerhofer** [openmaptiles/openmaptiles#428]
Hello,
I install  the docker image https://openmaptiles.org/docs/, than I like to raise the maximal  size of an GetMap-Request generated Image to round about 20000. 😄  
But it dos not work .
`{
  "styles": {
    "standard": [
      "dark-matter",
      "klokantech-basic",
      "osm-bright",
      "positron"
    ],
    "custom": [],
    "lang": "",
    "langLatin": true,
    "langAlts": true
  },
  "settings": {
    "serve": {
      "vector": true,
      "raster": true,
      "services": true,
      "static": true
    },
    "raster": {
      "format": "PNG_256",
      "hidpi": 3,
      "maxsize": 10000
    },
    "server": {
      "title": "",
      "redirect": "",
      "domains": []
    },
    "memcache": {
      "size": 4,
      "servers": [
        "localhost:11211"
      ]
    }
  }
}

`

`<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1">
    <ServiceException>
        <![CDATA[
received wms request with width or height over configured maxsize limit
]]>
    </ServiceException>
</ServiceExceptionReport>`

Please Help me out :) 

<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1">
    <ServiceException>
        <![CDATA[
received wms request with width or height over configured maxsize limit
]]>
    </ServiceException>
</ServiceExceptionReport>

**Comment by klokan** [comment]
https://stackoverflow.com/questions/49020110/how-to-raised-the-tiles-size-by-a-docker-openmaptiles-server/49030463#49030463
