### ISSUE TITLE
Underground rivers in waterway layer

### ISSUE THREAD

**Issue by xkomczax** [openmaptiles/openmaptiles#429]
Underground rivers/streams are now rendered in the same way as regular waterways. 

An example: Punkva river - https://www.openstreetmap.org/way/104375589

In OMT project, it is shown as a regular river.

The tags in OSM are tunnel=yes (for rivers in caves) or tunnel=culvert (for man made structures). Both should be used together with lever=* value (now always used).

For more info, check OSM wiki - https://wiki.openstreetmap.org/wiki/Tag:tunnel=culvert and https://wiki.openstreetmap.org/wiki/Key:tunnel

**Comment by jirik** [comment]
This one is already implemented, see https://github.com/openmaptiles/openmaptiles/issues/360
