### ISSUE TITLE
Intermittent streams

### ISSUE THREAD

**Issue by xkomczax** [openmaptiles/openmaptiles#430]
In OpenMapTiles, intermittent rivers/streams are shown in the same way as regular waterways. 

An example: https://www.openstreetmap.org/way/243694218

For more info, check OSM wiki: https://wiki.openstreetmap.org/wiki/Key:intermittent?uselang=en-US

This is an issue especially in desert areas (wadis - https://en.wikipedia.org/wiki/Wadi ).

**Comment by jirik** [comment]
Thanks, pull request is welcome. It can be solved in similar way as waterway brunnels in #393. Related to #100.
