### ISSUE TITLE
Data insufficient in mbtiles

### ISSUE THREAD

**Issue by Rajavelu** [openmaptiles/openmaptiles#431]
Hi, 
We setup vector tileserver using mbtiles(OpenStreetMap vector tiles from https://openmaptiles.com/downloads/tileset/osm/). But we found as many data missing in vector tiles which are available in OSM. 
For example railway station names(info) not available in mbtiles, and many building data not showing in vector tiles(refer attached images).
Also, we didn't get state codes from mbtiles, Kindly add the same. We need to show state codes(instead of names).

Vector tiles (using openmaptiles):
<img width="1064" alt="screen shot 2018-03-21 at 12 03 23 pm" src="https://user-images.githubusercontent.com/3033600/37696945-e7a0b4b6-2cff-11e8-836d-1f814127e3fa.png">

OSM raster map:
<img width="898" alt="screen shot 2018-03-21 at 12 02 56 pm" src="https://user-images.githubusercontent.com/3033600/37696946-e7d64dce-2cff-11e8-8a96-0f40879f7337.png">

**Comment by jirik** [comment]
OpenMapTiles are not 100 % copy of OpenStreetMap. We try to encode only the most relevant data for map outputs.

Country codes are already available:
- https://github.com/openmaptiles/openmaptiles/issues/306
- https://openmaptiles.org/schema/#place

If you are interested in US state codes, pull request is welcome.

Railway station names are be encoded in mbtiles in POI layer, class=railway. E.g. near provided example, there is Potheri station encoded.

For buildings, we do not yet encode building names, but it may be added in the future. The danger think about it is that it can easily increase size of mbtiles too much.
