### ISSUE TITLE
Vector tile decode for 3D rendering

### ISSUE THREAD

**Issue by DerKarlos** [openmaptiles/openmaptiles#436]
> The buildings are not yet ready for 3D rendering support and any help to improve this is welcomed.

I would like like to try using the vector tiles as input at my www.OSMgo.org and may need helping hands. And answers to questions like:
Is there ready to use code to read the tile byte stream to decode the contained components, prefared as call backs, in C++ and Javascript. Mind, I do use my own renderer.

**Comment by jirik** [comment]
Example of 3D buildings rendering: https://openmaptiles.github.io/klokantech-3d-gl-style/#15.36/40.7102/-74.0074/16/56

Decoding is done by https://github.com/mapbox/mapbox-gl-js and it's dependencies.
