### ISSUE TITLE
Download font only

### ISSUE THREAD

**Issue by emdadgar2** [openmaptiles/openmaptiles#438]
Hi,
Is there any way to download only fonts?

Thanks

**Comment by pathmapper** [comment]
Hi @emdadgar2 ,

are you looking for these?

https://github.com/openmaptiles/fonts

**Comment by emdadgar2** [comment]
Hi @pathmapper 
Thanks, but I cant compile ttf to pbf!
How I can download pbf files?

Thanks again.

**Comment by emdadgar2** [comment]
I tried but failed to install  "fontnik" package!

**Comment by klokan** [comment]
Downloads are as .zip files in https://github.com/openmaptiles/fonts/releases

**Comment by emdadgar2** [comment]
Thanks
