### ISSUE TITLE
Poi subway_entrance

### ISSUE THREAD

**Issue by alexspirtmsu** [openmaptiles/openmaptiles#440]
There is ‘subway_entrance’ in poi layer sql scripts. 
But I can’t find it in tiles and style them. 
I think they have subclass=entrance.

**Comment by jirik** [comment]
Exactly, already implemented by https://github.com/openmaptiles/openmaptiles/commit/5c740f85704c33402102e55e407d8cb365dc72df . Next release has deadline in these days and will be published in about two or three weeks.
