### ISSUE TITLE
question about the database

### ISSUE THREAD

**Issue by MoustafaMahgoub** [openmaptiles/openmaptiles#445]
Newbee squestion I am using the docker to generate my vector tiles, how and can I locate the database to be able to use it or edit for the project.(the data base that is used to generate the tiles)

**Comment by Bibi56** [comment]
Have a look at the Docker script or follow a manual installation.

**Comment by eva-j** [comment]
Hi @MoustafaMahgoub, did you solve this? Or do you still need help?
