### ISSUE TITLE
Openmaptiles Zoom level specified in Quickstart.md

### ISSUE THREAD

**Issue by nafis042** [openmaptiles/openmaptiles#446]
In QuickStart.md there has been told that the recommended max zoom level is 7. I wonder what is the difference between max zoom level 7 and 14? What extra features are we getting if we use max zoom 14

**Comment by febs** [comment]
ping

**Comment by nnhubbard** [comment]
You lose massive amounts of detail. Many map objects do not even show until zoom level 10 - 12. If you only create for level 7 you will get a very small `mbtiles` file but when you zoom in there will be no more data.

**Comment by daliborjanak** [comment]
https://openmaptiles.org/docs/generate/generate-openmaptiles/ quickstart is an example
How-to zoomable maps works: https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/
