### ISSUE TITLE
minzoom not working

### ISSUE THREAD

**Issue by Rajavelu** [openmaptiles/openmaptiles#455]
Hi, For showing state names from zoom level3, have below configuration in my style(with "minzoom" as 3).
But state names displaying from zoom level 4 and city names showing from zoomlevel3.  Can anyone help me? 

> {
>                         "id": "place-state",
>                         "type": "symbol",
>                         "metadata": {
>                                 "mapbox:group": "1444849242106.713"
>                         },
>                         "source": "openmaptiles",
>                         "source-layer": "place",
>                         **"minzoom":3,**
>                         "filter": [
>                                 "all",
>                                 [
>                                         "==",
>                                         "class",
>                                         "state"
>                                 ]
>                         ],
>                         "layout": {
>                                 "text-font": [
>                                         "Open Sans Bold"
>                                 ],
>                                 "text-field": "{name_en}",
>                                 "text-size": {
>                                         "stops": [
>                                                 [
>                                                         12,
>                                                         10
>                                                 ],
>                                                 [
>                                                         15,
>                                                         14
>                                                 ]
>                                         ]
>                                 },
>                                 "text-transform": "uppercase",
>                                 "text-max-width": 6.25
>                         },
>                         "paint": {
>                                 "text-color": "#334",
>                                 "text-halo-width": 2,
> 				                "text-halo-color": "rgba(255,255,255,0.8)"
>                         }
>                 }

<img width="371" alt="screen shot 2018-05-21 at 12 20 29 pm" src="https://user-images.githubusercontent.com/3033600/40294042-6f0d0cb2-5cf1-11e8-919c-021e41c6da7b.png">

Similarly, have config as below for show city border from zoom level 6. But its showing from zoom level9.

> {
>                         "id": "boundary-level-5",
>                         "type": "line",
>                         "source": "openmaptiles",
>                         "source-layer": "boundary",
>                         "minzoom":6,
>                         "filter": [
>                                 "==",
>                                 "admin_level",
>                                 5
>                         ],
>                         "layout": {
>                                 "line-join": "round"
>                         },
>                         "paint": {
>                                 "line-color": "#9e9cab",
>                                 "line-dasharray": [
>                                         3,
>                                         1,
>                                         1,
>                                         1
>                                 ],
>                                 "line-width": {
>                                         "base": 1.4,
>                                         "stops": [
>                                                 [
>                                                         4,
>                                                         0.4
>                                                 ],
>                                                 [
>                                                         5,
>                                                         1
>                                                 ],
>                                                 [
>                                                         12,
>                                                         3
>                                                 ]
>                                         ]
>                                 }
>                         }
>                 }

**Comment by jirik** [comment]
It's because state names are encoded in mbtiles since zoom 4. City borders will be probably the similar issue.

Style cannot display the data that is not encoded in mbtiles. You need to change the schema to contain state names also at zoom level 3 and to generate such tiles. Or you can make PR with this change and we will generate it in the next release.
