### ISSUE TITLE
Extra boundaries between land and water in Denmark

### ISSUE THREAD

**Issue by adamal** [openmaptiles/openmaptiles#457]
There seems to be rendered some form of administrative boundary between land and sea in Denmark
This is especially apparent on OSM Bright. Se e.g. [here - and switch to OSM Bright](https://openmaptiles.github.io/osm-bright-gl-style/#10.94/55.5968/12.8296)
The boundary is visible on all zoom levels.
The boundary is rendered by all four styles (KT Basic,  OSM Bright, Positron, Dark Matter)

Screen grab here. \
Note the extra thick blue line not just between Denmark and Sweden but all around Danish land.
<img width="418" alt="screen shot 2018-06-05 at 18 19 10" src="https://user-images.githubusercontent.com/3245228/40989183-5023b5a0-68ed-11e8-8176-704fefc003f3.png">

**Comment by jirik** [comment]
It's taken from OpenStreetMap, where similar visualization is used: https://www.openstreetmap.org/query?lat=55.6272&lon=12.7832#map=12/55.6327/12.7980

**Comment by Bibi56** [comment]
Some countries use a schema (DK, DE, UK), some use another one (BE, FR, NL). Some define their lower administrative boundaries on land, some also on water: territorial waters are part of the commune/district/county or not. Not sure if we can (or even should) homogenize that (representing the territorial waters). But the thick blue is probably too prominent to make the difference acceptable.
