### ISSUE TITLE
front end open map server infinitely loading

### ISSUE THREAD

**Issue by swan001** [openmaptiles/openmaptiles#473]
I encountered a problem to use openmaptiles server which I cannot see reported elsewhere.

I am running it via docker on a debian machine and after running the image, the server starts in the same way as in the video presentation (https://openmaptiles.com/server/#install in linux tab).
used command to start the image is the same as in the video :
docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/openmaptiles-server

When accessing the url, I can access the page and it infinitely reloads and I can only see 
"Starting OpenMapTiles Map Server..." and "loading".

The problem seems to come from the urls which are unsuccessfully accessed 
(e.g. https://openmaptiles.org/fonts/OpenSans-Regular.ttf). 

I attempted to acess this Url via a browser (without any proxy) and I get a 404 error.

Is is a known issue or am I doing anything wrong?

Thank you very much

**Comment by andi-di** [comment]
Same issue ...

**Comment by subay** [comment]
+1

**Comment by swan001** [comment]
In our case, the problem cas that when building with docker, some downloads were failing (silently) due to check certificates by a reverse proxy. Then while running with docker, openmaptile was trying to reach ressources.

I suppose that this behavior is a workaround but the location of the ressources (font etc.) have been modified? 

In any case, for those having the problem, check your proxy and certificates whilst building.

**Comment by paherbst** [comment]
I'm struggling to find why i'm having the same issue here.  No proxy.  But stuck at "loading".  Where can I look to troubleshoot?

**Comment by areve** [comment]
I tried hosting in Azure and I get this issue. The program created config.json and downloaded mbtiles into my file store but the link to open the maps does not work. What logs should I look at to work out what is going wrong?
