### ISSUE TITLE
understanding of mbtiles 'export' logs to help track performances issue

### ISSUE THREAD

**Issue by squalou** [openmaptiles/openmaptiles#474]
Hi,
I'm posting here more to get clarification on 'quickstart' log output meaning than open an 'issue'.

During the "export to mbtiles" phase, I see lines like this :
`[1h 18m 31.409999999999854s]  20.1177% 649.8k/ 3.23m @  138/s | ✓ 649.8k □ 162.2k | 5h 11m 39s left`
unfortunately in my latest test it transformed a few hours later to this :
`[12h 48m 13.661999999996624s]  71.0457%  2.15m/ 3.02m @   28/s | ✓ 2.15m □ 369.0k | 8h 42m 3s left`

Could anyone explain what each numbers tell us ? (apart from timestamp and time left ;) )

Especially the 138/s thta changes to 28/s ... I guess I have a performance issue around here, but no clue as how to improve things. )

For the records, on my test I compute min_zoom=12 max_zoom=14 on a pretty large country.

thank you !

**Comment by markuman** [comment]
>  649.8k/ 3.23m @ 138/s

means, you got already 649.8k tiles rendered of 3.23m at all. Performance is 138 tiles / s.

...it's just a guess. No idea why the total number drops later.

**Comment by squalou** [comment]
thank you for the clarification !

(fortunately for me I worked around the perf issue by building on dedicated compute servers,)
