### ISSUE TITLE
Feature request: Features required for "Übersichtsplan"-like style

### ISSUE THREAD

**Issue by lvonnied** [openmaptiles/openmaptiles#476]
I'm trying to create a style imitating [Kanton Zürich's "Übersichtsplan"](http://maps.zh.ch?topic=UPZH&scale=20000&x=2683653.42&y=1247104.21&srid=2056). I noticed that some features I need for that are missing from the tiles.

I would like a implementation of these OpenStreetMap tags:

- `natural=moor`: combination of wetlands + bog
- `power=tower`: towers carrying electricity cables
- `power=line`: electricity cables
- `aerialway=*`: several transportation means for ski resorts

**Comment by sfkeller** [comment]
(Petr: Thanks. Lucas is away from the office now until October.)

**Comment by eva-j** [comment]
Hi @lvonnied, I am going to close this issue.
`natural=moor` is deprecated and should be no more used in OSM - https://wiki.openstreetmap.org/wiki/Tag:natural%3Dmoor.
`power` and detailed `aerialway` tags could be in separate fork as a new topic/layers, not in the main repository https://github.com/openmaptiles/openmaptiles#openmaptiles-.
Thanks a lot for your understanding!
