### ISSUE TITLE
label's position not in good location

### ISSUE THREAD

**Issue by Rajavelu** [openmaptiles/openmaptiles#477]
hi,
I want to change continent/country label's position. Is it possible?

For example refer attached image, want to change position of 'Europe' label. 
<img width="826" alt="screen shot 2018-07-17 at 6 56 42 pm" src="https://user-images.githubusercontent.com/3033600/42821896-4027371e-89f7-11e8-957a-426d798b595b.png">

**Comment by klokan** [comment]
Make your own GeoJSON with these and use them in the map directly.

Or import it into Postgres, modify the files in appropriate 'layers' directory, and regenerate vector tile MBTiles.
