### ISSUE TITLE
Issue when runnning docker-compose pull (

### ISSUE THREAD

**Issue by carlos-mg89** [openmaptiles/openmaptiles#479]
```
WARNING: The BBOX variable is not set. Defaulting to a blank string.
WARNING: The MIN_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The MAX_ZOOM variable is not set. Defaulting to a blank string.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

I understand the warnings are not a problem, since while checking on other issues, I saw them in several logs. But I cannot understand why I get this error. I have successfully executed the docker hello world without any problems.

Thanks in advance to anyone who offers any light.

**Comment by klokan** [comment]
https://medium.com/@ibrahimgunduz34/if-you-faced-an-issue-like-couldnt-connect-to-docker-daemon-at-http-docker-localunixsocket-is-27b35f17d09d

**Comment by carlos-mg89** [comment]
@klokan thank you! It worked after adding my user to the docker user group. I have to confess I'm quite new in Docker and have barely used a few times.
