### ISSUE TITLE
water_name geometry is point

### ISSUE THREAD

**Issue by guyisra** [openmaptiles/openmaptiles#482]
while the schema says 
"This is based of the osm-lakelines project which derives nice centerlines from OSM water bodies"
and the osm-lakelines geojson does provide linestrings.

The tiles themselves return Point geometry so the text can't be placed on the centerlines

Is this intentional or a bug?

**Comment by klokan** [comment]
On the lakes these are lines...

OSM Bright / Lake Geneva:
![screen shot 2018-07-31 at 14 15 11](https://user-images.githubusercontent.com/59284/43458927-3237cd14-94cc-11e8-8ddb-f69cdb554c73.png)

**Comment by guyisra** [comment]
ah thanks! so what logic exists to decide which lake has a string and which is a point? 
I see now that some lakes have a line, it took me a while to find them
It seems lakes only above certain size get a line, and the rest a point?
