### ISSUE TITLE
Multi-lingual streets

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#484]
For some applications, the street names need to be localized too.
We have skipped that while working on the multilingual #279 #211, but this may be added the same way we made place names, and many other objects.

The issue was the amount of the streets, and the efficiency of Postgres import and tile generating speed. We have perceived bilingual street names as an edge case and skipped that temporarily.

This can be reopened if there is an interest from third parties... pull request or supported time would be very welcome.  

Discussed at #SoTM 2018 with @varpushaukka from @HSLdevcom

**Comment by hannesj** [comment]
Duplicate of #388? This is being worked on in #490.

**Comment by klokan** [comment]
Correct. Duplicate. Closing.
