### ISSUE TITLE
How to add additional osm datasets to openmaptiles ? 

### ISSUE THREAD

**Issue by michaelknave** [openmaptiles/openmaptiles#485]
I would like to ask how can I add some additional osm datasets (countries) to the database and at the end  to one map?

Case: I have imported one country. Everything works. 

What, if I want to add another one ?

**Comment by tobinbradley** [comment]
Rather than run two tile sets and merge them (something I admittedly don't know how to do), what I do it is to get an extract area larger than my subject area from geofabrik, then use osmconvert to chop it down to the area I want and build tiles from it. My process looks like this (bash file):

```bash 
echo "Getting OSM data..."
wget http://download.geofabrik.de/north-america/us-south-latest.osm.pbf -q --show-progress

echo "Clipping PBF and dropping in data folder as meck..."
osmconvert us-south-latest.osm.pbf -b=-82.641,34.125,-79.008,36.762 --complex-ways -o=openmaptiles/data/meck.osm.pbf

echo "Get to the right place..."
cd ~/workspace/openmaptiles

echo "Run OpenMapTiles on meck..."
./quickstart.sh meck
```

**Comment by michaelknave** [comment]
Isn't better to use tool OSMIUM and use merge ? Then you can merge to different .pbf files. 

Because in case I would need 2 different areas which are far away from each other, I would end up with a lot of useless data...

**Comment by tobinbradley** [comment]
Could do. In that scenario I'd make two different mbtiles sets to avoid generating a lot of empty tiles between the two areas.

**Comment by michaelknave** [comment]
And how can I load data from 2 separate mbtiles datasets?

**Comment by michaelknave** [comment]
Please correct me if I am wrong, but when I run './quickstart.sh country1' and afterwards './quickstart.sh country2'. 

Isn't country1 being overwritten by country2? 

Or how can I process 2 cities one after each other?
