### ISSUE TITLE
Docker image version 1.7 not working

### ISSUE THREAD

**Issue by kemalmemis** [openmaptiles/openmaptiles#488]
Hello,
When I run the container image in CENTOS 7.2.15.11 version with the specified "docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/openmaptiles-server" command, the container hangs in starting state. When I connect to container's console, I run "top" command I could only see xvbf process is runnıng. Neither "nginx" or "node" is running? I have succeded to run this image in Centos 7.4(virtual machine) Could you please help me to figure out this silly problem?

**Comment by TomPohys** [comment]
hi @kemalmemis, Is this still a problem?
