### ISSUE TITLE
Updates take so long with no logs

### ISSUE THREAD

**Issue by michaelknave** [openmaptiles/openmaptiles#492]
I want to run update script on my dataset. I do it basic way by the docs, by running 

> docker-compose run update-osm

Problem is, that it takes so long. There are no errors or logs. I am testing it on a small dataset, so it shouldn't take so long. 

Has somebody experienced this ?

**Comment by MartinMikita** [comment]
Update-osm could take longer, it depends on the hardware architecture and network connection (downloading large diffs).
