### ISSUE TITLE
Collecting money without providing service is SCAM. Does your service work?

### ISSUE THREAD

**Issue by AEiosApp** [openmaptiles/openmaptiles#493]
Two days ago I've purchased custom map extraction but still can't get it. On my account, I can only see status "waiting".

I've written you on info@klokantech.com, but nobody answered me.

**Collecting money without providing service is SCAM**

**Comment by MartinMikita** [comment]
The service is running, but there are now more tasks for last days, which take a longer time, other customers requested large area to extract.
Please, be patient, the extract should be available in the following day or two.
