### ISSUE TITLE
Customize country boundaries

### ISSUE THREAD

**Issue by Rajavelu** [openmaptiles/openmaptiles#495]
Hi Guys,
              
I am using OpenMapTiles for our vector tiles server.

**Default Boundary of India :**
 
<img width="685" alt="screen shot 2018-09-06 at 12 46 19 pm" src="https://user-images.githubusercontent.com/19775829/45150445-844dfd00-b1e9-11e8-8886-2a95119e4f7a.png">

**Proper boundary we need :** 

<img width="573" alt="screen shot 2018-09-06 at 12 46 03 pm" src="https://user-images.githubusercontent.com/19775829/45150503-99c32700-b1e9-11e8-88b5-495192136736.png">

- By default, it shows incorrect India boundary. So i have created a layer in style.json using geojson data of all countries boundary data(with updated India boundary).

- But it's taking too much time to render boundary line. I've also tried trimming the geojson data(1.6mb), but still its rendering very slowly.

- I also tried to render country boundary using OpenMapTiles boundary data for all countries except India, then add layer using geojson for India boundary only.
But i can't disable rendering the default boundary for India using OpenMapTiles, as they are not providing country code or name with boundary data.

Any alternate options ?

_**Is there an option to change the boundary data of select countries in the mbtiles itself ?**_

Thanks.

**Comment by eva-j** [comment]
We are trying to find a solution for these cases - https://github.com/openmaptiles/openmaptiles/pull/706.

**Comment by somm-doe** [comment]
I have a similar issue; currently you cannot use the `name=` attribute to select the borders manually.
