### ISSUE TITLE
Missing Tiles

### ISSUE THREAD

**Issue by einavh** [openmaptiles/openmaptiles#496]
Hello,

I was using the openmaptiles project for importing osm data into postgis and used the generate-vectortiles in order to generate an .mbtiles file. when looking into the mbtiles file I see there are missing tiles in different zoom levels. How can I know weather it is a bug or it is because there is no additional data in the lower zoom levels?

Thank you!

**Comment by MartinMikita** [comment]
Missing tiles are always only if they are no additional data.
