### ISSUE TITLE
Getting some artifacts water polygon boundaries

### ISSUE THREAD

**Issue by joaojoyce** [openmaptiles/openmaptiles#497]
Hi,

I'm getting some artifacts in the water polygon boundaries for some zoom levels. 

An example would be Lisbon.
![screen shot 2018-09-08 at 10 51 39](https://user-images.githubusercontent.com/5451182/45253423-eaa85c00-b35e-11e8-9de5-cc55b4be1683.jpg)
Live: http://www.maptiler.com/maps/#basic//vector/9.78/-9.0357/38.6927
![screen shot 2018-09-08 at 12 04 06](https://user-images.githubusercontent.com/5451182/45253657-bb93e980-b362-11e8-8960-63fc5c76a81a.jpg)
Live: http://www.maptiler.com/maps/#basic//vector/7.59/-8.762/38.612

Also it looks like sometimes some streets end up in water areas and the river gets duplicated...
![screen shot 2018-09-08 at 12 04 06](https://user-images.githubusercontent.com/5451182/45253474-9651ac00-b35f-11e8-85e6-6904ce6e1bd1.jpg)
Live: http://www.maptiler.com/maps/#basic//vector/7.59/-8.762/38.612

Is this something that should be fixed in this project? 
Can I create better polygons in order to avoid these issues? How can I do that?

Thanks.

**Comment by joaojoyce** [comment]
This all happens between zoom 7 and zoom 8...
I guess there is some kind of transition from zoom-ranges that makes it look like that.

Please let me know if this is not the place to report this kind of issues.

**Comment by TomPohys** [comment]
This should be resolved by https://github.com/openmaptiles/import-water/pull/6. There are no artefacts at this moment.
