### ISSUE TITLE
Add new dataset/country into existing database

### ISSUE THREAD

**Issue by michaelknave** [openmaptiles/openmaptiles#498]
How can I add new country to an existing database ? 

I am experiencing a problem, when I donwload another dataset and trying if import via using 

> make import-osm

> make import-sql

after generating vector tiles I am getting invalid .mbtiles dataset

**Comment by MartinMikita** [comment]
You need to set the correct [BBOX](https://github.com/openmaptiles/openmaptiles/blob/master/.env#L10) for your new country, after you run `import-osm` and `import-sql` command.

However, `import-osm` step is not yet prepared to just import a new country into an existing database. By default, it uses a rotate system - creates new tables from OSM, and when the import succeeds, these tables are rotated. Which means, old tables are discarded.

As a workaround, you could simply merge OSM.PBF of your countries via an external tool ([`osmconvert` example](https://wiki.openstreetmap.org/wiki/Osmconvert#Merging_two_or_more_Geographical_Areas)), and simply run `make import-osm && make import-sql` commands.
Note, that you need to modify the `BBOX` environment variable to contains the whole area of your merged OMS.PBF files. You can get that via [`osmconvert` tool](https://wiki.openstreetmap.org/wiki/Osmconvert#Retrieving_Statistical_Data) as well.
