### ISSUE TITLE
Data missing in 4th zoom

### ISSUE THREAD

**Issue by Rajavelu** [openmaptiles/openmaptiles#500]
Hi,
1. At 4th zoom, States name data not showing for South India. 
2. Telangana state boundary showing from 6th zoom only, but other state boundaries are showing from 4th zoom.

![sindiadata_telangana_border_issue](https://user-images.githubusercontent.com/3033600/45940192-26951f80-bff5-11e8-9d7d-5b9a20faa513.gif)

**Comment by eva-j** [comment]
Solved in https://github.com/openmaptiles/openmaptiles/pull/613.
