### ISSUE TITLE
Missing construction for highway (transportation)

### ISSUE THREAD

**Issue by MartinMikita** [openmaptiles/openmaptiles#501]
The `transportation` layer is missing the `construction` mapping, see [description of lifecycle](https://wiki.openstreetmap.org/wiki/Key:highway?uselang=en-US#Lifecycle).

An example: [The bridge `Honk-Kong-Zhuhai-Macao`](https://www.openstreetmap.org/way/572611768/history) has been tagged incorrectly as completed, but fixed later, now it is not visible in OSM vector tiles.

**Comment by pathmapper** [comment]
Related: https://github.com/openmaptiles/openmaptiles/issues/321, https://github.com/openmaptiles/openmaptiles/issues/82

**Comment by MartinMikita** [comment]
Thanks, haven't able to find it. Closed this ticket as duplicate of #321
