### ISSUE TITLE
Removal of Front Page Redirect?

### ISSUE THREAD

**Issue by AaronGeo** [openmaptiles/openmaptiles#502]
Hello,

as the title says, I've got a big problem with the redirect/URL remapping of the openmaptiles-server.

I've got docker set up on a web server that handles outgoing connections with Apache and can be reached from the internet, over the standard port. 
While setting up openmaptiles-server (locally on the server) with the wizard, I chose to redirect the frontpage to a folder in the localhost root directory. However, I misspelled. 
Now I cannot reach the service from anywhere, because of the meesed up redirect. 

I tried: 
- docker rm -f [openmaptiles-serverID]
- docker system prune -a
- restart docker
- clean browser cache
- restart server and apache service
- reinstall openmaptiles server with docker run --rm -it -v %cd%:/data -p 8080:80 klokantech/openmaptiles-server

still, after all that, as soon as the openmaptiles-server container gets istalled in the default location again, 

My question is simple: 
How, the hell, can I remove this front page remapping, once I configured it? It has to be reversible. 
I even tried reinstalling docker. Nothing works......the remapping still remains as soon as openmaptiles-server is reinstalled. 

Regards

Aaron

**Comment by MartinMikita** [comment]
This is not an issue of OpenMapTiles schema.

Please, use [free support channel](https://stackoverflow.com/questions/tagged/openmaptiles) related with OpenMapTiles instead.

P.S. The redirect can be saved by your browser, but not in the cache, and/or requires the restart of the browser. Or you have incorrectly set up your Apache server.
