### ISSUE TITLE
load map resource failed

### ISSUE THREAD

**Issue by HeiYanjing** [openmaptiles/openmaptiles#503]
Recently,something wrong happend in my docker openmaptiles,
![image](https://user-images.githubusercontent.com/42837853/46254009-3f9d4500-c4bb-11e8-96f1-d72f0f87b76d.png)
in  openmaptiles website ,I download the offline map of my city for free,and run in docker。
there is no problem for personal development.but in local area network，my colleagues something want  to see my development project.  Something in chrom or firefox broswer it cannot load map rescource , but  sometimes it can loaded successful. 
when failed.in development tools:
![image](https://user-images.githubusercontent.com/42837853/46254119-d5859f80-c4bc-11e8-8b06-24d965f36440.png)
![image](https://user-images.githubusercontent.com/42837853/46254121-db7b8080-c4bc-11e8-8d7a-c7433ded9c72.png)
I don't know why,Is it because I use the free map resource?

**Comment by MartinMikita** [comment]
This is not a problem of OpenMapTiles project - it seems you need to allow firewall or access in your local area network.
