### ISSUE TITLE
Totally remove mapbox-studio-classic

### ISSUE THREAD

**Issue by typebrook** [openmaptiles/openmaptiles#505]
@jirik @klokan @MartinMikita @lukasmartinelli 
I want to **totally** remove `mapbox-studio-classic` from openmaptiles.  
Please give me some feedback! Thanks!

Since travis build for [mapbox/mapbox-studio-classic](https://github.com/mapbox/mapbox-studio-classic) keeps failing from 9 months ago, I think there is no evidence that this project is alive/backed by Mapbox.

ref:
Travis build history: https://travis-ci.org/mapbox/mapbox-studio-classic/builds
related issue : https://github.com/mapbox/mapbox-studio-classic/issues/1581

The latest PR about `mapbox-studio-classic` is #304  (tiny part of quickstart refactoring #261 )
But since the author stopped working on it for 9 month, and original intend is moving it to Makefile, I think it's OK to just make another tiny commit on master branch.

by the way, it is a little scary that master branch stopped at :japanese_ogre: **666** commits over 2 months. if experienced contributors think it is OK, I will quickly make a simple PR for this.

**Comment by MartinMikita** [comment]
Hi @typebrook,

You can prepare a PR with a removal of mapbox-studio-classic, or you can try to find a way to get it working.

Well, there were no required changes, and we are still looking for enthusiastic contributors ;)

**Comment by typebrook** [comment]
@MartinMikita Thanks for you reply, PR made #506 
Removal is simple, but I think more important things is the necessity evaluation for this move.
I don't have any experience about this classic version, but it just annoyed me by failing on it's docker running.

Any Mapbox worker/experienced user here?  Do we still need this thing?

**Comment by typebrook** [comment]
#506 
Close
