### ISSUE TITLE
how to resolve openmaptiles-server cross-domain 

### ISSUE THREAD

**Issue by HeiYanjing** [openmaptiles/openmaptiles#507]
recently , a problem puzzled me.
I use docker toolbox to run openmaptiles-server,and mapbox develop for native. In my computer ,mapbox style.json file(url,sprite,glyphs)connect to openmaptiles-server. but in local area network. my mates cannot load map resource ,in  firefox browser console , it show: 
Intercepting cross source requests。The same-origin policy prohibits reading openmaptiles-server resource
I search this question.there are some solutions. 

1. in http request header add "Access-Control-Allow-Origin:*" ,but style.json  unable to add header.

2. in server's root folder add crossdomain.xml file

so in openmaptiles-server  in windows docker toolbox or in ubuntu docker environment ,how can I resolve it.

**Comment by MartinMikita** [comment]
This is not an issue of OpenMapTiles schema.

Please, [use free support channel](https://stackoverflow.com/questions/tagged/openmaptiles) related with OpenMapTiles instead.
