### ISSUE TITLE
Custom style directory not working

### ISSUE THREAD

**Issue by Rajavelu** [openmaptiles/openmaptiles#508]
Hi,
I am using docker for running tileserve-gl.
Having my customised styles (incl mbtiles) under /home/user/tileserver/tileserver-gl-styles.
config.json file contains the following:
{
  "options": {
    "paths": {
      "root": "/home/user/tileserver/tileserver-gl-styles",
      "fonts": "fonts",
      "styles": "styles",
      "mbtiles": "/data"
    }
  }
...........
}

When i am trying to start tileserver as: **docker --config /home/user/tileserver run -it -v /home/user/tileserver:/data -p 8080:80 klokantech/tileserver-gl --verbose**
got below error:
Waiting 3 seconds for xvfb to start...
Starting tileserver-gl v2.4.0
Using specified config file from config.json
Starting server
**The specified path for "styles" does not exist (/home/user/tileserver/tileserver-gl-styles/styles).**

I am sure /home/user/tileserver/tileserver-gl-styles/styles directory available & contains klokantech-basic & osm-bright as sub-directories (which has style.json).

**Comment by MartinMikita** [comment]
This repository is used for issues related with OpenMapTiles Schema, not for other systems, that uses OpenMapTiles.

If you want free support, take a look [on stackoverflow for OpenMapTiles](https://stackoverflow.com/questions/tagged/openmaptiles), or [search on tileserver-gl repo](https://github.com/klokantech/tileserver-gl).

Hints: you are using docker, where you mounts external path as volume. Change the root to **/data/tileserver-gl-styles**.
