### ISSUE TITLE
Landuse

### ISSUE THREAD

**Issue by pnorman** [openmaptiles/openmaptiles#51]
Landuse from OSM data is often tricky, and people can decide to go different ways with it. This being said, I just can't figure out what the cartographic decisions behind the selections in https://github.com/openmaptiles/openmaptiles/blob/master/layers/landuse/landuse.sql are.

**Comment by lukasmartinelli** [comment]
New links:
- **landcover**: https://openmaptiles.org/schema/#landcover
- **park**: https://openmaptiles.org/schema/#park
- **landuse**: https://openmaptiles.org/schema/#landuse
