### ISSUE TITLE
Ways with tag bicycle = designated should be tagged

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#512]
Some `ways` that are paths are not designated as a `highway = cycleway`, instead the use the `tag` `bicycle = designated`. See https://www.openstreetmap.org/way/107483312#map=15/45.6287/-122.4478

<img width="766" alt="screen shot 2018-10-16 at 12 38 16 pm" src="https://user-images.githubusercontent.com/30858/47042633-a4ee6880-d140-11e8-8cc4-5cc0877a6337.png">

These types of `paths` should include data in the .mbtiles file so that they can be styled as a bike path.

Other locations are correctly created with `highway = cycleway`, see: https://www.openstreetmap.org/way/88732778

<img width="926" alt="screen shot 2018-10-16 at 12 39 14 pm" src="https://user-images.githubusercontent.com/30858/47042643-b0419400-d140-11e8-8697-5d1a475f9fe7.png">

**Comment by MartinMikita** [comment]
Thanks for your discovery.

According to the [OSM wiki about cycling](https://wiki.openstreetmap.org/wiki/Bicycle_tags_map), this is correct and expected tagging.

Pull requests are welcome!

**Comment by nnhubbard** [comment]
I guess instead of making it a `cycleway`, the `bicycle = designated` tag should be imported so that those can be styled differently if needed.

**Comment by zstadler** [comment]
I agree with @nnhubbard comment above.

PR https://github.com/openmaptiles/openmaptiles/pull/573 is adding a `bicycle` tag, but it combines `bicycle=designated` info `bicycle=yes`:
```
WHEN bicycle IN ('yes', 'designated') THEN true
```
