### ISSUE TITLE
No national park names

### ISSUE THREAD

**Issue by Frankkky** [openmaptiles/openmaptiles#513]
Hi,

On all the world map, each national park and natural reserve doesn't have any name. I checked with the inspect mode and I can confirm that the names are not in the schema/tiles data (at least the point to localize the name is not there), so it's not a style problem. Also, those names appear correctly on OpenStreetMap (you can check for any national park in the world).

It's a huge miss, especially when we want to use the map for tourism... :-(

Any plan to add the national park and natural reserve names in the tiles/schema? On my side, I don't have the skill to tweak openmaptiles script to add them. I able to run it however on our server and edit the code files, if someone can tell me which one to edit.

Thank you in advance,

Frankkky

**Comment by jirik** [comment]
Implemented by #521

**Comment by jirik** [comment]
`park_label` layer should be merged with `park` layer. Label will be encoded as point features.
