### ISSUE TITLE
 Transparent islands in Denmark

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/openmaptiles#519]
Reported in: https://github.com/maputnik/osm-liberty/issues/41

Similar issue in the past: https://github.com/openmaptiles/openmaptiles/issues/458

-----
https://www.maptiler.com/maps/#streets//vector/12.15/11.90137/55.76951
![auswahl_431](https://user-images.githubusercontent.com/20856381/47619072-cf460b80-dada-11e8-8d52-fcd0007fa469.png)

-----
https://www.maptiler.com/maps/#streets//vector/12.1/11.20787/55.88158

![auswahl_432](https://user-images.githubusercontent.com/20856381/47619080-03213100-dadb-11e8-9676-0078ba5b9f63.png)

**Comment by jirik** [comment]
related: #447

**Comment by jirik** [comment]
Island (or generally land) polygons are not encoded in openmaptiles. Only water polygons are. The rest of the planet is considered as land.

The problem here is that water polygon Isefjorden does not contain "holes" of islands, so it's data related issue.
https://www.openstreetmap.org/relation/8312488

Solution: Add island holes to Isefjorden relation.

**Comment by pathmapper** [comment]
Fixed it in 

https://www.openstreetmap.org/changeset/64194291
and 
https://www.openstreetmap.org/changeset/64194575

> The problem here is that water polygon Isefjorden does not contain "holes" of islands, so it's data related issue.

Looks like this is a recurring issue for OMT, so I would like to note that:

> There is currently no definitive rule if small islands within a bay should be mapped as part of the bay or if they should be excluded of the bay area as inner rings of the corresponding multipolygon relation.

(from https://wiki.openstreetmap.org/wiki/Tag:natural=bay)

Maybe it's worth to think about to start a discussion whithin the OSM community whether there should be a definitve rule to exlude islands from bay areas.

**Comment by pathmapper** [comment]
Or is encoding [islands](https://wiki.openstreetmap.org/wiki/Tag:place%3Disland) and [islets](https://wiki.openstreetmap.org/wiki/Tag:place%3Dislet) in OpenMapTiles an option?

**Comment by jirik** [comment]
@pathmapper Thanks for fixing the data and especially for pointing out inexistence of the rule. I've created #522 issue with thoughts about prevention of such recurring issues.

**Comment by jirik** [comment]
> Or is encoding islands and islets in OpenMapTiles an option?

Erasing their area seems more reasonable with respect to current styles.

**Comment by arnekaiser** [comment]
Looks like there is the same problem at the port of Hvide Sande in Denmark:

![image](https://user-images.githubusercontent.com/5116350/58711224-5edbd180-83be-11e9-9b67-251c29718ad9.png)

https://www.maptiler.com/maps/#streets//vector/15.34/8.131292/56.001509

**Comment by daliborjanak** [comment]
@arnekaiser this is already fixed but not deployed. We are working on a new release, will be deployed soon
