### ISSUE TITLE
Add tram stops

### ISSUE THREAD

**Issue by pnorman** [openmaptiles/openmaptiles#52]
railway=tram_stop

I'm inclined to think this should go with highway=bus_stop into its own layer.

**Comment by pnorman** [comment]
Any decisions on this?

I'm inclined towards having one field for transit mode and another for station vs stop. You've got both bus station / bus stop and railway station / railway halt.

**Comment by lukasmartinelli** [comment]
> Any decisions on this?
> 
> I'm inclined towards having one field for transit mode and another for station vs stop. You've got both bus station / bus stop and railway station / railway halt.

Do you favor a field over a separate transport layer?
For me either way is good.  The `poi` layer as of right now is really not refined at all. The next implementation of the poi layers can adjust to your proposed schema. I have no hard opinions here.

**Comment by stirringhalo** [comment]
I think it should be a separate layer as the stops get can rather numerous in cities, and I can see that many would not find it strictly necessary for their uses.

**Comment by pnorman** [comment]
> Do you favor a field over a separate transport layer?

A separate layer for each mode?

`transport_stop` is an okay name, but I like `transit_stop` better because we're dealing with just transit stuff, not stuff like stop signs.

> I think it should be a separate layer as the stops get can rather numerous in cities, and I can see that many would not find it strictly necessary for their uses.

Although I support adding a layer, I don't find data density a reason to do so.

**Comment by pnorman** [comment]
Just to note, the mods that I have are

- ferry
- rail
- taxi
- bus

**Comment by lukasmartinelli** [comment]
Can you list the new fields and the possible values like you did for the other layers so I can add them to the docs?

So `transit_stop`= on of `ferry`, `rail`, `taxi`, `bus` ?

BTW. is there already an endpoint for the Wikimedia tiles?

**Comment by pnorman** [comment]
fields
- `mode` (text) The mode of transportation. Values are `ferry`, `rail`, `taxi`, `bus`, and `subway` (not implemented by me yet)
- `station` (boolean) If the feature is a larger station or a small stop.

Within ClearTables I'm calling the mode of transportation "transit_mode" to avoid name collisions with the "mode" function when writing queries.

> BTW. is there already an endpoint for the Wikimedia tiles?

The best bet is to poke me in #wikimedia-interactive on irc.freenode.net. There is a dev instance running Kosmtik with the tiles on a wmflabs machine, but Kosmtik gets shut down and restarted fairly regularly.

**Comment by jirik** [comment]
Most of this issue is already implemented:
- tram_stop as class=railway, subclass=tram_stop
- subway as class=railway, subclass=subway
- ferry as class=ferry_terminal
- bus as class=bus, subclass IN (bus_stop, bus_station)
- taxi as class=car, subclass=taxi

For the next major release of OMT (4.0) it probably makes sense to create separate stop for stations and stops.
