### ISSUE TITLE
Waterway:dock is showing up as land

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#526]
From: https://www.maptiler.com/how-to/forum/?place=msg%2Fmaptiler%2Fl1ze-S1tgDY%2F71P-1HIiBQAJ
>
> Waterway:dock is showing up as land on maptiler maps.
>
> I tried to add style to make it same as water. However, the layer doesn't show up.
> 
> On openstreetmap the Royal Dock in Grimsby is water, but not on MapTiler:
> https://www.openstreetmap.org/#map=15/53.5793/-0.0716
>
> Here's my style:
```
{
  "id": "waterway_dock",
  "type": "fill",
  "metadata": {},
  "source": "openmaptiles",
  "source-layer": "waterway",
  "filter": [
    "all",
    [
      "==",
      "class",
      "dock"
    ]
  ],
  "layout": {},
  "paint": {
    "fill-color": "rgba(232, 20, 20, 1)"
  }
}
```

https://www.maptiler.com/maps/#streets//vector/15/-0.0716/53.5793
https://openmaptiles.org/inspect/#15/53.5793/-0.0716

**Comment by klokan** [comment]
Probably related to #522 - but here we need to join with the water? @jirik

**Comment by klokan** [comment]
Could be probably also solved by modification of the data in OSM in this individual case... but the question is whether there are similar data issues elsewhere...

**Comment by anajavi** [comment]
Here's an another example:
https://www.openstreetmap.org/#map=15/53.9179/-3.0086
https://openmaptiles.org/inspect/#15/53.9177/-3.0138

**Comment by pathmapper** [comment]
There are likely a lot more:
http://overpass-turbo.eu/s/Du1

Some examples:

London:
https://www.openstreetmap.org/#map=15/51.5060/0.0436
https://www.maptiler.com/maps/#streets//vector/14.5/0.03945/51.50291

Paris:
https://www.openstreetmap.org/#map=16/48.7806/2.4871
https://www.maptiler.com/maps/#streets//vector/14.75/2.48263/48.78207

Bristol:
https://www.openstreetmap.org/relation/1250536
https://www.maptiler.com/maps/#streets//vector/14.83/-2.60485/51.44872

Liverpool:
https://www.openstreetmap.org/#map=14/53.4406/-3.0018
https://www.maptiler.com/maps/#streets//vector/12.76/-3.0247/53.4363

Hull:
https://www.openstreetmap.org/#map=15/53.7328/-0.3417
https://www.maptiler.com/maps/#streets//vector/14.83/-0.3355/53.73769
