### ISSUE TITLE
Water polygons over small islands in Finland

### ISSUE THREAD

**Issue by MartinMikita** [openmaptiles/openmaptiles#534]
Reported by the customers: https://support.maptiler.com/i221-missing-land

There are few tiles around Finland, which are filled fully with water:lake polygons over the whole vector tile. They are different on zooms 10, 11, and possibly 12.
Mostly around [the area here](https://openmaptiles.org/inspect/#9.68/60.0899/22.1208)

Zoom 9:
![image](https://user-images.githubusercontent.com/2283182/48556955-ac429680-e8e5-11e8-86e2-9775b405beaf.png)

Zoom 10:
![image](https://user-images.githubusercontent.com/2283182/48556941-a5b41f00-e8e5-11e8-8ecf-52cce46f9cb5.png)

Inspect mode Z9:
![image](https://user-images.githubusercontent.com/2283182/48556990-c67c7480-e8e5-11e8-94c8-9ef38f0f5b03.png)

Inspect mode Z10:
![image](https://user-images.githubusercontent.com/2283182/48557015-da27db00-e8e5-11e8-8a95-b86ef0de01ec.png)

**Comment by jirik** [comment]
Interesting: https://www.openstreetmap.org/way/25719239#map=16/60.2795/21.7701
![image](https://user-images.githubusercontent.com/2271850/48571356-ee300480-e906-11e8-8259-0ef33dec1312.png)

**Comment by klokan** [comment]
@jirik - is this related to #522 ? Going to be fixed in v3.9?

**Comment by jirik** [comment]
It's not related to #522, at least not directly. Not sure about v3.9 - waiting for planet rendering test.

**Comment by jirik** [comment]
Fixed in v3.9:
![image](https://user-images.githubusercontent.com/2271850/49212821-3c430e80-f3c3-11e8-9bf9-47c85af2b146.png)

It's probably some updates-related issue. New rendering should help to similar bugs.
