### ISSUE TITLE
Korean romanisation

### ISSUE THREAD

**Issue by ianthetechie** [openmaptiles/openmaptiles#537]
I noticed that the `name:ko_rm` tag is still used in the schema. I'm not sure if the best answer is to remove it or to update it to the proper tag.

The Korean OSM community decided that the tag should be discontinued in favor of `name:ko-Latn`, and we did an mass edit to clean up old data, so this isn't going to be particularly useful (see here for details: https://wiki.openstreetmap.org/wiki/Automated_edits/Ian_Wagner).

Looking at the YAML files, it seems like this is treated as a distinct language. Based on the generated SQL, it appears to fall back to the original Korean name (`name:ko`), so I guess the resulting map would be a mix of explicitly tagged romanisations of Korean names + a lot of original Korean names.

I wanted to check in and make sure I am understanding the bigger picture and best course of action before submitting a PR. I assume that since things still work properly today, there is some separate "latin name" logic derivation under the hood? I am aware the a large part of Korea is (somewhat incorrectly) tagged with `name:en` as well, so that may be another reason that all appears well on the surface, even after the changes.

**Comment by TomPohys** [comment]
Hi @ianthetechie, change from ko_rm (52)  to ko-Latn (135k) will be done! The same situation is for Japanese (name:ja (669k); name:ja_rm (99k); name:ja_kana (48k) ; name:ja_Latn (44k) ; name:ja-Hira (40k))
