### ISSUE TITLE
import-osm zlib read error

### ISSUE THREAD

**Issue by lanmaster** [openmaptiles/openmaptiles#538]
Trying to start ./quickstart.sh and get this error on import-osm step.
If i start this step manually - it occured againg.

> [root@localhost openmaptiles]# docker-compose run --rm import-osm
> Importing in normal mode
> [Nov 28 07:16:27] [INFO] removing existing cache /cache
> [Nov 28 07:16:27] [INFO] [reader] reading /import/albania.osm.pbf with data till 2018-11-27 21:14:02 +0000 UTC
> 2018/11/28 07:16:29 lowlevel.go:76: zlib read error: unexpected EOF900/s    1900/s (5678) W:       0/s       0/s (0) R:      0/s      0/s (0)
> panic: zlib read error: unexpected EOF
> 
> goroutine 30 [running]:
> log.Panic(0xc420043d90, 0x1, 0x1)
>         /usr/local/go/src/log/log.go:322 +0xc0
> github.com/omniscale/imposm3/parser/pbf.readPrimitiveBlock(0x7ffd2a8a6d59, 0x17, 0xbccbb2, 0xc4000086c6, 0xc42048ee68)
>         /go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:76 +0xe3
> github.com/omniscale/imposm3/parser/pbf.(*Parser).parseBlock(0xc4200a1c70, 0x7ffd2a8a6d59, 0x17, 0xbccbb2, 0x86c6)
>         /go/src/github.com/omniscale/imposm3/parser/pbf/process.go:89 +0x68
> github.com/omniscale/imposm3/parser/pbf.(*Parser).Parse.func1(0xc4202536e0, 0xc4200a1c70)
>         /go/src/github.com/omniscale/imposm3/parser/pbf/process.go:56 +0xc8
> created by github.com/omniscale/imposm3/parser/pbf.(*Parser).Parse
>         /go/src/github.com/omniscale/imposm3/parser/pbf/process.go:65 +0x101
> 

Hardware: 
--- Windows 7 64bit
--- --- VirtualBox 5.2.20
--- --- --- CentOS 7.5
--- --- --- --- Docker 1.13.1 / Docker-compose 1.23.1

**Comment by lanmaster** [comment]
I edited docker-compose.yml change line 31 from
image: "openmaptiles/import-osm:0.5"
to 
image: "openmaptiles/import-osm"

and restart 
>docker-compose run --rm import-osm

Docker loaded image 'docker.io/openmaptiles/import-osm:latest'.

And there is the same error occured.

**Comment by lanmaster** [comment]
Trying to start in virtual CentOS 7.2

**Comment by typebrook** [comment]
Make sure your osm.pbf file is complete
https://github.com/omniscale/imposm3/issues/172

If it is, try to make your docker image with latest `imposm`.
The latest `import-osm` use its code a year ago 
https://github.com/openmaptiles/import-osm/blob/master/Dockerfile

**Comment by MartinMikita** [comment]
@lanmaster have you verified, that the downloaded PBF is valid?

You can verify the file via MD5 sum from the [geofabrik download page](http://download.geofabrik.de/europe/albania.html) for your selected region (Albania, by default).

We have never experienced this problem, and as it was mentioned by @typebrook, it could be the problem with the incompleted download of your PBF file.

We are closing this ticket, as it is not the problem of this repository and the OpenMapTiles scheme.
