### ISSUE TITLE
Cannot show 'positron-gl-style' map on tileserver-GL

### ISSUE THREAD

**Issue by hc2013** [openmaptiles/openmaptiles#540]
I download positron-gl-style from `https://github.com/openmaptiles/positron-gl-style.git` and change style.json to reference local mbtiles  like that:
`"sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "mbtiles://{cuba}"
    }
  }`
and I have add {cuba} in config.json like that
`"data": {
      "cuba":{
        "source":"2017-07-03_central-america_cuba.mbtiles"
      }
    },`

then,I start tileserver-gl .It can start correctly,but when i click "viewer" button on the index page for  positron-gl-style.It can not show the map.It's totoally blank!

I'm sure that I have correctly config the mbtiles path in config.json.The other two styles 'Klokantech Basic' and 'Osm-Bright' can show the map correctly.
Is there some step that i missed for referencing mbtiles from data in style.json?
@klokan @sfkeller @smellman @hfu @prozessor13

**Comment by typebrook** [comment]
Seems format is incorrect, 
` "data": { "cuba":{ "source":"2017-07-03_central-america_cuba.mbtiles" } }`
should be changed into
` "data": { "mbtiles":{ "source":"2017-07-03_central-america_cuba.mbtiles" } }`

ref:
https://tileserver.readthedocs.io/en/latest/config.html#

**Comment by MartinMikita** [comment]
According to the [tileserver-gl config](https://tileserver.readthedocs.io/en/latest/config.html#data), the correct data should be:
```
"data": {
  "cuba": {
    "mbtiles": "2017-07-03_central-america_cuba.mbtiles"
  }
}
```

When using the `mbtiles://{cuba}` as URL for `sources` in the style.
