### ISSUE TITLE
Europe much longer than other regions

### ISSUE THREAD

**Issue by albanm** [openmaptiles/openmaptiles#541]
Hello,

Using the 3.8.1 version and the quickstart script after simply modifying .env to set MAX_ZOOM=14

I know long render times are to be expected for planet or large regions rendering. But still there is something weird here.

Large and dense regions like asia or north-america display rendering times of about 20 or 30 days on the VMs I use. But europe is at more than 300 ! When I llook at the processes using the top command, I see 4 posgres threads at almost 100% but the node process only at 3 or 4% while on the other regions the node process is at about 120%.

Any idea why this is so long, anything I can do ?

**Comment by MartinMikita** [comment]
Hello,

As you can see from [geofabrik download page](http://download.geofabrik.de/index.html), Europe has 19 GB, as opposed to Asia (6.5 GB) or North America (8.1 GB).

This means, there are 2-3x times more data, which requires more CPU to process. Therefore the postgres threads are at 100%, and node processes are waiting for the database.

There is nothing special you can do, just wait, or download our pre-generated tiles from [openmaptiles.com](https://openmaptiles.com/downloads/europe/).
