### ISSUE TITLE
Add possibility to render protected areas

### ISSUE THREAD

**Issue by sylvain-m** [openmaptiles/openmaptiles#542]
Following the requests made on the [OpenStreetMap-Carto rendering](https://github.com/gravitystorm/openstreetmap-carto/pull/3509) and on [Qwant Maps](https://github.com/QwantResearch/qwant-basic-gl-style/issues/61), it would be useful to be able to integrate the data on the protected areas (`boundary=proteced_area`), to allow their rendering.

I do not know enough about the OpenMapTiles project, but I would like to relay this request here because the subject of protected areas is of particular interest to me.

As for the OSM-Carto rendering, it will soon be operational. You can see [here the result of the PR](http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#8.00/49.297/2.519).

Thank you in advance to those who will allow this rendering.

Sylvain M.

**Comment by TomPohys** [comment]
Resolved by https://github.com/openmaptiles/openmaptiles/pull/773
