### ISSUE TITLE
Missing tiles & subdirectories after rending from maptiler plus

### ISSUE THREAD

**Issue by acberkley** [openmaptiles/openmaptiles#547]
It appears as though my maptiler plus render isn’t creating the full set of subdirectories and respective tiles. For example, when choosing Web Apps Standard hosting and setting a zoom from 0 to 4, zoom level 3 only has subdirectories 1 to 5, but should also include subdirectories 6 and 7 as well, no? 
My understanding is that this is causing doubling artifacts because it’s trying to load and draw new tiles while holding on to the previous layers, but some of the tiles aren't loading because they're not there. Initially I tried doing this with an image from a relatively small part of the planet (the MENA region) and thought that might be causing the issue, but I have also tried with an image covering the entire globe and still get double artifacts (please see attached). 
![map_tiler_issue_v2](https://user-images.githubusercontent.com/26399349/50082930-7fd6ae80-01f2-11e9-94a1-8b48d9a20982.JPG)

**Comment by MartinMikita** [comment]
Hi, If you are using MapTiler Desktop, you should report into the support channel from the application - https://support.maptiler.com/s2-desktop.
This is repository related to OpenMapTiles Vector Scheme project.
