### ISSUE TITLE
Place layer

### ISSUE THREAD

**Issue by pnorman** [openmaptiles/openmaptiles#55]
I'm looking at the place layer and have some feedback

## Column changes suggested
- `class` (String): `country`, `state`, `settlement`, `subregion`, or `other`. 
- `capital` (Numeric): For settlements the place is a capital, what admin_level it is capital of. `2` and `4` only.
- `place_detail` (String): For `settlement`, one of `city`, `town`, `village`, `hamlet`, `isolated_dwelling`. For  `subregion`, `suburb` or `neighbourhood`. For `other`, one of `locality` or `farm`.

I'm not certain of `rank`. As described, it ties an implementation into using Natural Earth data.

**Comment by lukasmartinelli** [comment]
The schema in place as described in https://openmaptiles.org/schema/#place works well for us and all the styles in https://openmaptiles.org/styles/.

If you want additional fields in the schema docs (superset) please note otherwise we would like to leave it as it is for OpenMapTiles.
