### ISSUE TITLE
Continued invalid key error when starting with docker

### ISSUE THREAD

**Issue by rustygreen** [openmaptiles/openmaptiles#551]
When running the maptiles server locally (localhost:8080) on Ubuntu 18.10 using Docker, I continually get the "Invalid key or download temporarily unavailable!" when I try to start a download. I get the key directly from the provided link, but any key I enter returns this message.

![image](https://user-images.githubusercontent.com/1774477/50232854-17b5d300-0380-11e9-8099-78b7ec31a5a0.png)

**Comment by MartinMikita** [comment]
Hi,

please, could you write more info - what region, enter the key itself, and submit it as the email to support@maptiler.com?

This repository is for OpenMapTiles Vector Scheme, [the support](https://openmaptiles.com/support/) for Downloads and OpenMapTiles Server is provided by MapTiler Team.
