### ISSUE TITLE
Use same docker version of "import-osm"

### ISSUE THREAD

**Issue by typebrook** [openmaptiles/openmaptiles#558]
Since `import-osm:0.5` is introduced in #356 for docker-compose service `import-osm`, it is weird to keep `import-osm:0.4` as another docker image for services `import-osm-diff` and `update-osm`. For now it is fine to use newer version without any bug.

**Comment by MartinMikita** [comment]
Yes, thanks for the notice. We have merged your PR #559.

Thanks for your contribution!
