### ISSUE TITLE
Bicycle and motorcycle parkings

### ISSUE THREAD

**Issue by Phyks** [openmaptiles/openmaptiles#565]
Hi,

It seems that currently both bicycle and motorcycle parkings are ignored from [the amenities included in the tiles](https://github.com/openmaptiles/openmaptiles/blob/master/layers/poi/mapping.yaml#L10).

Having them would be super useful for cycle-oriented render, but as well for regular renders (they are shown on numerous renders including the one on osm.org).

Could OMT include the `amenity=bicycle_parking` and `amenity=motorcycle_parking` tags? I could make a PR for this.

Best,

**Comment by Phyks** [comment]
I have a branch ready for this [here](https://github.com/phyks/openmaptiles/tree/parking).

On Albania, resulting `tiles.mbtiles` (at zoom level 14) is 106369024 bytes (versus 106508288 for the current `master`).

**Comment by MartinMikita** [comment]
Hi Phyks,

could you compare the size of Switzerland and Czechia (Czech republic) regions, with zooms 0-14?
It seems, these tags should not increase it a lot, but your comparison could help us to include it earlier.

Prepare a PR, please.

Thanks for your contribution!

**Comment by francois2metz** [comment]
This issue can now be closed.
