### ISSUE TITLE
No locksmith shop on tiles

### ISSUE THREAD

**Issue by bristow** [openmaptiles/openmaptiles#566]
I report this issue : https://github.com/QwantResearch/qwantmaps/issues/23

It seems that there is no shoemaker or locksmith on openmaptiles : https://github.com/openmaptiles/openmaptiles/blob/master/layers/poi/mapping.yaml#L117

Could openmaptiles include the shop=locksmith tags ?

Thanks !

**Comment by MartinMikita** [comment]
Hi @bristow,

Thanks for your interest in our OpenMapTiles project.

You can simply prepare PR and test your suggestion. We would welcome also comparison about sizes and times for your change, for some regions: Albania, Switzerland, Czechia, and/or your region.

Thanks for your contribution!
