### ISSUE TITLE
Update import-water docker image regularly

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/openmaptiles#575]
Currently OMT uses import-water `0.6`, probably with OSM data from [2017-10-28](https://github.com/openmaptiles/import-water#version-of-openstreetmapdata)  which is quite old.

A more frequent update would be desirable.

Until there is a solution as proposed in https://github.com/openmaptiles/openmaptiles/issues/522 (importing islands and islets polygons and erase their area from water polygons), it happens often that islands covered by water must be fixed in the OSM data like in https://github.com/openmaptiles/openmaptiles/issues/447 and https://github.com/openmaptiles/openmaptiles/issues/519.

Probably related: https://github.com/openmaptiles/openmaptiles/issues/574 (Edit: it seems to be not related)

**Comment by daliborjanak** [comment]
Import water was updated to 1.1. https://github.com/openmaptiles/openmaptiles/blob/master/docker-compose.yml#L21
