### ISSUE TITLE
Disputed borders are not marked as disputed at low zoom levels

### ISSUE THREAD

**Issue by xaerov** [openmaptiles/openmaptiles#577]
**Actual result:**
Disputed country borders are not marked as disputed in zoom levels [1-5]
![Actual result at zoom level 5](https://i.ibb.co/cXG69RT/map1.png)
https://openmaptiles.com/downloads/dataset/osm/#5.88/28.034/94.171
**Expected result:**
Disputed country borders should be marked as disputed in zoom levels 1-5
![Expected result is the same as actual one at zoom level 7](https://i.ibb.co/vDVKN6s/map2.png)

Hint:
Looks like, the problem is in layers/boundary/boundary.sql file:
```
CREATE OR REPLACE VIEW boundary_z4 AS (
    SELECT geometry, 2 AS admin_level, false AS disputed, false AS maritime
```
Should be replaced with something like:
```
CREATE OR REPLACE VIEW boundary_z4 AS (
    SELECT geometry, 2 AS admin_level, (CASE WHEN featurecla LIKE 'Disputed%' THEN true ELSE false END) AS disputed, false AS maritime
```

**Comment by eva-j** [comment]
Implemented in https://github.com/openmaptiles/openmaptiles/pull/704, thanks @xaerov
