### ISSUE TITLE
`make  'forced-clean-sql'` fails with Docker Toolbox for Windows 

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#580]
#### The problem
`./quickstart.sh` fails with the following error:
```
====> : Drop and Recreate PostgreSQL  public schema
docker-compose run --rm import-osm /usr/src/app/psql.sh -c "DROP SCHEMA IF EXISTS public CASCADE ; CREATE SCHEMA IF NOT EXISTS public; "
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"C:/Program Files/Git/usr/src/app/psql.sh\": stat C:/Program Files/Git/usr/src/app/psql.sh: no such file or directory": unknown
Makefile:192: recipe for target 'forced-clean-sql' failed
make: *** [forced-clean-sql] Error 1
```
#### Environment
Windows 10 Home
Docker Toolbox for Windows 18.03.0-ce, build 0520e24302
docker-compose version 1.20.1, build 5d8c71b2
openmaptiles/import-osm 0.5

#### Analysis
Docker Toolbox for Windows adds a `C:/Program Files/Git` prefix to the `/usr/src/app/psql.sh` command. This is a Toolbox for Windows bug.

However, this bug does not manifest itself in earlier `./quickstart.sh` use of `docker-compose run --rm import-osm` in `Makefile` targets, such as the `make download-geofabrik area=albania`:
```
docker-compose run --rm import-osm  ./download-geofabrik.sh albania
```
This is likely because `./download-geofabrik.sh` starts with a `.`.

#### Proposed solution
Since
```
$ docker-compose run --rm import-osm pwd
/usr/src/app
```
All references to `docker-compose run --rm import-osm /usr/src/app/...` in `Makefile` can be safely changed to `docker-compose run --rm import-osm ./...`, just as it is already done for downloading the OSM data.

**Comment by typebrook** [comment]
https://github.com/openmaptiles/import-osm/blob/68a6c8373363bc68c989fe1507121e6ca03cf5a2/Dockerfile#L53

`WORKDIR` in docker image may not change in most of the case, but would it make more sense to use bash command? like
`docker-compose run --rm import-osm bash -c 'usr/src/app/download-geofabrik.sh ...'`

**Comment by zstadler** [comment]
Such a change is indeed very unlikely. In fact, `osm-import`'s own scripts rely on running in `/usr/src/app`.

https://github.com/openmaptiles/import-osm/blob/68a6c8373363bc68c989fe1507121e6ca03cf5a2/psql.sh#L11
