### ISSUE TITLE
docker-compose is not installed as part of the openmaptiles-tools

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#583]
Per [documentation](https://github.com/openmaptiles/openmaptiles/blob/master/README.md#build), it should be possible to run make commands using docker:
```
docker run -v $(pwd):/tileset openmaptiles/openmaptiles-tools make
```

but [tools Dockerfile](https://github.com/openmaptiles/openmaptiles-tools/blob/master/Dockerfile) does not include `docker-compose`, making it impossible to run most of the targets.

Ideally it should be possible to run the above command with an extra parameter:  `-v /var/run/docker.sock:/var/run/docker.sock`, similar to how it is possible to execute it from the `docker/compose` image.

See pull request https://github.com/openmaptiles/openmaptiles-tools/pull/31 (once merged, the docs in this repo should be updated)

**Comment by typebrook** [comment]
> Per [documentation](https://github.com/openmaptiles/openmaptiles/blob/master/README.md#build), it should be possible to run make commands using docker:

My unmerged PR just remove this command(78e836f in #562 ), a Make file is used in a container with few targets maybe  a little confusing and unnecessary.

But the PR is just not yet reviewed over a month... @MartinMikita are you here?

**Comment by MartinMikita** [comment]
We have started Makefile with two simple targets - `make all` and `make clean`, which were meant to be run either locally (with installed `openmaptiles-tools` python package), or via docker (introduced later).

Other make targets have been iteratively added to simplify common steps of OpenMapTiles project, and they were never been meant to be used directly in docker.

We do not want to introduce docker-in-docker. Thanks to @typebrook, the Makefile is now again simplified and without the requirement to install `openmaptiles-tools` python package.

We will not merge your PR in openmaptiles-tools. Thanks for your comments and understanding.
