### ISSUE TITLE
Unmaintained Urban Areas source from Natural Earth

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#584]
When opening [Maputnik](https://maputnik.github.io/editor/#8.9/31.1016/35.5443) in zoom levels 6-8 and hiding the `background` layer, there seem to be two urban areas which do not exist in reality:

![image](https://user-images.githubusercontent.com/1304610/52853865-8b2c5480-3125-11e9-9edc-71cbf17208bf.png)

Indeed they disappear in zoom 9:

![image](https://user-images.githubusercontent.com/1304610/52855760-0cd2b100-312b-11e9-9485-f06e8e4f99cb.png)

These zoom levels are produced from [Natural Earth's Urban Areas in 10m scale](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-urban-area/). The info shows that the layer has not been updated for 15 years and an update that existed 10 years ago is not used yet.

> Derived from 2002-2003 MODIS satellite data at 1 km resolution
> ...
> New version of the MODIS-derived urban area grid is now available
> ...
>> Schneider, A., M. A. Friedl and D. Potere (2009) 

It seems like this source is no longer maintained.

I suggest avoiding the use of the Urban Areas source from Natural Earth and generating all relevant zoom levels by imposm3. A similar approach was taken for the transportation layer in [#116](https://github.com/openmaptiles/openmaptiles/issues/116#issuecomment-288386132).

**Comment by eva-j** [comment]
Please, check https://github.com/openmaptiles/openmaptiles/pull/717 if you have time.

**Comment by zstadler** [comment]
Thank you for fixing this issue.
