### ISSUE TITLE
openmaptiles.org -> openmaptiles.com -> no refund low-res images

### ISSUE THREAD

**Issue by rhalff** [openmaptiles/openmaptiles#587]
As the openmaptiles company is mixing .org and .com freely and is conveniently utilizing opensource to lure people into buying overpriced tiles, I feel free to use this issue system in an equally hybrid and mixed up manner.

I would like to inform potential buyers of the tiles that the purchased resolution is not as shown while exploring the map on [openmaptiles.com/satellite](https://openmaptiles.com/satellite/).

After you've looked at the beautiful maps over there you *must* click the preview for the tiles you are going to purchase. As it is not at all what is shown during exploration of the map.

Fortunately, I bought tiles for the Netherlands only, which is just a loss of $47 dollar.

In particular I want to warn future buyers of larger regions as the cost can be up to $1200 dollars, for low-res imagery.

Imagery which is unsuitable to be used in the majority of app use cases.

Note: Once you've made the purchase there will be no option for a refund.

**Expectation based on demo**:
![expected](https://user-images.githubusercontent.com/274358/53340075-57f97a80-3908-11e9-9e00-3146df4d82cd.png)

**Resolution after purchase**:
![received](https://user-images.githubusercontent.com/274358/53340117-72cbef00-3908-11e9-8696-389a6b20f3d7.png)

Hope this prevents anyone from making bad purchase decisions in the feature.

**Comment by klokan** [comment]
Rob @rhalff 

I'm really sorry for the inconvenience.  Your purchase has been refunded today.

We never wanted to mislead anybody. Your feedback is valuable and will lead to additional correction of the website in near future.

Before you purchase Satellite medium-res data, there is (and always was) a preview showing exactly the data you are ordering. For Netherlands it means:
https://openmaptiles.com/downloads/dataset/satellite/europe/netherlands/

There is also a many times mentioned "resolution of approximately 20m per pixel" in relation to Satellite layer.

The very high-resolution Aerial datasets will appear in our store soon (if you are interested in very highres data please contact us). This includes entire USA and most of Europe.

I would like to apologize for the misunderstanding which happened and we will try to adjust the website in the way that nobody else gets confused.

Petr Pridal, CEO
