### ISSUE TITLE
Unable to update database using docker-compose run update-osm

### ISSUE THREAD

**Issue by ingarpedersen** [openmaptiles/openmaptiles#589]
Hi,

I have installed an extract using quickstart.sh, and I have modified the tile generation to include zoom level 13. I can run both postserve, and tileserver-gl with no problems.

Now I wanted to update the database, and I try running update according to update.md:
docker-compose run update-osm

but that fails with the following error message:

[Mar  1 11:26:39] [diff] unable to read last.state.txt
stat /import/last.state.txt: no such file or directory

In the local datafolder (which is mapped to /import in the container), there is no last.state.txt, so that is correct, but why is there no last.state.txt? There was no errors when the data was imported.

What am I missing to be able to do diff updates? 

Thank you,
Ingar Pedersen

**Comment by ingarpedersen** [comment]
Hi,

I think I figured this out by myself:
There is a difference on how the database is imported. By default it seems the database is not enabled for diff updates. If you want diff updates to work you have to set the DIFF_MODE=true in the .env file BEFORE importing the database. 

I think the docs should emphasize this since a complete planet import with tile generation takes a lot of time and resources, and if you miss it you have to import again...

Thanks,

Ingar Pedersen

**Comment by gonick** [comment]
@ingarpedersen were you able to make it work?

nothing happens for me after this command. diff mode is true.
docker-compose run update-osm

no output from the command

**Comment by ingarpedersen** [comment]
> @ingarpedersen were you able to make it work?

Yes, as you can see above I resolved it by adding DIFF_MODE=true in the .env before creating the database. Adding DIFF_MODE after the database is created does nothing.

Exactly what the problem is in your case since you are getting no output at all, I can't say.
One way of debugging it is to log into the docker container and run the command manually to see if there is an error message or something that isn't displayed when running the docker-compose command... You will need to look at the codcker-compose file to see what else you need to run to get this to work. I made my own docker-compose file that started everything else, and then allowed my to run the update container manually.
