### ISSUE TITLE
explore db using pgadmin

### ISSUE THREAD

**Issue by anilkunchalaece** [openmaptiles/openmaptiles#590]
Hi,

Is it possible to view the database using pgadmin.

**Comment by eva-j** [comment]
Yes, you should be able to see the database using pgadmin or QGIS.
If you are running openmaptiles in docker, you can try it this way:
Command `docker ps` will give you somethin like this
```
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                     NAMES
60ae0783ebf6        openmaptiles/postgis:2.9   "docker-entrypoint.s…"   18 hours ago        Up 3 hours          0.0.0.0:32768->5432/tcp   openmaptiles_postgres_1
```
When making connection in QGIS or pgadmin, use `localhost` as a host and PORT number printed above.
![Screenshot from 2019-04-04 14-40-11](https://user-images.githubusercontent.com/8367628/55556709-82e5a400-56e8-11e9-8d61-9117a3a207b0.png)
