### ISSUE TITLE
openstreetmapdata.com -> osmdata.openstreetmap.de

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/openmaptiles#591]
http://openstreetmapdata.com is moving to https://osmdata.openstreetmap.de/ ([repo](https://github.com/fossgis/osmdata)).

There are some (minor) changes, so this needs some testing before updating [import-water](https://github.com/openmaptiles/import-water).

Source and more information:
Talk by @joto at FOSSGIS 2019:
https://media.ccc.de/v/fossgis2019-979-kstenlinien-icesheets-und-generalisierte-daten#t=94

**Comment by pathmapper** [comment]
More information:
https://blog.jochentopf.com/2019-03-07-the-new-osmdata-service.html

> If you are using the old service at openstreetmapdata.com, you should take action soon. If you are using the coastline or icesheet extracts, then download them from the new service and test them. While they should be mostly the same, we updated a lot of software and did some changes here and there, so we might have broken something. If it works for you, switch the download to the new server, if it doesn’t, tell us.

**Comment by eva-j** [comment]
After PR is merged, we need to upgrade version of import-water in docker-compose and change osmdata URL in documentation of openmaptiles.
