### ISSUE TITLE
Add parking as a poi

### ISSUE THREAD

**Issue by daliborjanak** [openmaptiles/openmaptiles#592]
We would like to add parking as a point into POIs. Try the size of the dataset. To be done with motorcycle parking from #567 and #565 

The value can be parking, parking_motocycle, ...

**Comment by eva-j** [comment]
https://github.com/openmaptiles/openmaptiles/pull/567 edited and tested, ready for merge.

**Comment by francois2metz** [comment]
This issue can now be closed.
