### ISSUE TITLE
admin_level 6 present only on zoom level 5

### ISSUE THREAD

**Issue by frodrigo** [openmaptiles/openmaptiles#594]
On may countries the data for admin_level=6 are present, but only on zoom level 5, look at Spain, France, Greece... 

Zoom 5, then Zoom 6
![image](https://user-images.githubusercontent.com/1785486/54834781-284c5100-4cc1-11e9-88f4-6dd63f73a98d.png)

**Comment by pathmapper** [comment]
This has been reported in https://github.com/openmaptiles/klokantech-basic-gl-style/issues/21, see also https://github.com/openmaptiles/openmaptiles/issues/586.

**Comment by eva-j** [comment]
Solved in https://github.com/openmaptiles/openmaptiles/pull/613.
