### ISSUE TITLE
Proposal: Consolidate openmaptiles repos

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#595]
I would like to propose that many of the "tiny" repos be merged into the main one (this one) for the following reasons:
* It will make tracking issues and pull requests far easier, as there is going to be just one place to report bugs and submit PRs. For example, [this minor fix](https://github.com/openmaptiles/import-osm/pull/11) has been in the `import-osm` repo for almost a year without anyone even noticing.
* It will make cross-project changes easier to manage - there won't be a situation of the PR cannot be merged because dependent PR in `openmaptiles-tools` hasn't merged yet.
* It will be possible to try older versions without issues -- simply check out older version, and all the tools will be consistent.
* Project structure can remain intact -- we can still build multiple docker images from different dockerfiles -- docker hub allows that.
* Consistent security - multiple repos have different people added to them, probably as an oversight and not by design.

P.S. This is consistent with an overall "industry trend" to move to "monorepos", while keeping logical sub-projects published independently, e.g. to NPM

### Implementation

I propose as the first step to refactor [openmaptiles-tools repo](https://github.com/openmaptiles/openmaptiles-tools).  Add all these repositories as sub-directories, and configure Docker hub build to use each subdir for a separate docker image. The original content of the `openmaptiles-tools` repo will be moved to the `/tools` sub-dir.  Git history for all repos will be preserved (will use merge-commits). Additionally, the [extracts](https://github.com/openmaptiles/extracts) repo does not really need its own subdir, but instead can be merged into the `/tools`.

Root
│ LICENSE.md (MIT)
│ README.md (general intro and links to each subpackage)
│
├─ /tools  (original content of the [openmaptiles-tools](https://github.com/openmaptiles/openmaptiles-tools))
├─ [/generate-vectortiles](https://github.com/openmaptiles/generate-vectortiles)
├─ [/import-lakelines](https://github.com/openmaptiles/import-lakelines)
├─ [/import-natural-earth](https://github.com/openmaptiles/import-natural-earth)
├─ [/import-osm](https://github.com/openmaptiles/import-osm)
├─ [/import-osmborder](https://github.com/openmaptiles/import-osmborder)
├─ [/import-sql](https://github.com/openmaptiles/import-sql)
├─ [/import-water](https://github.com/openmaptiles/import-water)
├─ [/import-wikidata](https://github.com/openmaptiles/import-wikidata)
├─ [/imposm3](https://github.com/openmaptiles/imposm3)
├─ [/postgis](https://github.com/openmaptiles/postgis)
├─ [/postserve](https://github.com/openmaptiles/postserve)

If we decide to merge with main [openmaptiles](https://github.com/openmaptiles/openmaptiles) repo, this structure would help us do that.

**Comment by typebrook** [comment]
Good to know somebody noticed this issue and have a proposal.
This really makes contribution easier and visible by admin here. 

I didn't know docker hub allow multiple Dockerfiles build, but anyway looks like `openmaptiles` doesn't have auto-build for images when a newer tag is added. So a one-line-fix contribution also takes a long time to be valid in this repo.
See my latest merge PR in [import-sql](https://github.com/openmaptiles/-sql/pull/8), even a newer [release](https://github.com/openmaptiles/import-sql/releases/tag/v0.9) is there, I still cannot solve [wikidata-related issue](https://github.com/openmaptiles/openmaptiles/issues/548) before a new image is [uploaded to dockerhub](https://hub.docker.com/r/openmaptiles/import-sql/tags).

**Comment by nyurik** [comment]
There appears to be 2 main licenses in use across the repositories: BSD-3 in this one, and MIT everywhere else (last discussed in #11).  It seems the first natural step would be to merge all repos into `openmaptiles-tools` first (consistently MIT), followed by another merge into the primary `openmaptiles` repo.  Either that, or we could add `tools` top level dir with a different LICENSE (MIT) file.

**Comment by nyurik** [comment]
I just updated the proposal with the actual first steps - which repos I think should be merged and in what format.  Will be happy to hear feedback :)

**Comment by RobJacobson** [comment]
I'm new to OpenMapTiles and I'm quite impressed.  However, I was tripped up by the two different repos for this project:  "maptiler/openmaptiles" and "openmaptiles/openmaptiles."

The maptiler/openmaptiles repo is a fork of the openmaptiles/openmaptiles repo, but it doesn't seem to be actively maintained.  I was confused because I followed the installation instructions from the forked maptiler repo (which are out-of-date and incorrect) rather than those from the openmaptiles repo.

I'm not quite sure of the purpose of the forked repo.  Would it be possible either for the forked repo to be archived?  Or could someone add some prominent text to the readme.md for this repo to indicate that people should use this repo ("openmaptiles/openmaptiles") and not the forked repo?

**Comment by golubev** [comment]
Hello! I am new to the openmaptiles. It is a really cool project as a free open source vector tiles alternative.

I can say that my experience of getting familiar with the project tells me that the consolidation would be a great idea. It would be easier to navigate across the project. I had to do searches on GitHub against the organization to trace some aspects of data flow, e.g. https://github.com/search?q=org%3Aopenmaptiles+wd_names&type=Code.

All components are quite coupled. IMHO, e.g. it makes sense to place `openmaptiles/import-osm` inside the `openmaptiles/openmaptiles`.

**Comment by lukasmartinelli** [comment]
I agree fully on moving it to one repo. 

Historic context: It was broken up for the reason to have one Docker inage per repo and trigger accordingly in DockerHub. That's all now possible with a monorepo.

**Comment by RobJacobson** [comment]
I would love to help with consolidating the project.  I think this is a fantastic project overall.  However, as a newbie to GIS and mapping, I also found it a bit intimidating at first.  The "Russian nesting dolls" format of the Docker projects doesn't help.

Would anyone object if I took a stab at implementing Nyurik's proposal?  I could fork the project elsewhere and then muck about.  I could report back in a month about progress.

**Comment by nyurik** [comment]
@RobJacobson I would advise first merging various tools, because they are all using MIT license - as part of the https://github.com/openmaptiles/openmaptiles-tools.

**Comment by nyurik** [comment]
Update:
* postserve - merged with tools, many improvements (parallel queries, cancellations, many config opts)
* import-sql - merged with tools, added parallel execution, the old repo is still open (todo @klokan)

**Comment by nyurik** [comment]
I created 5 PRs to migrate the `import-*` repos into tools as `imports/*` dirs:
* `import-water` https://github.com/openmaptiles/openmaptiles-tools/pull/86
* `import-lakelines` https://github.com/openmaptiles/openmaptiles-tools/pull/87
* `import-natural-earth` https://github.com/openmaptiles/openmaptiles-tools/pull/88
* `import-osmborder` https://github.com/openmaptiles/openmaptiles-tools/pull/89
* `import-wikidata` https://github.com/openmaptiles/openmaptiles-tools/pull/90

Once merged, docker hub needs to be set up to consume those, and the original repositories need to get a README update to point to the new location and archived.

**Comment by nyurik** [comment]
The following individual git repositories have been migrated to the [openmaptiles-tools/imports](https://github.com/openmaptiles/openmaptiles-tools/tree/master/imports). The docker images are now automatically building from the new location.  The old repos should not get any new pull requests, and should be archived soon.

| Legacy Repository | New location | Docker Images 
|---|---|---
| [import-lakelines](https://github.com/openmaptiles/import-lakelines) | [lakelines](https://github.com/openmaptiles/openmaptiles-tools/tree/master/imports/lakelines) | [import-lakelines](https://hub.docker.com/repository/docker/openmaptiles/import-lakelines)
| [import-natural-earth](https://github.com/openmaptiles/import-natural-earth) | [natural-earth](https://github.com/openmaptiles/openmaptiles-tools/tree/master/imports/natural-earth)| [import-natural](https://hub.docker.com/repository/docker/openmaptiles/import-natural-earth)
| [import-osm](https://github.com/openmaptiles/import-osm) | [osm](https://github.com/openmaptiles/openmaptiles-tools/tree/master/imports/osm) | [import-osm](https://hub.docker.com/repository/docker/openmaptiles/import-osm)
| [import-osmborder](https://github.com/openmaptiles/import-osmborder) | [osmborder](https://github.com/openmaptiles/openmaptiles-tools/tree/master/imports/osmborder) | [import-osmborder](https://hub.docker.com/repository/docker/openmaptiles/import-osmborder), [generate-osmborder](https://hub.docker.com/repository/docker/openmaptiles/generate-osmborder)
| [import-sql](https://github.com/openmaptiles/import-sql) | [sql](https://github.com/openmaptiles/openmaptiles-tools/tree/master/imports/sql) | [import-sql](https://hub.docker.com/repository/docker/openmaptiles/import-sql)
| [import-water](https://github.com/openmaptiles/import-water) | [water](https://github.com/openmaptiles/openmaptiles-tools/tree/master/imports/water) | [import-water](https://hub.docker.com/repository/docker/openmaptiles/import-water)
| [import-wikidata](https://github.com/openmaptiles/import-wikidata) | [wikidata](https://github.com/openmaptiles/openmaptiles-tools/tree/master/imports/wikidata) | [import-wikidata](https://hub.docker.com/repository/docker/openmaptiles/import-wikidata)
| [generate-vectortiles](https://github.com/openmaptiles/generate-vectortiles) | [vectortiles](https://github.com/openmaptiles/openmaptiles-tools/tree/master/imports/vectortiles) | [generate-vectortiles](https://hub.docker.com/repository/docker/openmaptiles/generate-vectortiles)

@eva-j when you have a secound, please archive the above repos, and close this ticket.  If anything happens, we can always un-archive them. Thanks!

**Comment by klokan** [comment]
I suggest to do that after 3.11 is finished - if the latest OMT release is
going to be generated with the migrated docker images successfully, then it
is the right moment to archive and break the bridges.

**Comment by nyurik** [comment]
Update:  there are now just a few docker images left: `generate-vectortiles, import-lakelines, import-natural-earth, import-osm, import-water, postgis`

My plan is to get rid of:
* `generate-vectortiles` -- this is a simple script, should be part of the primary osm-tools repo / docker image
* `import-osm` -- same thing

The `import-natural-earth` and `import-water` will be kept as independent docker images. They store significant amount of data in them, thus making re-import very predictable and convenient (re-running same import produces the same results, does not depend on same data being available on a site).

`postgis` will be kept as is for production reasons - it is far easier to manage a standalone database image.

`import-lakelines` -- this one is undecided. It relies on a lakeline file published by @lukasmartinelli , and that file hasn't updated in years.

**Comment by NasH5169** [comment]
Hello all,

By the way, it would be great if the generate-vectortiles image can be updated.

I had to update this image because of: https://github.com/openmaptiles/openmaptiles/issues/317

The dockerfile I suggest into this issue #317 is not the last version I used but I can provide you an updated version soon.

**Comment by nyurik** [comment]
Done. The final docker images:
* `openmaptitels-tools` (primary tool image that includes most of the needed code)
* `import-data` (includes all data-related files like natural earth, lakelines, and water polygons)
* `postgis` (PostgreSQL + Postgis + a few more needed extensions)
* `postgis-preloaded` (same as above, but also has a pre-populated database with everything from `import-data` image)
* `generate-vectortiles` -- this image has not had any changes done to it. I believe it eventually be deleted, and replaced with `tilelive-copy` directly from postgis, without native Mapnik. See https://github.com/openmaptiles/openmaptiles/pull/785#issuecomment-603700820
