### ISSUE TITLE
Add/Update contributing spec

### ISSUE THREAD

**Issue by typebrook** [openmaptiles/openmaptiles#607]
@eva-j 
Thanks for your amazing quick review on PRs recently! 
But you missed updating `landuse.yaml` and `mapping_diagram.png`(Can generate it by `make mapping-graph-landuse`) in #606 

This really reminds me to do some changes to `CONTRIBUTING.md`, followed by #597 from @nyurik

We should includes some necessary contributing specs into `CONTRIBUTING.md`, also the default message in PR form (which is only available for admin here)

I can work on this, but for now I can only think about things above like this:
> when you modify rules about importing in `mapping.yaml` or `*.sql`, please also update:
>1. Field description in `[layer].yaml`
>2. Comment starts with `#etldoc`
>3. If needed, generate new `mapping_diagram.png` or `etl_diagram.png` by commands below:
>```
>make mapping-graph-[layer]
>make etl-graph-[layer]
>```

There should be many things need to list, everybody please feel free to comment on this issue

**Comment by pathmapper** [comment]
> There should be many things need to list, everybody please feel free to comment on this issue

- Update layer description on https://openmaptiles.org/schema/ (https://github.com/openmaptiles/www.openmaptiles.org/tree/master/layers)
- Check if OMT styles are affected by the PR and if there is a need for style updates

**Comment by eva-j** [comment]
Suggestions included in https://github.com/openmaptiles/openmaptiles/pull/627
