### ISSUE TITLE
how to filter underground buildings

### ISSUE THREAD

**Issue by musicformellons** [openmaptiles/openmaptiles#609]
How can I filter underground buildings? For example [this metro/ subwaystation](http://editor.openmaptiles.org/#17.28/51.930907/4.457897) is underground. [This issue](https://github.com/openmaptiles/openmaptiles/issues/419) seems to address this same issue, but the point is how to filter underground buildings, whereas the answer is addressing only whether it is classified as a building y/n.
![Screenshot from 2019-04-15 12-17-41](https://user-images.githubusercontent.com/10334123/56125184-a1fdf480-5f78-11e9-8776-81b3be6436c3.png)

**Comment by Lorzer** [comment]
Filtering would be possible, if the field "level" is added to the layer "building" in the Schema: https://wiki.openstreetmap.org/wiki/Key:level

**Comment by TomPohys** [comment]
Done in https://github.com/openmaptiles/openmaptiles/pull/1241
