### ISSUE TITLE
wrong admin_level 4 for France

### ISSUE THREAD

**Issue by nbozon** [openmaptiles/openmaptiles#610]
The former admin_level 4 boundaries (old french regions) are still in use in OpenMapTiles, and that affects every style. The new regions (since 2017) available in OpenStreetMap should be used instead !

| <img width="299" alt="old-admin4-fr" src="https://user-images.githubusercontent.com/7135374/56273832-db13a180-60fd-11e9-9c22-b4a3198be1d1.png">  Old admin 4 | <img width="299" alt="new-admin4-fr" src="https://user-images.githubusercontent.com/7135374/56273916-09917c80-60fe-11e9-9015-4e565a98d2ef.png"> New admin 4 |
|---|---|

New geometries visible here: 
http://umap.openstreetmap.fr/en/map/contours-geographiques-des-nouvelles-regions-metro_43093#6/46.593/2.771
Details available here: 
https://en.wikipedia.org/wiki/Regions_of_France

**Comment by eva-j** [comment]
Suggestions for update of zoom 4:

1. update attributes of lines in France in NE source ne_10m_admin_1_states_provinces_lines.shp:
https://github.com/nvkelso/natural-earth-vector/tree/master/10m_cultural
according to https://en.wikipedia.org/wiki/Regions_of_France#Reform_and_mergers_of_regions

2. use NE data with `min_zoom <= 5` only (not `7`) here:
https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.sql#L46
this way regions in France (and other countries) are not displayed - only these countries are devided: USA, Canada, Brasil, Russia, China, India, Australia, Indonesia, South Africa

I vote for the second version, updates of NE are not really organized, as described in https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/, so there can be problems in other countries as well.
____

Another problematic zoom level is 5. I suggest to use the same content like in zoom 6 (not using NE input). This way there won't be too much data in z5 and there will not be too big difference between reduced z4 and z5. This solves problems in tickets https://github.com/openmaptiles/openmaptiles/issues/594 and https://github.com/openmaptiles/klokantech-basic-gl-style/issues/21.

**Comment by frodrigo** [comment]
I think it could be closed. It is now solved.
