### ISSUE TITLE
Quickstart does not generate docker-compose-config.yml when using custom OSM data

### ISSUE THREAD

**Issue by RobJacobson** [openmaptiles/openmaptiles#614]
I'd like to propose reopening this issue from before, since the problem is still ongoing:
https://github.com/openmaptiles/openmaptiles/issues/296

I'm a new user of openmaptiles. I encountered the same bug described in issue 296. The ReadMe files give instructions for running .quickstart.sh on your own downloaded data, but the program will consistently crash if you follow those instructions. (I spent hours trying to understand this problem.)

This strikes me as a major bug. The only way to run openstreetmaps correctly is by downloading the data from Geofabrik each time you run quickstart.sh, which is inefficient. This also makes it impossible, e.g., to use a custom .osm.pbf extract.

To reproduce:

1. Make a fresh installation of the openmaptiles directory from git.

2. Run "./quickstart.sh belgium."  This works as expected: quickstart will download the .osm.pbf file for Belgium and generate docker-compose-config.yml with the correct metadata.  It then correctly generates the .mbtiles.

docker-compose-config.yml now has the following content:
```
version: "2"`
services:`
  generate-vectortiles:`
    environment:`
      BBOX: " -5.6520170, 49.4352868, 8.5897635, 62.5146553"
      OSM_MAX_TIMESTAMP : "2019-05-04T20:11:09Z"
      OSM_AREA_NAME: "belgium"
      MIN_ZOOM: "0"
      MAX_ZOOM: "7"
```

3. Delete the .osm.pbf file for Belgium, download the data for the Netherlands manually, and run again:
```
rm ./data/belgium.osm.pbf
wget http://download.geofabrik.de/europe/netherlands-latest.osm.pbf
mv netherlands-latest.osm.pbf data/.
./quickstart.sh netherlands-latest
````

This time, the program does not read the metadata for the downloaded extract and does not update the metadata stored in docker-compose-config.yml. The program instead reuses the previous config file for Belgium. This results in the program crashing with the following message:

```
====> : Start generating MBTiles (containing gzipped MVT PBF) from a TM2Source project. 
      : TM2Source project definitions : ./build/openmaptiles.tm2source/data.yml 
      : Output MBTiles: ./data/tiles.mbtiles  
      : Source code: https://github.com/openmaptiles/generate-vectortiles 
      : We are using a lot of Mapbox Open Source tools! : https://github.com/mapbox 
      : Thank you https://www.mapbox.com !
      : See other MVT tools : https://github.com/mapbox/awesome-vector-tiles 
      :  
      : You will see a lot of deprecated warning in the log! This is normal!  
      :    like :  Mapnik LOG>  ... is deprecated and will be removed in Mapnik 4.x ... 
.FileNotFoundError: [Errno 2] No such file or directory: '././data/docker-compose-config.yml'
```

The problem seems to occur around lines 139-158 of quickstart.sh.  In pseudocode, the following seems to be happening:

```
Does /data/ contain the correct .osm.pbf file?
    No:
        Run make download-geofabrik area = ${osm_area}:
            Run import-osm ./download-geofabrik.sh $(area):
                Download "region-name.osm.pbf" using download-geofabrik
                Read the metadata from "region-name.osm.pfb" using osmconvert
                Generate "docker-compose-config.yml"
    Yes:
        Echo "testdata exists ... we don't need to download"
```

Consequently, quickstart only generates docker-compose-config.yml in the "no" case, not in the "yes" case.  This could be fixed with the following pseudocode:

```
Does /data/ contain the correct .osm.pbf file?
    No:
        Run make download-geofabrik area = ${osm_area}:
            Run import-osm ./download-geofabrik.sh $(area):
                Download "region-name.osm.pbf" using download-geofabrik
    Yes:
        Echo "testdata exists ... we don't need to download"

Read the metadata from "region-name.osm.pfb" using osmconvert
Generate "docker-compose-config.yml"
```

Would it be possible to fix this? This would require some refactoring to remove the "generate config file" logic from import-osm and insert that logic instead into the main Makefile.

(For the sake of asking, does this project actually need a separate import-osm module that relies on a third-party download library written in Go? That seems to add unnecessary complexity and code bloat. Couldn't we just just download the relevant .osm.pbf file directly using a wget command in the main Makefile?)

**Comment by typebrook** [comment]
>does this project actually need a separate import-osm module that relies on a third-party download library written in Go

Well, docker-compose services like `import-osm` or `generate-vectortiles` don't depends on `docker-compose-config.yml`. I also use custom OSM data without it and everything goes will (BTW, I simply follow the steps in READE but run `quickstart.sh`.

The error message you mentioned
`.FileNotFoundError: [Errno 2] No such file or directory: '././data/docker-compose-config.yml'`
is weird. `././` maybe the problem here, but `quickstart.sh` should not rename `./data/docker-compose-config.yml`, maybe you can trace it more.

Any way, what `docker-compose-config.yml` do is just to override env variables in docker-compose.yml and `.env`, and it could be negelect. you can just change
https://github.com/openmaptiles/openmaptiles/blob/65d90366160162872f90de755f14454181b810ad/quickstart.sh#L272
into
 docker-compose run --rm generate-vectortiles

**Comment by typebrook** [comment]
Ｗell, maybe it makes no sense to use relative path in docker-compose command
Could you change
https://github.com/openmaptiles/openmaptiles/blob/65d90366160162872f90de755f14454181b810ad/quickstart.sh#L272
into 
```
 docker-compose -f docker-compose.yml -f data/docker-compose-config.yml run --rm generate-vectortiles
```
and repeat your steps to see whether it works?

ref:
https://docs.docker.com/compose/extends/

**Comment by AnSmol** [comment]
Hi! I alose faced this issue.
I think the problem is [here](https://github.com/openmaptiles/openmaptiles/blob/c45e75542b0184530e8b5e6a26f8a25e2ac9690f/quickstart.sh#L139). 
quickstart.sh runs `make download-geofabrik`  only if there is no .pbf file in data folder. Without running `make download-geofabrik`,  file ./data/docker-compose-config.yml is not generated.
In consequens, it leads to crash in [this line](https://github.com/openmaptiles/openmaptiles/blob/c45e75542b0184530e8b5e6a26f8a25e2ac9690f/quickstart.sh#L272) of code, which uses  ./data/docker-compose-config.yml file unconditionaly

**Comment by eawagner** [comment]
Had the same problem, and @AnSmol is correct, it only generates the docker-compose-config.yml if the osm data isn't present and gets downloaded.  The reason for this is that the code for generating the docker-compose-configy.yml is located [here in the import-osm](https://github.com/openmaptiles/import-osm/blob/master/download-geofabrik.sh#L40) image.  So unless something is downloaded this code will never be called.

For the time being a simple workaround is to just copy the example docker-compose-configy.yml above and run the following to get the bounding box information and max timestamp.

```
docker-compose run --rm import-osm osmconvert  --out-statistics /import/${area}.osm.pbf
```
