### ISSUE TITLE
Readme talks about how to build custom ski later but does not exist

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#616]
In the Readme file is mentions that you can create your own custom layer and gives a link to `https://github.com/openmaptiles/openmaptiles-skiing`, but this URL does not exist.

**Comment by MartinMikita** [comment]
Hi @nnhubbard,

Thanks for the notice, we have prepared the repository earlier, but it was not published yet.

Now it is [public and available](https://github.com/openmaptiles/openmaptiles-skiing).
