### ISSUE TITLE
Boundary should expose name value

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#618]
Looking at the boundary layer it doesn't seem like there is an easy way to expose the name field. Is this possible just in `openmaptiles` or would there need to be a change in the source data for boundaries?

**Comment by nnhubbard** [comment]
I was hoping for just admin_level 6 which is US counties.

**Comment by eva-j** [comment]
Layer `boundary` contains lines and it would be quite complicated to add labels correctly for all the admin_levels. Easier way to label administrative units is using `place` layer.

I can see that there is no tag `place=county` included, but we could probably consider to add it (https://taginfo.openstreetmap.org/tags/place=county).

**Comment by nnhubbard** [comment]
Thanks for the hint about using `place=county`, that worked for what I needed!
