### ISSUE TITLE
waterway=dam needs to be added as a polygon to waterway layer

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#621]
Currently `waterway=dam` is not supported. It would be great to get this added to the `waterway` layer as a polygon.

**Comment by eva-j** [comment]
Thanks for your suggestion. Could you please give an example of locality where it is missing?

**Comment by nnhubbard** [comment]
Here is one in my local area: 

https://www.openstreetmap.org/way/352346672

**Comment by nnhubbard** [comment]
Another one in the same area:

https://www.openstreetmap.org/way/357304116

**Comment by eva-j** [comment]
I am going to test adding polygons of `waterway=dam` into `landuse` layer. This should definitely not be part of `waterway` layer (https://wiki.openstreetmap.org/wiki/Tag:waterway=dam).

**Comment by eva-j** [comment]
https://github.com/openmaptiles/openmaptiles/pull/713 merged.
