### ISSUE TITLE
Float/Double property in custom layer mapping file

### ISSUE THREAD

**Issue by NasH5169** [openmaptiles/openmaptiles#625]
Hi, 

Not an issue but just a very simple help i think.

I'm adding custom layer and and trying to use floating point value in the mapping.yaml file.

I've tried "float", "double", "numeric", "number", "real".

```
- name: myprop
      key: myprop
      type: ????
```

It is not working.

What is the right value in this case?

Thanks.

**Comment by eva-j** [comment]
Hi @NasH5169,
I am afraid there is no option to use float/double in mapping.yaml. According to documentation you can use: bool, boolint, string, direction, integer, enumerate, wayzorder; id, mapping_key, mapping_value, geometry, validated_geometry, area, webmerc_area, hstore_tags.
https://imposm.org/docs/imposm3/latest/mapping.html#id1
https://imposm.org/docs/imposm3/latest/mapping.html#column-types

**Comment by NasH5169** [comment]
Hi @eva-j 

Ok. I will round and use an integer instead. 

Thanks.
