### ISSUE TITLE
Rendering labels cut-off

### ISSUE THREAD

**Issue by mpaine-act** [openmaptiles/openmaptiles#628]
When I render OSM maps, I see various location labels cut-off

https://imgur.com/a/dUKGyWX

Is this a known issue that can be fixed easily?  It happens at all zoom levels, although the further zoomed in, the less the problem is visible (sometimes corrected).

**Comment by chebourne** [comment]
Duplicate of #347 

As far as I know this has never been resolved for raster maps.

I now try and use vector maps as much as possible in my applications so that this problem does not crop up.

**Comment by eva-j** [comment]
Duplicate of https://github.com/openmaptiles/openmaptiles/issues/224.
