### ISSUE TITLE
Why not use OSM boundary in z0~z5?

### ISSUE THREAD

**Issue by HansonYip** [openmaptiles/openmaptiles#629]
I realized that [layer boundary](https://github.com/openmaptiles/openmaptiles/tree/30539e78d193d9a471aaea5581372b3d0702a524/layers/boundary) is from NE below zoom 5, but from OSM above zoom 5. Why not use OSM data only in all zoom level?

**Comment by daliborjanak** [comment]
I didn't do it but I guess that performance is a reason

**Comment by HansonYip** [comment]
Boundary data from **Natural Earth** may be more complete than those from **OSM**. https://github.com/omniscale/imposm3/issues/12#issuecomment-41471515

**Comment by lhorus** [comment]
> Boundary data from **Natural Earth** may be more complete than those from **OSM**. [omniscale/imposm3#12 (comment)](https://github.com/omniscale/imposm3/issues/12#issuecomment-41471515)

From WOI might be even more complete for generalized boundaries at different admin levels.

**Comment by TomPohys** [comment]
From OpenMapTiles-Tools v4.0.0 (https://github.com/openmaptiles/openmaptiles-tools/pull/142) the `import-borders` using borders from given pbf file. It is also possible to import backup borders file from OMT-T v4.1.0 (https://github.com/openmaptiles/openmaptiles-tools/pull/191)
