### ISSUE TITLE
Understanding Boundary Layers

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#630]
I am wanting to get a better understanding of the boundary layer. As mentioned in another issue zoom >= 5 comes from OSM rather than Natural Earth.

I am wondering if I could be pointed in the right direction for how to add additional data to the table, such as if the boundary is `ceremonial` and also the name. 

Would this take modification of the Docker Image and the `import_osmborder_lines.sh` script? Or is there a way to do this directly in the boundary layer sql file?

**Comment by eva-j** [comment]
I think you understand it well.

Till zoom 4 Natural Earth data is used, then we import the lines using [import-osmborder](https://github.com/openmaptiles/openmaptiles-tools/tree/master/docker/import-osmborder). This import-osmborder takes all attributes from [osmborder](https://github.com/pnorman/osmborder#output) project - it means `osm_id`, `admin_level`, `dividing_line`, `disputed`, `maritime` and of course geometry. This way it is not so easy to add new attribute from original OSM data.

We consider other approaches to generate `boundary` layer, feel free to give your suggestions.
