### ISSUE TITLE
generate-qareports shows z15 as a layer

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#633]
I am running the `make generate-qareports` scripts to create qa files for all of my layers. For some reason every file that is created lists `z15` as a layer. Is z15 really being created in the `mbtiles` file, or is this just an error in the qa generation?

**Comment by typebrook** [comment]
>  Is z15 really being created in the mbtiles file

Nope, no "z15" in any git revision, but seems like scripts inside `./qa` just loop to z=15
https://github.com/openmaptiles/openmaptiles/blob/c45e75542b0184530e8b5e6a26f8a25e2ac9690f/qa/layer_numvar_analyze.sh#L11

A simple commit could fix this

**Comment by TomPohys** [comment]
QA scripts were moved from OpenMapTiles to OpenMapTiles-Tools (by https://github.com/openmaptiles/openmaptiles/pull/1031). Zooms are now managed by `-m` and `-n` in Makefile.
