### ISSUE TITLE
boundary layer is not constrained to bounding box for some admin_levels

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#634]
When looking at the `boundary.sql` file, it seems that while it is a good idea to create boundaries for the whole world for some `admin_levels` such as `2` and `4` which represent country borders and state borders, other `admin_levels` such as `6, 8, 10` etc should not expand out of the bbox for the imported `osm.pbf` file. 

Boundaries are some of the largest amounts of data in the database, so those boundaries such as `counties` (6) should only be added for the bbox. In my testing that is a lot of wasted data.

For exampling when I import `California` I get `admin_levels` showing for 6 other states around `California` at many zoom levels:

![IMG_E4358BC63ACA-1](https://user-images.githubusercontent.com/30858/58527379-374ef400-8187-11e9-8d48-4043b994afa1.jpeg)

Can something like `ST_Within` be used to restrict it for certain `admin_levels`?

**Comment by nnhubbard** [comment]
Does anyone have ideas about how to restrict boundaries to the `BBOX`?

**Comment by eva-j** [comment]
If you use import-osmborder docker image, you get boundaries for all the planet.
One option is to run import-osmborder (I mean generate .csv and then import) only on your OSM .pbf extract.

**Comment by TomPohys** [comment]
Hi @nnhubbard, Is this issue resolved by new import-borders script?

From OpenMapTiles-Tools v4.0.0 (https://github.com/openmaptiles/openmaptiles-tools/pull/142) the `import-borders` using borders from given pbf file. It is also possible to import backup borders file from OMT-T v4.1.0 (https://github.com/openmaptiles/openmaptiles-tools/pull/191)
