### ISSUE TITLE
Vector tile generation multithreading

### ISSUE THREAD

**Issue by Avadon** [openmaptiles/openmaptiles#635]
When I run "**generate-vectortiles**" on a whole planet **tilelive-copy** shows terrifying estimated time about 1500 days. Is there a way to speed up the process by utilizing all CPU/cores?

**Comment by MartinMikita** [comment]
https://github.com/openmaptiles/openmaptiles/issues/299#issuecomment-312423259
https://github.com/openmaptiles/openmaptiles/issues/242#issuecomment-300398462
