### ISSUE TITLE
`webmerc_area` field declared, but not used

### ISSUE THREAD

**Issue by golubev** [openmaptiles/openmaptiles#637]
While digging into the `mapping.yaml`s I've found that a field `webmerc_area` was declared. But I haven't found any usages of the field in any of the `openmaptiles` (as an org.) repos:
https://github.com/search?q=org%3Aopenmaptiles+webmerc_area&type=Code

I've seen that `webmerc_area` replaced the deprecated `pseudoarea` in the https://github.com/openmaptiles/openmaptiles/pull/137 as a type of the `area` field. But later in the https://github.com/openmaptiles/openmaptiles/pull/198 the `area` field was changed to use the `area` type. The `webmerc_area` type was moved into a separate field, named also `webmerc_area`, but it seems not to be used.

It looks like a good idea to remove that field to:
- reduce the tables' sizes
- not to do redundant calculations in the `imposm3` of an unused field
- remove the code being unused not to complicate the project's support

**Comment by eva-j** [comment]
https://github.com/openmaptiles/openmaptiles/pull/708 merged.

**Comment by golubev** [comment]
Thanks, @eva-j :wave:
