### ISSUE TITLE
3D buildings visual glitches

### ISSUE THREAD

**Issue by golubev** [openmaptiles/openmaptiles#639]
This bug can be seen on a live demo map (it can be accessed directly from the https://openmaptiles.org):
https://www.maptiler.com/maps/#streets//vector/17.21/30.449672/50.509455/13.60/49.0

Here is how it looks like (https://prnt.sc/nxzabk):
![image](https://user-images.githubusercontent.com/951364/58965499-61bd3480-87b9-11e9-95b4-2e97296b55fd.png)

I tried to reproduce this bug with openmaptiles vector tiles I had generated recently. But there were no glitches when I ran the tileserver with `make start-tileserver`. On the location http://localhost:8080/styles/osm-bright/?vector#17.08/50.509429/30.448716/8/44 everything was OK (I ran [this code](https://gist.github.com/golubev/ce04c76cae1d93240f66a003b43e3e5c) in browser's dev tools console to add the 3D layer):
![Screenshot from 2019-06-05 17-47-24](https://user-images.githubusercontent.com/951364/58966032-3d158c80-87ba-11e9-9572-2b4129e46b59.png)

But later I discovered that [`mapbox-gl.js` used in the `tileserver-gl`](https://github.com/klokantech/tileserver-gl/blob/e5060147633a654ee3ec12b19804d1e0a1b85570/public/resources/mapbox-gl.js) has version `0.43.0`.

I tried to reproduce the same steps with `openmaptiles` vector tiles with other `mapbox-gl.js` versions. For `0.53.1` I got:
![Screenshot from 2019-06-05 16-55-09](https://user-images.githubusercontent.com/951364/58966821-a9dd5680-87bb-11e9-9271-290d66dde7e5.png)

For `1.0.0` I got:
![Screenshot from 2019-06-05 16-49-08](https://user-images.githubusercontent.com/951364/58966861-bbbef980-87bb-11e9-8ce1-dc775404e794.png)

While that tallest building in the front was fixed other glitches appeared in the surrounding buildings - on both `mapbox-gl.js` versions :slightly_frowning_face:

Perhaps this bug can be related to issue https://github.com/mapbox/mapbox-gl-js/issues/7797. There was a bug in the PostGIS wich was fixed in version `2.4.5`. I don't know whether you use `St_AsMvT` function to render vector tiles (I was trying to research that but failed) but the version used in the `openmaptiles/postgis` seems to be `2.4.0` - https://github.com/openmaptiles/postgis/blob/b21d42051401e443825ea5a83fdd439de734b6bc/Dockerfile#L3-L4.

Another visually similar bug - https://github.com/mapbox/mapbox-gl-js/issues/8317 (screen there is the same location as in the example above) - but it is about the GeoJSON - not the MVT.

**Comment by golubev** [comment]
There is a rejected PR from @arindam1993 in the mapbox-gl-js - https://github.com/mapbox/mapbox-gl-js/pull/8600. It seems that a workaround for the polygons winding order implemented in that PR fixes this issue.

It looks like there is really an issue with the polygons' winding order.

**Comment by klokan** [comment]
Thanks for detailed informations @golubev 

PR welcome. Initial ideas:
- fixing SQL queries for buildings - if the winding order can be returned from PostGIS correctly - with something like https://postgis.net/docs/ST_ForceRHR.html or similar
- or testing if a newer mapnik-vt wrapped in tilelive-copy in generate-vectortiles - https://github.com/openmaptiles/generate-vectortiles/blob/master/export-local.sh is now fixing winding order of supplied incorrect polygons automatically, if upgraded

**Comment by golubev** [comment]
Hi @klokan! Thanks for your reply! We are currently using our own layer with fixed buildings' polygons as a workaround for this issue, but I was thinking about a PR too.

**Comment by golubev** [comment]
Tried to use `ST_ForcePolygonCW` (`ST_ForceRHR`) in https://github.com/lun/openmaptiles/commit/18540fda78ca21befc92ee7c280f74fcc8bc6b68, but it looks like it did not help:

![image](https://user-images.githubusercontent.com/951364/63788321-f2f60000-c8fd-11e9-975a-7d9b7f1861ea.png)

`mapbox-gl.js` `1.2.1` was used

**Comment by golubev** [comment]
I think that this issue and this comment are related to this issue - https://github.com/mapbox/mapnik-vector-tile/issues/59#issuecomment-215585370

**Comment by golubev** [comment]
Another one similar issue - https://github.com/mapbox/mapbox-gl-js/issues/8341#issuecomment-501218694:
> This kind of artifact usually means the input polygons are not valid polygons according to the vector tile specification (winding order of polygon rings is wrong)

**Comment by golubev** [comment]
I tried to generate a new tileset using OMT v3.11 (HEAD at https://github.com/openmaptiles/openmaptiles/commit/e4a9d90dec6aafcba058fd61085e45e2011980b6). Here is an example that uses the `mapbox-gl@^1.3.1`:

![Screenshot from 2019-12-25 17-13-47](https://user-images.githubusercontent.com/951364/71447663-ff6a5800-2739-11ea-876a-c524636f9718.png)

![captured (13)](https://user-images.githubusercontent.com/951364/71447660-f8434a00-2739-11ea-9225-fd6bc4eead15.gif)

I am thrilled to see that the bug has gone away! :tada::tada::tada:

I think that I should thank @nyurik for updating the `openmaptiles/postgis` docker image. As we can see here - https://github.com/mapbox/mapbox-gl-js/issues/7797#issuecomment-457504682 - refreshing the `2.4dev` tag could be the reason that had led to this bug being fixed.

You may check this out at map position `16.71/50.509309/30.450414` on a newely generated tiles.

Merry Christmas! :slightly_smiling_face: :christmas_tree:

**Comment by golubev** [comment]
The bug has been resolved on the MapTiler too:
https://www.maptiler.com/maps/#streets//vector/17.21/30.449672/50.509455/13.60/49.0

![Screenshot from 2020-01-11 14-40-50](https://user-images.githubusercontent.com/951364/72204443-a5c79480-3480-11ea-9f96-82b0c3edff00.png)
