### ISSUE TITLE
Canada Province and Country names missing

### ISSUE THREAD

**Issue by pramsey** [openmaptiles/openmaptiles#641]
I'm uncertain exactly at what zoom level this is, I think the top level one, as it manifests from a global view down to a regional one, but the Canada country name label and the province levels are missing. Past a certain zoom in, the province labels come in, which says "data missing" to me.
![screenshot_247](https://user-images.githubusercontent.com/113883/60050364-5147fd80-9685-11e9-9bc8-50380958e629.png)

**Comment by nnhubbard** [comment]
Is this on a planet import? Or? Have you viewed your .mbtiles tile using `make start-tileserver` and then the data option?

**Comment by pramsey** [comment]
This is using the online demo version of maputnik and whatever tiles are sitting behind it.

**Comment by nnhubbard** [comment]
> This is using the online demo version of maputnik and whatever tiles are sitting behind it.

I am not sure that would be an accurate representation of what the openmaptiles scripts actually produce. The demo on `maputnik` is just there to help with styling.

**Comment by pramsey** [comment]
OK, as long as everyone else can see Canada :)
