### ISSUE TITLE
using make on clean clone doesn't work

### ISSUE THREAD

**Issue by Shkarface** [openmaptiles/openmaptiles#643]
Steps to reproduce:
```bash
git clone git@github.com:openmaptiles/openmaptiles.git
cd openmaptiles
# Build the imposm mapping, the tm2source project and collect all SQL scripts
make
```
the output of this (without git related output):

docker-compose run --rm openmaptiles-tools generate-imposm3 openmaptiles.yaml > build/mapping.yaml
write /dev/stdout: permission denied
make: *** [Makefile:48: build/mapping.yaml] Error 1

Now I've tried modifying the Makefile and give full permission to the file in question, still same issue.

**Comment by eva-j** [comment]
Does it behave the same way if you use this clone command?
`git clone https://github.com/openmaptiles/openmaptiles.git`
Could you check access to 'build' folder?

**Comment by Shkarface** [comment]
@eva-j well I have no idea why, but that worked...

**Comment by Jnb2387** [comment]
I am getting this issue whenever I run quickstart more than once. It seems if I remove and git clone to a new location it works fine once and gets a permission error if run again.
