### ISSUE TITLE
Problem in downloading pbf file

### ISSUE THREAD

**Issue by masoud2vg** [openmaptiles/openmaptiles#648]
When I run quickstart.sh on Windows subsystem for linux, it downloads the pbf file but it won't move it to data folder and it's the error. What should I do?

ls -la ./data/albania.*
ls: cannot access './data/albania.*': No such file or directory
Makefile:65: recipe for target 'download-geofabrik' failed
make: *** [download-geofabrik] Error 2

-------------------------------------------------------------------------------------
====> : Osm metadata : albania.osm.pbf
cat: ./data/osmstat.txt: No such file or directory

-------------------------------------------------------------------------------------
====> : Generated docker-compose config
cat: ./data/docker-compose-config.yml: No such file or directory

**Comment by klokan** [comment]
Sorry. We don't have windows or linux subsystem here to test.

If you solved the issue let others know - I guess you would have to patch the scripts (which are primarily targetting native Linux and require docker locally.

Feel free to make a clean Pull Request 🥇
