### ISSUE TITLE
metadata attribution

### ISSUE THREAD

**Issue by zeevogels** [openmaptiles/openmaptiles#652]
The latest planet.mbtiles, that is available on https://openmaptiles.com/downloads/tileset/osm , mentions maptiler and openstreetmap contributors as metadata attribution but the license clearly states that openmaptiles.org and openstreetmap contributors should be attributed.

The metadata attribution should be updated to properly follow the license.

**Comment by sfkeller** [comment]
I'm with you that OpenMapTiles MBTiles MUST properly follow the OSM license guidelines. 
But what exactly is your proposal?

**Comment by daliborjanak** [comment]
Pregenerated datasets from openmaptiles.com are now produced by MapTiler team and they must require MapTiler attribution https://openmaptiles.com/terms/

For own generated from this repo requires OpenMapTiles with a link in attribution as is described in license https://github.com/openmaptiles/openmaptiles/blob/master/LICENSE.md.

Both must contain OpenStreetMap contributions.

We are also offering exceptions to OpenMapTiles/MapTiler attribution requirement for individual needs.

**Comment by zeevogels** [comment]
This copyright page https://www.maptiler.com/copyright/ confused me by stating that only tiles hosted by Maptiler should follow this attribution:

> 
> According to the OpenMapTiles license, all products or services using maps derived from OpenMapTiles schema must visibly credit "OpenMapTiles.org" or reference "OpenMapTiles" with a link to http://openmaptiles.org/. For MapTiler.com hosting we have a written legal permission from Klokan Technologies GmbH to replace the visible credit with MapTiler and a link to this page. 
> 

But the terms page on openmaptiles.com is very clear. Thanks for the quick response.
