### ISSUE TITLE
Local OSM border csv file. 

### ISSUE THREAD

**Issue by aerotypebharat** [openmaptiles/openmaptiles#653]
How can I import local border csv file. I don't want to import  whole world border,  is too large for small area.

**Comment by frodrigo** [comment]
Generated using osmboder and override the import

With osmborder_lines.csv in data/

```diff
-- a/docker-compose.yml                                                                                              
+++ b/docker-compose.yml  
     env_file: .env
     networks:
     - postgres_conn
+    volumes:                                                                                                         
+    - ./data:/import   
```

**Comment by TomPohys** [comment]
Hi @aerotypebharat, this issue was resolved by https://github.com/openmaptiles/openmaptiles-tools/pull/191. Now are borders imported from PBF file and stored into CSV.
