### ISSUE TITLE
Wetland subclasses are overwritten by the word wetland 

### ISSUE THREAD

**Issue by bramlinssen** [openmaptiles/openmaptiles#659]
For some wetlands the landuse value is **wetland** and the  wetland value is for example **tidalflats**

This happens since the layer_landcover has the following code:

```
        COALESCE(
            NULLIF("natural", ''), NULLIF(landuse, ''),
            NULLIF(leisure, ''), NULLIF(wetland, '')
        ) AS subclass

```
changing this in 

```
 COALESCE(
            NULLIF(wetland, ''), NULLIF("natural", ''),
            NULLIF(landuse, ''), NULLIF(leisure, '')
        ) AS subclass

```
will avoid this.

**Comment by eva-j** [comment]
After https://github.com/openmaptiles/openmaptiles/pull/646 it takes first value matching from the original OSM table (https://imposm.org/docs/imposm3/latest/mapping.html#mapping-key) and we have no way to decide which attribute has priority. This PR was made to optimize size of tiles and make the code easier to read.

If seeing different subclasses of wetland is really important for you, we can consider to revert this change.
