### ISSUE TITLE
Error: Postgis Plugin: ERROR:  unrecognized node type: 328

### ISSUE THREAD

**Issue by Yermo** [openmaptiles/openmaptiles#665]
I am attempting to convert https://download.geofabrik.de/north-america-latest.osm.pbf to mbtiles using the Openmaptiles docker images and Quickstart script on a CentOS7 host.

I have successfully done this, for example, for Canada, Ireland, and several other smaller regions.

However, when trying to run it on the North America extract, I am getting this error after 38 minutes:

```
[38m 9.757000000000062s]   0.2397% 199.8k/83.37m @   87/s | ✓ 199.8k □ 161.6k | 11d 0h 15m 59s left
/usr/local/lib/node_modules/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

Error: Postgis Plugin: ERROR:  unrecognized node type: 328
CONTEXT:  SQL function "landcover_class" during inlining
in executeQuery Full sql was: 'SELECT ST_AsBinary("geometry") AS geom,"class","subclass" FROM (SELECT geometry, class, subclass FROM layer_landcover(ST_SetSRID('BOX3D(-15390175.24156467 15223771.83098785,-15387652.81963126 15226294.25292125)'::box3d, 900913), z(34123.7))) AS t'

    at Error (native)
```

my docker-compose-config.yml file is:

```
version: "2.0"
services:
  generate-vectortiles:
    environment:
      BBOX: "-179.9999, 6.88283, -5.198412, 85.04177"
      OSM_MAX_TIMESTAMP : "2017-07-11T19:05:28Z"
      OSM_AREA_NAME: "North America"
      MIN_ZOOM: "0"
      MAX_ZOOM: "14"

```

**Comment by TomPohys** [comment]
Hi @Yermo, did you try to clean up PostgreSQL? Maybe there are some data or schema left in PostgreSQL from your previous imports.

**Comment by Yermo** [comment]
@TomPohys To the best of my knowledge, all the tables are dropped and recreated on each run.

**Comment by TomPohys** [comment]
Are you trying to run the SQL query directly in PostgreSQL database (```make psql``` and copy-paste the SQL). There will be maybe some more information about the error. 

Are you also sure, that the bbox is correct?

**Comment by Yermo** [comment]
@TomPohys Thats a good idea. My suspicion was that it was something specific about that particular dump because I have been able to successfully run it on a later dump. (I failed to update the issue for which I apologize.) 

How do I verify that the bounding box for North America is correct?

**Comment by TomPohys** [comment]
No problem, I am glad that with a new dump is everything OK.

Basically, if in ```data/docker-compose-config.yml``` is a correct bounding box. But maybe bounding box was not a problem. You can check values in the bbox through https://boundingbox.klokantech.com/
