### ISSUE TITLE
Bug: displaying ocean at zoom level 8 inverts

### ISSUE THREAD

**Issue by AnaalNathrakh** [openmaptiles/openmaptiles#666]
On zoom level 8 there are some places where for some tiles the ocean inverts (i.e. water becomes land, land becomes water). 
I found this at bug at three different places. Here is one example from italy:  https://imgur.com/a/OZN5akf

As this happens in raster and vector display and also shows in inspect mode in mapnik, i guess it must be because of the import?

**Comment by daliborjanak** [comment]
We didn't notice this bug. Can you send us link to live version or data?

**Comment by AnaalNathrakh** [comment]
I uploaded the data to : https://ufile.io/uw1frgaa
contains content of my cache from zoom level 7 and 8 

Other places that are bugged are around Helsinki, Stockholm and Sevilla. However, there the ocean does not invert, but how tiles are under water. But problem is only on zoom 8.

**Comment by AnaalNathrakh** [comment]
Any news on this?

As a work-around I now osm_ocean_polygon3 instead of 4 for zoom 8 by running 

CREATE OR REPLACE VIEW water_z8 AS (
    SELECT geometry, 'ocean'::text AS class, NULL::boolean AS is_intermittent FROM osm_ocean_polygon_gen3
    UNION ALL
    SELECT geometry, water_class(waterway) AS class, is_intermittent FROM osm_water_polygon_gen3
    WHERE "natural" != 'bay'
);

Works well

**Comment by eva-j** [comment]
Hello, I can't reproduce this bug. Are you using any of Geofabrik data packages for import?

**Comment by AnaalNathrakh** [comment]
No, used the planet file form osm.org

**Comment by eva-j** [comment]
As nobody else is reporting this problem and we are not able to reproduce is, I guess there was something wrong on generating the table `osm_ocean_polygon_gen4`. Please, try to clean your database and run `import-water` again.
