### ISSUE TITLE
How to render the whole planet?

### ISSUE THREAD

**Issue by andredoering** [openmaptiles/openmaptiles#669]
Hey guys,

I wonder how I can render the whole planet. The `quickstart.sh` script only offers areas, countries, continents but I can not see that there is the parameter "planet" or "world". 
It also says in the documentation that it is not recommended to do it for the whole planet. 

So how can I render the whole planet?

I know that it will take a long time. I wonder how I can monitor how long the time remaining will be, when I render it on a server?

Thank you!

**Comment by nnhubbard** [comment]
See [Using your own data](https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md#using-your-own-osm-data) for how to use your own downloaded `.osm.pbf` file.

As for the full planet render, I would not recommend it. It would take months to render and by that time your data will be old.

**Comment by andredoering** [comment]
thanks for the answer.

what would you suggest for having the whole planet, without paying $ 1000 or more for a pre rendered mbtiles?

**Comment by nnhubbard** [comment]
> what would you suggest for having the whole planet, without paying $ 1000 or more for a pre rendered mbtiles?

There is no cheap solution for this. If you want to do it yourself the best way would be to create a cluster of servers (12-16) that would each render a part of the planet. Then use a tool like [tippecanoe](https://github.com/mapbox/tippecanoe) to merge them.

**Comment by georgbachmann** [comment]
One question about that. So how would you split up the world? Into regions like continents? Or into boxes? What about the oceans? Would you need to render those as well form zero to let's say z14? Or does f.e. Mapbox fallback to higher zoom levels there?
And when tippecanoe merges the mbtiles, what about overlap? Is that handled properly?

**Comment by nnhubbard** [comment]
Yes, you would split the world up into regions using a coordinate bbox. I have not personally done this, but this is how Maptiler explains how they do it. See slide 46: [https://www.slideshare.net/Docker/take-control-of-your-maps-with-docker](https://www.slideshare.net/Docker/take-control-of-your-maps-with-docker)

**Comment by qlerebours** [comment]
I'm currently generating the whole plenty but it takes time and money. 
Honestly if maptiler was asking only $1000 I would have pay, but with their "professional" + "multi license" terms, it's not an option.
Using a single AWS ec2 c5.x4large, I will take 100 days to generate zoom 14.
I forked the generate-vectortiles docker container to be able to parallelize.
Zoom 14 generation will cost approximately $2000 
If someone has an idea to make it faster, it would be great

**Comment by klokan** [comment]
Hi! I am Petr Pridal - I am the person who speaks on the DockerCon presentation linked above, and also the one who gave birth to this open-source project...

Anybody who is keen to discuss our pricing - you are welcome to contact sales@maptiler.com.
If there is any meaningful reason we can provide custom deals and discounts...

Let me react on the public comments in this thread above:

- Yes, we offer the WEEKLY updated OSM planet data with additional data sources (Satellite, Hillshading, Contour lines) for a price that is significantly cheaper than what you have to pay if you do the data processing for entire world yourself (count both the machines and your own maintenance time for all the tilesets we provide).

- The money is invested back into further improvement of this and related projects so there are new releases and updates in the future. We have no investors, so we are fully dependent only on happy customers.

- The multi-license fee is here to protect the use-case where one company purchases for $1000 and sells to many other companies who will never buy from us anymore. If we don't put this in place, we could close the box and probably must stop to further develop, maintain and actively support this open-source project with a team of fulltime people - and the project probably stales or dies completely. I hope it is understandable.

If you actively use this project please consider contributing to the code or purchasing the services of our team. We have expert knowledge in the field and already invested thousands of working hours into this codebase and are keen to continue to improve it further. 

Community contributions are always very welcome. There is a group of people accepting Pull Requests here. There are many individuals, independent teams and companies who power their maps with this FOSS project (even fully without our assistance) and they contributed and continue to contribute back to the code base!

Unfortunately, there are also people who only use the project for their (commercial) purpose, and complain and shout and strongly demand free support and are angry, but never give anything back.

A truly huge thanks belong to everybody who really helps. Let's hope in a bright future together!

**Comment by klokan** [comment]
Duplicate to #242
