### ISSUE TITLE
Query for osm data in server

### ISSUE THREAD

**Issue by stephanielsx** [openmaptiles/openmaptiles#670]
Hi Team,

Is it possible to query for OpenStreetMap data in OpenMapTiles server?

**Comment by daliborjanak** [comment]
No, OMT Server contains only preprocessed data in vector tiles.

**Comment by sfkeller** [comment]
You have to setup your own tools like Turf.js or TileReduce. But much easier is to extract a region as vector geopackage e.g. using https://osmaxx.hsr.ch/ , load the data in QGIS and do the analysis there.

**Comment by klokan** [comment]
Vector tiles should contains for some features the OSM ID - so you can, in a web browser, click on a feature - and make additional query to an external system like OSM API - to get more details (for example more info about POIs) interactively.
