### ISSUE TITLE
No Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by stephanielsx** [openmaptiles/openmaptiles#671]
Hi Team,

I'm running the OMT server in Docker in a Linux VM and I am able to access the server from another network however I can't access to the image from the WMS service with the error: 

"Access to the image at 'http://192.168.120.xxx:8080/services/wms?...." has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

Appreciate if anyone could assist..
Thank you.

**Comment by petrsloup** [comment]
There is `Access-Control-Allow-Origin: *` on all the `/services` endpoints.

If you are running some kind of reverse proxy (nginx, apache, ...) or other network component in front of the server, make sure it's properly configured to pass the header through.
