### ISSUE TITLE
Different projections? Hobo-Dyer or Peters?

### ISSUE THREAD

**Issue by edent** [openmaptiles/openmaptiles#674]
Are there any vector tiles for Hobo-Dyer or Gall-Peters? (Yes, [I know!](https://xkcd.com/977/))

I'm trying to find a cylindrical equal-area projection.

Thanks for a brilliant resource.

**Comment by klokan** [comment]
No, not directly available in the free downloads.

You can patch this open-source stack and generate them yourself.

Or you can [contract us](mailto:sales@maptiler.com) to do that for you. 

WGS84 is now available at https://cloud.maptiler.com/maps/basic-4326/

Soon also French Lambert, UK OSGB, Dutch RD New, Swiss, Czech etc.

**Comment by klokan** [comment]
I see you are a geek:
You can try to modify our open-source client-side RASTER tile reprojection in OpenLayers into client-side VECTOR tile reprojection. That would be damn cool ;-)

More at:
https://epsg.io/map (Reproject Map feature)
https://openlayers.org/en/latest/examples/reprojection.html?q=reproject (try View as Mollweide and others).
https://openlayers.org/en/latest/examples/reprojection-by-code.html?q=reproject

**Comment by edent** [comment]
A geek!? How dare you?!?! 😂😂

I'll take a look at those. I can reproject the rasters using:
```
proj4.defs('GallPeters', "+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs");
```
That works, but I'd like to do it with vectors.
