### ISSUE TITLE
Missing a part of a river 

### ISSUE THREAD

**Issue by golubev** [openmaptiles/openmaptiles#683]
A part of a river in Nikolaev (Ukraine) is missing in the OMT-generated tiles:

![66826106-5989b880-ef54-11e9-81f1-5986ab7536e3](https://user-images.githubusercontent.com/951364/66918855-e30aba80-f028-11e9-85ef-127f33c8e7fc.png)

I tried to research this issue and found that this part of the river has the `natural=bay` tag:
https://www.openstreetmap.org/relation/9953396#map=12/46.9388/32.0154

While in the commit https://github.com/openmaptiles/openmaptiles/commit/68255e16add9273ac11decb064be878d5f37c5eb all bays were removed on the higher zooms.

I think that this commit was likely to lead to this issue. After reverting this commit in our OMT fork - https://github.com/lun/openmaptiles/commit/6e1ff30cd5172bd946c59e9e4d7e10c6708ca2a9 and https://github.com/lun/openmaptiles/commit/ecc899982eac937187327514e204819d6838c616 and regenerating the tiles the river became visible again:

![66918384-ecdfee00-f027-11e9-9e01-3dba28481b9f](https://user-images.githubusercontent.com/951364/66919210-97a4dc00-f029-11e9-9fee-ad4f3b880a8b.png)

/cc @eva-j

**Comment by eva-j** [comment]
This can be solved by updating import-water - please use current release v1.2.
The problem appeared after OSM edits, now this part of water is imported by import-water, not by import-osm.

Reverting "bay commit" can help in your area for now, but in general it is causing problems. Bays cover islands in many parts of the world.

**Comment by golubev** [comment]
OK! Thanks, @eva-j!

**Comment by golubev** [comment]
I've tried to generate tiles after the https://github.com/openmaptiles/openmaptiles/commit/5ea8d9ae8e33c15c16723249699da77f8c324cd4 (`openmaptiles/import-water:1.2`). Now everything is OK in Nikolaev:

![Screenshot from 2019-11-08 10-05-48](https://user-images.githubusercontent.com/951364/68459982-6629c580-020f-11ea-8df1-fb679f34cf5c.png)

Even more. I've found that some islands and coasts had become prettier. [mapbox/mapbox-gl-compare](https://github.com/mapbox/mapbox-gl-compare) is used to compare maps with old and new tiles. The newer map is on the right:

![captured (8)](https://user-images.githubusercontent.com/951364/68460280-18fa2380-0210-11ea-83d4-65deb7778608.gif)

Thanks :hand:

**Comment by golubev** [comment]
It's a pity, I've just found another one disappearing river in the new tiles here - https://www.openstreetmap.org/#map=15/48.5162/34.9433

![captured (11)](https://user-images.githubusercontent.com/951364/68461804-ce7aa600-0213-11ea-8567-983454edf49f.gif)

It is a bay too - https://www.openstreetmap.org/relation/1608906
