### ISSUE TITLE
Project maintenance & Updates

### ISSUE THREAD

**Issue by rkans02** [openmaptiles/openmaptiles#684]
I have downloaded and generated tiles for europe zoom "0 - 14". Generating took 4 days. The db is now 14 days old and I am trying to update it (using docker-compose run update-osm). The process starts but takes way to long.  So far I downloaded and imported 13 .osc files which took almost 2 days. Each import takes approx 5:50hrs.
Currently I get the follwing output:
[Oct 18 09:54:26] [INFO] [  1m0s] C:       0/s (0) N:     100/s (39) W:     500/s (276) R:      0/s (0)

I tried to understand why it takes so long and it seems like the COMMIT in the databae take a lot of time. Here is one example log:
LOG:  duration: 123468.036 ms  statement: COPY public.osm_ocean_polygon (gid, fid, geometry) TO stdout;

Specs:
24 CPU´s
16GB RAM
2TB Disk

Also: Whats the status of this project? Is it still maintained or is it more lika a community project now?
For example that the older version of imposm3 is still used. Here the config.json is not even used:
    - "http://planet.openstreetmap.org/replication/minute/" is always used.

Also the used tilelive repo not maintained anymore.

**Comment by klokan** [comment]
The project is in production use by multiple groups of people / companies and it serves as the backbone for many maps out there. It is actively developed and maintained - with regular releases.

See FOSS4G presentation with status report from September this year:
https://www.youtube.com/watch?v=nqCvfgdRLo4

As with every open-source project, feel free to fiddle with the code and use it for your own purpose. Free software means the freedom to do what you want. Contributions are welcome.

**Comment by nyurik** [comment]
@klokan awesome video!  Glad openmaptiles will shrink down on the number of repositories (I have already combined `postgis` into openmaptiles-tools, and pending a pull request to combine `import-sql`). Glad to see it picking up steam!

**Comment by TomPohys** [comment]
Hi @rkans02, nowadays have Europe`s pbf around 20GB. After imports, the PostgreSQL have almost 200GB. The processing time is something we care about, and we try to keep it as low as possible. Some processes take time. Thanks
