### ISSUE TITLE
Administrative borders on water

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#690]
I believe it is not possible to hide the country's border which is drawn over the water.

We should add an attribute to be able to style (or hide/show) only these parts of the administrative borders.

**Comment by zstadler** [comment]
I've been using the [`maritime`](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dmaritime) field.

**Comment by eva-j** [comment]
Yes, thanks @zstadler.


![Screenshot from 2019-11-07 15-30-54](https://user-images.githubusercontent.com/8367628/68397850-1ea22b80-0174-11ea-8b90-68a2b6fb35cb.png)

after aplying `maritime != 1`:
![Screenshot from 2019-11-07 15-30-38](https://user-images.githubusercontent.com/8367628/68397887-2bbf1a80-0174-11ea-92ea-53ce35b8f70f.png)
