### ISSUE TITLE
Archive import-sql repo

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#696]
Please archive [import-sql repo](https://github.com/openmaptiles/import-sql) -- it has been merged with [openmaptiles-tools](https://github.com/openmaptiles/openmaptiles-tools#importing-into-postgres)

One pending PR there can be safely closed (it was discussed [here](https://github.com/openmaptiles/openmaptiles-tools/pull/59))

**Comment by TomPohys** [comment]
Repo is arcived.
