### ISSUE TITLE
Fork mapbox/postgis-vt-util to openmaptiles to allow improvements

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#710]
[mapbox/postgis-vt-util](https://github.com/mapbox/postgis-vt-util) repo has not had any changes since 2017 ( thx @lukasmartinelli ).  There are some changes long overdue, such as adding "parallel safe" to all of them (this option is supported since PostgreSQL 9.6).

Please fork that repo into OMT, and grant me edit rights so I can merge some changes into it.  Thanks!

**Comment by daliborjanak** [comment]
Forked https://github.com/openmaptiles/postgis-vt-util, you have access rights now
