### ISSUE TITLE
version in metadata should be a number

### ISSUE THREAD

**Issue by xylosper** [openmaptiles/openmaptiles#716]
From MBTiles specification:
> * version (number): The version of the tileset. This refers to a revision of the tileset itself, not of the MBTiles specification.

So, version in metadata should be a number not a string.
However, .mbtiles files generated by openmaptiles tool contain version in semver style string.

**Comment by TomPohys** [comment]
Hi @xylosper, metadata table in .mbtiles  have columns `name` and `value` which are text data type both. I think that there is no way how to have `version` as a number if there have to be another text descriptions.

**Comment by klokan** [comment]
The decision in the early stages of the OpenMapTiles project was to include semver in the version.

There are several software tools using it and depending on it in metadata - including metadata headers in the OpenMapTiles compatible GL styles that define compatibility to the OpenMapTiles schema version.

We need more than a number.

**Comment by klokan** [comment]
BTW What software is complaining? BTW I consider "3.11" a number - which is what is in the releases.

**Comment by xylosper** [comment]
@klokan No software. I am pointing out that it violates Mbtiles specifications.
If you insist 3.11 is a number, 3.2 shoul be more recent version than 3.11 because 3.2 > 3.11 . However, as far as I can see from git log, I think 3.2 is way older version than 3.11 which means 3.11 is not a real number but a semver style string.

**Comment by klokan** [comment]
Thanks for pointing that out.

Related discussion at https://github.com/mapbox/mbtiles-spec/issues/62

Unfortunately, I don't see any immediate action here. Maybe on a major future release of OpenMapTiles (so 4.x), we could stop to use `version` field (and set it to a constant "1") and start to use different metadata attribute for openmaptiles semver for style compatibility - and patch all the tools which use it.

BTW The future may bring a switching from MBTiles to the standardized OGC GeoPackage with MVT extension.
This is what we use now in MapTiler Cloud for vector tiles in non-mercator coordinate systems - such as planet in WGS84 / Lambert / JTSK / Swiss / etc: https://cloud.maptiler.com/maps/basic-4326/
MBTiles is not supporting custom tilegrids and CRS (and probably never will - as it is not a priority of Mapbox).
