### ISSUE TITLE
Historic boundaries should not be shown on the map

### ISSUE THREAD

**Issue by kolb-stefan** [openmaptiles/openmaptiles#722]
Boundaries with the tag boundary=historic should either not been added to the vector tiles or should be be marked with historic or something similar.

An example for such a boundary can be found around the small town Attelwil in Switzerland https://www.maptiler.com/maps/#bright//vector/14.58/8.0396/47.26394 the shown relation is https://www.openstreetmap.org/relation/1684257.

**Comment by eva-j** [comment]
Hi @kolb-stefan, thanks for letting us know about this. It is a problem of old data in import-osmborder docker image, sorry for that. No `boundary=historic` relations or ways are included in OMT schema. After new release (in a few weeks) it will be ok. You can already use updated import-osmborder image from https://hub.docker.com/r/openmaptiles/import-osmborder/.

**Comment by kolb-stefan** [comment]
Thanks for the fast reply!

When will vector tiles downloaded from https://openmaptiles.com/downloads/planet/ be fixed, with the release in a few weeks or faster?

**Comment by eva-j** [comment]
With the release in a few weeks.

**Comment by TomPohys** [comment]
Hi @kolb-stefan, could this issue be closed? I looked at the [relation](https://www.openstreetmap.org/relation/1684257) and [map](https://www.maptiler.com/maps/#bright//vector/14.58/8.0396/47.26394) and it looks good.

Thanks
