### ISSUE TITLE
Water disappears in Crimea at zooms 6 and 7

### ISSUE THREAD

**Issue by golubev** [openmaptiles/openmaptiles#723]
At zooms 6 and 7 some areas in Crimea that are covered with water disappear. I used the revision https://github.com/openmaptiles/openmaptiles/commit/0545f1e27d1783c2a300db4eadaa26cef3dcb705 to generate new tiles.

This is how it was before (zoom 6):

![Screenshot from 2019-12-09 17-47-57](https://user-images.githubusercontent.com/951364/70450922-363f3d80-1aad-11ea-9524-58d4b3727f35.png)

And this is how it is with the new OMT revision (zoom 6):

![Screenshot from 2019-12-09 17-46-47](https://user-images.githubusercontent.com/951364/70450942-3ccdb500-1aad-11ea-966c-eab622eacdd3.png)

The same for zoom 7:

![Screenshot from 2019-12-09 17-49-37](https://user-images.githubusercontent.com/951364/70451001-52db7580-1aad-11ea-861e-07fc6783817c.png)

![Screenshot from 2019-12-09 17-49-01](https://user-images.githubusercontent.com/951364/70451021-5a9b1a00-1aad-11ea-9230-5dae68b674e6.png)

**Comment by eva-j** [comment]
Thanks for reporting this.
It is a problem of combining data sources - till z8 we use ocean polygons from import-water, starting z7 they come from Natural Earth. In Natural Earth is this problematic water area classified as lake, not part of ocean, this way it is in different dataset (this NE dataset is used starting z5).
https://github.com/openmaptiles/openmaptiles/blob/master/layers/water/etl_diagram.png

It could be easily solved by using import-water source for oceans in z6 and z7 too, I will test it.

**Comment by golubev** [comment]
Thanks, @eva-j!

That area is really like a lake - it is a large system of lagoons - https://en.wikipedia.org/wiki/Syvash

**Comment by eva-j** [comment]
https://github.com/openmaptiles/openmaptiles/pull/730 merged.

**Comment by golubev** [comment]
Before fix:

![Screenshot from 2019-12-18 13-11-49](https://user-images.githubusercontent.com/951364/71081724-7f238000-2198-11ea-8b23-d91d28b7f335.png)

After the fix:

![Screenshot from 2019-12-18 13-12-07](https://user-images.githubusercontent.com/951364/71081731-82b70700-2198-11ea-8080-bfa3377cad27.png)

Thanks, @eva-j :wave:
