### ISSUE TITLE
Closed way imported as Polygon

### ISSUE THREAD

**Issue by kylebarron** [openmaptiles/openmaptiles#724]
This [OSM way](https://www.openstreetmap.org/way/45671692) is a loop trail around a lake. While it is correctly imported as a LineString, it's _also_ incorrectly imported as a Polygon.

Here's how it [should be displayed](https://api.mapbox.com/styles/v1/mapbox/outdoors-v10.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#16.08/37.891222/-119.340094):
![image](https://user-images.githubusercontent.com/15164633/70484228-69330280-1aa8-11ea-94a8-c46d7950f2f2.png)

But looking at the tiles through `mbview`, it's clear that the polygon exists as well:
![image](https://user-images.githubusercontent.com/15164633/70484314-b4e5ac00-1aa8-11ea-8b1e-b1a39594df46.png)

It is displayed correctly [in the hosted Maptiler styles](https://www.maptiler.com/maps/#topo//vector/16.41/-119.340865/37.891167), because the styles check for the type of the path to be LineString when styling.

So I suppose this isn't a critical bug, as long as the style correctly checks for the path type. OSM Liberty does not, which renders like this:
![image](https://user-images.githubusercontent.com/15164633/70484681-d6936300-1aa9-11ea-89d4-fc2ffdee19f4.png)

I consider the bug to be here, not in OSM liberty because the OSM object is not a polygon.

I haven't checked all zoom levels, but it appears at least at zoom level 14.

**To reproduce**

From scratch:
Generate tiles for level 14 for California.

To see the result, here's the specific vector tile with the polygon
https://tiles.nst.guide/openmaptiles/14/2760/6326.pbf

**Comment by kylebarron** [comment]
Specifically, it matches [this rule](https://github.com/maputnik/osm-liberty/blob/e8b4e45be7410ed12c85e349e32e64ed9dd17fb4/style.json#L515-L522) in `osm-liberty/style.json`:
```json
    {
      "id": "road_area_pattern",
      "type": "fill",
      "source": "openmaptiles",
      "source-layer": "transportation",
      "filter": ["all", ["==", "$type", "Polygon"]],
      "paint": {"fill-pattern": "pedestrian_polygon"}
    },
```

The point is that this is a valid rule for areas that are intentionally pedestrian polygons.

Here's it showing in maputnik:
![image](https://user-images.githubusercontent.com/15164633/70485070-20c91400-1aab-11ea-9fcd-820032b5d5ed.png)


Note that with `tile.json` pointing to Maptiler's servers, the polygon isn't present:
![image](https://user-images.githubusercontent.com/15164633/70485105-3f2f0f80-1aab-11ea-8672-f02e869072a5.png)

I generated my tiles about 10 days ago from `openmaptiles/openmaptiles` master, so it's possible this is a regression?

**Comment by eva-j** [comment]
Hi @kylebarron, thanks a lot for reporting this, now it is fixed in master.

**Comment by kylebarron** [comment]
Awesome, thanks!
