### ISSUE TITLE
[imposm3] move back to imposm3 upstream

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#73]
- [ ]  move `exclude_tags` patch to imposm3 upstream
- [ ]  move from https://github.com/osm2vectortiles/imposm3  to  imposm3 upstream

related: 
https://github.com/openmaptiles/openmaptiles/issues/69#issuecomment-263580516

**Comment by ImreSamu** [comment]
work in progress :  https://github.com/openmaptiles/openmaptiles/pull/124

**Comment by lukasmartinelli** [comment]
Well I still want to use the omniscale/imposm3 upstream as source for the container if possible :)
So we get the updates for free without merging them.

**Comment by jirik** [comment]
@ImreSamu We are approaching [milestone 3.5](https://github.com/openmaptiles/openmaptiles/milestone/7). Do you plan to finish this ticket in next days? If not, I will move it to another milestone.

**Comment by ImreSamu** [comment]
@jirik :  
> Do you plan to finish this ticket in next days? 
-  I am waiting for a merge ... (  The new syntax is accepted , but my pull request is not merged yet. ) 
-  temporary I have moved to the "Later" milestone , but you can modify the milestone as you  like.

**Comment by jirik** [comment]
@ImreSamu Thanks for info, I completely understand.

I created fork of your ImreSamu/imposm3 under openmaptiles and applied there [fix of memory leak in Geom.Bounds](https://github.com/openmaptiles/imposm3/commit/2628d7595cac50bf15bb1ce5f0f591980bb66a8a). This fork is now used in openmaptiles/import-osm. Thanks to @MartinMikita for suggestion.

**Comment by jirik** [comment]
I suppose the fork [openmaptiles/import-osm](https://github.com/openmaptiles/import-osm/) to be temporary. It should be deleted after https://github.com/omniscale/imposm3/pull/135 will be merged.

**Comment by jirik** [comment]
We are already back to imposm3 upstream: https://github.com/openmaptiles/import-osm/releases/tag/v0.5
