### ISSUE TITLE
Disputed borders PR added warnings to SQL

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#742]
Beginning with TravisCI [build 774](https://travis-ci.org/openmaptiles/openmaptiles/builds/624268832?utm_medium=notification&utm_source=github_status) triggered by the merge of https://github.com/openmaptiles/openmaptiles/commit/d82ede81ce6adba82f5efa7cd637831142f8d0b3 by PR https://github.com/openmaptiles/openmaptiles/pull/727 a warning began to appearing in the logs:

```
psql:/sql/tileset.sql:1115: NOTICE:  Processing layer boundary
DO
Time: 0.755 ms
CREATE FUNCTION
Time: 1.593 ms
psql:/sql/tileset.sql:1135: WARNING:  column "disputed_name" has type "unknown"
DETAIL:  Proceeding with relation creation anyway.
psql:/sql/tileset.sql:1135: WARNING:  column "claimed_by" has type "unknown"
DETAIL:  Proceeding with relation creation anyway.
CREATE VIEW
```

Once this bug is resolved, merge #743 to avoid it in the future.

**Comment by MartinMikita** [comment]
Note: using PostgreSQL 11.4 DB with OMT-tools 3.1.0 does not generate this warning, and the lines in tileset.sql are moved (probably expected)?

**Comment by eva-j** [comment]
Thanks for detecting this, @nyurik!
