### ISSUE TITLE
Rework `download-geofabrick` to avoid frequent errors

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#746]
Geofabrick area download frequently crashes, possibly due to it trying to list all available areas on every quickstart.sh run.  This is wasteful and not really needed.

Example from a [recent build](https://travis-ci.org/openmaptiles/openmaptiles/builds/625683087#L336)

```
====> : Downloading testdata albania.osm.pbf
=============== download-geofabrik =======================
Download area : albania
[[ example: make download-geofabrik area=albania ]]
[[ list areas: make download-geofabrik-list ]]
docker-compose run --rm import-osm  ./download-geofabrik.sh albania
Creating network "openmaptiles_postgres_conn" with driver "bridge"
Creating volume "openmaptiles_pgdata" with default driver
Creating volume "openmaptiles_cache" with default driver
 DEBUG[0011] request URL: https://download.geofabrik.de/ failed with response: &{0 [] 0xc00015eb60 0xc0000ea500 <nil>} error=Get https://download.geofabrik.de/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  INFO[0011] /import/geofabrik.yml generated.
 FATAL[0000] can't find albania        error=albania is not in config. Please use "list" command
Makefile:91: recipe for target 'download-geofabrik' failed
make: *** [download-geofabrik] Error 1
The command "./quickstart.sh" exited with 2.
Done. Your build exited with 1.
```

**Comment by kylebarron** [comment]
I'm hitting this bug too

**Comment by nyurik** [comment]
I'm in the process of adding last missing pieces to the `download-osm` tool. It is already capable of doing most of the things `download-geofabrik` can do.

**Comment by andyzaharia** [comment]
Running into the same bug... cant seems to use the latest build at all...

**Comment by inventionzhang** [comment]
Running into the same bug. how to solve it？thx

**Comment by kylebarron** [comment]
Every time I've tried to generate an mbtiles in the last month I've hit this. Are you close to merging `download-osm`?

**Comment by kylebarron** [comment]
Sorry, I'm an idiot... I've been going through and generating U.S. states, and I've had an error message similar to the first post every time when trying to generate `georgia`. Well, Georgia's also a country so I meant to be running 
```
./quickstart.sh georgia-us
```

**Comment by TomPohys** [comment]
From OpenMapTiles-Tools v4.1 is implemented new `download-osm` -> https://github.com/openmaptiles/openmaptiles-tools/releases/tag/v4.1.0
