### ISSUE TITLE
Quickstart Testing PostgreSQL step crash

### ISSUE THREAD

**Issue by NasH5169** [openmaptiles/openmaptiles#759]
Hi all,

I've updated with the last code from the master branch and run my OpenMapTiles project.

(docker prune system --all before running this new version)

There is a Python traceback and a crash with the step: https://github.com/openmaptiles/openmaptiles/blob/master/quickstart.sh#L265

Please find the log below:
```
====> : Testing PostgreSQL tables to match layer definitions metadata
Connecting to PostgreSQL at postgres:5432, db=openmaptiles, user=openmaptiles...
* version()                       = PostgreSQL 9.6.16 on x86_64-pc-linux-gnu (Debian 9.6.16-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
* postgis_full_version()          = POSTGIS="2.4.0dev r15415" GEOS="3.6.0-CAPI-1.10.0 r0" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.2, released 2016/10/24" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" RASTER
* jit                             = unrecognized configuration parameter "jit"
* shared_buffers                  = 128MB
* work_mem                        = 4MB
* maintenance_work_mem            = 64MB
* max_connections                 = 100
* max_worker_processes            = 8
* max_parallel_workers            = unrecognized configuration parameter "max_parallel_workers"
* max_parallel_workers_per_gather = 0

Validating SQL fields in all layers of the tileset
Traceback (most recent call last):
  File "/usr/src/app/test-perf", line 97, in <module>
    main(docopt(__doc__, version=openmaptiles.__version__))
  File "/usr/src/app/test-perf", line 93, in main
    asyncio.run(perf.run())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/usr/src/app/openmaptiles/performance.py", line 107, in run
    await self._run(conn)
  File "/usr/src/app/openmaptiles/performance.py", line 124, in _run
    fields = await self.mvt.validate_layer_fields(conn, layer_id, layer_def)
  File "/usr/src/app/openmaptiles/sqltomvt.py", line 251, in validate_layer_fields
    layer_fields = layer_def.get_fields()
  File "/usr/src/app/openmaptiles/tileset.py", line 78, in get_fields
    layer_fields = list(self['layer']['fields'].keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

Any idea?

**Comment by NasH5169** [comment]
Update: I realize that it is perhaps my custom layers which with there is something missing in the SQL file... Some types or something like that...

**Comment by nyurik** [comment]
```
layer_fields = list(self['layer']['fields'].keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```
@NasH5169 the last few lines of python stack usually tell you what the problem is.  In this case, it means that `self['layer']['fields']` is None, in other words you don't have any `fields` defined in your `layer`, which is clearly a bug in your definition. See [example](https://github.com/openmaptiles/openmaptiles/blob/master/layers/aeroway/aeroway.yaml#L8) of various fields for the `aeroway` layer.

**Comment by NasH5169** [comment]
Ok, you're right, my custom layers don't have any fields in the <layer>.yaml file.

But why is it mandatory? 

Perhaps, I can just add on "ref" field like the one in aeroway layer:

**Comment by nyurik** [comment]
@NasH5169 the fields from the yaml file are used in the metadata, see https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#vector_layers -- `vector_layers / fields`.  Without the correct fields in yaml, the metadata will not be correct, which could affect any MVT consumer.
