### ISSUE TITLE
Add boundary=protected_area to park layer

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#760]
Currently, `boundary=protected_area` areas are not included in the park layer.

The OSM wiki pages for [`boundary=national_park`](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dnational_park) and [`leisure=nature_reserve`](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dnature_reserve) say under "Similar tags":

> [`boundary=protected_area`](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dprotected_area) is a more recently introduced tag with a more verbose tagging scheme which can deal with all kind of protections and protection levels. It attempts to encompass both nature reserves and national parks, and is used more and more.

[Back in 2016](https://github.com/openmaptiles/openmaptiles/issues/51#issuecomment-263535479), @lukasmartinelli said:
>  In the park layer we would then have `leisure=natural_reserve`, `boundary=national_park` and `boundary=protected_area`.

I have enhanced the park layer to include the missing areas, as this is the OSM mapping standard in my country.

Here is the new description of the `class` field where an attempt was made to unify the different tagging options:

> Use the **class** to differentiate between different parks.
> The class for `boundary=protected_area` parks is the lower-case of the [`protection_title`](http://wiki.openstreetmap.org/wiki/key:protection_title) value with blanks replaced by `_`.
> `national_park` is the class of `protection_title=National_park` and `boundary=national_park`.
> `nature_reserve` is the class of `protection_title=Nature Reserve` and `leisure=nature_reserve`.
> The class for other `protection_title` values is similarly assigned.

I will be happy to share this enhancement using a PR for this issue.

**Comment by TomPohys** [comment]
Hello @zstadler, your PR is very welcome. Can be part of v3.12 release. 

Connection to https://github.com/openmaptiles/openmaptiles/pull/773 and https://github.com/openmaptiles/openmaptiles/issues/776
