### ISSUE TITLE
Include all peaks in the `mountain_peak` layer 

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#761]
Only 65% of the peaks have an `ele` tag and therefore are included in the `mountain_peak` layer.
Some mappers, like the OSM default map, would like to show peaks even if the have no name or elevation. Peaks with names, for example, are valuable even of their elevation is unknown.

If all peaks are included in the `mountain_peak` layer, it would be up to the style creator to decide which peaks to show.

I will be happy to submit a PR.

Data source: [Overpass-Turbo query](http://overpass-turbo.eu/s/PvT) (click "Run" and be patient):
* 619k peaks
* 401k peaks with `ele` (65%)
* 142k peaks with `name` and without `ele` (23%)
* 76k peaks without `name` or `ele` (12%)

**Comment by kylebarron** [comment]
FYI I think it's simpler to get those statistics directly from `taginfo`:
https://taginfo.openstreetmap.org/tags/natural=peak#combinations

**Comment by nyurik** [comment]
Would it make sense to fix the `ele` tag in OSM instead?

**Comment by kylebarron** [comment]
Probably, but it'll take a long time to update those 218,000 peaks with their elevation values.

**Comment by nyurik** [comment]
would it be possible to semi-automate that?  I.e. get at least some of them from some global elevation map?   TBH, a peak without `ele` and without a `name` feels like junk data.

**Comment by kylebarron** [comment]
Absolutely, though OSM bulk edits are highly discouraged without lots of planning/talking with the community, and I don't want to take the time to deal with planning a bulk edit like that.

**Comment by nyurik** [comment]
sigh, i'm well aware of that :)  I'm ok with including nameless and elevationless peaks, but only on higher zooms to prevent data bloat... even though it does feel like adding junk data tbh.

**Comment by kylebarron** [comment]
I personally wouldn't include peaks that are both nameless and elevationless. I might consider only elevationless peaks.

**Comment by zstadler** [comment]
> FYI I think it's simpler to get those statistics directly from `taginfo`:
> https://taginfo.openstreetmap.org/tags/natural=peak#combinations

Could not find there the number of peaks with a name but no elenation.

**Comment by zstadler** [comment]
> sigh, i'm well aware of that :) I'm ok with including nameless and elevationless peaks, but only on higher zooms to prevent data bloat... even though it does feel like adding junk data tbh.

I agree. What would be a reasonable minimum zoom for nameless peaks w/o elevation?

**Comment by kylebarron** [comment]
I personally would be in favor of elevationless peaks at z14, and wouldn't include nameless peaks at all. Though in [my style](https://github.com/nst-guide/osm-liberty-topo), I also have contour lines, so adding all peaks isn't high importance.

**Comment by zstadler** [comment]
It is not clear to me if all of the previous comments were related to the inclusion of peak data elements in the vector tiles, or if they referred to the style preferences of their author.

IMO, the vector tiles need to include the nameless and elevation-less peaks so that style authors can choose what to show at each zoom level.

**Comment by zstadler** [comment]
[Earlier](https://github.com/openmaptiles/openmaptiles/issues/761#issuecomment-573340965) @nyurik  wrote:

 > sigh, i'm well aware of that :) I'm ok with including nameless and elevationless peaks, but only on higher zooms to prevent data bloat... even though it does feel like adding junk data tbh.

The existing SQL code already performs rank-base filtering of the number of mountain peaks in a given vector tile in zoom levels lower than 14:

```sql
  WHERE zoom_level >= 7 AND (rank <= 5 OR zoom_level >= 14)
  ORDER BY "rank" ASC;
```

Elevation-less peaks could be filtered out, for example, by giving them a -10000 "rank penalty", similar to the current 10000 "rank bonus" for named peaks:

```sql
      row_number() OVER (
          PARTITION BY LabelGrid(geometry, 100 * pixel_width)
          ORDER BY (
            (CASE WHEN ele ~ E'^-?\\d{1,4}(\\D|$)'
              THEN substring(ele from E'^(-?\\d+)(\\D|$)')::int ELSE -10000 END) +
            (CASE WHEN NULLIF(wikipedia, '') is not null THEN 10000 ELSE 0 END) +
            (CASE WHEN NULLIF(name, '') is not null THEN 10000 ELSE 0 END)
          ) DESC
      )::int AS "rank"

```

**Comment by kylebarron** [comment]
> It is not clear to me if all of the previous comments were related to the inclusion of peak data elements in the vector tiles, or if they referred to the style preferences of their author.

My above comments are referring to the inclusion of peak data elements in the main  OpenMapTiles repository, because I've seen multiple issues where maintainers place a high importance on keeping the vector tile size small. There clearly must be some level of style decision making when generating the vector tiles, otherwise the tiles would be huge. The question is where to draw the line. (Regardless, I'm not a maintainer so my comments don't hold much weight).

Are you suggesting to remove the existing
```sql
WHERE zoom_level >= 7 AND (rank <= 5 OR zoom_level >= 14)
```
entirely, or keep that line with your updated rank code? I think I'd support keeping the existing `WHERE` clause with your new `rank` code, because that would include nameless/elevationless peaks in areas where there are no peaks with higher rank.

**Comment by zstadler** [comment]
Here is the code snippet with the two proposed modification:

1. Add a -10000 rank to peaks with no `ele`, `name`, and `wikepadia` tags
2. Remove the filtering-out of peaks without a valid `ele` tag from the inner `WHERE` clause

```
      row_number() OVER (
          PARTITION BY LabelGrid(geometry, 100 * pixel_width)
          ORDER BY (
            (CASE WHEN ele ~ E'^-?\\d{1,4}(\\D|$)'
              THEN substring(ele from E'^(-?\\d+)(\\D|$)')::int ELSE -10000 END) +
            (CASE WHEN NULLIF(wikipedia, '') is not null THEN 10000 ELSE 0 END) +
            (CASE WHEN NULLIF(name, '') is not null THEN 10000 ELSE 0 END)
          ) DESC
      )::int AS "rank"
      FROM osm_peak_point
      WHERE geometry && bbox
    ) AS ranked_peaks
  WHERE zoom_level >= 7 AND (rank <= 5 OR zoom_level >= 14)
  ORDER BY "rank" ASC;
```

**Comment by kylebarron** [comment]
Doesn't that add a -10000 rank to peaks with no `ele` tags, even if they do have `name` and/or `wikipedia` tags? So if `elevation` is `null` but `name` exists, then it would have rank of `0`? This is what I understood your text to be
```sql
      row_number() OVER (
          PARTITION BY LabelGrid(geometry, 100 * pixel_width)
          ORDER BY (
            (CASE WHEN ele ~ E'^-?\\d{1,4}(\\D|$)'
              THEN substring(ele from E'^(-?\\d+)(\\D|$)')::int ELSE 0 END) +
            (CASE WHEN NULLIF(wikipedia, '') is not null THEN 10000 ELSE 0 END) +
            (CASE WHEN NULLIF(name, '') is not null THEN 10000 ELSE 0 END) +
			(CASE WHEN NULLIF(name, '') is null AND NULLIF(wikipedia, '') is null AND NULLIF(ele, '') is null THEN -10000 ELSE 0 END)
          ) DESC
      )::int AS "rank"
      FROM osm_peak_point
      WHERE geometry && bbox
    ) AS ranked_peaks
  WHERE zoom_level >= 7 AND (rank <= 5 OR zoom_level >= 14)
  ORDER BY "rank" ASC;
```

In any case, I feel that we need a maintainer to comment on what they'd accept.

**Comment by TomPohys** [comment]
We are planning to organized the 3rd OpenMapTiles community meeting. The best date was selected on April 15th, at 11 AM ET (5 PM CET). We are using Google Hangouts (https://meet.google.com/eek-pfot-nji). If interested, please, send me an email and I will add you to the Google Calendar Meeting. Thanks.
