### ISSUE TITLE
Wrong name on roads with ref

### ISSUE THREAD

**Issue by eva-j** [openmaptiles/openmaptiles#762]
It looks like there is problem in transportation_name layer - if there is no `name` tag, it takes name from different way with the same `ref` value.

Examples:

**Coridorul 4 Pan European** (`ref=A1`)
not only in Romania:
https://www.maptiler.com/maps/#basic//vector/11.78/22.01018/45.81468
but also in Lithuania:
https://www.maptiler.com/maps/#basic//vector/10.87/22.0357/55.6261

**Central Syria** (`ref=7`)
not only in Syria:
https://www.maptiler.com/maps/#basic//vector/13/38.6149/34.64652
but also in Czechia:
https://www.maptiler.com/maps/#basic//vector/14/9.25055/60.46731
or in Norway:
https://www.maptiler.com/maps/#basic//vector/14/9.25393/60.46312

**Comment by ilessiivi** [comment]
I ran across the same issue with a `ref=4` way in Finland: https://www.maptiler.com/maps/#streets//vector/10.27/25.8193/64.1901 ([416192821](https://www.openstreetmap.org/way/416192821) is named and label is shown correctly, [4391705](https://www.openstreetmap.org/way/4391705) is unnamed and wrong name is guessed).

Same situation with a `ref=4` way in Norway: https://www.maptiler.com/maps/#streets//vector/14.5/10.74135/60.15204 ([296803826](https://www.openstreetmap.org/way/296803826) and [25663921](https://www.openstreetmap.org/way/25663921)).

**Comment by TomPohys** [comment]
Thank you for an update on this issue. Feel free to make a pull request.

**Comment by eva-j** [comment]
It seems like the wrong name is getting there from `tags`. I tried it on Europe data extract - if I select all lines with `ref='A1'` without `name` filled, I get this result:

![screenshot_](https://user-images.githubusercontent.com/8367628/83186833-6b0f8180-a12d-11ea-897f-5d2a334189d8.png)

For all of the selected lines (red lines in the map) there is this in tags:
`"int_name"=>"Coridorul 4 Pan European", "name_int"=>"Coridorul 4 Pan European", "wikidata"=>"Q12777840", "name:latin"=>"Coridorul 4 Pan European"`

I expect the problem is happening in this part of code https://github.com/openmaptiles/openmaptiles/blob/master/layers/transportation_name/update_transportation_name.sql#L41

I checked Wikidata ID https://www.wikidata.org/wiki/Q12777840 - it is a tunnel on A1 street in Croatia.

Is there anybody who could continue with this issue?

**Comment by xkomczax** [comment]
[Replaced with a different name](https://support.maptiler.com/i556-basemap-data-road-name-coridorul-4-pan-european#item_comment_block_65608), which still makes no sense.

**Comment by zstadler** [comment]
@eva-j 
Potentially this issue was resolved by #989

**Comment by eva-j** [comment]
@zstadler that would be great! I am going to test it.

**Comment by eva-j** [comment]
It looks good! Tested on Europe extract and known problems disappeared. Solved by https://github.com/openmaptiles/openmaptiles/pull/989, thanks a lot @zstadler!
