### ISSUE TITLE
Cannot convert custom osm data use quickstart.sh 

### ISSUE THREAD

**Issue by hnqdarktime** [openmaptiles/openmaptiles#768]
Hi guys,
I'm trying to convert custom data set(osm.pbf) to mbtiles file.

I get osm data by two ways:
  1. https://extract.bbbike.org/
  2. Get an extract area larger than my subject area from geofabrik then use osmconvert to chop it down to the area I want.

Then run quickstart command, script run to `/import_osm.sh` step then occur error:

`./import_osm.sh: line 19:     8 Killed                  imposm import -connection "postgis://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE" -mapping "$MAPPING_YAML" -overwritecache -diffdir "$DIFF_DIR" -cachedir "$IMPOSM_CACHE_DIR" -read "$pbf_file" -deployproduction -write $diff_flag -config "$CONFIG_JSON"`

[quickstart.log](https://github.com/openmaptiles/openmaptiles/files/4076403/quickstart.log)

Could you guys give me some advice?

**Comment by nyurik** [comment]
Seems like imposm is crashing with exit code 8.  I am really not sure what that means - do you have enough RAM and disk for the database?

**Comment by hnqdarktime** [comment]
@nyurik thanks for your advice. After upgrade configuration, the process goes well.

**Comment by neilireson** [comment]
@hnqdarktime I'm experiencng the same issue, could you provide some details on what you did to "upgrade configuration".
