### ISSUE TITLE
Some US state labels not available at appropriate zoom levels

### ISSUE THREAD

**Issue by brewin** [openmaptiles/openmaptiles#774]
New York and Florida have rank 4 while all other states have rank 1, so the labels don't exist at the right zoom levels. They should be in zoom level 3 tiles, but are only in zoom levels 5 and 6.

Edit:
It looks like labels for South Carolina, North Carolina, Maryland, and Hawaii are also not in the appropriate zoom levels.

**Comment by TomPohys** [comment]
@brewin Thank you for reporting this problem. I will look at that.

**Comment by TomPohys** [comment]
This should be now fixed by #969.
Thanks
