### ISSUE TITLE
Sign In Issue

### ISSUE THREAD

**Issue by Momina12** [openmaptiles/openmaptiles#775]
I am trying to sign in to openmaptiles.com to purchase tiles but unfortunately, sign in page is not showing username and password fields to sign in.... please help 
I am sharing link:
https://openmaptiles.com/auth/widget?mode=select&next=https%3A%2F%2Fopenmaptiles.com%2Fdownloads%2Ftileset%2Fsatellite-lowres%2F

**Comment by MartinMikita** [comment]
Hi,

1. You should see the following page:
![image](https://user-images.githubusercontent.com/2283182/73336673-bb0b3400-4272-11ea-90de-f94ee198d72d.png)

If you are not, please, submit a request to https://support.maptiler.com/add-ticket, and write your Browser and OS version, you are using.

**Comment by Momina12** [comment]
Exactly! I am expecting the page that you shared but I am getting this:

![Screenshot (3)](https://user-images.githubusercontent.com/51845054/73344330-0a337380-4237-11ea-953f-2545cfefe004.png)
