### ISSUE TITLE
Add area-base filtering for park names in lower zoom levels

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#776]
Park names are available as point features for all parks in a given zoom level. In lower zoom levels, some parks are completely hidden by their own labels and park labels can extend far beyond their boundaries.

This problem has already been handled in the `water_name` layer, using zoom-dependent filtering:

https://github.com/openmaptiles/openmaptiles/blob/9f4d48cf25fec4dfa80e3abb67801edd6607745f/layers/water_name/layer.sql#L38

I'll be glad to prepare a PR that use the `area > 70000*2^(20-zoom_level)` expression for filtering park labels in zoom levels other than 14.

**Comment by zstadler** [comment]
Please let me know if you like me to create a PR based on https://github.com/IsraelHikingMap/openmaptiles/commit/1530dc551a0bd38a11e51ed59354917e294423f6.

It would be best to apply it after https://github.com/openmaptiles/openmaptiles/pull/773 is merged.

**Comment by TomPohys** [comment]
Hello @zstadler, thank you for this update. 

Your PR is very welcome and can be part of v3.12 release.

**Comment by zstadler** [comment]
Hello @TomPohys,

I'll be happy to prepare it after https://github.com/openmaptiles/openmaptiles/pull/773 is closed becuase of its dependency.

**Comment by klokan** [comment]
Hi @zstadler - do you think you could manage to push this change till feature freeze of 3.12 (Friday?)

It could be a great contribution for the next release.

**Comment by zstadler** [comment]
@klokan per your request, I've prepared a PR.

**Comment by TomPohys** [comment]
@zstadler, thanks a lot. It going to be part of 3.12 release.

**Comment by klokan** [comment]
Thank you very much @zstadler - cool!
