### ISSUE TITLE
My node package

### ISSUE THREAD

**Issue by sabas** [openmaptiles/openmaptiles#781]
Hi,
since you're using in the docs the package I made long time ago (https://github.com/sabas/genfontgl), would you like to have it under your organization? Since I don't code in Node and I don't touch it since 2016 perhaps you can extend  it or rewrite if you need.

Thanks,
Stefano

**Comment by nyurik** [comment]
I'm all for transfering repo ownership to openmaptiles org. You essentially have to initiate the transfer, and it will have to be someone like @klokan to accept it. Thanks!

**Comment by sabas** [comment]
Okay, I need the permission to create repositories in the org to transfer.

**Comment by nyurik** [comment]
Hmm.. this might take some time.  A quicker option could be for you to transfer it to me, and i will add it to OMT?

**Comment by nyurik** [comment]
Done - https://github.com/openmaptiles/genfontgl , closing. Thanks!!
