### ISSUE TITLE
Makefile:204: recipe for target 'import-wikidata' failed make: *** [import-wikidata] Error 1

### ISSUE THREAD

**Issue by limh821** [openmaptiles/openmaptiles#784]
I followd the instructions here https://openmaptiles.org/docs/generate/generate-openmaptiles/ to generate the vector tiles using the quickstart bash script. After running "./quickstart.sh" in the terminal, I got the following error message: 

limh@dell:~/mywork/openmaptiles/openmaptiles$ ./quickstart.sh
No parameter - set area=albania 
 
-------------------------------------------------------------------------------------
                       Docker check & Download images                                
-------------------------------------------------------------------------------------
====> : Please check the Docker and docker-compose version!
      : We are using docker-compose v2 file format!  see more at https://docs.docker.com/
      : Minimum required Docker version: 1.12.3+
      : Minimum required docker-compose version: 1.7.1+
      : See the .travis build for the currently supported versions.
      : Your docker system:
Docker version 19.03.6, build 369ce74a3c
docker-compose version 1.25.4, build 8d51620a
./quickstart.sh: line 60: gawk: command not found
./quickstart.sh: line 60: gawk: command not found
./quickstart.sh: line 63: [: : integer expression expected
./quickstart.sh: line 60: gawk: command not found
./quickstart.sh: line 60: gawk: command not found
./quickstart.sh: line 69: [: : integer expression expected
 
-------------------------------------------------------------------------------------
====> : Pulling or refreshing OpenMapTiles docker images 
docker-compose pull --ignore-pull-failures
Pulling postgres                     ... done
Pulling import-natural-earth         ... done
Pulling import-water                 ... done
Pulling import-lakelines             ... done
Pulling import-osm                   ... done
Pulling import-osmborder             ... done
Pulling import-osm-diff              ... done
Pulling update-osm                   ... done
Pulling openmaptiles-tools           ... done
Pulling openmaptiles-tools-latest    ... done
Pulling generate-changed-vectortiles ... done
Pulling generate-vectortiles         ... done
Pulling postserve                    ... done
 
-------------------------------------------------------------------------------------
                                Start processing                                     
-------------------------------------------------------------------------------------
====> : OpenMapTiles quickstart! [ https://github.com/openmaptiles/openmaptiles ]    
      : This will be logged to the ./quickstart.log file (for debugging) and to the screen
      : Area             : albania 
      : Git version      : 2edbbfa1a0e3b3e3ba0a47a2d97f352377663dd2 
      : Started          : 2020-02-19T15:33+0800 
      : Your bash version: 4.3.48(1)-release
      : Your OS          : linux-gnu
Docker version 19.03.6, build 369ce74a3c
docker-compose version 1.25.4, build 8d51620a
 
-------------------------------------------------------------------------------------
      : This is working on x86_64 ; Your kernel is:
4.15.0-76-generic
x86_64
      : --- Memory, CPU info ---- 
system memory (GB): 15.3731
SwapTotal:      19999740 kB
cpu number: 12 x bogomips	: 5808.00
MemFree:          245496 kB
SwapFree:       19998192 kB
CmaFree:               0 kB
HugePages_Free:        0
 
-------------------------------------------------------------------------------------
====> : Stopping running services & removing old containers
docker-compose down -v --remove-orphans
Removing network openmaptiles_postgres_conn
Removing volume openmaptiles_pgdata
Removing volume openmaptiles_cache
docker-compose rm -fv
No stopped containers
docker volume ls -q | grep openmaptiles  | xargs -r docker volume rm || true
 
-------------------------------------------------------------------------------------
====> : Checking OpenMapTiles docker images 
openmaptiles/openmaptiles-tools     latest              fa969df63e81        2 hours ago         1.27GB
openmaptiles/openmaptiles-tools     <none>              14a75c48a63b        3 days ago          1.27GB
openmaptiles/import-osmborder       3.1.0               8fe6f6dde1e6        2 months ago        4.19GB
openmaptiles/import-lakelines       3.1.0               bb2f2b427171        2 months ago        188MB
openmaptiles/import-natural-earth   3.1.0               a5338e617df5        2 months ago        383MB
openmaptiles/import-osm             3.1.0               c6f79d4245e7        2 months ago        1.14GB
openmaptiles/openmaptiles-tools     3.1.0               91cf245a0559        2 months ago        1.08GB
openmaptiles/import-water           3.1.0               0b1ab57b88ee        2 months ago        1.9GB
openmaptiles/postgis                3.1.0               ea3300ed669c        2 months ago        1.03GB
openmaptiles/generate-vectortiles   3.1.0               e3a7de4f3ea9        2 months ago        819MB
klokantech/openmaptiles-server      latest              c7dfe7244ef9        7 months ago        1.48GB
 
-------------------------------------------------------------------------------------
====> : Making directories - if they don't exist ( ./build ./data ./pgdata ) 
 
-------------------------------------------------------------------------------------
====> : Removing old MBTILES if exists ( ./data/*.mbtiles ) 
 
-------------------------------------------------------------------------------------
====> : The testdata ./data/albania.osm.pbf exists, we don't need to download!
 
-------------------------------------------------------------------------------------
====> : Remove old generated source files ( ./build/* ) ( if they exist ) 
rm -f build/openmaptiles.tm2source/data.yml && rm -f build/mapping.yaml && rm -f build/tileset.sql
 
_... (ignoring hundreds of lines here)_

INFO:  analyzing "public.osm_water_polygon_gen1"
INFO:  "osm_water_polygon_gen1": scanned 52 of 52 pages, containing 838 live rows and 0 dead rows; 838 rows in sample, 838 estimated total rows
ANALYZE
 
-------------------------------------------------------------------------------------
====> : Start importing Wikidata: Wikidata Query Service -> PostgreSQL
      : The Wikidata license: CC0 - https://www.wikidata.org/wiki/Wikidata:Main_Page 
      : Thank you Wikidata Contributors ! 
 FIXME:   switch to openmaptiles-tools after v3.2+ is published
docker-compose run --rm openmaptiles-tools-latest import-wikidata openmaptiles.yaml
Found 13 tables with the 'tags' hstore fields
  * osm_aerodrome_label_point
  * osm_city_point
  * osm_continent_point
  * osm_country_point
  * osm_island_point
  * osm_island_polygon
  * osm_marine_point
  * osm_peak_point
  * osm_poi_point
  * osm_poi_polygon
  * osm_state_point
  * osm_water_polygon
  * osm_waterway_linestring
Searching for Wikidata IDs in 13 tables...
Found 565 Wikidata IDs to load.
Deleting any existing data in wd_names...
Inserting Wikidata IDs...
**Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f70f661f700>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query.wikidata.org', port=443): Max retries exceeded with url: /bigdata/namespace/wdq/sparql (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f70f661f700>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/import-wikidata", line 164, in <module>
    asyncio.run(main(docopt(__doc__, version=openmaptiles.__version__)))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/usr/src/app/import-wikidata", line 85, in main
    for row in wd_query(query):
  File "/usr/src/app/import-wikidata", line 145, in wd_query
    r = requests.post(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='query.wikidata.org', port=443): Max retries exceeded with url: /bigdata/namespace/wdq/sparql (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f70f661f700>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Makefile:204: recipe for target 'import-wikidata' failed
make: *** [import-wikidata] Error 1**

It seems like it's a connection problem, but I have no idea how to fix it. Can anyone help me?

**Comment by smellman** [comment]
@limh821 If you don't need importing wikidata, comment out this line.
https://github.com/openmaptiles/openmaptiles/blob/master/quickstart.sh#L258

**Comment by nyurik** [comment]
Also your `gawk` seems to be missing (same as `awk` but GNU). What OS are you using?  Also, is Wikidata issue still there?

**Comment by limh821** [comment]
> Also your `gawk` seems to be missing (same as `awk` but GNU). What OS are you using? Also, is Wikidata issue still there?

My OS is Ubuntu16.04. I figured out it might have something to do with the proxy settings. Because I can access the query.wikidata.org after openning the VPN (I kept my  VPN on during my running of ./quickstart.sh). But the error message told me that I could not connect to query.wikidata.org by trying to establish a connection via the python requests mechanism (Simply because the default settings do not consider any usage of VPN.). Some one told me that I have to modify the requests commands by adding the proxy into it, i.e. 
--------------------------------------------------------------------------------------------
      # xx.aa.com is the url of the VPN server and the port is 8080
       proxy={"https":"xx.aa.com:8080","http":"xx.aa.com:8080"}
       requests.get(url, proxies=proxy)
　　requests.post(url, proxies=proxy)
--------------------------------------------------------------------------------------------
But actually I don't have a python3.8 installed on "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py" mentioned in the error message. I 'm wondering where this path comes and trying to figure where to modify and add the proxy. Any comments are welcome!

**Comment by nyurik** [comment]
ah, ok, so its not a wikidata issue, but rather a proxy issue, i.e. you might be behind some sort of a great firewall.   The reason for python3.8 is because you run tools from a docker container - which was built with python 3.8.  You may want to look at https://docs.docker.com/network/proxy/ on how to configure docker to use your proxy.  This way you may avoid having to modify the python code itself.

**Comment by limh821** [comment]
>  importing wikidata

Thank you very much for your advice. I tried it and skipped the error, but ran into another:

====> : Start importing Wikidata: Wikidata Query Service -> PostgreSQL
      : The Wikidata license: CC0 - https://www.wikidata.org/wiki/Wikidata:Main_Page 
      : Thank you Wikidata Contributors ! 
'make import-wikidata' is commented this out to avoid requests.exceptions.ConnectionError.
See https://github.com/openmaptiles/openmaptiles/issues/784 for more details.
 
====> : Testing PostgreSQL tables to match layer definitions metadata
Connecting to PostgreSQL at postgres:5432, db=openmaptiles, user=openmaptiles...
* version()                       = PostgreSQL 9.6.16 on x86_64-pc-linux-gnu (Debian 9.6.16-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
* postgis_full_version()          = POSTGIS="2.4.0dev r15415" GEOS="3.6.0-CAPI-1.10.0 r0" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.2, released 2016/10/24" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" RASTER
* jit                             = unrecognized configuration parameter "jit"
* shared_buffers                  = 128MB
* work_mem                        = 4MB
* maintenance_work_mem            = 64MB
* max_connections                 = 100
* max_worker_processes            = 8
* max_parallel_workers            = unrecognized configuration parameter "max_parallel_workers"
* max_parallel_workers_per_gather = 0

Validating SQL fields in all layers of the tileset

Running all layers test 'null' at zoom 14 (0 tiles) - Empty set, useful for query validation....
Query returned no data after 0:00:00.062213


================ SUMMARY ================
No tiles were generated in 0:00:00
 

====> : Start generating MBTiles (containing gzipped MVT PBF) from a TM2Source project. 
      : TM2Source project definitions : ./build/openmaptiles.tm2source/data.yml 
      : Output MBTiles: ./data/tiles.mbtiles  
      : Source code: https://github.com/openmaptiles/openmaptiles-tools/tree/master/docker/generate-vectortiles 
      : We are using a lot of Mapbox Open Source tools! : https://github.com/mapbox 
      : Thank you https://www.mapbox.com !
      : See other MVT tools : https://github.com/mapbox/awesome-vector-tiles 
      :  
      : You will see a lot of deprecated warning in the log! This is normal!  
      :    like :  Mapnik LOG>  ... is deprecated and will be removed in Mapnik 4.x ... 
.FileNotFoundError: [Errno 2] No such file or directory: '././data/docker-compose-config.yml'

My docker version is :
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:28:06 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:38 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Do you have any idea about this? Thank you!

**Comment by nyurik** [comment]
`docker-compose-config.yml` is a file that gets downloaded as part of `geofabrik download`. Your data dir might be corrupted - try cleaning up all the non-git dirs.

**Comment by limh821** [comment]
> `docker-compose-config.yml` is a file that gets created as part of `geofabrik download`. Your data dir might be corrupted - try cleaning up all the non-git dirs.

Yes. In fact, I got the following error at first:


  INFO[0070] /import/geofabrik.yml generated.
 DEBUG[0000] Downloading https://download.geofabrik.de/europe/albania-updates/state.txt to /import/albania.state
  INFO[0001] /import/albania.state downloaded.
 DEBUG[0001] 113 bytes downloaded.    
 DEBUG[0000] Downloading https://download.geofabrik.de/europe/albania-latest.osm.pbf to /import/albania.osm.pbf
 FATAL[1988] can't download element    error=error while writing /import/albania.osm.pbf - unexpected EOF
Makefile:89: recipe for target 'download-geofabrik' failed
make: *** [download-geofabrik] Error 1


For some unknown reasons the downloading of albania-latest.osm.pbf was interrupted when it was 90% finished (40.6MB has been downloaded while the full file is 41.6MB. I tried twice but didn't succeed). Then I went to https://download.geofabrik.de/europe/albania-latest.osm.pbf to download the albania-latest.osm.pbf file manually and placed it in the openmaptiles/data/ directory and re-ran the "./quickstart.sh". Then I found myself stuck in the ".FileNotFoundError: [Errno 2] No such file or directory: '././data/docker-compose-config.yml' " error.

PS: The "make import-wikidata" command in the quickstart.sh was commented to avoid the possible "requests.exceptions.ConnectionError" error.

**Comment by nyurik** [comment]
@limh821 that file gets auto-created for you based on the downloaded data, and usually looks something like this:

```yaml
version: "2"
services:
  generate-vectortiles:
    environment:
      BBOX: " 12.2403364, 35.8223957, 23.3262014, 45.8046357"
      OSM_MAX_TIMESTAMP : "2020-02-18T21:58:05Z"
      OSM_AREA_NAME: "albania"
      MIN_ZOOM: "0"
      MAX_ZOOM: "7"
```

In the next version of the tools I plan to switch to the `download-osm` tool rather than use geofabrik downloader. That tool should improve the download experience because it uses `aria2c` - a well known downloader.

**Comment by limh821** [comment]
> ```yaml
> version: "2"
> services:
>   generate-vectortiles:
>     environment:
>       BBOX: " 12.2403364, 35.8223957, 23.3262014, 45.8046357"
>       OSM_MAX_TIMESTAMP : "2020-02-18T21:58:05Z"
>       OSM_AREA_NAME: "albania"
>       MIN_ZOOM: "0"
>       MAX_ZOOM: "7"
> 

Thank you @nyurik ! I used your docker-compose-config.yml and now I can generate the .mbtiles successfully! I'm glad to hear that the geofabrik downloader would be replaced by a new one. 

It would be appreciated if the quickstart.sh and Makefile be modified to allow generation of the docker-compose-config.yml as well as the osmstat.txt and other files in the data directory for the manually downloaded .osm.pbf file by users in that directory (now the generation is triggered only by automatically successful download).

Thank you again for your prompt reply! Much obliged!

**Comment by nyurik** [comment]
@limh821 if you use the latest tools, you can generate that file already by hand.

```
docker-compose run --rm openmaptiles-tools-latest  download-osm make-dc data/albania-latest.osm.pbf -d data/result.yml
```

You can add `-u $(id -u "$USER"):$(id -g "$USER")` right after `--rm` to make the file have the same rights as your current user.

See full docs by running 

```
docker-compose run --rm openmaptiles-tools-latest  download-osm --help
```

**Comment by nyurik** [comment]
P.S. make sure to do `docker pull openmaptiles/openmaptiles-tools` first to get the latest

**Comment by TomPohys** [comment]
For summary: 
**Reported errors**
1. a user proxy cause problem with downloading wikidata and pbf file from geofabrik
2. nonexistence of `/data/docker-compose-config.yml` file cause an error during generating tiles
---
**Solutions**
1. error was not caused by a bug in OpenMapTiles project
2. now this file is optional. Data for generating tiles is gathered from `docker-compose-config.yml` or from `.env` file

Thanks @nyurik and @limh821 for discussion!
