### ISSUE TITLE
Review at which zoom levels which Roads appear

### ISSUE THREAD

**Issue by lukasmartinelli** [openmaptiles/openmaptiles#79]
We are quite conservative with showing roads early right now (first step in showing more was #41).
But it makes sense to look over this more in detail (and keep tile size in mind!!!). This can be done in a later step - it looks good enough now.

Compare the implementation now with the Mapnik styles mentioned in #47 (it is fine to show less imho).

![image](https://cloud.githubusercontent.com/assets/1288339/20790740/0ee68f44-b7ba-11e6-94ea-0250f4ca9aa2.png)

**Comment by ianthetechie** [comment]
Another issue to note is roads which are marked as ramps. These are quite prominent in the industrial northern US cities. I've attached a few examples of where there are some rather wide gaps in the road.

![screen shot 2017-01-23 at 22 39 02](https://cloud.githubusercontent.com/assets/2140440/22233383/087fe1fe-e1be-11e6-9389-46d574f2c107.png)
![screen shot 2017-01-23 at 22 45 33](https://cloud.githubusercontent.com/assets/2140440/22233386/0d383430-e1be-11e6-8b71-014d1b4a5e39.png)

**Comment by jirik** [comment]
Created standalone issuee for missing ramps: https://github.com/openmaptiles/openmaptiles/issues/250
