### ISSUE TITLE
Migrate from Travis to GitHub Actions

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#790]
We are keen to have more automated quality checks - with the new OpenMapTiles Tools - comparing the size and speed of the modifications introduced in Pull Requests.

GitHub Actions should provide more flexibility to store the result of previous runs, and the ability to post comments back to the PRs.

In this ticket we should do a first step towards the goal - just migrate the basic calls and test validation.

**Comment by klokan** [comment]
If migration is done - we should remove the Travis button - and replace it with GitHub Actions button - in the main README.MD perhaps?

**Comment by klokan** [comment]
Are pull requests now checked with GitHub Actions? I still see Travis only - or will it happen only on new pull requests?

**Comment by TomPohys** [comment]
I will change README.MD

The first check by GitHub Actions was https://github.com/openmaptiles/openmaptiles/pull/802. Any future push (commit or PR) into the master branch will be tested by GitHub Actions.
