### ISSUE TITLE
Extend GitHub Actions to test size and generating performance for PRs.

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles#813]
GitHub Actions should not only run through `quickstart` but also test the size and performance of new PRs.

**Comment by nyurik** [comment]
We need to pick the target areas which we will test on.  Looking at the latest Geofabrik extracts, these are the smallest ones.  Which should we use?  We can [combine](https://gis.stackexchange.com/questions/242704/merging-osm-pbf-files) several into a single file.

area | size
-- | --
europe/monaco | 392,742
africa/saint-helena-ascension-and-tristan-da-cunha | 404,608
africa/sao-tome-and-principe | 737,850
europe/great-britain/england/rutland | 1,245,960
europe/andorra | 1,664,842
africa/equatorial-guinea | 2,184,657
europe/liechtenstein | 2,344,565
europe/isle-of-man | 2,393,136
africa/seychelles | 2,396,110
europe/great-britain/england/london/enfield | 2,509,057
africa/comores | 3,023,615
asia/maldives | 3,085,039
europe/faroe-islands | 3,390,201
europe/france/mayotte | 4,314,030
europe/malta | 4,630,071
africa/mauritius | 5,438,263
central-america/belize | 5,689,304
europe/great-britain/england/bedfordshire | 6,801,084
europe/great-britain/england/herefordshire | 6,813,186
europe/great-britain/england/isle-of-wight | 6,862,216
africa/djibouti | 7,112,533
asia/bhutan | 7,381,412
africa/eritrea | 7,525,215
africa/guinea-bissau | 7,526,716
africa/cape-verde | 7,762,585
africa/gabon | 8,025,899
australia-oceania/fiji | 9,541,916
central-america/jamaica | 9,812,405

**Comment by klokan** [comment]
Liechtenstein used to be our smallest test area in the past, Zurich our second, Switzerland and Czech Republic as third - US New York and San Francisco.

We need ideally a data-rich region with different tags - on different parts of the planet.

**Comment by nyurik** [comment]
@klokan thx, I can easily merge multiple regions into a standard "test" dataset, which I will upload to the data store you've set up.  We should also include some low-density area to evaluate near-empty tile generation speed.

**Comment by nyurik** [comment]
@klokan thx, I can easily merge multiple regions into a standard "test" dataset, which I will upload to the data store you've set up.  We should also include some low-density area to evaluate near-empty tile generation speed.

**Comment by TomPohys** [comment]
What I see from the first results from GitHub Actions: for PR https://github.com/openmaptiles/openmaptiles/pull/835 and https://github.com/openmaptiles/openmaptiles/pull/765 there are fluctuations during generating each zoom levels even when there is no change in PR (see edits of GH Actions comment). 

Until z10 the generation took less than 1s. So even very small time change made a significant change in percentage.

**Comment by TomPohys** [comment]
The speed of importing and generating tiles is too much depend on Virtual Machine performance. Even for update readme can test show changes between 5 - 10 %. And it causes just performance fluctuations. Hence, on real hardware should run a test for speed and time. 

https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by klokan** [comment]
We can organize a true dedicated machine...

I guess it does not have to be a super-strong machine, as long as it is dedicated hardware.
SSD is nice-to-have - but not required, right? We may upgrade to SSD later on.

Intel  i5-2300 | 4c/4t | 2,8GHz | 16Go DDR3 1333 MHz | HDD 2To | 100 Mbps.
Fine?

**Comment by TomPohys** [comment]
Of course, any dedicated hardware will be fine. Github actions now runs on 2 core and 4GB of RAM.

**Comment by nyurik** [comment]
Should we close this ticket and maybe open a new one to use real hardware for testing?
