### ISSUE TITLE
Dicussion: Makefile support for multiple data/*.pbf files

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#820]
This discussion is about the way `Makefile` is expected to handle a potential situation of multiple `data/*.pbf` files.

The discussion is a spin-off of [this discussion](https://github.com/openmaptiles/openmaptiles/pull/812#pullrequestreview-395977085).
_Note: this is irrelevant for `quickstart.sh` that prevents this condition._

#### Problem Description
`make download-*` allows multiple `data/*.pbf` files to be created.
`make import-osm` [imports the first `data/*.pbf` file found](https://github.com/openmaptiles/openmaptiles-tools/blob/55dd0b4622d8a18b86d74900a8fd0f5c2e7b324b/docker/import-osm/import_osm.sh#L41-L55). 

As a result, the following sequence will import the **albania** data rather than **zambia**, unlike the expectations of an ordinary user. 

```
make download-geofabrik area=albania
# ...
make download-geofabrik area=zambia
# ...
make import-osm
```

#### Discussion framework
I suggest the discussion will be done in two phases:
1. Discuss the user-flows that use `make download-*` and `make import-osm` with multiple `data/*.pbf` files.
2. Explore the possible ways to consolidate
   - The expectations of users of the above flows 
   - The expectations of ordinary users of the Makefile
   - The desire to maintain backward-compatibility

@nyurik, can you start the discussion on the user-flows, as [you proposed here](https://github.com/openmaptiles/openmaptiles/pull/812#discussion_r412316627)?

**Comment by nyurik** [comment]
My perspective on this is that we should limit downloads if possible, so ideally we should move towards the situation where this sequence would only download two files:

```
./quickstart albania

**Comment by nyurik** [comment]
I added the implementation of this as part of the #855 -- allows `make import-data PBF_FILE=...`. This way one could want to download multiple files using `make download-geofabrik ...`, and use different `import-data` without redownloading

**Comment by TomPohys** [comment]
Thank @nyurik for PR and @zstadler for discussion.
