### ISSUE TITLE
Enable `Require status checks to pass before merging` for master

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#829]
Admins, please add `master` protection rule to https://github.com/openmaptiles/openmaptiles/settings/branches :+1: 

## *  click "add new rule"

![image](https://user-images.githubusercontent.com/1641515/80244554-1b71fd80-8637-11ea-944d-cbb70e553360.png)

## Set parameters:
* set `master` as branch
* Enable `Require status checks to pass before merging`
* Enable `Require branches to be up to date before merging`
* Set checkbox next to `Evaluate performance`

Please don't enable any other rules just yet.  Thanks!

![image](https://user-images.githubusercontent.com/1641515/80244371-cfbf5400-8636-11ea-89f3-69c8689a2246.png)

**Comment by klokan** [comment]
Done - thanks!
