### ISSUE TITLE
boundary lines

### ISSUE THREAD

**Issue by pnorman** [openmaptiles/openmaptiles#83]
My suggestions for a schema are

Description: Administrative boundaries as linestrings, with maritime boundaries excluded.
Type: Lines only
Fields
`admin_level` (Number): Lowest admin_level the line participates in. admin_level values equivalent to OSM.
`disputed` (Boolean): If the boundary is disputed

Contents:
admin_level <= 2 data starts at z2  
admin_level <= 4 data starts at z4  
admin_level <= 6 data starts at z7  
admin_level <= 8 data starts at z10  
admin_level > 8 data starts at z14

**Comment by lukasmartinelli** [comment]
Thanks Paul for the osmborder project!! Really helped a lot.
