### ISSUE TITLE
Make "squash" the only available merge option

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#830]
Please make "squash" the only available merge option in https://github.com/openmaptiles/openmaptiles/settings#merge-button-settings and https://github.com/openmaptiles/openmaptiles-tools/settings#merge-button-settings This makes commit history much cleaner, making it far easier to figure out what commit/PR has caused an issue.

![image](https://user-images.githubusercontent.com/1641515/80249069-2c267180-863f-11ea-9a1f-1953bd001daa.png)

When we use other methods, it creates a very hard-to-follow history, making it much less useful:

![image](https://user-images.githubusercontent.com/1641515/80249365-b242b800-863f-11ea-8c73-f759dc579497.png)

**Comment by klokan** [comment]
Yep. Fixed.

Spotted on #828 after "Merge" button ;-). Going to run better. 👍

**Comment by nyurik** [comment]
@klokan please also do this for the tools repo -- https://github.com/openmaptiles/openmaptiles-tools/settings#merge-button-settings

**Comment by klokan** [comment]
Done
