### ISSUE TITLE
Incorrect behavior in an attempt to process custom *.osm.pbf 

### ISSUE THREAD

**Issue by Andygol** [openmaptiles/openmaptiles#844]
https://github.com/openmaptiles/openmaptiles/blob/5445a70c300ae82ee286e4561800b6febacce819/quickstart.sh#L30

This line ^ cause an issue when you try to process custom data according to https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md#using-your-own-osm-data

```mv my.osm.pbf data/
./quickstart.sh my
```

Run of the command ^ points to an unexisted `my-latest.osm.pbf` file.

**Comment by Andygol** [comment]
ref #843

**Comment by nyurik** [comment]
I agree that we should have a better way to define custom data, or moreover, we should probably rework the quickstart / download / provide your own data pipeline.

To make it happen, we need to solve a few things:
* downloading by "name" -- we should allow pattern `[<service>] <area>`, with the meaning that if `service` is not set, it is assumed to be `GeoFabrik`.  Service could be `url` (in which case <area> would be a url to download from), or it could be other services like `bbbike`.
* downloaded file should automatically be renamed to strip `-latest`

**Comment by Andygol** [comment]
@nyurik could you move this convo to #843 and close this one. I've not spotted that the same issue had been already reported.

**Comment by nyurik** [comment]
Closing as a dup of #843
