### ISSUE TITLE
[landuse] class=yes  -  imposm3 mapping 

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#86]
Testing the layers  with the current master   +   ` ./quickstart.sh  switzerland `

I have detected a strange :  ˙class=yes` 

imho : it would be better to use the `mapping_value` mapping in the imposm3 mappings.
```
    - name: class
      type: mapping_value
```

## the FREQ stat  landuse z14  ( Switzerland )
|       class       | _count_ |
|-------------------|---------|
| cemetery          |    1775 |
| college           |     167 |
| commercial        |     930 |
| forest            |       1 |
| grass             |       1 |
| hospital          |     294 |
| industrial        |    2810 |
| kindergarten      |     797 |
| library           |     111 |
| military          |     301 |
| parking           |       1 |
| railway           |     703 |
| recreation_ground |       1 |
| residential       |   14108 |
| retail            |     258 |
| school            |    4141 |
| sports            |       1 |
| stadium           |     161 |
| theatre           |       1 |
| university        |     328 |
| yes               |       1 |

**Comment by MartinMikita** [comment]
Not relevant anymore, class is not mapped directly.
