### ISSUE TITLE
OpenMapTiles Server is designed to work with data downloaded from OpenMapTiles.com

### ISSUE THREAD

**Issue by markuman** [openmaptiles/openmaptiles#863]
So, I'm rendering my own mbtiles and if I want to serve it via `klokantech/openmaptiles-server` I got a error message

> OpenMapTiles Server is designed to work with data downloaded from OpenMapTiles.com, the following files are unknown and will not be used: planet.mbtiles

So I figure out that my mbtiles file is just missing an `omtm` table. When I add it, my mbtiles file is accepted.

So my question: is this the right way to serve my tiles? The watermark is still present, so credits still goes to you.

**Comment by markuman** [comment]
Ok, it looks like https://github.com/maptiler/tileserver-gl is the starting point for that.

**Comment by daliborjanak** [comment]
Yes, there are more ways how to serve tiles. All solutions (by language) are described in https://openmaptiles.org/docs/
