### ISSUE TITLE
[waterway] 'name_en' is missing , but has a 'name' field 

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#88]
From a bird view -  
*  Usually  if has a 'name'  -  it should be also a 'name_en' field 

Only exception the 'waterway' layer  :  https://github.com/openmaptiles/openmaptiles/wiki/waterway

**Comment by lukasmartinelli** [comment]
Well I also leave out the `name_en` in the `poi` and `transportation_name` layer right now.
IMHO `name_en` is most important for the places. Everywhere else it is nice to have but not really necessary.

**Comment by klokan** [comment]
I am in favour to have both whenever reasonable.
The increase on the size of the vector tiles is not significant - if both contain the same data.

Are there any numbers. What for example POIs / transportation in china or Japan, where western people usually can't read the local names. I expect important POIs are often bilingual in OSM in such cases...

**Comment by lukasmartinelli** [comment]
> Are there any numbers. What for example POIs / transportation in china or Japan, where western people usually can't read the local names. I expect important POIs are often bilingual in OSM in such cases...

From what I know is that POIs are not so well translated as places - what works is pulling translations from Wikipedia for POIs.

But it is cheap to add the extra fields - so why not do it in the end. At least for `name_en`. But I don't think once there are more languages than English a waterway should have all the fields for all the languages - that's really only important for places.

**Comment by lukasmartinelli** [comment]
> But it is cheap to add the extra fields - so why not do it in the end. At least for name_en. But I don't think once there are more languages than English a waterway should have all the fields for all the languages - that's really only important for places.

Actually I see that I already included `name:en` in the mapping to be future proof :)
So just the SQL queries must be changed - nothing else.
