### ISSUE TITLE
Where to add landuse=quarry ?

### ISSUE THREAD

**Issue by jpbede** [openmaptiles/openmaptiles#890]
I would like to add the tag `landuse=quarry` but for me it isn't clear where to add it.

In which layer should it be added, landcover or landuse ?
What is the exactly difference between these layers ?

May you can explain a bit more, what to add in landcover and what in landuse.

**Comment by TomPohys** [comment]
Hi @jpbede, the landcover is defined as [the physical material at the surface of the earth](https://openmaptiles.org/schema/#landcover) and landuse as [use of land by humans](https://openmaptiles.org/schema/#landuse). So quarry is landuse same as stadium, pitch or zoo.

Does it help?

**Comment by jpbede** [comment]
Thanks. It is a bit clear now.
