### ISSUE TITLE
Release 3.12

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles#900]
[Milestone 3.12](https://github.com/openmaptiles/openmaptiles/milestone/16)

We are planning to release a new version of OpenMapTiles before summer. So we need to start working on merging last thoughts and test it on planet rendering. ~~It looks there can be a feature freeze on the 7th of June.~~ 

The issues in [milestone 3.12](https://github.com/openmaptiles/openmaptiles/milestone/16) have to be solved before the feature freeze and **any help is very welcome**.

If anyone has some unfinished work or thoughts and would like to have it as part of 3.12 release, please finish it as soon as possible.  

Thank you all for your contributions to the OpenMapTiles project.

Feature freeze will be set up after solved all issues in [milestone 3.12](https://github.com/openmaptiles/openmaptiles/milestone/16). 

particularly @nyurik, @frodrigo, @zstadler

**Comment by nyurik** [comment]
I think #903 and #814 should be merged if @TomPohys could check it works on his set up.  Thx!

**Comment by nyurik** [comment]
P.S. I will try to resolve #904 as well today or tomorrow, so would be awesome to merge that too :)

**Comment by TomPohys** [comment]
Release v3.12 is out (https://github.com/openmaptiles/openmaptiles/releases/tag/v3.12). Thank you all!
