### ISSUE TITLE
'import-borders' failed when i use data from osmfr

### ISSUE THREAD

**Issue by toinouu** [openmaptiles/openmaptiles#901]
Hello,

I imported data from geofabrik "europe/malta" with this command

`
make import-osm
make import-borders
make import-sql
make import-wikidata
`

Everything works correctly,  import does not return any error and my map is displayed correctly

But when I try to import data from osmfr (openstreetmap.fr) I got an error when ordering import-border.

`docker-compose run --rm -u 1000:1000 openmaptiles-tools sh -c 'pgwait && import-borders'
Skipping broken references cleanup because BORDERS_CLEANUP is not set to 'true'
Enable borders cleanup if you see 'location for one or more nodes not found in node location index' error
Filtering /import/brussels_capital_region-latest.osm.pbf into /import/borders/filtered.pbf
Creating a CSV borders file /import/borders/lines.csv
terminate called after throwing an instance of 'osmium::not_found'
  what():  location for one or more nodes not found in node location index
/usr/src/app/import-borders: line 91:    37 Aborted                 (core dumped) osmborder -o "$BORDERS_CSV_FILE" "$BORDERS_PBF_FILE"
Makefile:192: recipe for target 'import-borders' failed
make: *** [import-borders] Error 134
`

I think problem come from the source but in the documentation it says that we can use omsfr (make download-osmfr)

Thanks for the help

**Comment by nyurik** [comment]
@toinouu make sure to use `BORDERS_CLEANUP=true` in your `.env` file
