### ISSUE TITLE
Improve Makefile handling of area/planet

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#904]
There is currently a lot of assumptions that are made throughout the OMT and OMT-tools about the download/import/update pipeline, thus generating a number of issues/complaints from the community.  I would like to streamline this process a bit.

The main change I believe we need is to make `area` the key parameter in the Makefile, where `area` could be `planet` or any specific area offered by Geofabrik, BBBike, and OSM.FR.

* Make `area` required for many `make` commands such as `download-*`, `import-osm`, `import-borders`, and `generate-tiles`.  This way users will be able to have multiple downloaded areas at the same time.
* Makefile will always check if `area` parameter is set, and if not, it will check `./data/*.osm.pbf` files. If there is a **single** matching file, the file name (without the `.osm.pbf`) will become the `area` param.
* `download-*` targets will always save downloaded files as `./data/$(area).osm.pbf` file.
* Add a new `download` target that will pass `$(area)` as is to `download-osm`, letting `download-osm` choose where to get the data.
* `import-osm` and `import-borders` targets will always process `./data/$(area).osm.pbf` file.
* `generate-tiles` will always generate `./data/$(area).mbtiles` file (if the file already exists, it will always delete it first)

Related:   #895 #843 #844 #820 openmaptiles/openmaptiles-tools#288 openmaptiles/openmaptiles-tools#286 openmaptiles/openmaptiles-tools#246 

cc: @zstadler @frodrigo @TomPohys @MartinMikita @markuman @AdamGolota @andygol

**Comment by zstadler** [comment]
The solution sounds good to me.

> - Add a new `download` target that will pass `$(area)` as is to `download-osm`, letting `download-osm` choose where to get the data.

@nyurik, is `download-osm` is a new Makefile target name or an execution of `download-osm` in an `openmaptiles-tools` container?

**Comment by nyurik** [comment]
> @nyurik, is `download-osm` is a new Makefile target name or an execution of `download-osm` in an `openmaptiles-tools` container?

@zstadler `download` would be a new make target, e.g. `make download area=paris`
