### ISSUE TITLE
Wrong maximum zoom level when creating from quickstart.sh

### ISSUE THREAD

**Issue by saberraz** [openmaptiles/openmaptiles#909]
I have created a tileset from quickstart.sh. In my yaml, the max zoom level is set to 7 but the resultant tileset has the max zoom level of 14.

This is causing problem for displaying in QGIS: https://github.com/qgis/QGIS/issues/36862

**Comment by TomPohys** [comment]
Hi @saberraz, the min, max zoom for metadata of mbtiles was taken from `openmaptiles.yaml`. From OMT 5.2 is used `mbtiles-tools meta-generate` and min, max zoom is taken from `data/docker-compose-config.yml`

**Comment by yetzt** [comment]
you can retroactively edit the metadata table in the mbtiles file with sqlite.

**Comment by saberraz** [comment]
I suspect it was some left overs in my configuration file. Happy to close this issue.
