### ISSUE TITLE
Border artifacts and misclassification

### ISSUE THREAD

**Issue by yetzt** [openmaptiles/openmaptiles#914]
Using [planet-200525.osm.pbf](https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/planet-200525.osm.pbf) i get without altering anything some strange artifacts like a country level land border in the middle of the ocean or a regional level land border at the coast.

![maritime land borders](https://imgur.com/6Ae6NOG.png)

What can i do about it?

**Comment by yetzt** [comment]
i found the offentding osm ids, `766404249` and `775175432` — how can i set the maritime property to true for them easily?

**Comment by eva-j** [comment]
Hi @yetzt, `maritime` needs to be set in OpenStreetMap, it looks like for the two osm ids it is already done.
