### ISSUE TITLE
Schema: Add property for private or otherwise inaccessible roads

### ISSUE THREAD

**Issue by westnordost** [openmaptiles/openmaptiles#925]
There is no property on roads to mark them as private or otherwise inaccessible roads in the current schema.

This information is quite important for anyone using the map to navigate.

([First posted here](https://support.maptiler.com/i746-vector-tile-schema-roads-with-access-restrictions-private-roads))

**Comment by TomPohys** [comment]
similar discussion in #1066

**Comment by Falke-Design** [comment]
@TomPohys @ZeLonewolf is this fixed with #1174?

**Comment by ZeLonewolf** [comment]
@Falke-Design yes, I believe this issue can be closed as fixed.

**Comment by westnordost** [comment]
👍
