### ISSUE TITLE
Generating vector tiles for Great-Britain zoom level 22 takes 5000 days

### ISSUE THREAD

**Issue by dav101** [openmaptiles/openmaptiles#933]
Issue
It says it will take 5000 days to generate vector tile maps for great-britain at zoom level 22.

Process:
I am following from a [guide on quickstart](https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md)

1. Cloned repo from https://github.com/openmaptiles/openmaptiles.git
2. Installed docker.io docker-compose
3. Setup default vector tile generation for albania (worked) with `./quickstart` 
4. View on localhost albania maps (worked) with  `./make start-tileserver`
5. Change maps to great britain maps with .`/quickstart great-britain`
6. Change from default zoom level 7 to 22 (worked) editing docker-compose file max zoom
7. Start map generation on zoom level 22 for great-britain with `./quickstart great-britain`

It says will take 5000 days with current setup even after 2 weeks of map generating
<img width="550" alt="mapgeneration" src="https://user-images.githubusercontent.com/10588751/84529635-b0a97e00-acd9-11ea-9c67-a02b6b7db451.PNG">

Spec:
Set on a ubuntu server 18.04.4 LTS
Storage: 500TB on rust disk
RAM: 64GB
CPUS: 16

Questions:
1. How can i reduce the current 5000 days to generate zoom level 22 for great-britain maps?
1. What hardware is more appropriate to setup?
1. What are other developers doing to generate maps for great-britain or world? 
1. How are other developers reducing map generation timescales?

**Comment by nyurik** [comment]
Maps are usually generated to z14. Why do you need z22?

**Comment by lukasmartinelli** [comment]
I've rarely ever seen z22 tiles that need that kind of precision. As Yury said, z16 is usually lossless for 10cm map data.

**Comment by MartinMikita** [comment]
Hi @dav101 

You do not need vector tiles beyond z14, especially not for OpenMapTiles, which has nothing more or precise beyond z14.

This is actually right answer. You can reduce the generation time by introducing multiple computers and split the generation job into smaller tasks.

This is related to other relevant topics for the generation the world - #242 #299 #669
