### ISSUE TITLE
cannot drop table backup.osm_highway_linestring because other objects depend on it 

### ISSUE THREAD

**Issue by erictheise** [openmaptiles/openmaptiles#935]
It's been a while since I've worked with `openmaptiles`.

Fresh install, following the steps in `README.md`, using `area=california`. Few hours invested in `make import-osm` and I have no idea what state my installation is in after this:

```
[Jun 16 02:20:13] [INFO] [PostGIS] Rotating tables took: 160.408597ms
[Jun 16 02:20:13] SQL Error: pq: cannot drop table backup.osm_highway_linestring because other objects depend on it in query SELECT DropGeometryTable('backup', 'osm_highway_linestring');
make: *** [import-osm] Error 1
```

**Comment by TomPohys** [comment]
Hi @erictheise, did you figure out where was problem?

**Comment by erictheise** [comment]
Hi @TomPohys, not really. I spent another few hours working on it, encountering different transient errors, and finally I got a run to complete. Found out I needed a larger extract, hopefully it'll run overnight without error. Thanks for asking.

**Comment by kender1314** [comment]
I have the same problem

**Comment by kender1314** [comment]
How did you solve it @erictheise

**Comment by erictheise** [comment]
To be honest, @kender1314, I'm not even sure I remember what I was working on back in June. It's quite possible I was working on map styles and, in the interest of time, I abandoned the import and just downloaded [their 2017 planet.mbtiles files](https://openmaptiles.com/downloads/tileset/osm/?usage=personal). Sorry I can't be of more help.

**Comment by tjiho** [comment]
I had this issue, I solved it by cleaning docker and images:
```
make destroy-db
make stop-db
make clean-unnecessary-docker
make remove-docker-images
make refresh-docker-images
```

**Comment by PhanTask** [comment]
> I had this issue, I solved it by cleaning database and docker images:
> 
> ```
> make destroy-db
> make stop-db
> make clean-unnecessary-docker
> make remove-docker-images
> make refresh-docker-images
> ```

You saved my life bro
