### ISSUE TITLE
Improve docs for iso_a2 (place layer)

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/openmaptiles#939]
https://openmaptiles.org/schema/#place

It would be good to explicitly mention for which features  `iso_a2` is available (e.g. `class=country`) to avoid that people could think that  `iso_a2` is available for all features in the place layer.

Related SE post: https://gis.stackexchange.com/questions/365651/maputnik-iso-a2-filter
Related issue: https://github.com/openmaptiles/openmaptiles/issues/306

**Comment by TomPohys** [comment]
Thanks @pathmapper. PR created.
