### ISSUE TITLE
Introduce an `aerialway` class for the `transportation` layer

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#940]
Line 39 in this code

https://github.com/openmaptiles/openmaptiles/blob/c86f4a557a489c7e79ad2aec98051c066ccf7ad7/layers/transportation/layer.sql#L35-L42

suggests that all `aerialway` elements in the transportation layer will be mapped to the `aerialway ` class. This is not the case and I cannot find out why.

For example, [Val Veny](https://www.openstreetmap.org/way/95749074#map=15/45.8098/6.9560) is tagged with `aerialway=cable_car`. Inspecting the Maptiler tiles using Maputnik shows that the element is mapped to the `cable_car` class rather than the `aerialway` class. It is also missing a `subclass` field, as would be expected if the `aerialway` class was used.

![image](https://user-images.githubusercontent.com/1304610/85420314-b4f85580-b57b-11ea-8296-c9d6313e8f3c.png)

To reproduce:
- Open Maputnik [at this location](https://maputnik.github.io/editor/#15.01/45.80985/6.95387).
- Select "Open" -> "Gallery Styles" -> "OSM Liberty".
- Select "View" -> "Inspect".
- Move the mouse over the cable car's line, as in the above screenshot.

**Comment by zstadler** [comment]
I now realize that the class is the value of the `aerialway` tag, not the string "aerialway"...

I wish a complex layer like `transportation` would have greater use of the `subclass` field, not only for `railway` and `path` classes.
For example, have literal `aerialway` class will allow easier extension of the `aerialway` class to include additional subclasses, such as `chair_lift`, `drag_lift`, and `goods` while allowing simpler style filter that does not require enumerating all possible  `aerialway` tag values.

**Comment by sdaratha** [comment]
We need this aerialway, too.
The way to produce an own mbtiles-file is to big to be done by ourself.
But we want to show skiroutes, lifts and so on, too.

**Comment by zstadler** [comment]
@TomPohys, @eva-j 

I'd like to clarify this issue because this is a **schema change request** that applys OMT's `class`/`subclass` classification to `aerialway` . Please tag it as such.

The proposed change is this:
| `aerialway` value | Current `class` | Proposed `class` | Current `subclass` | Proposed `subclass` |
|---|---|---|---|---|
|  `cable_car` |  `cable_car` | `aerialway` | _not set_ |  `cable_car` |
|  `gondola` |  `gondola` | `aerialway` | _not set_ |  `gondola` |
