### ISSUE TITLE
recipe for target 'update-osm' failed

### ISSUE THREAD

**Issue by RS974** [openmaptiles/openmaptiles#943]
I just ran a new installation test (newly-installed server).

```
git clone https://github.com/openmaptiles/openmaptiles.git
cd openmaptiles
make
./quickstart.sh
```

Installation is successfully completed.
I encountered an error with update-osm.

```
make update-osm
```

Starting postgres docker compose target using default image (no recreate if exists)
Starting openmaptiles_postgres_1 ... done
Detected area=albania based on the found data/ pbf file. Use 'area' parameter (or env var) to override.
docker-compose run --rm -u 0:0 openmaptiles-tools sh -c 'pgwait && import-update'
2020/06/26 11:56:25 config.go:290: open data/albania.repl.json: no such file or directory
Makefile:336: recipe for target 'update-osm' failed
make: *** [update-osm] Error 1

I'm confirming that the data/last.state.txt file is missing #942

**Comment by TomPohys** [comment]
Hi @RS974, when you set `DIFF_MODE=true` in `.env` file and run `make download area=albania`, then it will download also `last.state.txt` file for this area (after #1010 is merged)

**Comment by frodrigo** [comment]
Note: the `DIFF_MODE=true` must be set before the initial import.

**Comment by RS974** [comment]
Hi

I formatted my server, I have no more data.
But I left DIFF_MODE=false during the initial import.

I was hoping for the release  v3.12 to resume my tests.

Thank you for your feedback, I will do a test as soon as possible.

**Comment by TomPohys** [comment]
Hi @RS974, work on [release 3.12](https://github.com/openmaptiles/openmaptiles/milestone/16) is in progress (https://github.com/openmaptiles/openmaptiles/issues/900). Thanks
