### ISSUE TITLE
How to update mbtiles for multi zoom level

### ISSUE THREAD

**Issue by thangdc94** [openmaptiles/openmaptiles#946]
I followed instructions in [UPDATE.md](https://github.com/openmaptiles/openmaptiles/blob/master/UPDATE.md) 

`make import-diff` only generate lists of tiles for 1 zoom level (default is 14)
So when I run `docker-compose run generate-changed-vectortiles`, it updated only for zoom 14

I want all zoom to be updated (`MIN_ZOOM` to `MAX_ZOOM` in `.env`). How can I do this?

I tried run `import-diff` with difference `EXPIRETILES_ZOOM` but seems like there are some problems when I do that.
- duplicate import diff process while I only need lists of changed tiles
- delete seems not work for  zoom level because I already deleted it in previous run.

I added the following target in make file:
```
.PHONY: import-diff-all
import-diff-all: all start-db-nowait
        for i in `seq 6 18`; do \
        echo "Generate tile change for zoom=$$i"; \
        $(DOCKER_COMPOSE) run $(DC_OPTS) -e EXPIRETILES_ZOOM=$$i openmaptiles-tools sh -c 'pgwait && import-diff'; \
        done;
```

**Comment by thangdc94** [comment]
I think it's ` imposm3` issue. `imosm3` only generate Expire tiles for specific zoom level. There is no range option.

**Comment by frodrigo** [comment]
You approach is not efficient at all.

I write this script to that: https://github.com/makinacorpus/makina-maps/blob/master/nginx/tile_multiplier.py

**Comment by thangdc94** [comment]
@frodrigo Thank you for your script. So I should generate tile list  for the max zoom level and use your script to generate tile list lower zoom levels?

**Comment by frodrigo** [comment]
Yes, It is the idea. But you can choose the zoom level reported by imposm, the script scale up and down the tiles coords.

**Comment by thangdc94** [comment]
I think max we will get best performance if we input the max zoom level. 
After looking at your map project, I also think your map is a good starting point. Thank you :D

**Comment by zstadler** [comment]
Thanks @thangdc94 for the observation and thanks @frodrigo for the solution!
See https://github.com/makina-maps/makina-maps/pull/24 for a proposed improvement.

IMHO, the mechanism in [tile_multiplier.py](https://github.com/makinacorpus/makina-maps/blob/master/nginx/tile_multiplier.py) should be integrated into the underlying [openmaptiles-tools' import-diff](https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/import-diff) with the `MIN_ZOOM` and `MAX_ZOOM` environment variables.

**Comment by frodrigo** [comment]
Since only one zoom level is extracted on the update, there is lot of wasted computation time for update all zoom levels on the database.

Implementing it in imposm should be the best way. Note the project if on light maintenance.

**Comment by zstadler** [comment]
`imposm` updates the DB. It has no knowledge of which zoom levels will be extracted from it, cached, or stored in any other means. This is probably why `imposm` has chosen to provide the minimal information about "expired tiles" so that the owners of each `imposm`-based flow will use this information on a case-by-case basis.

Considering this and the imposm maintenance level, it will be more practical to make it part of the OpenMapTiles flow.
