### ISSUE TITLE
Use better `id` in the generated mbtiles

### ISSUE THREAD

**Issue by petrsloup** [openmaptiles/openmaptiles#95]
Now the mbtiles files contains `id|tmsource:///tmp/project` in the `metadata` table, it would be much better to have the name of the tileset yaml there (e.g. `id|openmaptiles`). Adding `bounds` would also be very useful.

**Comment by ImreSamu** [comment]
As I know ~ now ~ so much better ( 'id','bounds', .... )

The current metadata status implementation :
* openmaptiles-tools  -  `generate-metadata`  ( used for ./quickstart.sh )
   *  https://github.com/openmaptiles//blob/master/bin/generate-metadata#L67
* openmaptiles/extracts   - `create_extracts.py`  ( used for extracts )
   *  https://github.com/openmaptiles/extracts/blob/master/create_extracts.py#L68

**Comment by jirik** [comment]
@petrsloup Can we close this issue?
