### ISSUE TITLE
Proxy pass to a subdirectory of a URL

### ISSUE THREAD

**Issue by 4nuragk** [openmaptiles/openmaptiles#959]
I'm running the omt server in Docker in a Linux srever. I am able to access it using ip:port 

I'm trying to proxy pass it to my apache subdirectory but it resolves to the main directory (/)

Example: 
When i try to proxypass 172.16.x.x:8888 to https://example.com/test/openmaptiles/, it tries searching for script in https://example.com/

How do I make the openmaptiles the default directory?
Please help. @pnorman @klokan @sfkeller @francois2metz @frodrigo 

![Screenshot from 2020-08-02 15-28-22](https://user-images.githubusercontent.com/29572449/89120568-024dd800-d4d5-11ea-9832-4028dd59bec4.png)

**Comment by frodrigo** [comment]
Please, does not ping everybody like this.

Are you asking about a MBTiles within OpenMapTiles Map Server ? It does not have link direct to OpenMapTiles project.

**Comment by 4nuragk** [comment]
> Please, does not ping everybody like this.
> 
> Are you asking about a MBTiles within OpenMapTiles Map Server ? It does not have link direct to OpenMapTiles project.

I am sorry to disturb. It's actually a very urgent work and I am not able to find a fix. 

No. I am actually asking about the whole openmaptiles server. I want to proxy it to a URL(apache server). (I have already proxied different websites hosted locally)

But I don't know how to set the proxy to a sub-directory. Every time it looks for content in www.example.com whereas I proxy passed it to www.example.com/test/openmaptiles/

**Comment by frodrigo** [comment]
OpenMapTiles Maps Server is not part of this project, OpenMapTiles, It is MapTiler product.

Maybe you are talking about the small server of openmaptiles-tool postserve?
https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/postserve

**Comment by 4nuragk** [comment]
> OpenMapTiles Maps Server is not part of this project, OpenMapTiles, It is MapTiler product.
> 
> Maybe you are talking about the small server of openmaptiles-tool postserve?
> https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/postserve

I am talking about the one I installed from https://openmaptiles.com/server/

**Comment by frodrigo** [comment]
Yes it is the MapTiler product.

This github project is this part only https://openmaptiles.org/

**Comment by 4nuragk** [comment]
Oh okay. Sorry to disturb.
