### ISSUE TITLE
import sql error. No function that matches "osml10n_get_name_without_brackets_from_tags"

### ISSUE THREAD

**Issue by PraneethaMoturi** [openmaptiles/openmaptiles#965]
On running "./quickstart.sh asia" on the master branch, I'm getting import-sql error.

The error is 
`psql:/usr/src/app/sql/zzz_language.sql:74: ERROR:  function osml10n_get_name_without_brackets_from_tags(hstore, unknown, geometry) does not exist
LINE 9:       NULLIF(osml10n_get_name_without_brackets_from_tags(tag...
                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Time: 0.958 ms
make: *** [import-sql] Error 3
`

**Comment by frodrigo** [comment]
https://github.com/openmaptiles/openmaptiles-tools/issues/312

**Comment by TomPohys** [comment]
Hi @PraneethaMoturi, is there any update about this error? Can you please provide some more information? Thanks
