### ISSUE TITLE
Support for Indic languages

### ISSUE THREAD

**Issue by naveenpf** [openmaptiles/openmaptiles#971]
Currently, only Kannada has supported the support from openmaptiles. 

https://wiki.openstreetmap.org/wiki/Map_internationalization_(India)#Internationalized_OSM_map_renderings_of_India

Recent changes in Wikimedia maps. 
https://twitter.com/naveenpf/status/1299194566159945730

**Comment by TomPohys** [comment]
Hi @naveenpf, what other languages do you suggest to be added into OpenMapTiles? Kannada language has now 66 502 names based on [taginfo](https://taginfo.openstreetmap.org/search?q=name%3Akn).

**Comment by naveenpf** [comment]
Malayalam is not working. 
![image](https://user-images.githubusercontent.com/12662835/91800105-0725b900-ec46-11ea-9a1e-31cfcf669555.png)

Kannada is working
![image](https://user-images.githubusercontent.com/12662835/91800165-23295a80-ec46-11ea-8a64-b19cdb4561d8.png)

**Comment by naveenpf** [comment]
https://public.flourish.studio/visualisation/3624571/

**Comment by TomPohys** [comment]
There are only 6 365 names for 8 462 objects for the Malayalam language (https://taginfo.openstreetmap.org/keys/name%3Aml). The Kannada language has 33 247 names for 66 536 objects. Are all cities translated into the Malayalam language in OpenStreetMap?

**Comment by naveenpf** [comment]
@TomPohys Malayalam is only spoken in Kerala State. We have good coverage in Kerala State

**Comment by naveenpf** [comment]
it was supposed to be part of https://github.com/openmaptiles/openmaptiles/pull/478
