### ISSUE TITLE
Building layer optimization

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles#974]
After PR https://github.com/openmaptiles/openmaptiles/pull/936 there is huge memory consumption on larger areas (https://github.com/openmaptiles/openmaptiles/issues/938).

Any sugestion how to optimize a code in osm_building_block_gen1() function in [update_building.sql](https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/update_building.sql#L12)?

Thank you

**Comment by frodrigo** [comment]
I also disable this z13 layer. But I think the memory issue is from here https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/update_building.sql#L25-L32

The solution may be to cluster using a grid. May be the z13 grid.
If necessary a second pass may be used to merge the grided clusters.

The idea is close to PR #725.

**Comment by TomPohys** [comment]
Buildings aggregation is now fixed by #1044
