### ISSUE TITLE
[QA] China FREQ reports 

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#99]
see :  https://gist.github.com/680ad0ddbb7bdd8ac2a93680bb602861
date: 2016-12-06 

replicating:
```bash
git checkout quickstart_v2
make refresh-docker-images
./quickstart.sh china
make generate-qareports
ls ./build/qareports/*.md
```

**Comment by lukasmartinelli** [comment]
I like the FREQ reports but we should make issues out of them if there is something to take action upon ;)
